// "Am I Ready?" question bank. One 5-question set per subject, mixed across
// that subject's VERY HIGH topics. Sciences/FNS/POA questions are extracted
// from each subject's own Sure Questions Vault (with the Vault's answer keys);
// maths and humanities sets are hand-authored to the same topics because those
// Vaults are structured/essay format with no natively auto-gradable items.
//
// ⚠️ REVIEW BEFORE LAUNCH — especially the hand-authored sets (maths,
// histories, geographies, social studies, POA fills). Every question is one
// mark. Edit or replace any entry; the shape is all that matters.
//
// SECURITY: this module must ONLY be imported from server code. `correctKey`
// and `workedSolution` must never reach the client before submission; pages
// send the client a sanitized shape via sanitizeSet().

export type DiagnosticProduct = "companion" | "vault" | "master";

export interface DiagnosticQuestion {
  id: string;
  type: "mcq" | "short";
  // Which VERY HIGH topic this question belongs to (shown to the student).
  topic: string;
  stem: string;
  // MCQ options; omitted for short-answer.
  options?: string[];
  // MCQ: the correct option's index as a string (e.g. "2").
  // Short: every accepted answer, compared case/space-insensitively.
  correctKey: string[];
  marks: number;
  workedSolution: string;
  // What a wrong answer here signals — drives the tailored CTA.
  misconceptionTag: string;
  mapsToProduct: DiagnosticProduct;
}

export interface DiagnosticSet {
  level: "o-level" | "na-level";
  slug: string;
  // Display name for what the check covers.
  topicLabel: string;
  questions: DiagnosticQuestion[];
}

const SETS: DiagnosticSet[] = [
  {
    level: "na-level",
    slug: "a-math",
    topicLabel: "Mixed — the VERY HIGH topics",
    questions: [
    {
      id: "a-math-vq1",
      type: "short",
      topic: "Calculus (Differentiation & Integration)",
      stem: "Differentiate y = x² with respect to x. Give dy/dx.",
      correctKey: ["2x", "2 x"],
      marks: 1,
      workedSolution: "Power rule: d/dx(xⁿ) = n·xⁿ⁻¹, so d/dx(x²) = 2x.",
      misconceptionTag: "Calculus (Differentiation & Integration)",
      mapsToProduct: "vault",
    },
    {
      id: "a-math-vq2",
      type: "short",
      topic: "Calculus (Differentiation & Integration)",
      stem: "Differentiate y = 4x³ with respect to x. Give dy/dx.",
      correctKey: ["12x2", "12x^2", "12x²", "12 x^2"],
      marks: 1,
      workedSolution: "Multiply the coefficient by the power, then reduce the power: 4 × 3 = 12 and x³ becomes x², giving 12x².",
      misconceptionTag: "Calculus (Differentiation & Integration)",
      mapsToProduct: "vault",
    },
    {
      id: "a-math-vq3",
      type: "mcq",
      topic: "Trigonometry",
      stem: "What is the exact value of sin 30°?",
      options: ["1/2", "√3/2", "√2/2", "1"],
      correctKey: ["0"],
      marks: 1,
      workedSolution: "sin 30° = 1/2 — a special-angle value to memorise alongside cos 30° = √3/2 and tan 45° = 1.",
      misconceptionTag: "Trigonometry",
      mapsToProduct: "vault",
    },
    {
      id: "a-math-vq4",
      type: "short",
      topic: "Calculus (Differentiation & Integration)",
      stem: "The gradient function of a curve is dy/dx = 2x + 3. What is the gradient at x = 0?",
      correctKey: ["3"],
      marks: 1,
      workedSolution: "Substitute x = 0: 2(0) + 3 = 3. Evaluating the derivative at a point gives the gradient of the curve there.",
      misconceptionTag: "Calculus (Differentiation & Integration)",
      mapsToProduct: "companion",
    },
    {
      id: "a-math-vq5",
      type: "mcq",
      topic: "Calculus (Differentiation & Integration)",
      stem: "∫ 2x dx equals:",
      options: ["x² + c", "2x² + c", "x + c", "2 + c"],
      correctKey: ["0"],
      marks: 1,
      workedSolution: "Integration reverses differentiation: raise the power by one and divide by the new power — 2x integrates to x², plus the constant of integration c.",
      misconceptionTag: "Calculus (Differentiation & Integration)",
      mapsToProduct: "companion",
    },
    ],
  },
  {
    level: "na-level",
    slug: "biology",
    topicLabel: "Mixed — the VERY HIGH topics",
    questions: [
    {
      id: "biology-vq1",
      type: "mcq",
      topic: "B8 Plant Nutrition",
      stem: "Which pair of substances is used up as raw materials during photosynthesis in a green leaf?",
      options: ["carbon dioxide and water", "oxygen and water", "carbon dioxide and oxygen", "glucose and oxygen"],
      correctKey: ["0"],
      marks: 1,
      workedSolution: "The word equation for photosynthesis is: carbon dioxide + water → glucose + oxygen (in the presence of light and chlorophyll). The two substances taken IN as raw materials are carbon dioxide and water. Oxygen and glucose are the products, so options containing them as reactants are wrong.",
      misconceptionTag: "B8 Plant Nutrition",
      mapsToProduct: "vault",
    },
    {
      id: "biology-vq2",
      type: "mcq",
      topic: "B8 Rate of Photosynthesis",
      stem: "A pondweed is illuminated and the rate of photosynthesis is measured as light intensity is increased. The rate rises steeply, then levels off to a plateau. What is limiting the rate at the plateau, where more light causes no further increase?",
      options: ["light intensity", "chlorophyll concentration", "carbon dioxide concentration or temperature", "the amount of glucose made"],
      correctKey: ["2"],
      marks: 1,
      workedSolution: "While the graph rises, light is the limiting factor — adding more light speeds the reaction up. Once the line flattens, extra light makes no difference, so something ELSE has become the limiting factor: usually the carbon dioxide concentration or the temperature. A limiting factor is the one in shortest supply that holds the rate back.",
      misconceptionTag: "B8 Rate of Photosynthesis",
      mapsToProduct: "vault",
    },
    {
      id: "biology-vq3",
      type: "mcq",
      topic: "B6 Inspired vs Expired Air",
      stem: "Compared with inspired (breathed-in) air, expired (breathed-out) air contains:",
      options: ["more oxygen and more carbon dioxide", "less oxygen and more carbon dioxide", "more oxygen and less carbon dioxide", "the same oxygen and less carbon dioxide"],
      correctKey: ["1"],
      marks: 1,
      workedSolution: "In the alveoli, oxygen diffuses from the air into the blood and carbon dioxide diffuses from the blood into the air. So the air you breathe out has had some oxygen removed and carbon dioxide added: less oxygen, more carbon dioxide (and it is also warmer and more saturated with water vapour) than the air breathed in.",
      misconceptionTag: "B6 Inspired vs Expired Air",
      mapsToProduct: "vault",
    },
    {
      id: "biology-vq4",
      type: "mcq",
      topic: "B4 Hepatic Portal Vein",
      stem: "After a meal, the blood vessel that carries newly absorbed, nutrient-rich blood from the small intestine directly to the liver is the:",
      options: ["hepatic artery", "hepatic portal vein", "pulmonary vein", "aorta"],
      correctKey: ["1"],
      marks: 1,
      workedSolution: "Products of digestion absorbed in the small intestine are carried in the hepatic portal vein straight to the liver, where the level of nutrients such as glucose is adjusted before the blood goes on to the rest of the body. The hepatic artery brings oxygenated blood TO the liver; it does not carry the absorbed food.",
      misconceptionTag: "B4 Hepatic Portal Vein",
      mapsToProduct: "vault",
    },
    {
      id: "biology-vq5",
      type: "mcq",
      topic: "B5 Blood Vessels",
      stem: "Which feature of an artery is directly related to the high blood pressure of the blood it carries?",
      options: ["the presence of valves along its length", "a thick, muscular and elastic wall", "a wall that is only one cell thick", "a very wide internal space (lumen) with thin walls"],
      correctKey: ["1"],
      marks: 1,
      workedSolution: "2026 Sure Questions Vault - N(A)-Level Science (Biology) 5106/5107 © 2026 StudyLah Education • visit www.studylah.education for other subjects • Original content — not SEAB/MOE/UCLES material 28 Arteries carry blood pumped straight from the heart at high pressure, so they have thick, muscular and elastic walls that withstand and smooth out the pressure surges. Valves along the length and a wide lumen with thin walls are features of VEINS; a one-c",
      misconceptionTag: "B5 Blood Vessels",
      mapsToProduct: "vault",
    },
    ],
  },
  {
    level: "na-level",
    slug: "chemistry",
    topicLabel: "Mixed — the VERY HIGH topics",
    questions: [
    {
      id: "chemistry-vq1",
      type: "mcq",
      topic: "C7 Patterns in the Periodic Table",
      stem: "Chlorine is bubbled through separate colourless solutions of potassium bromide and potassium iodide. In which solution(s) does a displacement reaction occur?",
      options: ["potassium bromide only", "potassium iodide only", "both potassium bromide and potassium iodide", "neither solution"],
      correctKey: ["2"],
      marks: 1,
      workedSolution: "Reactivity falls down Group 17: chlorine > bromine > iodine. A more reactive halogen displaces a less reactive one from its salt, so chlorine displaces bromine from potassium bromide and iodine from potassium iodide — both solutions react.",
      misconceptionTag: "C7 Patterns in the Periodic Table",
      mapsToProduct: "vault",
    },
    {
      id: "chemistry-vq2",
      type: "mcq",
      topic: "C4 Chemical Calculations",
      stem: "Aluminium forms the ion Al³⁺ and oxygen forms the ion O²⁻. What is the formula of aluminium oxide?",
      options: ["AlO", "Al₂O₃", "Al₃O₂", "Al₂O"],
      correctKey: ["1"],
      marks: 1,
      workedSolution: "The compound must be electrically neutral. Two Al³⁺ ions carry +6 and three O²⁻ ions carry −6, so the ratio is 2 : 3, giving Al₂O₃. Swapping the numbers (Al₃O₂) puts them on the wrong ions.",
      misconceptionTag: "C4 Chemical Calculations",
      mapsToProduct: "vault",
    },
    {
      id: "chemistry-vq3",
      type: "mcq",
      topic: "Organic Chemistry",
      stem: "Which is the general formula of the alkane homologous series?",
      options: ["CₙH₂ₙ", "CₙH₂ₙ₊₂", "CₙH₂ₙ₋₂", "CₙH₂ₙ₊₁OH"],
      correctKey: ["1"],
      marks: 1,
      workedSolution: "Alkanes are saturated hydrocarbons with the general formula CₙH₂ₙ₊₂ — methane CH₄, ethane C₂H₆, propane C₃H₈ all fit it. CₙH₂ₙ is the alkene family.",
      misconceptionTag: "Organic Chemistry",
      mapsToProduct: "vault",
    },
    {
      id: "chemistry-vq4",
      type: "mcq",
      topic: "Acids, Bases & Salts",
      stem: "Which gas is produced when dilute hydrochloric acid reacts with magnesium?",
      options: ["carbon dioxide", "hydrogen", "oxygen", "chlorine"],
      correctKey: ["1"],
      marks: 1,
      workedSolution: "Acid + reactive metal → salt + hydrogen. Test: a lighted splint gives a squeaky pop. Carbon dioxide comes from acid + carbonate, not acid + metal.",
      misconceptionTag: "Acids, Bases & Salts",
      mapsToProduct: "vault",
    },
    {
      id: "chemistry-vq5",
      type: "mcq",
      topic: "Experimental Chemistry",
      stem: "Which method separates an insoluble solid from a liquid?",
      options: ["evaporation", "crystallisation", "filtration", "fractional distillation"],
      correctKey: ["2"],
      marks: 1,
      workedSolution: "Filtration traps the insoluble solid as residue while the liquid passes through as filtrate. Evaporation and crystallisation recover a DISSOLVED solid; fractional distillation separates miscible liquids.",
      misconceptionTag: "Experimental Chemistry",
      mapsToProduct: "companion",
    },
    ],
  },
  {
    level: "na-level",
    slug: "e-math",
    topicLabel: "Mixed — the VERY HIGH topics",
    questions: [
    {
      id: "e-math-vq1",
      type: "short",
      topic: "Equations & Inequalities",
      stem: "Solve for x: 3x + 4 = 19",
      correctKey: ["5", "x=5", "x = 5"],
      marks: 1,
      workedSolution: "Subtract 4 from both sides: 3x = 15, then divide by 3: x = 5. Undo the + and × in reverse order.",
      misconceptionTag: "Equations & Inequalities",
      mapsToProduct: "vault",
    },
    {
      id: "e-math-vq2",
      type: "short",
      topic: "Data Handling & Analysis",
      stem: "Find the mean of the numbers 4, 7, 9 and 12.",
      correctKey: ["8"],
      marks: 1,
      workedSolution: "Mean = total ÷ how many = (4 + 7 + 9 + 12) ÷ 4 = 32 ÷ 4 = 8.",
      misconceptionTag: "Data Handling & Analysis",
      mapsToProduct: "vault",
    },
    {
      id: "e-math-vq3",
      type: "short",
      topic: "Mensuration",
      stem: "A rectangle is 8 cm long and 5 cm wide. What is its area in cm²?",
      correctKey: ["40", "40cm2", "40 cm2", "40cm²", "40 cm²"],
      marks: 1,
      workedSolution: "Area of a rectangle = length × width = 8 × 5 = 40 cm². Remember area units are ALWAYS squared.",
      misconceptionTag: "Mensuration",
      mapsToProduct: "vault",
    },
    {
      id: "e-math-vq4",
      type: "short",
      topic: "Algebraic Manipulation",
      stem: "Simplify: 4a + 3a − 2a",
      correctKey: ["5a", "5 a"],
      marks: 1,
      workedSolution: "All three are like terms in a: 4 + 3 − 2 = 5, so the answer is 5a. Only like terms can be combined.",
      misconceptionTag: "Algebraic Manipulation",
      mapsToProduct: "companion",
    },
    {
      id: "e-math-vq5",
      type: "short",
      topic: "Pythagoras & Trigonometry",
      stem: "A right-angled triangle has shorter sides 3 cm and 4 cm. How long is the hypotenuse in cm?",
      correctKey: ["5", "5cm", "5 cm"],
      marks: 1,
      workedSolution: "h² = 3² + 4² = 9 + 16 = 25 → h = 5 cm. The 3-4-5 triangle is the most common Pythagorean triple in exams.",
      misconceptionTag: "Pythagoras & Trigonometry",
      mapsToProduct: "vault",
    },
    ],
  },
  {
    level: "na-level",
    slug: "food-and-nutrition",
    topicLabel: "Mixed — the VERY HIGH topics",
    questions: [
    {
      id: "food-and-nutrition-vq1",
      type: "mcq",
      topic: "L9 Balanced Diet",
      stem: "A Singapore family wants each meal to follow the idea of a balanced diet. Which statement best describes a balanced diet?",
      options: ["a diet made up mainly of carbohydrate for energy", "a diet containing all the nutrients in the correct amounts and proportions for the body's needs", "a diet that avoids all fat and sugar completely", "a diet based only on fresh, home-cooked food"],
      correctKey: ["1"],
      marks: 1,
      workedSolution: "A balanced diet provides all the nutrients (proteins, carbohydrates, fats, vitamins, minerals), plus water and fibre, in the correct amounts and proportions to meet the body's needs for energy, growth, repair and health. It is not about one nutrient dominating, nor about banning fat or sugar outright — it is about the right overall balance.",
      misconceptionTag: "L9 Balanced Diet",
      mapsToProduct: "vault",
    },
    {
      id: "food-and-nutrition-vq2",
      type: "mcq",
      topic: "L9 Energy Balance",
      stem: "A hawker eats meals that give more energy than his body uses each day over many months. What is the most likely result?",
      options: ["he loses body mass because energy is wasted", "his body mass stays exactly the same", "he gains body mass as the extra energy is stored as fat", "he becomes dehydrated"],
      correctKey: ["2"],
      marks: 1,
      workedSolution: "Energy balance compares energy taken IN (from food) with energy used UP (basal metabolism + activity). When intake regularly exceeds output, the surplus energy is stored as body fat, so the person gains mass over time. Long-term positive energy balance is the direct route to being overweight and obesity.",
      misconceptionTag: "L9 Energy Balance",
      mapsToProduct: "vault",
    },
    {
      id: "food-and-nutrition-vq3",
      type: "mcq",
      topic: "S13 Functions of Eggs",
      stem: "In making a Singapore-style steamed egg custard, the eggs are beaten with stock and set by steaming. What is the main function of the eggs in this dish?",
      options: ["emulsifying, to blend oil and water", "coagulating, to set the mixture into a soft solid when heated", "aerating, to trap air and make the dish rise", "glazing, to give a shiny surface"],
      correctKey: ["1"],
      marks: 1,
      workedSolution: "When egg proteins are heated they denature and coagulate — they set from a runny liquid into a soft solid. This is what thickens and sets a steamed egg custard. Eggs can also emulsify (as in mayonnaise), aerate (as in a whisked sponge) and glaze, but in a set custard the key function is coagulation on heating.",
      misconceptionTag: "S13 Functions of Eggs",
      mapsToProduct: "vault",
    },
    {
      id: "food-and-nutrition-vq4",
      type: "mcq",
      topic: "S15 Dextrinisation vs Caramelisation",
      stem: "A slice of bread is toasted and its surface turns golden-brown. Which reaction is mainly responsible for this browning?",
      options: ["caramelisation of sugar", "gelatinisation of starch", "dextrinisation of starch", "enzymatic browning"],
      correctKey: ["2"],
      marks: 1,
      workedSolution: "Bread is mostly starch and contains little sugar, so its dry-heat browning is dextrinisation — starch broken down to dextrins that brown under dry heat. Caramelisation is the browning of SUGAR under dry heat (as when sugar is heated for a caramel). Gelatinisation needs liquid and enzymatic browning happens in cut fruit, not toast.",
      misconceptionTag: "S15 Dextrinisation vs Caramelisation",
      mapsToProduct: "vault",
    },
    {
      id: "food-and-nutrition-vq5",
      type: "mcq",
      topic: "N5 Potassium",
      stem: "Bananas and leafy vegetables are good sources of potassium. Which food would be an ADDITIONAL good source of potassium?",
      options: ["white sugar", "vegetable oil", "potatoes", "table salt"],
      correctKey: ["2"],
      marks: 1,
      workedSolution: "Potassium is found in fruit and vegetables such as bananas, leafy greens and potatoes. Pure sugar, oil and salt are single-nutrient foods (sugar is carbohydrate, oil is fat, salt is sodium chloride) and are not sources of potassium. So potatoes are the additional good source.",
      misconceptionTag: "N5 Potassium",
      mapsToProduct: "vault",
    },
    ],
  },
  {
    level: "na-level",
    slug: "history",
    topicLabel: "Mixed — the VERY HIGH topics",
    questions: [
    {
      id: "history-vq1",
      type: "mcq",
      topic: "H2 Nazi Germany",
      stem: "Hitler was appointed Chancellor of Germany in January 1933 by:",
      options: ["President Hindenburg", "the Reichstag", "a national referendum", "the army"],
      correctKey: ["0"],
      marks: 1,
      workedSolution: "President Hindenburg appointed Hitler Chancellor on 30 January 1933, persuaded that he could be controlled in a coalition — the constitutional door to Nazi power.",
      misconceptionTag: "H2 Nazi Germany",
      mapsToProduct: "vault",
    },
    {
      id: "history-vq2",
      type: "mcq",
      topic: "H2 Nazi Germany",
      stem: "What did the Enabling Act of 1933 allow Hitler's government to do?",
      options: ["make laws without the Reichstag", "leave the League of Nations", "invade Poland", "ban trade with Britain"],
      correctKey: ["0"],
      marks: 1,
      workedSolution: "The Enabling Act transferred law-making power to Hitler's cabinet for four years — renewed thereafter, it made the Reichstag irrelevant.",
      misconceptionTag: "H2 Nazi Germany",
      mapsToProduct: "vault",
    },
    {
      id: "history-vq3",
      type: "mcq",
      topic: "H7 Origins of the Cold War",
      stem: "Who described an 'Iron Curtain' dividing Europe in a famous 1946 speech?",
      options: ["Truman", "Churchill", "Stalin", "Roosevelt"],
      correctKey: ["1"],
      marks: 1,
      workedSolution: "Churchill's Fulton speech of March 1946 named the division of Europe — from Stettin to Trieste — an 'iron curtain', crystallising Western alarm at Soviet expansion.",
      misconceptionTag: "H7 Origins of the Cold War",
      mapsToProduct: "vault",
    },
    {
      id: "history-vq4",
      type: "mcq",
      topic: "H7 Origins of the Cold War",
      stem: "The Western response to the Berlin Blockade (1948-49) was to:",
      options: ["supply West Berlin by air", "abandon the city", "declare war on the USSR", "build the Berlin Wall"],
      correctKey: ["0"],
      marks: 1,
      workedSolution: "For almost eleven months Allied aircraft supplied West Berlin with food and fuel until the blockade was lifted — containment in action without direct fighting.",
      misconceptionTag: "H7 Origins of the Cold War",
      mapsToProduct: "vault",
    },
    {
      id: "history-vq5",
      type: "mcq",
      topic: "H9 Decline of the USSR",
      stem: "NATO, formed in 1949, was primarily:",
      options: ["a trading bloc", "a Western military alliance for collective defence", "a communist alliance", "a UN agency"],
      correctKey: ["1"],
      marks: 1,
      workedSolution: "NATO bound the USA, Canada and Western Europe to treat an attack on one as an attack on all — the military backbone of containment; the Warsaw Pact (1955) was the Soviet answer.",
      misconceptionTag: "H9 Decline of the USSR",
      mapsToProduct: "vault",
    },
    ],
  },
  {
    level: "na-level",
    slug: "physics",
    topicLabel: "Mixed — the VERY HIGH topics",
    questions: [
    {
      id: "physics-vq1",
      type: "mcq",
      topic: "P3 Force & Pressure",
      stem: "An astronaut and her equipment are taken from Earth to the Moon, where the gravitational field strength is smaller. Which quantity stays the same?",
      options: ["her weight", "the force she needs to lift a rock", "her mass", "the reading on a bathroom scale she stands on"],
      correctKey: ["2"],
      marks: 1,
      workedSolution: "Mass is a measure of the amount of matter in a body and is the same everywhere. Weight is the gravitational force on that mass, W = mg, so it falls when g falls. On the Moon her weight, the lifting force and the scale reading (which measures weight) all drop; only her mass is unchanged.",
      misconceptionTag: "P3 Force & Pressure",
      mapsToProduct: "vault",
    },
    {
      id: "physics-vq2",
      type: "mcq",
      topic: "P11 D.C. Circuits",
      stem: "Two 6 Ω resistors are connected in parallel. What is their combined (effective) resistance?",
      options: ["12 Ω", "6 Ω", "3 Ω", "1.5 Ω"],
      correctKey: ["2"],
      marks: 1,
      workedSolution: "For two equal resistors in parallel the combined resistance is simply half of one resistor: 6 / 2 = 3 Ω. Adding a second path always makes it EASIER for current to flow, so the effective resistance is less than either resistor on its own. Only in SERIES would you add them to get 12 Ω.",
      misconceptionTag: "P11 D.C. Circuits",
      mapsToProduct: "vault",
    },
    {
      id: "physics-vq3",
      type: "mcq",
      topic: "P2 Kinematics",
      stem: "On a speed-time graph, a body's line is horizontal (flat) and above the time axis. What is the body doing?",
      options: ["speeding up at a steady rate", "slowing down", "moving at a constant (steady) speed", "stationary"],
      correctKey: ["2"],
      marks: 1,
      workedSolution: "On a speed-time graph the height is the speed and the gradient is the acceleration. A flat line above the axis has zero gradient but a non-zero height, so the speed is steady and not zero — constant speed. A line ON the axis (zero height) would mean stationary; a sloping line would mean speeding up or slowing down.",
      misconceptionTag: "P2 Kinematics",
      mapsToProduct: "vault",
    },
    {
      id: "physics-vq4",
      type: "mcq",
      topic: "P12 Practical Electricity",
      stem: "An appliance is rated 230 V, 690 W and is used on the 230 V mains. Fuses available are 1 A, 3 A, 5 A and 13 A. Which is the most suitable fuse?",
      options: ["1 A", "3 A", "5 A", "13 A"],
      correctKey: ["2"],
      marks: 1,
      workedSolution: "The normal working current is I = P/V = 690 / 230 = 3 A. A fuse must be rated just ABOVE the normal current, so the 5 A fuse is chosen. A 1 A or 3 A fuse would blow in normal use; a 13 A fuse is too high and would let a dangerous fault current flow before melting.",
      misconceptionTag: "P12 Practical Electricity",
      mapsToProduct: "companion",
    },
    {
      id: "physics-vq5",
      type: "mcq",
      topic: "P1 Physical Quantities, Units & Measurement",
      stem: "Which of the following is a vector quantity?",
      options: ["mass", "speed", "temperature", "force"],
      correctKey: ["3"],
      marks: 1,
      workedSolution: "A vector has both magnitude and direction; a scalar has magnitude only. Force has a direction (you push or pull a particular way), so it is a vector. Mass, speed and temperature have size but no direction, so they are scalars. (Velocity, unlike speed, IS a vector because it includes direction.)",
      misconceptionTag: "P1 Physical Quantities, Units & Measurem",
      mapsToProduct: "vault",
    },
    ],
  },
  {
    level: "na-level",
    slug: "principles-of-accounts",
    topicLabel: "Mixed — the VERY HIGH topics",
    questions: [
    {
      id: "principles-of-accounts-vq1",
      type: "mcq",
      topic: "G10 Financial Statements",
      stem: "Which financial statement shows the financial POSITION of a business at one date?",
      options: ["income statement", "statement of financial position", "trial balance", "bank statement"],
      correctKey: ["1"],
      marks: 1,
      workedSolution: "The statement of financial position lists assets, liabilities and equity AT a single date — a snapshot. The income statement shows performance OVER a period.",
      misconceptionTag: "G10 Financial Statements",
      mapsToProduct: "vault",
    },
    {
      id: "principles-of-accounts-vq2",
      type: "short",
      topic: "G7 Inventory & Depreciation",
      stem: "A machine costs $10,000, has a residual value of $1,000 and a useful life of 3 years. Using the straight-line method, what is the annual depreciation in dollars?",
      correctKey: ["3000", "$3000", "3,000", "3000 dollars"],
      marks: 1,
      workedSolution: "Straight-line depreciation = (cost − residual value) ÷ useful life = (10,000 − 1,000) ÷ 3 = $3,000 per year. Forgetting to subtract the residual value is the classic slip.",
      misconceptionTag: "G7 Inventory & Depreciation",
      mapsToProduct: "vault",
    },
    {
      id: "principles-of-accounts-vq3",
      type: "mcq",
      topic: "G5 Double Entry",
      stem: "A business buys inventory and pays immediately by cheque. The double entry is:",
      options: ["debit Inventory, credit Bank", "debit Bank, credit Inventory", "debit Inventory, credit Capital", "debit Trade payables, credit Bank"],
      correctKey: ["0"],
      marks: 1,
      workedSolution: "The business gains inventory (debit the asset that increases) and its bank balance falls (credit the asset that decreases). Trade payables are only involved when buying on credit.",
      misconceptionTag: "G5 Double Entry",
      mapsToProduct: "companion",
    },
    {
      id: "principles-of-accounts-vq4",
      type: "mcq",
      topic: "G8 Trade Receivables & Impairment",
      stem: "An impairment loss on trade receivables is recorded when:",
      options: ["a customer pays early", "a debt is unlikely to be collected", "sales increase", "the owner withdraws cash"],
      correctKey: ["1"],
      marks: 1,
      workedSolution: "Prudence requires recognising the loss as soon as collection becomes doubtful — profit and receivables are reduced before the cash is formally written off.",
      misconceptionTag: "G8 Trade Receivables & Impairment",
      mapsToProduct: "vault",
    },
    {
      id: "principles-of-accounts-vq5",
      type: "mcq",
      topic: "G10 Financial Statements",
      stem: "Gross profit is calculated as:",
      options: ["revenue − cost of sales", "revenue − all expenses", "cash received − cash paid", "assets − liabilities"],
      correctKey: ["0"],
      marks: 1,
      workedSolution: "Gross profit = revenue − cost of sales, the profit from trading alone. Subtracting ALL expenses gives profit for the year; assets − liabilities gives equity.",
      misconceptionTag: "G10 Financial Statements",
      mapsToProduct: "vault",
    },
    ],
  },
  {
    level: "o-level",
    slug: "a-math",
    topicLabel: "Mixed — the VERY HIGH topics",
    questions: [
    {
      id: "a-math-vq1",
      type: "short",
      topic: "Calculus",
      stem: "Differentiate y = x³ with respect to x. Give dy/dx.",
      correctKey: ["3x2", "3x^2", "3x²", "3 x^2"],
      marks: 1,
      workedSolution: "Power rule: bring the power down and reduce it by one — d/dx(xⁿ) = n·xⁿ⁻¹, so d/dx(x³) = 3x².",
      misconceptionTag: "Calculus",
      mapsToProduct: "vault",
    },
    {
      id: "a-math-vq2",
      type: "short",
      topic: "Calculus",
      stem: "The gradient function of a curve is dy/dx = 6x − 4. What is the gradient at x = 1?",
      correctKey: ["2"],
      marks: 1,
      workedSolution: "Substitute x = 1 into the gradient function: 6(1) − 4 = 2. The derivative IS the gradient — evaluating it at a point gives the gradient there.",
      misconceptionTag: "Calculus",
      mapsToProduct: "companion",
    },
    {
      id: "a-math-vq3",
      type: "mcq",
      topic: "Trigonometry",
      stem: "For all θ, sin²θ + cos²θ equals:",
      options: ["0", "1", "tan²θ", "2"],
      correctKey: ["1"],
      marks: 1,
      workedSolution: "This is the fundamental Pythagorean identity: sin²θ + cos²θ = 1. It underpins almost every identity proof — quote it, don't re-derive it.",
      misconceptionTag: "Trigonometry",
      mapsToProduct: "vault",
    },
    {
      id: "a-math-vq4",
      type: "short",
      topic: "Calculus",
      stem: "The curve y = x² − 4x + 3 has a stationary point where dy/dx = 0. Find the x-coordinate of this point.",
      correctKey: ["2", "x=2", "x = 2"],
      marks: 1,
      workedSolution: "dy/dx = 2x − 4 = 0 → x = 2. Stationary points are always found by differentiating and setting the derivative to zero.",
      misconceptionTag: "Calculus",
      mapsToProduct: "companion",
    },
    {
      id: "a-math-vq5",
      type: "mcq",
      topic: "Trigonometry",
      stem: "What is the exact value of sin 30°?",
      options: ["1/2", "√3/2", "1", "√2/2"],
      correctKey: ["0"],
      marks: 1,
      workedSolution: "sin 30° = 1/2 — one of the special-angle values (30°, 45°, 60°) that must be recalled exactly, without a calculator.",
      misconceptionTag: "Trigonometry",
      mapsToProduct: "vault",
    },
    ],
  },
  {
    level: "o-level",
    slug: "biology-pure",
    topicLabel: "Mixed — the VERY HIGH topics",
    questions: [
    {
      id: "biology-pure-vq1",
      type: "mcq",
      topic: "T14 Inheritance",
      stem: "In pea plants, tall (T) is dominant to short (t). Two heterozygous tall plants are crossed. What is the expected ratio of tall to short offspring?",
      options: ["1 tall : 1 short", "2 tall : 1 short", "3 tall : 1 short", "all tall"],
      correctKey: ["2"],
      marks: 1,
      workedSolution: "Tt × Tt gives TT, Tt, Tt, tt — three plants with at least one T (tall) to one tt (short): a 3:1 ratio. Option A is a test-cross ratio (Tt × tt).",
      misconceptionTag: "T14 Inheritance",
      mapsToProduct: "vault",
    },
    {
      id: "biology-pure-vq2",
      type: "mcq",
      topic: "T8 Homeostasis, Co-ordination & Response",
      stem: "In a reflex arc, in which order does the nerve impulse travel?",
      options: ["effector → motor neurone → relay neurone → sensory neurone → receptor", "receptor → sensory neurone → relay neurone → motor neurone → effector", "receptor → motor neurone → relay neurone → sensory neurone → effector", "sensory neurone → receptor → relay neurone → effector → motor neurone"],
      correctKey: ["1"],
      marks: 1,
      workedSolution: "A reflex runs receptor → sensory → relay (in the spinal cord) → motor → effector. Option A is the pathway reversed.",
      misconceptionTag: "T8 Homeostasis, Co-ordination & Response",
      mapsToProduct: "vault",
    },
    {
      id: "biology-pure-vq3",
      type: "mcq",
      topic: "T11 Organisms & their Environment",
      stem: "Only about 10% of the energy in one trophic level passes to the next. Which is NOT a reason for this energy loss?",
      options: ["energy is used in respiration", "energy is lost as heat", "energy is used for movement", "energy is destroyed by the consumer"],
      correctKey: ["3"],
      marks: 1,
      workedSolution: "Energy is transferred and lost (as heat, in respiration, movement, undigested material) but never destroyed — energy cannot be created or destroyed. A, B and C are all genuine losses.",
      misconceptionTag: "T11 Organisms & their Environment",
      mapsToProduct: "vault",
    },
    {
      id: "biology-pure-vq4",
      type: "mcq",
      topic: "T5 Transport in Humans",
      stem: "Why is the wall of the left ventricle thicker than the wall of the right ventricle?",
      options: ["it pumps blood a shorter distance", "it pumps blood to the lungs only", "it must generate a higher pressure to pump blood around the whole body", "it holds more blood"],
      correctKey: ["2"],
      marks: 1,
      workedSolution: "The left ventricle pumps blood to the entire body, needing a higher pressure, so its muscular wall is thicker. The right ventricle only pumps to the nearby lungs.",
      misconceptionTag: "T5 Transport in Humans",
      mapsToProduct: "vault",
    },
    {
      id: "biology-pure-vq5",
      type: "mcq",
      topic: "T10 Nutrition & Transport in Plants",
      stem: "A potometer measures the rate of water uptake by a shoot. Which change would INCREASE the transpiration rate?",
      options: ["increasing the humidity around the leaves", "decreasing the light intensity", "increasing the air movement (wind)", "lowering the temperature"],
      correctKey: ["2"],
      marks: 1,
      workedSolution: "Wind removes water vapour from around the leaves, maintaining a steep concentration gradient and speeding transpiration. Higher humidity, less light and lower temperature all slow it.",
      misconceptionTag: "T10 Nutrition & Transport in Plants",
      mapsToProduct: "vault",
    },
    ],
  },
  {
    level: "o-level",
    slug: "biology-science",
    topicLabel: "Mixed — the VERY HIGH topics",
    questions: [
    {
      id: "biology-science-vq1",
      type: "mcq",
      topic: "T9 Nutrition & Transport in Flowering Plants",
      stem: "Which structure in a leaf allows carbon dioxide to enter for photosynthesis?",
      options: ["the cuticle", "the stoma", "the xylem", "the palisade cell"],
      correctKey: ["1"],
      marks: 1,
      workedSolution: "Stomata (controlled by guard cells) are the pores through which CO₂ enters and water vapour/oxygen leave. The cuticle is a waxy barrier; xylem carries water.",
      misconceptionTag: "T9 Nutrition & Transport in Flowering Pl",
      mapsToProduct: "vault",
    },
    {
      id: "biology-science-vq2",
      type: "mcq",
      topic: "T5 Transport in Humans",
      stem: "Why is the wall of the left ventricle thicker than the wall of the right ventricle?",
      options: ["it pumps blood a shorter distance", "it pumps blood only to the lungs", "it must generate a higher pressure to pump blood around the whole body", "it holds more blood"],
      correctKey: ["2"],
      marks: 1,
      workedSolution: "The left ventricle pumps blood to the whole body, needing a higher pressure, so its muscular wall is thicker. The right ventricle pumps only to the nearby lungs.",
      misconceptionTag: "T5 Transport in Humans",
      mapsToProduct: "vault",
    },
    {
      id: "biology-science-vq3",
      type: "mcq",
      topic: "T10 Organisms & their Environment",
      stem: "Which activity would INCREASE the capacity of a carbon sink?",
      options: ["burning fossil fuels", "planting and protecting forests", "clearing land for farming", "increasing car use"],
      correctKey: ["1"],
      marks: 1,
      workedSolution: "Forests absorb CO₂ by photosynthesis, acting as carbon sinks; planting and protecting them increases that capacity. The other options release CO₂ or remove sinks. Sure Questions Vault — O-Level Combined Science (Biology) 5088 © 2026 StudyLah Education • visit www.studylah.education for other subjects • Original content — not SEAB/MOE/UCLES material 8",
      misconceptionTag: "T10 Organisms & their Environment",
      mapsToProduct: "vault",
    },
    {
      id: "biology-science-vq4",
      type: "mcq",
      topic: "T8 Homeostasis & Co-ordination",
      stem: "Which hormone triggers ovulation during the menstrual cycle?",
      options: ["progesterone", "oestrogen", "luteinising hormone (LH)", "insulin"],
      correctKey: ["2"],
      marks: 1,
      workedSolution: "A surge of LH at around day 14 triggers ovulation. Oestrogen repairs the uterus lining; progesterone maintains it.",
      misconceptionTag: "T8 Homeostasis & Co-ordination",
      mapsToProduct: "vault",
    },
    {
      id: "biology-science-vq5",
      type: "mcq",
      topic: "T7 Infectious Diseases in Humans",
      stem: "Which is NOT a function of a white blood cell?",
      options: ["engulfing pathogens by phagocytosis", "producing antibodies", "transporting oxygen", "destroying pathogens"],
      correctKey: ["2"],
      marks: 1,
      workedSolution: "Transporting oxygen is the job of RED blood cells (haemoglobin). White cells engulf pathogens, make antibodies and destroy pathogens.",
      misconceptionTag: "T7 Infectious Diseases in Humans",
      mapsToProduct: "vault",
    },
    ],
  },
  {
    level: "o-level",
    slug: "chemistry-pure",
    topicLabel: "Mixed — the VERY HIGH topics",
    questions: [
    {
      id: "chemistry-pure-vq1",
      type: "short",
      topic: "C4 Chemical Calculations",
      stem: "What is the relative formula mass, Mr, of ammonium sulfate, (NH₄)₂SO₄? (Ar: N = 14, H = 1, S = 32, O = 16)",
      correctKey: ["132"],
      marks: 1,
      workedSolution: "The brackets multiply everything inside them: 2 × (14 + 4) for the two NH₄ groups gives 36, plus 32 for sulfur and 4 × 16 = 64 for oxygen — total 132. Counting only one NH₄ group gives the classic wrong answer 114; doubling the whole formula gives 264.",
      misconceptionTag: "C4 Chemical Calculations",
      mapsToProduct: "vault",
    },
    {
      id: "chemistry-pure-vq2",
      type: "mcq",
      topic: "C11 Organic Chemistry",
      stem: "Which pair of compounds are isomers of each other?",
      options: ["ethanol and ethanoic acid", "propanoic acid and methyl ethanoate", "butane and but-1-ene", "methanol and ethanol"],
      correctKey: ["1"],
      marks: 1,
      workedSolution: "Isomers share one molecular formula but differ in structure. Propanoic acid (CH₃CH₂COOH) and methyl ethanoate (CH₃COOCH₃) are both C₃H₆O₂ — one a carboxylic acid, the other an ester. Every other pair differs in molecular formula, so they cannot be isomers. Count every atom before judging structures.",
      misconceptionTag: "C11 Organic Chemistry",
      mapsToProduct: "vault",
    },
    {
      id: "chemistry-pure-vq3",
      type: "mcq",
      topic: "C3 Chemical Bonding & Structure",
      stem: "Which substance conducts electricity when molten but not when solid?",
      options: ["copper", "graphite", "sodium chloride", "silicon dioxide"],
      correctKey: ["2"],
      marks: 1,
      workedSolution: "Sodium chloride is a giant ionic lattice: in the solid the ions are locked in fixed positions and cannot carry charge, but melting frees them to move, so the liquid conducts. Copper and graphite conduct in BOTH states (delocalised electrons); silicon dioxide conducts in neither. Always answer conductivity questions by naming the mobile charge carrier.",
      misconceptionTag: "C3 Chemical Bonding & Structure",
      mapsToProduct: "companion",
    },
    {
      id: "chemistry-pure-vq4",
      type: "mcq",
      topic: "C7 Redox Chemistry & Electrochemistry",
      stem: "Household bleach is made by passing chlorine into cold aqueous sodium hydroxide: Cl₂(g) + 2NaOH(aq) → NaCl(aq) + NaOCl(aq) + H₂O(l). Which statement about the chlorine is correct?",
      options: ["It is oxidised only.", "It is reduced only.", "It is both oxidised and reduced.", "Its oxidation state does not change."],
      correctKey: ["2"],
      marks: 1,
      workedSolution: "Assign oxidation states element by element: chlorine starts at 0 in Cl₂, falls to −1 in NaCl (reduced) and rises to +1 in NaOCl (oxidised). The same element moving both up and down is a disproportionation — a favourite setter's twist. The method to bank: write the oxidation state of the element in EVERY species before judging.",
      misconceptionTag: "C7 Redox Chemistry & Electrochemistry",
      mapsToProduct: "companion",
    },
    {
      id: "chemistry-pure-vq5",
      type: "mcq",
      topic: "C5 Acid-Base Chemistry",
      stem: "Which oxide reacts with both dilute hydrochloric acid and aqueous sodium hydroxide?",
      options: ["calcium oxide", "zinc oxide", "carbon dioxide", "copper(II) oxide"],
      correctKey: ["1"],
      marks: 1,
      workedSolution: "Zinc oxide is amphoteric — it neutralises hydrochloric acid (forming zinc chloride) and also dissolves in aqueous sodium hydroxide. Calcium oxide and copper(II) oxide are basic (react with acid only); carbon dioxide is acidic (reacts with alkali only). The amphoteric trio to memorise: ZnO, Al₂O₃, PbO.",
      misconceptionTag: "C5 Acid-Base Chemistry",
      mapsToProduct: "vault",
    },
    ],
  },
  {
    level: "o-level",
    slug: "chemistry-science",
    topicLabel: "Mixed — the VERY HIGH topics",
    questions: [
    {
      id: "chemistry-science-vq1",
      type: "mcq",
      topic: "C11 Organic Chemistry",
      stem: "Which compound is a member of the alkene homologous series?",
      options: ["C₂H₆", "C₃H₆", "C₃H₈", "CH₄"],
      correctKey: ["1"],
      marks: 1,
      workedSolution: "Alkenes have the general formula CₙH₂ₙ. Only C₃H₆ (propene) fits: three carbons pair with exactly six hydrogens. C₂H₆, C₃H₈ and CH₄ all fit CₙH₂ₙ₊₂ — they are alkanes.",
      misconceptionTag: "C11 Organic Chemistry",
      mapsToProduct: "vault",
    },
    {
      id: "chemistry-science-vq2",
      type: "mcq",
      topic: "C4 Chemical Calculations",
      stem: "Element X is a metal that forms the ion X²⁺. The nitride ion is N³⁻. What is the formula of X nitride?",
      options: ["X₂N₃", "X₃N₂", "XN", "X₂N"],
      correctKey: ["1"],
      marks: 1,
      workedSolution: "A compound is electrically neutral, so total positive charge must cancel total negative charge. Three X²⁺ ions give 6+, two N³⁻ ions give 6−: formula X₃N₂.",
      misconceptionTag: "C4 Chemical Calculations",
      mapsToProduct: "vault",
    },
    {
      id: "chemistry-science-vq3",
      type: "mcq",
      topic: "C8 Patterns in the Periodic Table",
      stem: "Three metals are tested. Q reacts rapidly with cold water. R does not react with cold water but reacts with dilute hydrochloric acid. T does not react with cold water or with dilute hydrochloric acid. What is the order of reactivity, from most reactive to least reactive?",
      options: ["Q, T, R", "T, R, Q", "Q, R, T", "R, Q, T"],
      correctKey: ["2"],
      marks: 1,
      workedSolution: "The reactivity series is deduced from how demanding a reagent each metal needs: reacting with cold water outranks reacting only with acid, which outranks reacting with neither. So Q > R > T.",
      misconceptionTag: "C8 Patterns in the Periodic Table",
      mapsToProduct: "vault",
    },
    {
      id: "chemistry-science-vq4",
      type: "mcq",
      topic: "C11 Organic Chemistry",
      stem: "A cooking oil sold at a supermarket is labelled polyunsaturated. Which statement about this oil is correct?",
      options: ["Each molecule contains no carbon–carbon double bonds.", "The oil cannot react with aqueous bromine.", "The oil is hardened for spreads by boiling it with water.", "Each molecule contains several carbon–carbon double bonds, and the oil can be hardened by an"],
      correctKey: ["3"],
      marks: 1,
      workedSolution: "'Polyunsaturated' means each molecule carries several C=C double bonds. Reacting the oil with hydrogen adds H atoms across some of these double bonds, raising the melting point so the product is a soft solid — this is how margarine is manufactured.",
      misconceptionTag: "C11 Organic Chemistry",
      mapsToProduct: "vault",
    },
    {
      id: "chemistry-science-vq5",
      type: "mcq",
      topic: "C3 Chemical Bonding & Structure",
      stem: "Which property is typical of an ionic compound such as sodium chloride?",
      options: ["low melting point", "conducts electricity when solid", "high melting point and conducts when molten", "exists as simple molecules"],
      correctKey: ["2"],
      marks: 1,
      workedSolution: "Ionic lattices are held by strong electrostatic forces between oppositely charged ions, so melting points are high — and only when molten (or dissolved) are the ions free to move and conduct. Solids never conduct: the ions are fixed.",
      misconceptionTag: "C3 Chemical Bonding & Structure",
      mapsToProduct: "vault",
    },
    ],
  },
  {
    level: "o-level",
    slug: "e-math",
    topicLabel: "Mixed — the VERY HIGH topics",
    questions: [
    {
      id: "e-math-vq1",
      type: "short",
      topic: "N5 — Algebraic Manipulation",
      stem: "Expand and simplify: 3(2x − 5) + 4x",
      correctKey: ["10x-15", "10x−15", "10x - 15", "10 x - 15", "-15+10x"],
      marks: 1,
      workedSolution: "3(2x − 5) = 6x − 15; adding 4x gives 10x − 15. Expand the bracket term by term before collecting like terms.",
      misconceptionTag: "N5 — Algebraic Manipulation",
      mapsToProduct: "vault",
    },
    {
      id: "e-math-vq2",
      type: "short",
      topic: "N7 — Equations & Inequalities",
      stem: "Solve for x: 5x − 7 = 2x + 8",
      correctKey: ["5", "x=5", "x = 5"],
      marks: 1,
      workedSolution: "Bring the x terms together: 5x − 2x = 8 + 7 → 3x = 15 → x = 5. Move terms across the equals sign by doing the same operation to both sides.",
      misconceptionTag: "N7 — Equations & Inequalities",
      mapsToProduct: "companion",
    },
    {
      id: "e-math-vq3",
      type: "short",
      topic: "G4 — Pythagoras & Trigonometry",
      stem: "A right-angled triangle has shorter sides 6 cm and 8 cm. What is the length of the hypotenuse in cm?",
      correctKey: ["10", "10cm", "10 cm"],
      marks: 1,
      workedSolution: "By Pythagoras: h² = 6² + 8² = 36 + 64 = 100, so h = 10 cm. The 3-4-5 family of triangles (here scaled ×2) is worth recognising on sight.",
      misconceptionTag: "G4 — Pythagoras & Trigonometry",
      mapsToProduct: "vault",
    },
    {
      id: "e-math-vq4",
      type: "short",
      topic: "G5 — Mensuration",
      stem: "Taking π = 22/7, what is the area of a circle of radius 7 cm, in cm²?",
      correctKey: ["154", "154cm2", "154 cm2", "154cm²", "154 cm²"],
      marks: 1,
      workedSolution: "Area = πr² = (22/7) × 7 × 7 = 22 × 7 = 154 cm². With π = 22/7, a radius that is a multiple of 7 cancels cleanly — a strong exam hint.",
      misconceptionTag: "G5 — Mensuration",
      mapsToProduct: "vault",
    },
    {
      id: "e-math-vq5",
      type: "mcq",
      topic: "N5 — Algebraic Manipulation",
      stem: "Which is the correct factorisation of x² − 9?",
      options: ["(x − 3)(x − 3)", "(x + 3)(x − 3)", "(x + 9)(x − 1)", "x(x − 9)"],
      correctKey: ["1"],
      marks: 1,
      workedSolution: "x² − 9 is a difference of two squares: a² − b² = (a + b)(a − b) with a = x, b = 3. Check by expanding: (x + 3)(x − 3) = x² − 9.",
      misconceptionTag: "N5 — Algebraic Manipulation",
      mapsToProduct: "companion",
    },
    ],
  },
  {
    level: "o-level",
    slug: "geography-elective",
    topicLabel: "Mixed — the VERY HIGH topics",
    questions: [
    {
      id: "geography-elective-vq1",
      type: "mcq",
      topic: "GE2 Tourism",
      stem: "A person travelling from Singapore to Bangkok for a three-day holiday is classified as:",
      options: ["a domestic tourist", "an international tourist", "an excursionist", "a migrant"],
      correctKey: ["1"],
      marks: 1,
      workedSolution: "Crossing an international border for a stay of at least one night makes an international tourist. Domestic tourism happens within one's own country; a same-day visitor is an excursionist.",
      misconceptionTag: "GE2 Tourism",
      mapsToProduct: "vault",
    },
    {
      id: "geography-elective-vq2",
      type: "mcq",
      topic: "GE2 Tourism",
      stem: "The multiplier effect of tourism refers to:",
      options: ["tourists returning many times", "tourist spending circulating and generating further income in the local economy", "hotels doubling their prices", "the growth of package tours"],
      correctKey: ["1"],
      marks: 1,
      workedSolution: "A tourist dollar spent at a hotel pays wages, buys local produce and gets spent again — each round generates additional local income beyond the original spending.",
      misconceptionTag: "GE2 Tourism",
      mapsToProduct: "vault",
    },
    {
      id: "geography-elective-vq3",
      type: "mcq",
      topic: "GE2 Tourism",
      stem: "In tourism economics, 'leakage' occurs when:",
      options: ["tourists overstay their visas", "tourism income leaves the destination, e.g. to foreign-owned chains", "hotels waste water", "attractions close in the off-season"],
      correctKey: ["1"],
      marks: 1,
      workedSolution: "Leakage is the share of tourism revenue that exits the local economy — repatriated profits of foreign operators, imported food, overseas marketing — shrinking the multiplier.",
      misconceptionTag: "GE2 Tourism",
      mapsToProduct: "vault",
    },
    {
      id: "geography-elective-vq4",
      type: "mcq",
      topic: "GE1.3 Fieldwork & Geographical Methods",
      stem: "Which of these is PRIMARY data for a tourism fieldwork study?",
      options: ["visitor arrival statistics from a tourism board", "your own questionnaire responses collected on site", "a travel blog", "an atlas map"],
      correctKey: ["1"],
      marks: 1,
      workedSolution: "Primary data is gathered first-hand — your questionnaires, counts and observations. Official statistics and publications, however reliable, are secondary sources.",
      misconceptionTag: "GE1.3 Fieldwork & Geographical Methods",
      mapsToProduct: "companion",
    },
    {
      id: "geography-elective-vq5",
      type: "mcq",
      topic: "GE2 Tourism",
      stem: "Sustainable tourism primarily aims to:",
      options: ["maximise visitor numbers every year", "meet tourists' needs while protecting the environment and benefiting local communities long-term", "replace all local businesses with resorts", "keep destinations secret"],
      correctKey: ["1"],
      marks: 1,
      workedSolution: "Sustainability balances the economic gains of tourism against environmental protection and local wellbeing, so the destination still prospers for future generations.",
      misconceptionTag: "GE2 Tourism",
      mapsToProduct: "vault",
    },
    ],
  },
  {
    level: "o-level",
    slug: "geography-pure",
    topicLabel: "Mixed — the VERY HIGH topics",
    questions: [
    {
      id: "geography-pure-vq1",
      type: "mcq",
      topic: "G1.3 Fieldwork & Geographical Methods",
      stem: "Which of these is PRIMARY data in a geographical investigation?",
      options: ["population figures from a government website", "temperature readings you take on site", "a newspaper report", "a published journal article"],
      correctKey: ["1"],
      marks: 1,
      workedSolution: "Primary data is collected first-hand by the investigator — your own measurements, counts or survey responses. Anything already published by others is secondary data.",
      misconceptionTag: "G1.3 Fieldwork & Geographical Methods",
      mapsToProduct: "companion",
    },
    {
      id: "geography-pure-vq2",
      type: "mcq",
      topic: "G1.3 Fieldwork & Geographical Methods",
      stem: "In systematic sampling, sample points are chosen:",
      options: ["wherever is easiest to reach", "at regular, fixed intervals", "only where results look interesting", "by asking volunteers"],
      correctKey: ["1"],
      marks: 1,
      workedSolution: "Systematic sampling takes measurements at regular intervals — every 10 m along a transect, every 5th passer-by — reducing bias while staying practical in the field.",
      misconceptionTag: "G1.3 Fieldwork & Geographical Methods",
      mapsToProduct: "companion",
    },
    {
      id: "geography-pure-vq3",
      type: "mcq",
      topic: "G1.1 Thinking Geographically",
      stem: "In geography, a 'place' differs from a 'space' because a place:",
      options: ["is always larger", "has meanings and identity attached to it by people", "cannot change over time", "only exists in cities"],
      correctKey: ["1"],
      marks: 1,
      workedSolution: "Space is location; place is location made meaningful — the memories, uses and identities people attach to it. It's the lens for the whole 2279 syllabus.",
      misconceptionTag: "G1.1 Thinking Geographically",
      mapsToProduct: "vault",
    },
    {
      id: "geography-pure-vq4",
      type: "mcq",
      topic: "G5.1 Singapore: Small Island City-State",
      stem: "Which strategy has Singapore used most directly to overcome its land constraint?",
      options: ["claiming territory from neighbours", "land reclamation and building upwards and underground", "abandoning industry", "capping its population at one million"],
      correctKey: ["1"],
      marks: 1,
      workedSolution: "Reclamation has grown Singapore's land area by about a quarter since independence, alongside intensifying use upward (high-rise) and downward (underground) — the classic small-state response.",
      misconceptionTag: "G5.1 Singapore: Small Island City-State",
      mapsToProduct: "vault",
    },
    {
      id: "geography-pure-vq5",
      type: "mcq",
      topic: "G1.3 Fieldwork & Geographical Methods",
      stem: "A good hypothesis for fieldwork must be:",
      options: ["a question with no expected answer", "a testable statement that data can support or reject", "a proven fact", "an opinion about the area"],
      correctKey: ["1"],
      marks: 1,
      workedSolution: "A hypothesis states an expected relationship — 'pedestrian counts fall with distance from the MRT' — that your measurements can confirm or reject. If no data could disprove it, it isn't testable.",
      misconceptionTag: "G1.3 Fieldwork & Geographical Methods",
      mapsToProduct: "companion",
    },
    ],
  },
  {
    level: "o-level",
    slug: "history-elective",
    topicLabel: "Mixed — the VERY HIGH topics",
    questions: [
    {
      id: "history-elective-vq1",
      type: "mcq",
      topic: "H2 Nazi Germany",
      stem: "After the Reichstag Fire of February 1933, the Decree for the Protection of People and State:",
      options: ["suspended civil liberties and allowed arrest without trial", "banned the Nazi Party", "restored the Kaiser", "ended the Depression"],
      correctKey: ["0"],
      marks: 1,
      workedSolution: "The Reichstag Fire Decree suspended basic freedoms — press, assembly, privacy — and let the regime imprison opponents without trial, clearing the road to the Enabling Act.",
      misconceptionTag: "H2 Nazi Germany",
      mapsToProduct: "vault",
    },
    {
      id: "history-elective-vq2",
      type: "mcq",
      topic: "H7 Origins of the Cold War",
      stem: "How did the Western powers respond to the Berlin Blockade of 1948-49?",
      options: ["they abandoned West Berlin", "they supplied the city by air for almost a year", "they invaded East Germany", "they built the Berlin Wall"],
      correctKey: ["1"],
      marks: 1,
      workedSolution: "The Berlin Airlift flew food and fuel into West Berlin for nearly eleven months until Stalin lifted the blockade — a defining containment victory without a shot fired.",
      misconceptionTag: "H7 Origins of the Cold War",
      mapsToProduct: "vault",
    },
    {
      id: "history-elective-vq3",
      type: "mcq",
      topic: "H8 Korean War 1950-53",
      stem: "The Korean War began in June 1950 when:",
      options: ["UN forces landed at Incheon", "North Korean forces invaded South Korea across the 38th parallel", "China attacked Japan", "the USA bombed Pyongyang"],
      correctKey: ["1"],
      marks: 1,
      workedSolution: "North Korea's surprise invasion across the 38th parallel opened the war; the UN force under MacArthur intervened, and the Incheon landing came later, in September 1950.",
      misconceptionTag: "H8 Korean War 1950-53",
      mapsToProduct: "vault",
    },
    {
      id: "history-elective-vq4",
      type: "mcq",
      topic: "H2 Nazi Germany",
      stem: "The Night of the Long Knives (June 1934) removed which threat to Hitler's power?",
      options: ["the SS", "the SA leadership under Ernst Röhm", "the Catholic Church", "the army generals"],
      correctKey: ["1"],
      marks: 1,
      workedSolution: "Hitler purged Röhm and the SA leadership to reassure the army and eliminate a rival power base — after it, the army swore a personal oath to Hitler.",
      misconceptionTag: "H2 Nazi Germany",
      mapsToProduct: "vault",
    },
    {
      id: "history-elective-vq5",
      type: "mcq",
      topic: "H7 Origins of the Cold War",
      stem: "The Marshall Plan of 1947 aimed to:",
      options: ["rearm Western Europe", "rebuild European economies to resist communism", "punish Germany with reparations", "create the United Nations"],
      correctKey: ["1"],
      marks: 1,
      workedSolution: "Marshall Aid poured US dollars into rebuilding Western Europe on the logic that prosperity would starve communism of support — the USSR forbade its satellites from accepting it.",
      misconceptionTag: "H7 Origins of the Cold War",
      mapsToProduct: "vault",
    },
    ],
  },
  {
    level: "o-level",
    slug: "history-pure",
    topicLabel: "Mixed — the VERY HIGH topics",
    questions: [
    {
      id: "history-pure-vq1",
      type: "mcq",
      topic: "P1.1 British Malaya 1870s-1920s",
      stem: "Under the Residential System that followed the Pangkor Engagement of 1874, the Resident's advice had to be followed in all matters EXCEPT:",
      options: ["taxation and revenue", "Malay religion and custom", "land administration", "appointment of officials"],
      correctKey: ["1"],
      marks: 1,
      workedSolution: "The Pangkor Engagement required the Sultan to act on the Resident's advice in all matters except those touching Malay religion and custom — the carve-out that defined the system's limits.",
      misconceptionTag: "P1.1 British Malaya 1870s-1920s",
      mapsToProduct: "vault",
    },
    {
      id: "history-pure-vq2",
      type: "mcq",
      topic: "P2.5 Malaya decolonisation 1945-1957",
      stem: "Why did many Malays oppose the Malayan Union of 1946?",
      options: ["it delayed independence", "it gave equal citizenship to non-Malays and cut the Sultans' powers", "it banned political parties", "it merged Malaya with Singapore"],
      correctKey: ["1"],
      marks: 1,
      workedSolution: "The Malayan Union offered citizenship on equal terms to non-Malays and transferred the Sultans' sovereignty to the British Crown — provoking mass Malay opposition led by UMNO, and its replacement by the Federation of Malaya in 1948.",
      misconceptionTag: "P2.5 Malaya decolonisation 1945-1957",
      mapsToProduct: "vault",
    },
    {
      id: "history-pure-vq3",
      type: "mcq",
      topic: "P1.4 Nazi Germany",
      stem: "What did the Enabling Act of March 1933 allow Hitler to do?",
      options: ["dissolve the army", "make laws without the Reichstag", "abolish the presidency immediately", "leave the League of Nations"],
      correctKey: ["1"],
      marks: 1,
      workedSolution: "The Enabling Act let Hitler's government issue laws without the Reichstag — the legal foundation of the dictatorship. Within months all other parties were banned.",
      misconceptionTag: "P1.4 Nazi Germany",
      mapsToProduct: "vault",
    },
    {
      id: "history-pure-vq4",
      type: "mcq",
      topic: "P2.2 Origins of the Cold War",
      stem: "The Truman Doctrine of 1947 committed the USA to:",
      options: ["rebuilding Japan's military", "supporting free peoples resisting communist pressure", "joining the Warsaw Pact", "dividing Germany permanently"],
      correctKey: ["1"],
      marks: 1,
      workedSolution: "Truman pledged American support for 'free peoples' resisting armed minorities or outside pressure — the policy of containment, first applied to Greece and Turkey.",
      misconceptionTag: "P2.2 Origins of the Cold War",
      mapsToProduct: "vault",
    },
    {
      id: "history-pure-vq5",
      type: "mcq",
      topic: "P2.5 Malaya decolonisation 1945-1957",
      stem: "In which year did the Federation of Malaya achieve independence (Merdeka)?",
      options: ["1948", "1955", "1957", "1963"],
      correctKey: ["2"],
      marks: 1,
      workedSolution: "Merdeka came on 31 August 1957, with Tunku Abdul Rahman as the first Prime Minister. 1948 was the Federation agreement; 1963 was the formation of Malaysia.",
      misconceptionTag: "P2.5 Malaya decolonisation 1945-1957",
      mapsToProduct: "vault",
    },
    ],
  },
  {
    level: "o-level",
    slug: "physics-pure",
    topicLabel: "Mixed — the VERY HIGH topics",
    questions: [
    {
      id: "physics-pure-vq1",
      type: "mcq",
      topic: "T20 Radioactivity",
      stem: "A nucleus of radium is written as ²²⁶₈₈Ra. How many neutrons does this nucleus contain?",
      options: ["88", "138", "226", "314"],
      correctKey: ["1"],
      marks: 1,
      workedSolution: "The lower number (88) is the proton number and the upper number (226) is the nucleon (mass) number. Neutrons are the difference: 226 − 88 = 138. Option A (88) is the proton count, C (226) is the total nucleons and D adds the two numbers by mistake.",
      misconceptionTag: "T20 Radioactivity",
      mapsToProduct: "vault",
    },
    {
      id: "physics-pure-vq2",
      type: "mcq",
      topic: "T12 Light",
      stem: "A narrow beam of light enters a rectangular glass block from the air. It strikes the top surface at an angle of incidence of 40° and bends to an angle of refraction of 25° inside the glass. What is the refractive index of the glass? (sin 40° = 0.643, sin 25° = 0.423)",
      options: ["0.66", "1.52", "1.60", "1.75"],
      correctKey: ["1"],
      marks: 1,
      workedSolution: "Refractive index n = sin i / sin r, using the angles measured from the normal: 0.643 ÷ 0.423 = 1.52. Option A inverts the fraction (sin r / sin i); the others come from using the wrong pair of angles.",
      misconceptionTag: "T12 Light",
      mapsToProduct: "vault",
    },
    {
      id: "physics-pure-vq3",
      type: "mcq",
      topic: "T3 Dynamics",
      stem: "A loaded supermarket trolley is pushed along a level, frictionless floor. A single resultant force of 18 N gives it an acceleration of 2.5 m/s². What is the total mass of the trolley and its load?",
      options: ["0.14 kg", "7.2 kg", "20.5 kg", "45 kg"],
      correctKey: ["1"],
      marks: 1,
      workedSolution: "Rearranging F = ma gives m = F/a = 18 ÷ 2.5 = 7.2 kg. Option A inverts the fraction; option D multiplies force by acceleration; option C adds them.",
      misconceptionTag: "T3 Dynamics",
      mapsToProduct: "vault",
    },
    {
      id: "physics-pure-vq4",
      type: "mcq",
      topic: "T15 D.C. Circuits",
      stem: "Two resistors of 6.0 Ω and 3.0 Ω are connected in parallel. What is their combined (effective) resistance?",
      options: ["2.0 Ω", "4.5 Ω", "9.0 Ω", "18 Ω"],
      correctKey: ["0"],
      marks: 1,
      workedSolution: "For parallel resistors 1/R = 1/6.0 + 1/3.0 = 1/6.0 + 2/6.0 = 3/6.0, giving R = 2.0 Ω. The combined parallel resistance is always smaller than the smallest branch (3.0 Ω), which rules out every larger option. Option C is the series value; D multiplies them.",
      misconceptionTag: "T15 D.C. Circuits",
      mapsToProduct: "vault",
    },
    {
      id: "physics-pure-vq5",
      type: "mcq",
      topic: "T20 Radioactivity",
      stem: "Three types of radiation pass through a magnetic field directed into the page. One type is deflected strongly, one is deflected weakly in the opposite direction, and one is not deflected at all. Which statement is correct?",
      options: ["The undeflected radiation is alpha.", "The strongly deflected radiation is gamma.", "The weakly deflected radiation is alpha and the strongly deflected radiation is beta.", "All three are deflected because all carry charge."],
      correctKey: ["2"],
      marks: 1,
      workedSolution: "Beta particles are very light electrons, so a magnetic force deflects them strongly. Alpha particles are about 8000 times heavier, so the same field deflects them only weakly, and in the opposite sense because their charge is opposite. Gamma rays carry no charge, so they pass straight through undeflected.",
      misconceptionTag: "T20 Radioactivity",
      mapsToProduct: "vault",
    },
    ],
  },
  {
    level: "o-level",
    slug: "physics-science",
    topicLabel: "Mixed — the VERY HIGH topics",
    questions: [
    {
      id: "physics-science-vq1",
      type: "mcq",
      topic: "T16 Radioactivity",
      stem: "A teacher demonstrates that a radioactive source emits all three types of nuclear radiation. Which row lists the radiations in order from most ionising to least ionising?",
      options: ["alpha → beta → gamma", "gamma → beta → alpha", "beta → alpha → gamma", "gamma → alpha → beta"],
      correctKey: ["0"],
      marks: 1,
      workedSolution: "Ionising power runs opposite to penetrating power: alpha is the heaviest and carries the most charge, so it ionises most strongly but is stopped first; gamma is uncharged, weakly ionising and most penetrating.",
      misconceptionTag: "T16 Radioactivity",
      mapsToProduct: "vault",
    },
    {
      id: "physics-science-vq2",
      type: "mcq",
      topic: "T13 D.C. Circuits",
      stem: "Two 4.0 Ω resistors are connected in parallel. This pair is then connected in series with a 2.0 Ω resistor. What is the effective resistance of the whole combination?",
      options: ["2.0 Ω", "4.0 Ω", "6.0 Ω", "10 Ω"],
      correctKey: ["1"],
      marks: 1,
      workedSolution: "Two equal resistors in parallel halve: 4.0 Ω becomes 2.0 Ω. Adding the series 2.0 Ω gives 4.0 Ω overall.",
      misconceptionTag: "T13 D.C. Circuits",
      mapsToProduct: "vault",
    },
    {
      id: "physics-science-vq3",
      type: "mcq",
      topic: "T7 Kinetic Particle Model",
      stem: "A sealed rigid container of gas is heated. Why does the pressure increase?",
      options: ["the particles expand", "the particles hit the walls harder and more often", "the number of particles increases", "the particles stick to the walls"],
      correctKey: ["1"],
      marks: 1,
      workedSolution: "Heating raises the average kinetic energy: particles move faster, striking the container walls harder and more frequently — that IS the pressure rise. The particles themselves do not expand and none are added.",
      misconceptionTag: "T7 Kinetic Particle Model",
      mapsToProduct: "companion",
    },
    {
      id: "physics-science-vq4",
      type: "short",
      topic: "T3 Force & Pressure",
      stem: "A force of 60 N acts on an area of 0.2 m². Calculate the pressure in pascals (Pa).",
      correctKey: ["300", "300 pa", "300pa"],
      marks: 1,
      workedSolution: "Pressure = force ÷ area = 60 ÷ 0.2 = 300 Pa. Keep the units consistent: newtons over square metres gives pascals directly.",
      misconceptionTag: "T3 Force & Pressure",
      mapsToProduct: "vault",
    },
    {
      id: "physics-science-vq5",
      type: "mcq",
      topic: "T1 Physical Quantities & Measurement",
      stem: "Which statement about mass and weight is correct?",
      options: ["mass is a force measured in newtons", "weight is the amount of matter in a body", "mass stays the same everywhere; weight depends on gravitational field strength", "weight stays the same everywhere; mass depends on gravity"],
      correctKey: ["2"],
      marks: 1,
      workedSolution: "Mass (kg) is the amount of matter and never changes with location; weight (N) is the gravitational force on that mass, W = mg — so it falls on the Moon while mass is unchanged.",
      misconceptionTag: "T1 Physical Quantities & Measurement",
      mapsToProduct: "vault",
    },
    ],
  },
  {
    level: "o-level",
    slug: "principles-of-accounts",
    topicLabel: "Mixed — the VERY HIGH topics",
    questions: [
    {
      id: "principles-of-accounts-vq1",
      type: "mcq",
      topic: "P13 Ratios & Interpretation",
      stem: "A business reports a gross profit margin that has fallen from 40% to 32% over one year, while the mark-up on cost was left unchanged. Which single change is the most likely cause?",
      options: ["The business sold a higher volume of goods.", "Selling prices were cut to clear slow-moving inventory, without a matching fall in cost.", "Trade receivables were collected more quickly.", "The owner increased their drawings."],
      correctKey: ["1"],
      marks: 1,
      workedSolution: "Gross profit margin = gross profit / revenue. If cost per unit is unchanged but selling prices are cut, each dollar of sales carries less gross profit, so the margin falls. Collection speed and drawings affect liquidity and equity, not the gross margin; higher volume alone does not change the margin.",
      misconceptionTag: "P13 Ratios & Interpretation",
      mapsToProduct: "vault",
    },
    {
      id: "principles-of-accounts-vq2",
      type: "mcq",
      topic: "P13 — Accounting Ratios & Interpretation",
      stem: "Which formula gives the current ratio?",
      options: ["current assets ÷ current liabilities", "current liabilities ÷ current assets", "gross profit ÷ revenue", "net profit ÷ capital"],
      correctKey: ["0"],
      marks: 1,
      workedSolution: "The current ratio compares what the business can turn into cash within the year against what it owes within the year: current assets ÷ current liabilities. Gross profit ÷ revenue is the gross profit margin.",
      misconceptionTag: "P13 — Accounting Ratios & Interpretation",
      mapsToProduct: "vault",
    },
    {
      id: "principles-of-accounts-vq3",
      type: "mcq",
      topic: "P6 — Adjustments",
      stem: "At the year end, rent paid in advance for the next financial year should be treated as:",
      options: ["an expense of this year", "a current asset (prepayment)", "a current liability (accrual)", "income of this year"],
      correctKey: ["1"],
      marks: 1,
      workedSolution: "Only the portion that belongs to THIS year is this year's expense. Rent covering next year is a prepayment — a current asset — because the business has paid for a benefit it has not yet used.",
      misconceptionTag: "P6 — Adjustments",
      mapsToProduct: "companion",
    },
    {
      id: "principles-of-accounts-vq4",
      type: "mcq",
      topic: "P8 — Financial Statements — Limited Company",
      stem: "Which item appears in the equity of a limited company but never of a sole trader?",
      options: ["drawings", "share capital", "trade payables", "inventory"],
      correctKey: ["1"],
      marks: 1,
      workedSolution: "Companies raise equity by issuing shares, so share capital (and retained earnings) sit in company equity. A sole trader's equity is capital plus profit less drawings — there are no shares to issue.",
      misconceptionTag: "P8 — Financial Statements — Limited Comp",
      mapsToProduct: "vault",
    },
    {
      id: "principles-of-accounts-vq5",
      type: "mcq",
      topic: "P6 — Adjustments",
      stem: "Wages for the last week of the financial year will only be paid next month. At the year end this amount is:",
      options: ["ignored until paid", "added to wages expense and shown as a current liability", "deducted from wages expense", "shown as a current asset"],
      correctKey: ["1"],
      marks: 1,
      workedSolution: "The expense belongs to the period the work was done (the accruals concept): add it to wages expense AND show the unpaid amount as an accrued expense under current liabilities.",
      misconceptionTag: "P6 — Adjustments",
      mapsToProduct: "companion",
    },
    ],
  },
  {
    level: "o-level",
    slug: "social-studies",
    topicLabel: "Mixed — the VERY HIGH topics",
    questions: [
    {
      id: "social-studies-vq1",
      type: "mcq",
      topic: "Issue 1 — Citizenship and Governance",
      stem: "In governance, a 'trade-off' refers to:",
      options: ["a trade agreement between countries", "giving up one benefit to gain another when resources are limited", "exchanging ministers between ministries", "a fall in trade volume"],
      correctKey: ["1"],
      marks: 1,
      workedSolution: "Governing means choosing between competing needs — spending more on healthcare may mean less for defence. Recognising what is given up is the heart of evaluating policy decisions.",
      misconceptionTag: "Issue 1 — Citizenship and Governance",
      mapsToProduct: "companion",
    },
    {
      id: "social-studies-vq2",
      type: "mcq",
      topic: "Issue 1 — Citizenship and Governance",
      stem: "Which principle of governance is shown when a government plans for challenges BEFORE they arrive?",
      options: ["leadership is key", "anticipate change and stay relevant", "reward for work and work for reward", "a stake for everyone"],
      correctKey: ["1"],
      marks: 1,
      workedSolution: "'Anticipate change and stay relevant' is the forward-looking principle — planning for ageing, climate or economic shifts before they bite.",
      misconceptionTag: "Issue 1 — Citizenship and Governance",
      mapsToProduct: "vault",
    },
    {
      id: "social-studies-vq3",
      type: "mcq",
      topic: "Issue 2 — Living in a Diverse Society",
      stem: "Integration differs from assimilation because integration:",
      options: ["requires minorities to abandon their culture", "lets communities keep their identities while building common ground", "separates communities physically", "applies only to new citizens"],
      correctKey: ["1"],
      marks: 1,
      workedSolution: "Assimilation absorbs minorities into the majority culture; integration keeps distinct identities while strengthening shared experiences — Singapore's approach to managing diversity.",
      misconceptionTag: "Issue 2 — Living in a Diverse Society",
      mapsToProduct: "vault",
    },
    {
      id: "social-studies-vq4",
      type: "mcq",
      topic: "Issue 3 — Being Part of a Globalised World",
      stem: "Which development most directly drove modern globalisation?",
      options: ["advances in transport and communications technology", "the end of all trade barriers worldwide", "a single world government", "identical cultures everywhere"],
      correctKey: ["0"],
      marks: 1,
      workedSolution: "Cheaper, faster transport and instant communications shrank distance — the enabling condition for global flows of goods, people, capital and ideas.",
      misconceptionTag: "Issue 3 — Being Part of a Globalised Wor",
      mapsToProduct: "vault",
    },
    {
      id: "social-studies-vq5",
      type: "mcq",
      topic: "Issue 2 — Living in a Diverse Society",
      stem: "The Ethnic Integration Policy (EIP) in Singapore's public housing aims to:",
      options: ["reserve estates for one community", "maintain a balanced ethnic mix in HDB estates", "price flats by ethnic group", "speed up en-bloc sales"],
      correctKey: ["1"],
      marks: 1,
      workedSolution: "The EIP sets ethnic proportions block by block so no estate becomes an enclave — everyday interaction across communities is the policy's goal.",
      misconceptionTag: "Issue 2 — Living in a Diverse Society",
      mapsToProduct: "vault",
    },
    ],
  },
];

export function getDiagnosticSet(level: string, slug: string): DiagnosticSet | undefined {
  return SETS.find((s) => s.level === level && s.slug === slug);
}

export function listDiagnosticSets(): {
  level: string;
  slug: string;
  topicLabel: string;
}[] {
  return SETS.map((s) => ({ level: s.level, slug: s.slug, topicLabel: s.topicLabel }));
}

// What the browser is allowed to see before submission.
export interface PublicQuestion {
  id: string;
  type: "mcq" | "short";
  topic: string;
  stem: string;
  options?: string[];
  marks: number;
}

export function sanitizeSet(set: DiagnosticSet): {
  topicLabel: string;
  questions: PublicQuestion[];
  totalMarks: number;
} {
  return {
    topicLabel: set.topicLabel,
    questions: set.questions.map(({ id, type, topic, stem, options, marks }) => ({
      id,
      type,
      topic,
      stem,
      options,
      marks,
    })),
    totalMarks: set.questions.reduce((sum, q) => sum + q.marks, 0),
  };
}
