// The REAL 2026 prediction tables, extracted from each subject's Forecast
// PDF (private/pdfs/<level>/<slug>/forecast.pdf, "The 2026 prediction
// table" section). The study-plan checklist must match what the customer's
// PDF says — never the site's illustrative topic generator. Regenerate by
// re-running the extraction when forecast PDFs are updated.
import type { ForecastTier } from "@/components/heat";

export interface ForecastTableRow {
  topic: string;
  tier: ForecastTier;
}

/** The real table's top `n` calls for a subject (empty if no table exists). */
export function realTopCalls(
  level: string,
  slug: string,
  n = 5
): ForecastTableRow[] {
  return (FORECAST_TABLES[`${level}/${slug}`] ?? []).slice(0, n);
}

export const FORECAST_TABLES: Record<string, ForecastTableRow[]> = {
  "na-level/a-math": [
    { topic: "Calculus (Differentiation & Integration)", tier: "very-high" },
    { topic: "Trigonometry (Functions, Identities, R-formula)", tier: "very-high" },
    { topic: "Polynomials & Partial Fractions", tier: "high" },
    { topic: "Coordinate Geometry & Circles", tier: "high" },
    { topic: "Equations & Inequalities", tier: "high" },
    { topic: "Surds", tier: "moderate" },
    { topic: "Quadratic Functions", tier: "watch" },
  ],
  "na-level/biology": [
    { topic: "Nutrition & Transport in Flowering Plants", tier: "very-high" },
    { topic: "Respiration in Humans", tier: "very-high" },
    { topic: "Nutrition in Humans", tier: "high" },
    { topic: "Transport in Humans", tier: "high" },
    { topic: "Biological Molecules & Enzymes", tier: "high" },
    { topic: "Movement of Substances", tier: "moderate" },
    { topic: "Cell Structure and Organisation", tier: "moderate" },
    { topic: "Infectious Diseases in Humans", tier: "high" },
  ],
  "na-level/chemistry": [
    { topic: "Organic Chemistry", tier: "very-high" },
    { topic: "Patterns in the Periodic Table", tier: "very-high" },
    { topic: "Experimental Chemistry", tier: "high" },
    { topic: "Chemical Calculations", tier: "high" },
    { topic: "Chemical Bonding and Structure", tier: "high" },
    { topic: "The Particulate Nature of Matter", tier: "moderate" },
    { topic: "Acid-Base Chemistry", tier: "moderate" },
    { topic: "Maintaining Air Quality", tier: "moderate" },
    { topic: "Qualitative Analysis", tier: "watch" },
  ],
  "na-level/e-math": [
    { topic: "Equations & Inequalities", tier: "very-high" },
    { topic: "Data Handling & Analysis", tier: "very-high" },
    { topic: "Mensuration", tier: "very-high" },
    { topic: "Numbers & Their Operations", tier: "very-high" },
    { topic: "Pythagoras' Theorem & Trigonometry", tier: "very-high" },
    { topic: "Algebraic Expressions & Formulae", tier: "high" },
    { topic: "Functions & Graphs", tier: "high" },
    { topic: "Percentage", tier: "high" },
    { topic: "Ratio & Proportion", tier: "high" },
    { topic: "Coordinate Geometry", tier: "high" },
    { topic: "Angles, Triangles & Polygons", tier: "moderate" },
    { topic: "Congruence & Similarity", tier: "moderate" },
    { topic: "Rate & Speed", tier: "moderate" },
    { topic: "Probability", tier: "moderate" },
    { topic: "Properties of Circles", tier: "watch" },
  ],
  "na-level/food-and-nutrition": [
    { topic: "Diet & Meal Planning", tier: "very-high" },
    { topic: "Preparation & Cooking of Food", tier: "very-high" },
    { topic: "Functional Properties & Reactions", tier: "very-high" },
    { topic: "Diet & Health Problems", tier: "very-high" },
    { topic: "Methods of Cooking", tier: "high" },
    { topic: "Convenience Food & Food Labels", tier: "high" },
    { topic: "Proteins", tier: "high" },
    { topic: "Food Safety & Hygiene", tier: "high" },
    { topic: "Vitamins", tier: "moderate" },
    { topic: "Minerals", tier: "moderate" },
    { topic: "Fats", tier: "moderate" },
    { topic: "Sensory Evaluation", tier: "moderate" },
    { topic: "Dietary Fibre", tier: "watch" },
    { topic: "Carbohydrates", tier: "moderate" },
    { topic: "Meal Analysis & Modification", tier: "watch" },
    { topic: "Water", tier: "moderate" },
  ],
  "na-level/history": [
    { topic: "H2 Nazi Germany", tier: "very-high" },
    { topic: "H7 Origins of the Cold War in Europe", tier: "very-high" },
    { topic: "H4 Outbreak of WWII in Europe", tier: "high" },
    { topic: "H9 Decline of the USSR & end of the Cold War", tier: "high" },
    { topic: "H5 Outbreak of WWII in the Asia-Pacific", tier: "moderate" },
    { topic: "H6 Reasons for the end of WWII", tier: "moderate" },
    { topic: "H1 Paris Peace, Versailles & the League", tier: "moderate" },
    { topic: "H8 Vietnam War 1954-75", tier: "watch" },
    { topic: "H3 Rise of authoritarian regimes (context)", tier: "watch" },
  ],
  "na-level/physics": [
    { topic: "Force & Pressure", tier: "very-high" },
    { topic: "D.C. Circuits", tier: "very-high" },
    { topic: "Kinematics", tier: "very-high" },
    { topic: "Energy", tier: "very-high" },
    { topic: "Practical Electricity", tier: "very-high" },
    { topic: "General Properties of Waves", tier: "high" },
    { topic: "Thermal Processes", tier: "high" },
    { topic: "Physical Quantities, Units & Measurement", tier: "moderate" },
    { topic: "Kinetic Particle Model of Matter", tier: "moderate" },
    { topic: "Electric Charge & Current of Electricity", tier: "high" },
    { topic: "Radioactivity", tier: "high" },
    { topic: "Dynamics", tier: "watch" },
    { topic: "Electromagnetic Spectrum", tier: "watch" },
  ],
  "na-level/principles-of-accounts": [
    { topic: "G10 Financial Statements (Performance + Position)", tier: "very-high" },
    { topic: "G7 Inventory, Non-Current Assets & Depreciation", tier: "very-high" },
    { topic: "G5 Double Entry, Journals, Ledgers & Trial Balance", tier: "very-high" },
    { topic: "G8 Trade Receivables & Impairment", tier: "very-high" },
    { topic: "G9 Liabilities, Capital, Drawings & Equity", tier: "high" },
    { topic: "G11 Correction of Errors & Bank Reconciliation", tier: "high" },
    { topic: "G6 Income & Expenses and Year-End Adjustments", tier: "high" },
    { topic: "G3 Elements, Accounting Equation & Types of Business", tier: "high" },
    { topic: "G4 Source Documents & Internal Controls", tier: "moderate" },
    { topic: "G2 Accounting Theories (assumptions & principles)", tier: "moderate" },
    { topic: "G1 Accounting, Accountants, Stakeholders & Ethics", tier: "moderate" },
    { topic: "Scenario-Based Decision Question", tier: "moderate" },
  ],
  "o-level/a-math": [
    { topic: "Calculus (Differentiation, Integration & Kinematics)", tier: "very-high" },
    { topic: "Trigonometry (Functions, Identities, R-formula)", tier: "very-high" },
    { topic: "Coordinate Geometry, Circles & Linear Law", tier: "high" },
    { topic: "Exponential & Logarithmic Functions", tier: "high" },
    { topic: "Polynomials & Partial Fractions", tier: "high" },
    { topic: "Equations & Inequalities", tier: "moderate" },
    { topic: "Plane Geometry Proofs", tier: "moderate" },
    { topic: "Binomial Expansions", tier: "moderate" },
    { topic: "Quadratic Functions", tier: "moderate" },
    { topic: "Surds", tier: "watch" },
  ],
  "o-level/biology-pure": [
    { topic: "T14 Inheritance", tier: "very-high" },
    { topic: "T8 Homeostasis, Co-ordination & Response", tier: "very-high" },
    { topic: "T11 Organisms & their Environment", tier: "very-high" },
    { topic: "T5 Transport in Humans", tier: "very-high" },
    { topic: "T10 Nutrition & Transport in Plants", tier: "very-high" },
    { topic: "T7 Excretion in Humans", tier: "high" },
    { topic: "T13 Reproduction", tier: "high" },
    { topic: "T3 Biological Molecules & Enzymes", tier: "high" },
    { topic: "T6 Respiration in Humans", tier: "high" },
    { topic: "T9 Infectious Diseases in Humans", tier: "high" },
    { topic: "T1 Cell Structure & Organisation", tier: "moderate" },
    { topic: "T4 Nutrition in Humans", tier: "moderate" },
    { topic: "T2 Movement of Substances", tier: "moderate" },
    { topic: "T12 Molecular Genetics", tier: "moderate" },
  ],
  "o-level/biology-science": [
    { topic: "T9 Nutrition & Transport in Flowering Plants", tier: "very-high" },
    { topic: "T10 Organisms & their Environment", tier: "very-high" },
    { topic: "T8 Homeostasis & Co-ordination", tier: "very-high" },
    { topic: "T5 Transport in Humans", tier: "very-high" },
    { topic: "T7 Infectious Diseases in Humans", tier: "very-high" },
    { topic: "T6 Respiration in Humans", tier: "high" },
    { topic: "T13 Inheritance", tier: "high" },
    { topic: "T4 Nutrition in Humans", tier: "high" },
    { topic: "T3 Biological Molecules & Enzymes", tier: "moderate" },
    { topic: "T11 Molecular Genetics", tier: "moderate" },
    { topic: "T1 Cell Structure & Organisation", tier: "moderate" },
    { topic: "T12 Reproduction in Humans", tier: "moderate" },
    { topic: "T2 Movement of Substances", tier: "moderate" },
  ],
  "o-level/chemistry-pure": [
    { topic: "C4 Chemical Calculations", tier: "very-high" },
    { topic: "C11 Organic Chemistry", tier: "very-high" },
    { topic: "C3 Chemical Bonding & Structure", tier: "very-high" },
    { topic: "C7 Redox Chemistry & Electrochemistry", tier: "very-high" },
    { topic: "C5 Acid-Base Chemistry", tier: "very-high" },
    { topic: "C8 Patterns in the Periodic Table", tier: "high" },
    { topic: "C10 Rate of Reactions", tier: "high" },
    { topic: "C12 Maintaining Air Quality", tier: "high" },
    { topic: "C2 Particulate Nature of Matter", tier: "moderate" },
    { topic: "C9 Chemical Energetics", tier: "moderate" },
    { topic: "C6 Qualitative Analysis", tier: "moderate" },
    { topic: "C1 Experimental Chemistry", tier: "watch" },
  ],
  "o-level/chemistry-science": [
    { topic: "C11 Organic Chemistry", tier: "very-high" },
    { topic: "C4 Chemical Calculations", tier: "very-high" },
    { topic: "C3 Chemical Bonding & Structure", tier: "very-high" },
    { topic: "C8 Patterns in the Periodic Table", tier: "very-high" },
    { topic: "C6 Qualitative Analysis", tier: "very-high" },
    { topic: "C2 Particulate Nature of Matter", tier: "high" },
    { topic: "C5 Acid-Base Chemistry", tier: "high" },
    { topic: "C10 Rate of Reactions", tier: "high" },
    { topic: "C12 Maintaining Air Quality", tier: "high" },
    { topic: "C1 Experimental Chemistry", tier: "high" },
    { topic: "C9 Chemical Energetics", tier: "moderate" },
    { topic: "C7 Redox Chemistry", tier: "watch" },
  ],
  "o-level/e-math": [
    { topic: "N5 — Algebraic Manipulation & Formulae", tier: "very-high" },
    { topic: "N7 — Equations & Inequalities", tier: "very-high" },
    { topic: "G4 — Pythagoras, Trigonometry & Bearings", tier: "very-high" },
    { topic: "G5 — Mensuration", tier: "very-high" },
    { topic: "S1 — Data Analysis & Statistics", tier: "high" },
    { topic: "N4 — Rate, Speed & Financial Maths", tier: "high" },
    { topic: "N6 — Functions & Graphs", tier: "high" },
    { topic: "N1 — Numbers, Indices & Standard Form", tier: "moderate" },
    { topic: "G7 — Vectors in Two Dimensions", tier: "moderate" },
    { topic: "G2 — Congruence & Similarity", tier: "moderate" },
    { topic: "G6 — Coordinate Geometry", tier: "moderate" },
    { topic: "N2 — Ratio, Proportion & Map Scales", tier: "moderate" },
    { topic: "S2 — Probability", tier: "watch" },
    { topic: "G3 — Properties of Circles", tier: "watch" },
    { topic: "N9 — Matrices", tier: "watch" },
    { topic: "N3 — Percentage", tier: "watch" },
    { topic: "G1 — Angles, Triangles & Polygons", tier: "watch" },
    { topic: "N8 — Set Language & Venn Diagrams", tier: "watch" },
  ],
  "o-level/geography-elective": [
    { topic: "GE2 Tourism (Section A Q2 = 18 compulsory marks)", tier: "very-high" },
    { topic: "GE-AO3 The 9-mark AO3 'How far do you agree' (Section B host)", tier: "very-high" },
    { topic: "GE1.3 Fieldwork & Geographical Methods (embedded in Q1)", tier: "very-high" },
    { topic: "GE4.3 Disaster Risk Management (Tectonics AO3 magnet)", tier: "high" },
    { topic: "GE3.2 Climate Change — enhanced greenhouse effect (Climate AO3 magnet)", tier: "high" },
    { topic: "GE1.1 Thinking Geographically — sense of place & spatial patterns (Q1 opener)", tier: "high" },
    { topic: "GE1.2 Sustainable Development — ecosystem services & urban hazards", tier: "high" },
    { topic: "GE4.2 Earthquakes & Volcanoes — processes & hazards", tier: "moderate" },
    { topic: "GE4.1 Plate Tectonics — boundaries &", tier: "moderate" },
    { topic: "GE3.1 Weather & Climate — temperature factors & rainfall", tier: "moderate" },
    { topic: "GE3.3 Climate Action — mitigation & adaptation (Climate AO3 host)", tier: "moderate" },
    { topic: "GE2.1 Tourism Activity — system, growth, life cycle", tier: "moderate" },
    { topic: "GE2.2 Tourism Development — impacts & diversity", tier: "moderate" },
    { topic: "GE2.3 Sustainable Tourism Development — stakeholders & ecotourism", tier: "watch" },
    { topic: "GEDS Data & geographical skills (cross-cutting)", tier: "high" },
  ],
  "o-level/geography-pure": [
    { topic: "G1.3 Fieldwork & Geographical Methods (P1 Q1)", tier: "very-high" },
    { topic: "G5.1 Singapore: Small Island City-State (P2 Q3 core)", tier: "very-high" },
    { topic: "G1.1 Thinking Geographically (P2 Q1)", tier: "very-high" },
    { topic: "G1.2 Sustainable Development & Urban Hazards (P2 Q1)", tier: "high" },
    { topic: "G2.3 Sustainable Tourism (P1 Q2 - prime 9-mark AO3 slot)", tier: "very-high" },
    { topic: "G4.2 Earthquakes & Volcanoes (P2 Q2 core)", tier: "high" },
    { topic: "G3.2 Climate Change evidence & causes (P1 Q3 - prime 9-mark AO3 slot)", tier: "high" },
    { topic: "G3.1 Weather & Climate processes (P1 Q3 core)", tier: "high" },
    { topic: "G5.2 Singapore: Opportunities & Challenges (P2 Q3 - prime 9-mark AO3 slot)", tier: "high" },
    { topic: "G4.1 Plate Tectonics processes (P2 Q2 opener)", tier: "moderate" },
    { topic: "G2.1 Tourism Activity / system & life cycle (P1 Q2 opener)", tier: "moderate" },
    { topic: "G4.3 Disaster Risk Management (P2 Q2 evaluation)", tier: "moderate" },
    { topic: "G2.2 Tourism Development / impacts (P1 Q2 mid)", tier: "moderate" },
    { topic: "G5.3 Sustainable & Resilient Singapore (P2 Q3 - AO3 host 2025)", tier: "moderate" },
    { topic: "G3.3 Climate Action (P1 Q3 mid)", tier: "watch" },
  ],
  "o-level/history-elective": [
    { topic: "H2 Nazi Germany (rise & consolidation of Hitler)", tier: "very-high" },
    { topic: "H7 Origins & development of the Cold War in Europe", tier: "very-high" },
    { topic: "H8 Korean War 1950-53", tier: "very-high" },
    { topic: "H4 Outbreak of WWII in Europe (appeasement, German aggression)", tier: "high" },
    { topic: "H10 Decline of the USSR & the end of the Cold War", tier: "high" },
    { topic: "H5 Outbreak of WWII in the Asia-Pacific", tier: "moderate" },
    { topic: "H9 Vietnam War 1954-75", tier: "moderate" },
    { topic: "H3 Militarist Japan 1920s-1930s", tier: "moderate" },
    { topic: "H1 Paris Peace Settlement, Versailles & the League", tier: "moderate" },
    { topic: "H6 Reasons for the end of WWII", tier: "watch" },
  ],
  "o-level/history-pure": [
    { topic: "P1.1 British Malaya 1870s-1920s (Perak, Residential System, FMS)", tier: "very-high" },
    { topic: "P2.5 British Malaya decolonisation 1945-1957 (Malayan Union, Emergency, Merdeka)", tier: "very-high" },
    { topic: "P1.4 Nazi Germany (rise & consolidation of Hitler)", tier: "very-high" },
    { topic: "P2.2 Origins & development of the Cold War in Europe", tier: "very-high" },
    { topic: "P1.6 Outbreak of WWII in Europe (appeasement, German aggression)", tier: "high" },
    { topic: "P2.3 Korean War 1950-1953", tier: "high" },
    { topic: "P1.3 After WWI: Paris Peace Conference, Versailles, League (1920s)", tier: "high" },
    { topic: "P2.7 End of the Cold War (decline of the USSR, Gorbachev)", tier: "high" },
    { topic: "P1.2 Dutch Indonesia / French Vietnam 1870s-1920s (either/or)", tier: "moderate" },
    { topic: "P1.5 Militarist Japan 1920s-1930s", tier: "moderate" },
    { topic: "P2.4 Vietnam War 1954-1975", tier: "moderate" },
    { topic: "P2.6 Indonesia / Vietnam decolonisation (either/or)", tier: "moderate" },
    { topic: "P2.1 Reasons for the end of WWII", tier: "watch" },
    { topic: "P1.7 Outbreak of WWII in the Asia-Pacific", tier: "watch" },
  ],
  "o-level/physics-pure": [
    { topic: "T20 Radioactivity", tier: "very-high" },
    { topic: "T12 Light", tier: "very-high" },
    { topic: "T3 Dynamics", tier: "very-high" },
    { topic: "T19 Electromagnetic Induction", tier: "very-high" },
    { topic: "T16 Practical Electricity", tier: "very-high" },
    { topic: "T15 D.C. Circuits", tier: "high" },
    { topic: "T6 Energy Stores & Transfers", tier: "high" },
    { topic: "T2 Kinematics", tier: "high" },
    { topic: "T9 Thermal Properties of Matter", tier: "high" },
    { topic: "T10 General Wave Properties", tier: "high" },
    { topic: "T14 Current of Electricity", tier: "high" },
    { topic: "T17 Magnetism", tier: "high" },
    { topic: "T18 Electromagnetism", tier: "moderate" },
    { topic: "T4 Turning Effect of Forces", tier: "moderate" },
    { topic: "T13 Static Electricity", tier: "moderate" },
    { topic: "T5 Pressure", tier: "moderate" },
    { topic: "T7 Kinetic Particle Model of Matter", tier: "moderate" },
    { topic: "T11 Electromagnetic Spectrum", tier: "moderate" },
    { topic: "T1 Physical Quantities & Measurement", tier: "watch" },
    { topic: "T8 Thermal Processes", tier: "watch" },
  ],
  "o-level/physics-science": [
    { topic: "T16 Radioactivity", tier: "very-high" },
    { topic: "T7 Kinetic Particle Model", tier: "very-high" },
    { topic: "T3 Force & Pressure", tier: "very-high" },
    { topic: "T6 Energy", tier: "very-high" },
    { topic: "T13 D.C. Circuits", tier: "very-high" },
    { topic: "T9 General Wave Properties & Sound", tier: "very-high" },
    { topic: "T2 Kinematics", tier: "high" },
    { topic: "T4 Dynamics", tier: "high" },
    { topic: "T14 Practical Electricity", tier: "high" },
    { topic: "T8 Thermal Processes", tier: "high" },
    { topic: "T10 Electromagnetic Spectrum", tier: "high" },
    { topic: "T15 Magnetism & Electromagnetism", tier: "high" },
    { topic: "T5 Turning Effects of Forces", tier: "moderate" },
    { topic: "T11 Light", tier: "moderate" },
    { topic: "T12 Electric Charge & Current", tier: "moderate" },
    { topic: "T1 Physical Quantities & Measurement", tier: "watch" },
  ],
  "o-level/principles-of-accounts": [
    { topic: "P13 — Accounting Ratios & Interpretation", tier: "very-high" },
    { topic: "P7 — Financial Statements — Sole Trader", tier: "very-high" },
    { topic: "P6 — Adjustments", tier: "very-high" },
    { topic: "P8 — Financial Statements — Limited Company", tier: "very-high" },
    { topic: "P14 — Business Ownership & Decision-Making", tier: "high" },
    { topic: "P2 — Accounting Theories, Ethics & ICT", tier: "high" },
    { topic: "P11 — Correction of Errors & Suspense", tier: "high" },
    { topic: "P1 — The Accounting Cycle & Framework", tier: "moderate" },
    { topic: "P4 — Books of Prime Entry & Double Entry", tier: "moderate" },
    { topic: "P5 — Ledgers & the Trial Balance", tier: "moderate" },
    { topic: "P3 — Source Documents", tier: "moderate" },
    { topic: "P9 — Control Accounts", tier: "watch" },
    { topic: "P12 — Incomplete Records", tier: "watch" },
    { topic: "P10 — Bank Reconciliation", tier: "watch" },
  ],
  "o-level/social-studies": [
    { topic: "Issue 1 — Exploring Citizenship and Governance", tier: "very-high" },
    { topic: "Issue 2 — Living in a Diverse Society", tier: "very-high" },
    { topic: "Issue 3 — Being Part of a Globalised World", tier: "high" },
  ],
};
