import type { PlaygroundLesson } from "@/lib/playground-lessons";

// Project Playground Round 2 (Coddy-authored): one interactive lesson per
// previously-uncovered O-Level pure-science topic. This batch is 5 chemistry,
// 14 physics and 10 biology lessons, which fills the last gaps so the whole
// suite reaches full coverage: Chemistry 12/12, Physics 20/20, Biology 14/14.

export const SCIENCE_EXPANSION: Record<"chemistry" | "physics" | "biology", PlaygroundLesson[]> = {
  chemistry: [
    {
      key: "chem-organic-1",
      title: "Alkanes and alkenes",
      minutes: 6,
      topic: "c11-organic-chemistry",
      steps: [
        {
          kind: "concept",
          heading: "Carbon builds families",
          body: "Organic chemistry is the chemistry of carbon compounds. Carbon forms chains, and a family with the same general formula is a homologous series. Alkanes such as CH_4 have only single bonds and are saturated. Alkenes such as C_2H_4 have a carbon to carbon double bond and are unsaturated.",
        },
        {
          kind: "match",
          prompt: "Match each molecule to its family.",
          pairs: [
            { left: "CH_4", right: "Alkane, single bonds only" },
            { left: "C_2H_6", right: "Alkane, ends in ane" },
            { left: "C_2H_4", right: "Alkene, has a double bond" },
            { left: "C_3H_6", right: "Alkene, ends in ene" },
          ],
          ask: "Sort these molecules into alkanes and alkenes. Look at the name endings and whether there is a double bond.",
          hints: [
            "Alkane names end in ane and have single bonds only. Alkene names end in ene.",
            "An alkene formula fits the pattern with fewer hydrogens, because a double bond takes the place of two.",
            "Methane and ethane are alkanes. Ethene and propene are alkenes.",
          ],
          explain: "Methane and ethane are alkanes with single bonds only. Ethene and propene are alkenes, each with a carbon to carbon double bond.",
        },
        {
          kind: "choice",
          question: "Bromine water is added to two gases. It stays orange with gas P and turns colourless with gas Q. What is gas Q?",
          options: ["An alkene", "An alkane", "A noble gas", "Hydrogen"],
          correct: 0,
          ask: "Bromine water is the test for a double bond. Which gas decolourises it, the alkane or the alkene?",
          hints: [
            "The double bond in an alkene reacts with bromine and removes its colour.",
            "An alkane has no double bond, so bromine water stays orange with it.",
          ],
          explain: "Gas Q is an alkene. The carbon to carbon double bond reacts with bromine water and turns it from orange to colourless. An alkane leaves it orange.",
        },
        {
          kind: "insight",
          body: "Ane means saturated single bonds, ene means a double bond. Bromine water going colourless reveals the alkene.",
        },
      ],
      talkPrompt: "Quiz me on alkanes and alkenes, one at a time.",
    },
    {
      key: "chem-periodic-1",
      title: "Patterns in the Periodic Table",
      minutes: 6,
      topic: "c8-patterns-in-the-periodic-table",
      steps: [
        {
          kind: "concept",
          heading: "Order on a grid",
          body: "The Periodic Table arranges elements by increasing proton number. A vertical column is a group, and elements in a group share similar properties. A horizontal row is a period. Group I holds the reactive alkali metals, Group VII the halogens, and Group 0 the unreactive noble gases.",
        },
        {
          kind: "match",
          prompt: "Match each group to its description.",
          pairs: [
            { left: "Group I", right: "Alkali metals, soft and reactive" },
            { left: "Group VII", right: "Halogens, coloured non-metals" },
            { left: "Group 0", right: "Noble gases, full outer shell" },
            { left: "Transition elements", right: "Hard metals that form coloured compounds" },
          ],
          ask: "Match each part of the table to what it is like. Start with the group you remember best.",
          hints: [
            "Group I metals are soft and react with water. Group 0 gases barely react at all.",
            "The halogens in Group VII are coloured non-metals. Transition metals are hard and make coloured compounds.",
            "Group I alkali metals, Group VII halogens, Group 0 noble gases, and the transition metals in the middle.",
          ],
          explain: "Group I are reactive alkali metals, Group VII are the halogens, Group 0 are unreactive noble gases with full outer shells, and the transition elements are hard metals that form coloured compounds.",
        },
        {
          kind: "order",
          prompt: "Order these Group I metals from least to most reactive.",
          items: ["Lithium", "Sodium", "Potassium"],
          ask: "Reactivity of Group I increases as you go down the group. Put these three from least to most reactive.",
          hints: [
            "Lower down the group means more reactive.",
            "Lithium is at the top, potassium is further down.",
            "Least to most reactive is lithium, then sodium, then potassium.",
          ],
          explain: "Reactivity increases down Group I, so the order from least to most reactive is lithium, sodium, then potassium.",
        },
        {
          kind: "insight",
          body: "Groups are columns of similar elements. Down Group I the metals get more reactive, down Group VII the non-metals get less reactive.",
        },
      ],
      talkPrompt: "Quiz me on Periodic Table patterns, one at a time.",
    },
    {
      key: "chem-air-1",
      title: "Maintaining air quality",
      minutes: 5,
      topic: "c12-maintaining-air-quality",
      steps: [
        {
          kind: "concept",
          heading: "What pollutes the air",
          body: "Burning fuels releases gases that harm health and the environment. Carbon monoxide CO is a toxic gas from incomplete burning. Sulfur dioxide SO_2 causes acid rain. Oxides of nitrogen NO_2 form in hot engines. A catalytic converter helps by changing these into safer gases.",
        },
        {
          kind: "match",
          prompt: "Match each pollutant to its main problem.",
          pairs: [
            { left: "Carbon monoxide CO", right: "Toxic, reduces oxygen carried in blood" },
            { left: "Sulfur dioxide SO_2", right: "Causes acid rain" },
            { left: "Oxides of nitrogen NO_2", right: "Cause acid rain and smog" },
            { left: "Carbon dioxide CO_2", right: "Adds to the greenhouse effect" },
          ],
          ask: "Match each gas to the harm it does. Think about which ones make acid rain and which is toxic.",
          hints: [
            "Carbon monoxide is the toxic one that affects the blood.",
            "Sulfur dioxide and oxides of nitrogen both lead to acid rain.",
            "Carbon dioxide is not toxic here, but it adds to the greenhouse effect.",
          ],
          explain: "Carbon monoxide is toxic and reduces oxygen carried in the blood. Sulfur dioxide and oxides of nitrogen cause acid rain. Carbon dioxide adds to the greenhouse effect.",
        },
        {
          kind: "choice",
          question: "In a catalytic converter, carbon monoxide is changed into which safer gas?",
          options: ["Carbon dioxide", "Sulfur dioxide", "Hydrogen", "Ammonia"],
          correct: 0,
          ask: "A catalytic converter turns toxic carbon monoxide into a less harmful gas. Which one? Pick it.",
          hints: [
            "The carbon stays, and more oxygen is added to it.",
            "Carbon monoxide gains an oxygen to become the fuller oxide.",
          ],
          explain: "It is changed into carbon dioxide. The catalytic converter adds oxygen to toxic carbon monoxide, turning it into the less harmful carbon dioxide.",
        },
        {
          kind: "insight",
          body: "Carbon monoxide is toxic, sulfur dioxide and nitrogen oxides bring acid rain. Catalytic converters change them into safer gases.",
        },
      ],
      talkPrompt: "Quiz me on air pollutants, one at a time.",
    },
    {
      key: "chem-particulate-1",
      title: "Particulate nature of matter",
      minutes: 5,
      topic: "c2-particulate-nature-of-matter",
      steps: [
        {
          kind: "concept",
          heading: "Everything is made of particles",
          body: "All matter is made of tiny particles that are always moving. How the particles are arranged decides the state. In a solid they are packed and vibrate in place. In a liquid they touch but can slide. In a gas they are far apart and move quickly in all directions.",
        },
        {
          kind: "order",
          prompt: "Order the three states from least to most particle energy.",
          items: ["Solid", "Liquid", "Gas"],
          ask: "As particles gain energy they move more freely. Put the states in order from least energy to most.",
          hints: [
            "A solid holds its particles most tightly, so they have the least energy of movement.",
            "A gas lets particles fly apart, so it has the most.",
            "Least to most is solid, then liquid, then gas.",
          ],
          explain: "From least to most particle energy the order is solid, liquid, then gas. More energy lets the particles move further apart and faster.",
        },
        {
          kind: "match",
          prompt: "Match each state to how its particles behave.",
          pairs: [
            { left: "Solid", right: "Packed in a fixed pattern, vibrate in place" },
            { left: "Liquid", right: "Close together but able to slide past each other" },
            { left: "Gas", right: "Far apart, moving fast in all directions" },
          ],
          ask: "Match each state to its particle picture. Think about spacing and movement for each.",
          hints: [
            "A solid keeps a fixed shape because its particles cannot move around.",
            "A liquid flows because its particles slide. A gas spreads to fill a space.",
            "Solid particles vibrate in place, liquid particles slide, gas particles move fast and far apart.",
          ],
          explain: "In a solid the particles are packed and vibrate in place. In a liquid they are close but slide past each other. In a gas they are far apart and move fast in all directions.",
        },
        {
          kind: "insight",
          body: "Same particles, different arrangement. Adding energy loosens them from solid to liquid to gas.",
        },
      ],
      talkPrompt: "Quiz me on states and particles, one at a time.",
    },
    {
      key: "chem-energetics-1",
      title: "Exothermic and endothermic",
      minutes: 6,
      topic: "c9-chemical-energetics",
      steps: [
        {
          kind: "concept",
          heading: "Reactions move energy",
          body: "Every reaction breaks bonds and makes new ones. Breaking bonds takes in energy, making bonds gives out energy. If more energy is released than taken in, the reaction is exothermic and the surroundings warm up. If more is taken in, it is endothermic and the surroundings cool down.",
        },
        {
          kind: "match",
          prompt: "Match each change to its energy type.",
          pairs: [
            { left: "Burning fuel", right: "Exothermic, gives out heat" },
            { left: "Neutralising an acid", right: "Exothermic, mixture warms up" },
            { left: "Thermal decomposition", right: "Endothermic, needs heating to continue" },
            { left: "Dissolving some salts", right: "Endothermic, mixture cools down" },
          ],
          ask: "Sort these into exothermic and endothermic. Ask whether each one warms the surroundings or cools them.",
          hints: [
            "If it releases heat and warms things up, it is exothermic.",
            "Burning and neutralising release heat. Decomposition needs heat put in.",
            "Burning and neutralising are exothermic. Thermal decomposition and some dissolving are endothermic.",
          ],
          explain: "Burning fuel and neutralising an acid are exothermic and warm the surroundings. Thermal decomposition and some dissolving are endothermic and take in heat, cooling the surroundings.",
        },
        {
          kind: "tiles",
          prompt: "Build the rule for the overall energy change from bonds.",
          tiles: ["energy", "=", "bonds", "broken", "made", "minus"],
          answer: ["energy", "=", "bonds", "broken", "minus", "made"],
          ask: "Let us build the bond energy rule. Overall energy equals the energy for bonds broken minus the energy for bonds made. Lay out the tiles.",
          hints: [
            "Start with energy equals bonds broken.",
            "Then subtract the energy given out when bonds are made.",
            "The order is energy, equals, bonds, broken, minus, made.",
          ],
          explain: "The rule is energy equals bonds broken minus bonds made. If bonds made release more than breaking took in, the answer is negative and the reaction is exothermic.",
        },
        {
          kind: "insight",
          body: "Exothermic gives out heat, endothermic takes it in. Compare bonds broken with bonds made to tell which.",
        },
      ],
      talkPrompt: "Quiz me on exothermic and endothermic reactions, one at a time.",
    },
  ],
  physics: [
    {
      key: "phys-radioactivity-1",
      title: "Radioactivity and half-life",
      minutes: 6,
      topic: "t20-radioactivity",
      steps: [
        {
          kind: "concept",
          heading: "Three kinds of radiation",
          body: "Some unstable nuclei give out radiation. Alpha is a helium nucleus, stopped by paper. Beta is a fast electron, stopped by thin aluminium. Gamma is a high energy wave, only reduced by thick lead. The half-life is the time for half the nuclei to decay.",
        },
        {
          kind: "match",
          prompt: "Match each radiation to what stops it.",
          pairs: [
            { left: "Alpha", right: "Stopped by a sheet of paper" },
            { left: "Beta", right: "Stopped by a few mm of aluminium" },
            { left: "Gamma", right: "Only reduced by thick lead" },
          ],
          ask: "Match each type of radiation to the material that stops it. Alpha is the least penetrating, gamma the most.",
          hints: [
            "Alpha is the weakest at getting through, so even paper stops it.",
            "Beta needs thin metal, gamma needs thick lead.",
            "Alpha stopped by paper, beta by aluminium, gamma reduced by lead.",
          ],
          explain: "Alpha is stopped by paper, beta by a few millimetres of aluminium, and gamma is only reduced by thick lead. Penetrating power increases from alpha to gamma.",
        },
        {
          kind: "slider",
          prompt: "A source reads 80 counts per second. Its half-life is 5 minutes. Slide to the count rate after 15 minutes.",
          min: 0,
          max: 80,
          step: 1,
          unit: " cps",
          start: 55,
          targetMin: 9,
          targetMax: 11,
          ask: "Fifteen minutes is three half-lives. Halve the count rate three times, then slide to the answer.",
          hints: [
            "Each half-life halves the count. Fifteen divided by five is three half-lives.",
            "Eighty halves to forty, then twenty, then ten.",
            "After three half-lives the count rate is ten counts per second.",
          ],
          explain: "Fifteen minutes is three half-lives. Eighty halves to forty, to twenty, to ten, so the count rate is ten counts per second.",
        },
        {
          kind: "insight",
          body: "Alpha, beta, gamma rise in penetrating power. Each half-life cuts the count rate in half again.",
        },
      ],
      talkPrompt: "Quiz me on radioactivity and half-life, one at a time.",
    },
    {
      key: "phys-light-1",
      title: "Reflection and refraction",
      minutes: 5,
      topic: "t12-light",
      steps: [
        {
          kind: "concept",
          heading: "Light bounces and bends",
          body: "When light hits a mirror it reflects, and the angle of incidence equals the angle of reflection, both measured from the normal. When light passes into a denser material like glass or water it slows and bends towards the normal. This bending is called refraction.",
        },
        {
          kind: "slider",
          prompt: "A ray hits a mirror at an angle of incidence of 35 degrees from the normal. Set the angle of reflection.",
          min: 0,
          max: 90,
          step: 1,
          unit: " degrees",
          start: 68,
          targetMin: 34,
          targetMax: 36,
          ask: "The law of reflection says the reflected angle equals the incident angle. Slide to match it.",
          hints: [
            "Both angles are measured from the normal line.",
            "The angle of reflection is the same as the angle of incidence.",
            "The angle of incidence is thirty five, so the reflection is thirty five degrees.",
          ],
          explain: "By the law of reflection the angle of reflection equals the angle of incidence, so it is thirty five degrees.",
        },
        {
          kind: "choice",
          question: "A ray of light passes from air into glass. What happens to it at the surface?",
          options: [
            "It slows and bends towards the normal",
            "It speeds up and bends towards the normal",
            "It slows and bends away from the normal",
            "It carries on with no change at all",
          ],
          correct: 0,
          ask: "Light enters denser glass from air. Think about its speed and which way it bends. Pick the correct pair.",
          hints: [
            "Glass is denser than air, so the light slows down.",
            "Going into a denser material, the ray bends towards the normal.",
          ],
          explain: "Going from air into denser glass, the light slows down and bends towards the normal. That combination is refraction into a denser material.",
        },
        {
          kind: "insight",
          body: "Reflection keeps equal angles from the normal. Refraction into a denser material slows the light and bends it towards the normal.",
        },
      ],
      talkPrompt: "Quiz me on reflection and refraction, one at a time.",
    },
    {
      key: "phys-kinematics-1",
      title: "Speed and distance-time graphs",
      minutes: 6,
      topic: "t2-kinematics",
      steps: [
        {
          kind: "concept",
          heading: "Reading motion from a graph",
          body: "Speed is the distance travelled each second, found from speed = distance ÷ time. On a distance-time graph the gradient gives the speed. A straight sloped line means steady speed, a steeper line means faster, and a flat line means the object is at rest.",
        },
        {
          kind: "tiles",
          prompt: "Build the equation for speed.",
          tiles: ["v", "=", "s", "t", "÷", "×"],
          answer: ["v", "=", "s", "÷", "t"],
          ask: "Let us build the speed equation. Speed equals distance divided by time. Place the tiles in order.",
          hints: [
            "Start with speed equals.",
            "Distance is on top, so it comes before the divide sign.",
            "The order is v, equals, s, divide, t.",
          ],
          explain: "The equation is v equals s divided by t. Speed equals distance divided by time.",
        },
        {
          kind: "plot",
          prompt: "An object moves at a steady speed and is 20 m from the start after 4 s. Plot that point on the distance-time graph.",
          xLabel: "t / s",
          yLabel: "s / m",
          xMax: 6,
          yMax: 30,
          targetX: 4,
          targetY: 20,
          ask: "Plot where the object is on the distance-time graph. It has gone twenty metres at four seconds.",
          hints: [
            "Read across to four seconds on the time axis.",
            "Then go up to twenty metres on the distance axis.",
            "Plot the point at four seconds and twenty metres.",
          ],
          explain: "The point is at four seconds and twenty metres. Its gradient, twenty over four, gives a steady speed of five metres per second.",
        },
        {
          kind: "insight",
          body: "On a distance-time graph the gradient is the speed. Steeper means faster, flat means stopped.",
        },
      ],
      talkPrompt: "Quiz me on speed and distance-time graphs, one at a time.",
    },
    {
      key: "phys-pressure-1",
      title: "Pressure from force and area",
      minutes: 5,
      topic: "t5-pressure",
      steps: [
        {
          kind: "concept",
          heading: "Force spread over area",
          body: "Pressure tells you how concentrated a force is. It equals the force divided by the area it acts on, so P = F ÷ A. The same force on a smaller area gives a higher pressure. That is why a sharp knife or a drawing pin works, all the force is squeezed onto a tiny area.",
        },
        {
          kind: "tiles",
          prompt: "Build the pressure equation.",
          tiles: ["P", "=", "F", "A", "÷", "×"],
          answer: ["P", "=", "F", "÷", "A"],
          ask: "Let us build the pressure equation. Pressure equals force divided by area. Place the tiles in order.",
          hints: [
            "Start with pressure equals.",
            "Force is on top, so it comes before the divide sign.",
            "The order is P, equals, F, divide, A.",
          ],
          explain: "The equation is P equals F divided by A. Pressure equals force divided by area.",
        },
        {
          kind: "slider",
          prompt: "A force of 200 N presses on an area of 4 m^2. Slide to the pressure.",
          min: 0,
          max: 100,
          step: 1,
          unit: " Pa",
          start: 73,
          targetMin: 49,
          targetMax: 51,
          ask: "Use the equation. Force is two hundred newtons, area is four square metres. Slide to the pressure.",
          hints: [
            "Pressure equals force divided by area.",
            "That is two hundred divided by four.",
            "Two hundred divided by four is fifty pascals.",
          ],
          explain: "Pressure is force divided by area, which is two hundred divided by four, giving fifty pascals.",
        },
        {
          kind: "insight",
          body: "Same force, smaller area, higher pressure. Pressure equals force divided by area.",
        },
      ],
      talkPrompt: "Quiz me on pressure, one at a time.",
    },
    {
      key: "phys-thermal-1",
      title: "Heat capacity and latent heat",
      minutes: 6,
      topic: "t9-thermal-properties-of-matter",
      steps: [
        {
          kind: "concept",
          heading: "Energy to heat and to melt",
          body: "Heating a substance raises its temperature, and the energy needed is Q = m c ΔT, where c is the specific heat capacity. During melting or boiling the temperature stays constant while energy still flows in. That hidden energy is the latent heat, used to change state rather than to raise temperature.",
        },
        {
          kind: "tiles",
          prompt: "Build the equation for heating a substance.",
          tiles: ["Q", "=", "m", "c", "ΔT", "÷"],
          answer: ["Q", "=", "m", "c", "ΔT"],
          ask: "Let us build the heating equation. Energy equals mass times specific heat capacity times temperature change. Place the tiles in order.",
          hints: [
            "Start with Q equals.",
            "Multiply mass by the specific heat capacity, then by the temperature change.",
            "The order is Q, equals, m, c, then delta T.",
          ],
          explain: "The equation is Q equals m times c times delta T. Energy equals mass times specific heat capacity times temperature change.",
        },
        {
          kind: "choice",
          question: "Ice at its melting point is given energy and turns to water, but the thermometer does not rise. Why?",
          options: [
            "The energy is latent heat used to change state",
            "The thermometer has broken",
            "The ice has stopped absorbing energy",
            "Water cannot get warmer than ice",
          ],
          correct: 0,
          ask: "Energy goes in during melting, yet the temperature holds steady. What is the energy doing? Pick the reason.",
          hints: [
            "During a change of state the temperature stays constant.",
            "The energy is breaking the bonds between particles, not speeding them up.",
          ],
          explain: "The energy is latent heat, used to change the state from solid to liquid. It breaks the forces between particles instead of raising the temperature, so the thermometer holds steady.",
        },
        {
          kind: "insight",
          body: "Use Q equals m c delta T to warm a substance. During melting or boiling, latent heat changes the state at constant temperature.",
        },
      ],
      talkPrompt: "Quiz me on heat capacity and latent heat, one at a time.",
    },
    {
      key: "phys-current-1",
      title: "Current and charge",
      minutes: 5,
      topic: "t14-current-of-electricity",
      steps: [
        {
          kind: "concept",
          heading: "Flow of charge",
          body: "An electric current is a flow of electric charge. The current tells you how much charge passes each second, so charge Q = I t, where I is the current in amperes and t is the time in seconds. A larger current means more charge flows past a point every second.",
        },
        {
          kind: "tiles",
          prompt: "Build the equation for charge.",
          tiles: ["Q", "=", "I", "t", "×", "÷"],
          answer: ["Q", "=", "I", "×", "t"],
          ask: "Let us build the charge equation. Charge equals current times time. Place the tiles in order.",
          hints: [
            "Start with charge equals.",
            "Current and time are multiplied.",
            "The order is Q, equals, I, times, t.",
          ],
          explain: "The equation is Q equals I times t. Charge equals current multiplied by time.",
        },
        {
          kind: "slider",
          prompt: "A current of 3 A flows for 4 s. Slide to the charge that passes.",
          min: 0,
          max: 20,
          step: 0.5,
          unit: " C",
          start: 15.5,
          targetMin: 11.5,
          targetMax: 12.5,
          ask: "Use the equation. Current three amperes, time four seconds. Slide to the charge.",
          hints: [
            "Charge equals current times time.",
            "That is three times four.",
            "Three times four is twelve coulombs.",
          ],
          explain: "Charge is current times time, which is three times four, giving twelve coulombs.",
        },
        {
          kind: "insight",
          body: "Current is charge per second. Multiply current by time to get the total charge, Q equals I times t.",
        },
      ],
      talkPrompt: "Quiz me on current and charge, one at a time.",
    },
    {
      key: "phys-magnetism-1",
      title: "Magnets and fields",
      minutes: 5,
      topic: "t17-magnetism",
      steps: [
        {
          kind: "concept",
          heading: "Poles and their field",
          body: "A magnet has a north pole and a south pole. Like poles repel and unlike poles attract. Around a magnet is a magnetic field, drawn as field lines that run from north to south. Where the lines are closest together the field is strongest.",
        },
        {
          kind: "match",
          prompt: "Match each pole pairing to what it does.",
          pairs: [
            { left: "North near north", right: "Repel, push apart" },
            { left: "South near south", right: "Repel, push apart" },
            { left: "North near south", right: "Attract, pull together" },
            { left: "Field lines close together", right: "Stronger field" },
          ],
          ask: "Match each pairing to attract, repel, or field strength. Remember like poles repel.",
          hints: [
            "Two of the same pole always push apart.",
            "Opposite poles pull together.",
            "Like poles repel, unlike poles attract, and closely spaced lines mean a stronger field.",
          ],
          explain: "Like poles repel, so north near north and south near south push apart. Unlike poles attract, so north near south pull together. Closely spaced field lines mean a stronger field.",
        },
        {
          kind: "choice",
          question: "A steel bar is attracted to both ends of a magnet. What does this tell you?",
          options: [
            "The steel bar is not a magnet, only a magnetic material",
            "The steel bar is a permanent magnet",
            "The steel bar has two north poles",
            "The magnet has lost its poles",
          ],
          correct: 0,
          ask: "The bar is pulled in by both poles, never pushed away. What does that reveal about it? Pick one.",
          hints: [
            "A real magnet would be repelled by one of the poles.",
            "Being attracted to both ends means it has no fixed poles of its own.",
          ],
          explain: "The steel bar is a magnetic material, not a magnet. A true magnet would be repelled by one pole. Attraction to both ends shows it has no poles of its own.",
        },
        {
          kind: "insight",
          body: "Like poles repel, unlike attract. Only repulsion proves something is truly a magnet.",
        },
      ],
      talkPrompt: "Quiz me on magnets and fields, one at a time.",
    },
    {
      key: "phys-electromagnetism-1",
      title: "Electromagnetism",
      minutes: 5,
      topic: "t18-electromagnetism",
      steps: [
        {
          kind: "concept",
          heading: "Current makes magnetism",
          body: "An electric current creates a magnetic field around it. Wind the wire into a coil, called a solenoid, and the fields add up to make a strong magnet with a north and south end. Add an iron core and switch the current, and you have an electromagnet you can turn on and off.",
        },
        {
          kind: "match",
          prompt: "Match each change to its effect on an electromagnet.",
          pairs: [
            { left: "More turns on the coil", right: "Stronger magnetic field" },
            { left: "Larger current", right: "Stronger magnetic field" },
            { left: "Adding an iron core", right: "Much stronger field" },
            { left: "Switching the current off", right: "The magnetism disappears" },
          ],
          ask: "Match each change to what it does to the electromagnet. Think about what makes the field stronger.",
          hints: [
            "More turns and more current both build the field up.",
            "An iron core boosts the field a lot, and cutting the current removes it.",
            "More turns, more current, and an iron core all strengthen it, while switching off removes the magnetism.",
          ],
          explain: "More turns, a larger current, and an iron core all make the field stronger. Switching the current off makes the magnetism disappear, which is why electromagnets are so useful.",
        },
        {
          kind: "choice",
          question: "Why is an electromagnet used in a scrapyard crane instead of a permanent magnet?",
          options: [
            "It can be switched off to drop the load",
            "It never needs any electricity",
            "It is weaker and safer to hold",
            "It works only with non-magnetic metals",
          ],
          correct: 0,
          ask: "A crane must pick up scrap and then release it. Why choose an electromagnet? Pick the reason.",
          hints: [
            "Think about how the crane lets go of the metal.",
            "A permanent magnet could not release the load on command.",
          ],
          explain: "An electromagnet can be switched off to drop the load. A permanent magnet would keep holding the scrap, so it could not release it on demand.",
        },
        {
          kind: "insight",
          body: "Current makes a magnetic field. An electromagnet can be strengthened, and it switches on and off with the current.",
        },
      ],
      talkPrompt: "Quiz me on electromagnetism, one at a time.",
    },
    {
      key: "phys-static-1",
      title: "Static electricity",
      minutes: 5,
      topic: "t13-static-electricity",
      steps: [
        {
          kind: "concept",
          heading: "Charge from rubbing",
          body: "Rubbing two insulators moves electrons from one to the other. The material that gains electrons becomes negatively charged, and the one that loses them becomes positively charged. Like charges repel and unlike charges attract, just like the poles of a magnet.",
        },
        {
          kind: "match",
          prompt: "Match each charge pairing to what it does.",
          pairs: [
            { left: "Negative near negative", right: "Repel" },
            { left: "Positive near positive", right: "Repel" },
            { left: "Positive near negative", right: "Attract" },
            { left: "Gains electrons", right: "Becomes negatively charged" },
          ],
          ask: "Match each pairing to attract or repel, and the last one to the charge it gains. Like charges repel.",
          hints: [
            "Two of the same charge push apart.",
            "Opposite charges pull together.",
            "Like charges repel, unlike attract, and gaining electrons makes an object negative.",
          ],
          explain: "Like charges repel and unlike charges attract. An object that gains electrons becomes negatively charged, since electrons carry negative charge.",
        },
        {
          kind: "choice",
          question: "A plastic rod is rubbed with a cloth and becomes negatively charged. What happened?",
          options: [
            "The rod gained electrons from the cloth",
            "The rod lost electrons to the cloth",
            "The rod gained protons from the cloth",
            "The rod created new charge from nothing",
          ],
          correct: 0,
          ask: "The rod ends up negative after rubbing. Which particles moved, and which way? Pick the answer.",
          hints: [
            "Only electrons move during rubbing, protons stay put.",
            "To become negative the rod must gain electrons.",
          ],
          explain: "The rod gained electrons from the cloth. Electrons are negative, so gaining them makes the rod negatively charged. Protons do not move.",
        },
        {
          kind: "insight",
          body: "Rubbing transfers electrons, not protons. Gaining electrons gives negative charge, and like charges repel.",
        },
      ],
      talkPrompt: "Quiz me on static electricity, one at a time.",
    },
    {
      key: "phys-induction-1",
      title: "Electromagnetic induction",
      minutes: 5,
      topic: "t19-electromagnetic-induction",
      steps: [
        {
          kind: "concept",
          heading: "Movement makes a voltage",
          body: "When a wire and a magnetic field move relative to each other, a voltage is induced across the wire. If the wire is part of a complete circuit, that voltage drives a current. Moving faster, using a stronger magnet, or adding more turns of wire all increase the induced voltage.",
        },
        {
          kind: "order",
          prompt: "Order the steps that produce an induced current in a coil.",
          items: [
            "A magnet is pushed towards the coil",
            "The magnetic field through the coil changes",
            "A voltage is induced across the coil",
            "A current flows in the complete circuit",
          ],
          ask: "Think about what has to change before any current appears. Put the steps in order.",
          hints: [
            "It begins with movement of the magnet.",
            "The changing field comes before the voltage, and the voltage before the current.",
            "Move the magnet, change the field, induce a voltage, then a current flows.",
          ],
          explain: "First the magnet moves towards the coil, this changes the field through the coil, which induces a voltage, and in a complete circuit that voltage drives a current.",
        },
        {
          kind: "choice",
          question: "A magnet is held still inside a coil. What current is induced?",
          options: [
            "None, because the field is not changing",
            "A large steady current",
            "A current that grows over time",
            "A current only if the magnet is strong",
          ],
          correct: 0,
          ask: "The magnet sits still, so the field is steady. What does that mean for the induced current? Pick one.",
          hints: [
            "Induction needs a change in the field, not just a field.",
            "A still magnet gives no change, so nothing is induced.",
          ],
          explain: "No current is induced. Induction needs the field through the coil to change. A stationary magnet gives a steady field, so there is nothing to induce a voltage.",
        },
        {
          kind: "insight",
          body: "Only a changing field induces a voltage. No movement, no change, no induced current.",
        },
      ],
      talkPrompt: "Quiz me on electromagnetic induction, one at a time.",
    },
    {
      key: "phys-practical-1",
      title: "Electrical power at home",
      minutes: 5,
      topic: "t16-practical-electricity",
      steps: [
        {
          kind: "concept",
          heading: "Power in a circuit",
          body: "Electrical power is the energy used each second, and for a device it equals the voltage times the current, so P = V I. Power is measured in watts. Knowing the power lets you choose the right fuse and work out how much energy an appliance uses over time.",
        },
        {
          kind: "tiles",
          prompt: "Build the equation for electrical power.",
          tiles: ["P", "=", "V", "I", "×", "÷"],
          answer: ["P", "=", "V", "×", "I"],
          ask: "Let us build the power equation. Power equals voltage times current. Place the tiles in order.",
          hints: [
            "Start with power equals.",
            "Voltage and current are multiplied.",
            "The order is P, equals, V, times, I.",
          ],
          explain: "The equation is P equals V times I. Power equals voltage multiplied by current.",
        },
        {
          kind: "slider",
          prompt: "A device runs at 12 V and draws a current of 2 A. Slide to its power.",
          min: 0,
          max: 50,
          step: 1,
          unit: " W",
          start: 39,
          targetMin: 23,
          targetMax: 25,
          ask: "Use the equation. Voltage twelve volts, current two amperes. Slide to the power.",
          hints: [
            "Power equals voltage times current.",
            "That is twelve times two.",
            "Twelve times two is twenty four watts.",
          ],
          explain: "Power is voltage times current, which is twelve times two, giving twenty four watts.",
        },
        {
          kind: "insight",
          body: "Power equals voltage times current. Higher power means more energy used every second.",
        },
      ],
      talkPrompt: "Quiz me on electrical power, one at a time.",
    },
    {
      key: "phys-kinetic-1",
      title: "Kinetic particle model",
      minutes: 5,
      topic: "t7-kinetic-particle-model-of-matter",
      steps: [
        {
          kind: "concept",
          heading: "Hotter means faster",
          body: "The kinetic particle model says all matter is made of particles in constant motion. Temperature is a measure of the average kinetic energy of those particles. Heat a gas and its particles move faster, hit the walls harder and more often, so the pressure rises if the volume is fixed.",
        },
        {
          kind: "order",
          prompt: "Order the states from slowest to fastest particle movement.",
          items: ["Solid", "Liquid", "Gas"],
          ask: "More energy means faster particles. Put the states in order from slowest to fastest movement.",
          hints: [
            "Solid particles only vibrate in place, so they are slowest overall.",
            "Gas particles move fastest and most freely.",
            "Slowest to fastest is solid, then liquid, then gas.",
          ],
          explain: "From slowest to fastest movement the order is solid, liquid, then gas. Adding energy lets the particles move faster and more freely.",
        },
        {
          kind: "choice",
          question: "A sealed gas is heated in a fixed container. Why does the pressure rise?",
          options: [
            "Particles move faster and hit the walls harder and more often",
            "New particles are created by the heat",
            "The particles get bigger",
            "The particles stop moving",
          ],
          correct: 0,
          ask: "Heating a sealed gas raises its pressure. Think about how the particles behave. Pick the reason.",
          hints: [
            "Temperature is about how fast the particles move.",
            "Faster particles strike the walls harder and more frequently.",
          ],
          explain: "The particles move faster when heated, so they hit the walls harder and more often. More frequent, harder collisions raise the pressure in a fixed container.",
        },
        {
          kind: "insight",
          body: "Temperature measures average particle energy. Heat a fixed gas and harder, more frequent collisions raise the pressure.",
        },
      ],
      talkPrompt: "Quiz me on the kinetic particle model, one at a time.",
    },
    {
      key: "phys-emspectrum-1",
      title: "The electromagnetic spectrum",
      minutes: 5,
      topic: "t11-electromagnetic-spectrum",
      steps: [
        {
          kind: "concept",
          heading: "One family of waves",
          body: "The electromagnetic spectrum is a family of waves that all travel at the speed of light in a vacuum. They differ in wavelength and frequency. From longest wavelength to shortest they are radio, microwave, infrared, visible light, ultraviolet, X-rays, and gamma rays. Shorter wavelength means higher frequency and more energy.",
        },
        {
          kind: "order",
          prompt: "Order these from longest wavelength to shortest.",
          items: ["Radio waves", "Infrared", "Visible light", "Gamma rays"],
          ask: "The spectrum runs from long radio waves to short gamma rays. Put these four in order from longest wavelength to shortest.",
          hints: [
            "Radio waves have the longest wavelength of the whole family.",
            "Gamma rays have the shortest wavelength and the most energy.",
            "Longest to shortest is radio, infrared, visible light, then gamma.",
          ],
          explain: "From longest wavelength to shortest the order is radio waves, infrared, visible light, then gamma rays. As wavelength falls, frequency and energy rise.",
        },
        {
          kind: "match",
          prompt: "Match each wave to a common use.",
          pairs: [
            { left: "Radio waves", right: "Broadcasting and communication" },
            { left: "Microwaves", right: "Cooking and mobile phone signals" },
            { left: "Infrared", right: "Remote controls and heaters" },
            { left: "X-rays", right: "Seeing inside the body" },
          ],
          ask: "Match each wave to what we use it for. Think of an everyday example for each.",
          hints: [
            "Radio and microwaves are used to carry signals.",
            "Infrared carries heat and remote signals, X-rays see through soft tissue.",
            "Radio for broadcasting, microwaves for cooking and phones, infrared for remotes and heaters, X-rays for medical images.",
          ],
          explain: "Radio waves are used for broadcasting, microwaves for cooking and phone signals, infrared for remote controls and heaters, and X-rays for seeing inside the body.",
        },
        {
          kind: "insight",
          body: "All these waves travel at the speed of light. Shorter wavelength means higher frequency and more energy.",
        },
      ],
      talkPrompt: "Quiz me on the electromagnetic spectrum, one at a time.",
    },
    {
      key: "phys-thermalprocesses-1",
      title: "Conduction, convection, radiation",
      minutes: 5,
      topic: "t8-thermal-processes",
      steps: [
        {
          kind: "concept",
          heading: "Three ways heat travels",
          body: "Thermal energy moves in three ways. Conduction passes energy through a solid as particles vibrate and bump neighbours. Convection carries energy in a moving fluid as warm parts rise and cool parts sink. Radiation carries energy as infrared waves and needs no material at all.",
        },
        {
          kind: "match",
          prompt: "Match each example to its type of heat transfer.",
          pairs: [
            { left: "A metal spoon heats up in hot soup", right: "Conduction" },
            { left: "Warm air rising above a heater", right: "Convection" },
            { left: "Heat reaching Earth from the Sun", right: "Radiation" },
            { left: "A sea breeze forming as air circulates", right: "Convection" },
          ],
          ask: "Match each everyday example to conduction, convection, or radiation. Ask whether a solid, a moving fluid, or empty space is involved.",
          hints: [
            "Heat through a solid metal is conduction.",
            "Moving warm air or water is convection, and heat across empty space is radiation.",
            "The spoon is conduction, rising air and the sea breeze are convection, and the Sun's heat is radiation.",
          ],
          explain: "The metal spoon heating is conduction. Warm air rising and the sea breeze are convection. Heat from the Sun crossing empty space is radiation, which needs no material.",
        },
        {
          kind: "choice",
          question: "How does heat from the Sun reach the Earth through empty space?",
          options: ["By radiation", "By conduction", "By convection", "By all three equally"],
          correct: 0,
          ask: "Space between the Sun and Earth has almost no particles. Which transfer still works? Pick one.",
          hints: [
            "Conduction and convection both need particles to carry the energy.",
            "Only one method travels through a vacuum.",
          ],
          explain: "Heat from the Sun reaches us by radiation. It travels as infrared waves and needs no particles, so it is the only method that crosses empty space.",
        },
        {
          kind: "insight",
          body: "Conduction needs a solid, convection needs a moving fluid, radiation needs nothing at all.",
        },
      ],
      talkPrompt: "Quiz me on conduction, convection and radiation, one at a time.",
    },
  ],
  biology: [
    {
      key: "bio-homeostasis-1",
      title: "Homeostasis and feedback",
      minutes: 6,
      topic: "t8-homeostasis-co-ordination-and-response",
      steps: [
        {
          kind: "concept",
          heading: "Keeping the inside steady",
          body: "Homeostasis is the way the body keeps its internal conditions steady, such as temperature and blood sugar. It works by negative feedback: a receptor detects a change, a control centre responds, and an effector brings the level back to normal. This keeps cells working in a stable environment.",
        },
        {
          kind: "order",
          prompt: "Order the steps of a negative feedback response when the body gets too hot.",
          items: [
            "Receptors detect that body temperature has risen",
            "The brain acts as the control centre",
            "Effectors such as sweat glands are activated",
            "Sweating cools the body back to normal",
          ],
          ask: "Think about what must be sensed before the body can react. Put the feedback steps in order.",
          hints: [
            "Detection comes before any response.",
            "The control centre decides, then the effectors act, then the level returns to normal.",
            "Detect the change, control centre responds, effectors act, temperature returns to normal.",
          ],
          explain: "Receptors detect the rise in temperature, the brain as control centre responds, effectors such as sweat glands are activated, and sweating cools the body back to normal.",
        },
        {
          kind: "choice",
          question: "Why is this called negative feedback?",
          options: [
            "The response reverses the change and restores normal",
            "The response makes the change even bigger",
            "The response has no effect at all",
            "The response only works when you are asleep",
          ],
          correct: 0,
          ask: "Negative feedback is named for what the response does to the original change. What does it do? Pick one.",
          hints: [
            "Think about whether the body pushes the level further away or back.",
            "The response opposes the change that set it off.",
          ],
          explain: "It is negative feedback because the response reverses the change and restores the normal level. A rise triggers cooling, and a fall would trigger warming.",
        },
        {
          kind: "insight",
          body: "Detect, respond, correct. Negative feedback always pushes a changed level back towards normal.",
        },
      ],
      talkPrompt: "Quiz me on homeostasis and feedback, one at a time.",
    },
    {
      key: "bio-environment-1",
      title: "Food chains and energy flow",
      minutes: 5,
      topic: "t11-organisms-and-their-environment",
      steps: [
        {
          kind: "concept",
          heading: "Energy passes along",
          body: "A food chain shows how energy passes from one organism to the next. It starts with a producer, usually a green plant that captures light energy. Then come consumers that eat other organisms. At each step most of the energy is lost as heat and movement, so chains are usually short.",
        },
        {
          kind: "order",
          prompt: "Order this food chain from producer to top consumer.",
          items: ["Grass", "Grasshopper", "Frog", "Snake"],
          ask: "A food chain starts with the producer that captures light. Put these in the order energy flows.",
          hints: [
            "The producer is the green plant that starts the chain.",
            "Each animal eats the one before it in the chain.",
            "The order is grass, grasshopper, frog, then snake.",
          ],
          explain: "Energy flows from grass, the producer, to the grasshopper, then the frog, then the snake. Each arrow points in the direction the energy travels.",
        },
        {
          kind: "choice",
          question: "Why are food chains usually only four or five steps long?",
          options: [
            "Energy is lost at each step, so little is left for higher levels",
            "Animals cannot count past five",
            "Producers run out of light",
            "Predators refuse to eat small prey",
          ],
          correct: 0,
          ask: "Something limits how many links a chain can have. Think about the energy at each step. Pick the reason.",
          hints: [
            "Only some of the energy passes on at each level.",
            "Most energy is lost as heat and movement, leaving little for the next level.",
          ],
          explain: "Energy is lost at each step as heat and movement, so less is available higher up. After a few steps there is too little energy left to support another level.",
        },
        {
          kind: "insight",
          body: "Producers capture the energy, and each step loses most of it. That is why food chains stay short.",
        },
      ],
      talkPrompt: "Quiz me on food chains and energy flow, one at a time.",
    },
    {
      key: "bio-transport-humans-1",
      title: "The heart and blood vessels",
      minutes: 6,
      topic: "t5-transport-in-humans",
      steps: [
        {
          kind: "concept",
          heading: "A double pump and its pipes",
          body: "The heart pumps blood around the body through three kinds of vessel. Arteries carry blood away from the heart at high pressure with thick walls. Veins return blood to the heart at low pressure and have valves. Capillaries are tiny and thin, letting substances pass into and out of cells.",
        },
        {
          kind: "match",
          prompt: "Match each vessel to its key feature.",
          pairs: [
            { left: "Artery", right: "Thick wall, carries blood from the heart" },
            { left: "Vein", right: "Has valves, returns blood to the heart" },
            { left: "Capillary", right: "One cell thick, allows exchange with cells" },
          ],
          ask: "Match each blood vessel to its feature. Think about pressure and what each one does.",
          hints: [
            "Arteries carry blood away from the heart, so they hold high pressure.",
            "Veins bring blood back and use valves. Capillaries are where exchange happens.",
            "Artery thick wall away from heart, vein valves back to heart, capillary thin for exchange.",
          ],
          explain: "Arteries have thick walls and carry blood away from the heart. Veins have valves and return blood to the heart. Capillaries are one cell thick and allow exchange with cells.",
        },
        {
          kind: "order",
          prompt: "Order the path of blood starting as it returns from the body.",
          items: [
            "Blood enters the right side of the heart from the body",
            "Blood is pumped to the lungs to collect oxygen",
            "Oxygen rich blood returns to the left side of the heart",
            "Blood is pumped out to the rest of the body",
          ],
          ask: "Follow one drop of blood. It comes back low in oxygen first. Put the steps in order.",
          hints: [
            "Blood returning from the body is low in oxygen and enters the right side.",
            "It goes to the lungs for oxygen before the left side sends it out.",
            "Right side, to the lungs, back to the left side, then out to the body.",
          ],
          explain: "Blood returns from the body to the right side of the heart, is pumped to the lungs for oxygen, returns to the left side, and is then pumped out to the rest of the body.",
        },
        {
          kind: "insight",
          body: "Arteries away, veins back, capillaries exchange. The heart sends blood to the lungs, then out to the body.",
        },
      ],
      talkPrompt: "Quiz me on the heart and blood vessels, one at a time.",
    },
    {
      key: "bio-plants-1",
      title: "Transport in plants",
      minutes: 5,
      topic: "t10-nutrition-and-transport-in-plants",
      steps: [
        {
          kind: "concept",
          heading: "Two pipelines in a plant",
          body: "Plants move substances through two kinds of tissue. Xylem carries water and dissolved minerals up from the roots to the leaves. Phloem carries dissolved food, mainly sugars, from the leaves to the rest of the plant. The loss of water vapour from the leaves is called transpiration.",
        },
        {
          kind: "match",
          prompt: "Match each tissue or term to what it does.",
          pairs: [
            { left: "Xylem", right: "Carries water and minerals up from the roots" },
            { left: "Phloem", right: "Carries sugars from the leaves" },
            { left: "Transpiration", right: "Loss of water vapour from the leaves" },
            { left: "Root hair cell", right: "Absorbs water from the soil" },
          ],
          ask: "Match each part or term to its job. Xylem is water, phloem is food.",
          hints: [
            "Xylem moves water upward, phloem moves sugar around.",
            "Transpiration is water leaving the leaves. Root hairs take water in.",
            "Xylem carries water up, phloem carries sugars, transpiration is water loss, root hairs absorb water.",
          ],
          explain: "Xylem carries water and minerals up from the roots. Phloem carries sugars from the leaves. Transpiration is the loss of water vapour from the leaves, and root hair cells absorb water from the soil.",
        },
        {
          kind: "choice",
          question: "On a hot, windy day, what happens to the rate of transpiration?",
          options: [
            "It increases",
            "It decreases",
            "It stops completely",
            "It stays exactly the same",
          ],
          correct: 0,
          ask: "Heat and wind both affect how fast water leaves a leaf. What happens to transpiration? Pick one.",
          hints: [
            "Warmth gives water molecules more energy to evaporate.",
            "Wind carries the water vapour away, keeping evaporation going.",
          ],
          explain: "Transpiration increases. Heat speeds up evaporation from the leaves, and wind carries the water vapour away, so water is lost faster.",
        },
        {
          kind: "insight",
          body: "Xylem carries water up, phloem carries sugars around. Heat and wind speed transpiration up.",
        },
      ],
      talkPrompt: "Quiz me on transport in plants, one at a time.",
    },
    {
      key: "bio-excretion-1",
      title: "Excretion and the kidney",
      minutes: 6,
      topic: "t7-excretion-in-humans",
      steps: [
        {
          kind: "concept",
          heading: "Clearing the waste",
          body: "Excretion is the removal of waste made by the body's own reactions. The kidneys filter the blood, removing urea, excess water, and salts to form urine. Useful substances such as glucose are reabsorbed back into the blood. This keeps the blood clean and balanced.",
        },
        {
          kind: "order",
          prompt: "Order what happens to the blood in a kidney.",
          items: [
            "Blood enters the kidney under pressure",
            "Small molecules are filtered out of the blood",
            "Useful glucose and some water are reabsorbed",
            "The remaining urea and water leave as urine",
          ],
          ask: "The kidney filters first, then takes back what is useful. Put the steps in order.",
          hints: [
            "Filtering happens before anything is taken back.",
            "Glucose is reabsorbed, and what is left becomes urine.",
            "Blood enters, small molecules are filtered, useful ones are reabsorbed, then urine forms.",
          ],
          explain: "Blood enters the kidney under pressure, small molecules are filtered out, useful glucose and some water are reabsorbed, and the remaining urea and water leave as urine.",
        },
        {
          kind: "choice",
          question: "Glucose is filtered out of the blood but is not lost in the urine of a healthy person. Why?",
          options: [
            "It is all reabsorbed back into the blood",
            "It is destroyed inside the kidney",
            "It never enters the kidney at all",
            "It is turned into urea",
          ],
          correct: 0,
          ask: "Healthy urine has no glucose, yet glucose is small enough to be filtered. Where does it go? Pick one.",
          hints: [
            "Glucose is useful, so the body does not waste it.",
            "After filtering, the useful glucose is taken back into the blood.",
          ],
          explain: "The glucose is all reabsorbed back into the blood, because it is useful. Filtering removes it first, then reabsorption returns it, so none is lost in healthy urine.",
        },
        {
          kind: "insight",
          body: "The kidney filters everything small, then reabsorbs what is useful. Urea and excess water leave as urine.",
        },
      ],
      talkPrompt: "Quiz me on excretion and the kidney, one at a time.",
    },
    {
      key: "bio-reproduction-1",
      title: "Sexual reproduction in humans",
      minutes: 5,
      topic: "t13-reproduction",
      steps: [
        {
          kind: "concept",
          heading: "Two cells become one",
          body: "Sexual reproduction joins two sex cells, called gametes. The male gamete is the sperm and the female gamete is the egg, or ovum. When a sperm and egg join at fertilisation, they form a zygote that carries genetic information from both parents. The zygote then divides and grows.",
        },
        {
          kind: "match",
          prompt: "Match each structure to its role.",
          pairs: [
            { left: "Sperm", right: "Male gamete, adapted to swim" },
            { left: "Egg", right: "Female gamete, carries food store" },
            { left: "Zygote", right: "Cell formed at fertilisation" },
            { left: "Oviduct", right: "Where fertilisation usually happens" },
          ],
          ask: "Match each part to its role in reproduction. Start with the two gametes.",
          hints: [
            "The sperm is the male gamete, the egg is the female gamete.",
            "The zygote forms when they join, and this usually happens in the oviduct.",
            "Sperm male gamete, egg female gamete, zygote the joined cell, oviduct the site of fertilisation.",
          ],
          explain: "The sperm is the male gamete adapted to swim, the egg is the female gamete with a food store, the zygote is the cell formed at fertilisation, and fertilisation usually happens in the oviduct.",
        },
        {
          kind: "choice",
          question: "How many parents contribute genetic information to the zygote in sexual reproduction?",
          options: ["Two", "One", "Three", "None"],
          correct: 0,
          ask: "A zygote forms from two gametes. How many parents does its genetic information come from? Pick one.",
          hints: [
            "Each gamete comes from a different parent.",
            "One gamete from each parent means information from both.",
          ],
          explain: "Two parents contribute. One gamete comes from each parent, so the zygote carries genetic information from both, which is why offspring show a mix of features.",
        },
        {
          kind: "insight",
          body: "A sperm and an egg join at fertilisation to form a zygote, carrying genes from both parents.",
        },
      ],
      talkPrompt: "Quiz me on human reproduction, one at a time.",
    },
    {
      key: "bio-respiration-1",
      title: "Respiration in humans",
      minutes: 6,
      topic: "t6-respiration-in-humans",
      steps: [
        {
          kind: "concept",
          heading: "Releasing energy from food",
          body: "Respiration releases energy from glucose in every living cell. Aerobic respiration uses oxygen and gives out carbon dioxide and water, releasing a lot of energy. The word equation is glucose plus oxygen gives carbon dioxide plus water. Without oxygen, cells respire anaerobically and release much less energy.",
        },
        {
          kind: "tiles",
          prompt: "Build the word equation for aerobic respiration.",
          tiles: ["glucose", "+", "oxygen", "carbon dioxide", "water", "="],
          answer: ["glucose", "+", "oxygen", "=", "carbon dioxide", "+", "water"],
          ask: "Let us build the aerobic respiration equation. Glucose plus oxygen gives carbon dioxide plus water. Lay out the tiles.",
          hints: [
            "The reactants glucose and oxygen go on the left.",
            "The products are carbon dioxide and water.",
            "Glucose plus oxygen equals carbon dioxide plus water.",
          ],
          explain: "The word equation is glucose plus oxygen equals carbon dioxide plus water. Oxygen is used and carbon dioxide and water are made, releasing energy.",
        },
        {
          kind: "choice",
          question: "During hard exercise, muscles may respire without enough oxygen. What is the main effect?",
          options: [
            "Less energy is released and lactic acid builds up",
            "More energy is released than with oxygen",
            "No energy is released at all",
            "Carbon dioxide stops being produced forever",
          ],
          correct: 0,
          ask: "When oxygen runs short in the muscles, respiration changes. What happens to the energy and the products? Pick one.",
          hints: [
            "Anaerobic respiration releases much less energy than aerobic.",
            "In muscles it also produces lactic acid.",
          ],
          explain: "Less energy is released and lactic acid builds up. Anaerobic respiration in muscles gives far less energy than aerobic respiration and leaves lactic acid, which causes fatigue.",
        },
        {
          kind: "insight",
          body: "Glucose plus oxygen releases energy, carbon dioxide and water. Without oxygen, cells get much less energy.",
        },
      ],
      talkPrompt: "Quiz me on respiration, one at a time.",
    },
    {
      key: "bio-disease-1",
      title: "Infectious diseases",
      minutes: 5,
      topic: "t9-infectious-diseases-in-humans",
      steps: [
        {
          kind: "concept",
          heading: "Tiny invaders",
          body: "An infectious disease is caused by a pathogen, an organism that invades the body. Pathogens include bacteria, viruses, and fungi. They spread in different ways, such as through the air, in water, or by contact. Simple habits like washing hands and safe food handling reduce their spread.",
        },
        {
          kind: "match",
          prompt: "Match each pathogen or route to an example.",
          pairs: [
            { left: "Bacteria", right: "Living cells that can be killed by antibiotics" },
            { left: "Virus", right: "Not a cell, multiplies only inside a host" },
            { left: "Airborne spread", right: "Passed on by coughs and sneezes" },
            { left: "Waterborne spread", right: "Passed on through dirty water" },
          ],
          ask: "Match each term to its example. Think about what each pathogen is and how diseases travel.",
          hints: [
            "Bacteria are living cells, viruses are not cells at all.",
            "Coughs spread disease through the air, dirty water spreads it too.",
            "Bacteria killed by antibiotics, viruses need a host, airborne by coughs, waterborne by dirty water.",
          ],
          explain: "Bacteria are living cells that antibiotics can kill. Viruses are not cells and multiply only inside a host. Airborne diseases spread by coughs and sneezes, and waterborne diseases spread through dirty water.",
        },
        {
          kind: "choice",
          question: "Why does washing your hands help prevent the spread of disease?",
          options: [
            "It removes pathogens before they can enter the body",
            "It makes your skin immune to all disease",
            "It kills every pathogen in the room",
            "It replaces the need for any vaccines",
          ],
          correct: 0,
          ask: "Handwashing is a simple but powerful habit. What does it actually do? Pick the best answer.",
          hints: [
            "Think about where pathogens sit before they get inside you.",
            "Clean hands carry fewer pathogens to your mouth or food.",
          ],
          explain: "Washing hands removes pathogens before they can enter the body through your mouth or food. It lowers the number of pathogens passed on, though it does not make you immune.",
        },
        {
          kind: "insight",
          body: "Pathogens can be bacteria, viruses or fungi, and they spread in set ways. Good hygiene cuts that spread.",
        },
      ],
      talkPrompt: "Quiz me on infectious diseases, one at a time.",
    },
    {
      key: "bio-nutrition-1",
      title: "Nutrition and digestion",
      minutes: 6,
      topic: "t4-nutrition-in-humans",
      steps: [
        {
          kind: "concept",
          heading: "Breaking food down",
          body: "Digestion breaks large food molecules into small soluble ones the body can absorb. Enzymes speed this up. Amylase breaks starch into sugars, protease breaks proteins into amino acids, and lipase breaks fats into fatty acids and glycerol. The small molecules are then absorbed in the small intestine.",
        },
        {
          kind: "match",
          prompt: "Match each enzyme to what it digests.",
          pairs: [
            { left: "Amylase", right: "Starch into simple sugars" },
            { left: "Protease", right: "Proteins into amino acids" },
            { left: "Lipase", right: "Fats into fatty acids and glycerol" },
          ],
          ask: "Match each enzyme to the food it breaks down. The names give you a clue.",
          hints: [
            "Amylase works on starch, and its name is a hint.",
            "Protease works on protein, lipase works on lipids, which are fats.",
            "Amylase starch, protease protein, lipase fats.",
          ],
          explain: "Amylase breaks starch into simple sugars, protease breaks proteins into amino acids, and lipase breaks fats into fatty acids and glycerol.",
        },
        {
          kind: "order",
          prompt: "Order these parts of the gut in the direction food travels.",
          items: ["Mouth", "Stomach", "Small intestine", "Large intestine"],
          ask: "Follow the food from the first bite onward. Put these parts of the gut in order.",
          hints: [
            "Digestion starts in the mouth.",
            "After the stomach, most absorption happens in the small intestine.",
            "Mouth, stomach, small intestine, then large intestine.",
          ],
          explain: "Food travels from the mouth to the stomach, then the small intestine where most is absorbed, and finally the large intestine where water is absorbed.",
        },
        {
          kind: "insight",
          body: "Enzymes break big molecules into small ones. Amylase, protease and lipase each handle their own food group.",
        },
      ],
      talkPrompt: "Quiz me on nutrition and digestion, one at a time.",
    },
    {
      key: "bio-molgenetics-1",
      title: "DNA and base pairing",
      minutes: 5,
      topic: "t12-molecular-genetics",
      steps: [
        {
          kind: "concept",
          heading: "The code of life",
          body: "DNA carries the genetic instructions for building an organism. It is a double helix, two strands held together by pairs of bases. There are four bases: A, T, C, and G. They always pair in the same way, A with T and C with G, which lets DNA copy itself accurately.",
        },
        {
          kind: "match",
          prompt: "Match each base to the one it pairs with.",
          pairs: [
            { left: "A", right: "Pairs with T" },
            { left: "T", right: "Pairs with A" },
            { left: "C", right: "Pairs with G" },
            { left: "G", right: "Pairs with C" },
          ],
          ask: "Match each DNA base to its partner. Remember A goes with T, and C goes with G.",
          hints: [
            "A always pairs with T.",
            "C always pairs with G.",
            "A with T, T with A, C with G, G with C.",
          ],
          explain: "The base pairing rule is A with T and C with G. Each base has only one partner, which is why the two strands fit together exactly.",
        },
        {
          kind: "choice",
          question: "One DNA strand reads A C G. What is the matching sequence on the other strand?",
          options: ["T G C", "A C G", "G T A", "T C G"],
          correct: 0,
          ask: "Use the pairing rule on each base of A, C, G in turn. What is the partner sequence? Pick one.",
          hints: [
            "Take each base and write its partner underneath.",
            "A pairs with T, C pairs with G, G pairs with C.",
          ],
          explain: "The matching strand is T G C. A pairs with T, C pairs with G, and G pairs with C, so A C G becomes T G C.",
        },
        {
          kind: "insight",
          body: "DNA is two strands with A to T and C to G pairing. That fixed rule lets the code copy itself.",
        },
      ],
      talkPrompt: "Quiz me on DNA and base pairing, one at a time.",
    },
  ],
};
