// Interactive science micro-lessons (O-Level) for Project Playground.
// 5 chemistry, 8 physics, 8 biology. Displayed formulae use _ and ^ markers;
// spoken fields (ask, hints, explain) use plain words for text to speech.
import type { PlaygroundLesson } from "@/lib/playground-lessons";

export const SCIENCE_EXPANSION: Record<"chemistry" | "physics" | "biology", PlaygroundLesson[]> = {
  chemistry: [
    {
      key: "chem-particles-1",
      title: "Solids, liquids and gases",
      topic: "c2-particulate-nature-of-matter",
      minutes: 5,
      talkPrompt: "Quiz me on the three states of matter, one at a time.",
      steps: [
        {
          kind: "concept",
          heading: "Three states of matter",
          body: "All matter is made of tiny particles. In a solid they are packed close in a fixed pattern and only vibrate. In a liquid they touch but can slide past one another. In a gas they are far apart and move quickly in every direction.",
        },
        {
          kind: "order",
          prompt: "Order these states from least to most kinetic energy of the particles:",
          items: ["Solid", "Liquid", "Gas"],
          explain: "Adding heat gives particles more energy. Solid particles only vibrate, liquid particles slide, and gas particles fly around freely, so kinetic energy rises from solid to liquid to gas.",
          ask: "Which state has particles with the most energy, and which has the least?",
          hints: [
            "Think about how freely the particles can move in each state.",
            "Heating a solid turns it into a liquid, then into a gas.",
            "The freest, fastest particles carry the most energy.",
          ],
        },
        {
          kind: "match",
          prompt: "Match each state to how it behaves:",
          pairs: [
            { left: "Solid", right: "Fixed shape and fixed volume" },
            { left: "Liquid", right: "Fixed volume, takes the shape of its container" },
            { left: "Gas", right: "No fixed shape, fills its whole container" },
          ],
          explain: "A solid keeps its shape because its particles are locked in place. A liquid flows to fit the container but keeps its volume. A gas spreads out to fill any space it is given.",
          ask: "Which state keeps both its shape and its volume?",
          hints: [
            "Only one state holds a rigid shape on its own.",
            "A liquid pours but does not expand to fill a room.",
            "A gas has neither a fixed shape nor a fixed volume.",
          ],
        },
        {
          kind: "insight",
          body: "The state of matter is really just a story about how much energy the particles have and how tightly they are held together.",
        },
      ],
    },
    {
      key: "chem-periodic-1",
      title: "Reading the Periodic Table",
      topic: "c8-patterns-in-the-periodic-table",
      minutes: 5,
      talkPrompt: "Quiz me on groups and periods, one at a time.",
      steps: [
        {
          kind: "concept",
          heading: "Groups and periods",
          body: "The Periodic Table sorts elements by increasing proton number. A vertical column is a group, and elements in the same group share similar chemical properties. A horizontal row is a period, and the number of electron shells matches the period number.",
        },
        {
          kind: "choice",
          question: "For a main group element, what does the group number tell you?",
          options: [
            "The number of electrons in its outer shell",
            "The number of neutrons in the atom",
            "The relative atomic mass",
            "The number of electron shells",
          ],
          correct: 0,
          explain: "The group number for a main group element equals the number of outer shell, or valence, electrons. That is why elements in a group react in similar ways.",
          ask: "What do the atoms in a single group have in common about their electrons?",
          hints: [
            "It is about the outermost shell, not the whole atom.",
            "Elements in the same group react in similar ways for this reason.",
            "The count of outer electrons matches the group number.",
          ],
        },
        {
          kind: "tiles",
          prompt: "Tap the Group I metals in order of increasing reactivity:",
          tiles: ["Li", "Na", "K", "Mg", "Ca"],
          answer: ["Li", "Na", "K"],
          explain: "In Group I, reactivity increases going down the group, so lithium is less reactive than sodium, which is less reactive than potassium. Magnesium and calcium are Group II distractors.",
          ask: "As you go down Group one, does reactivity increase or decrease?",
          hints: [
            "Lithium sits at the top of the group and calcium is not in this group.",
            "Reactivity rises as you move down Group one.",
            "The order runs lithium, then sodium, then potassium.",
          ],
        },
        {
          kind: "insight",
          body: "Position on the Periodic Table is a shortcut to behaviour: the group tells you the outer electrons, and the period tells you the number of shells.",
        },
      ],
    },
    {
      key: "chem-energetics-1",
      title: "Exothermic or endothermic",
      topic: "c9-chemical-energetics",
      minutes: 5,
      talkPrompt: "Quiz me on exothermic and endothermic reactions, one at a time.",
      steps: [
        {
          kind: "concept",
          heading: "Energy in and energy out",
          body: "Every reaction breaks bonds and makes new ones. Breaking bonds takes in energy and making bonds gives out energy. If more energy is released than taken in, the reaction is exothermic and the surroundings warm up. If more is taken in, it is endothermic and the surroundings cool down.",
        },
        {
          kind: "choice",
          question: "Which of these is an exothermic reaction?",
          options: [
            "Combustion of methane fuel",
            "Thermal decomposition of CaCO_3",
            "Photosynthesis in a leaf",
            "Melting of ice",
          ],
          correct: 0,
          explain: "Burning a fuel releases a lot of heat to the surroundings, so combustion is exothermic. Decomposition, photosynthesis, and melting all take in energy.",
          ask: "Does burning a fuel release heat or take it in?",
          hints: [
            "Think about what happens to the temperature near a flame.",
            "A process that heats up the surroundings is exothermic.",
            "Burning fuel gives out heat, so it is exothermic.",
          ],
        },
        {
          kind: "match",
          prompt: "Match each process to its energy type:",
          pairs: [
            { left: "Combustion of fuel", right: "Exothermic" },
            { left: "Neutralisation of acid and alkali", right: "Exothermic" },
            { left: "Photosynthesis", right: "Endothermic" },
            { left: "Thermal decomposition", right: "Endothermic" },
          ],
          explain: "Combustion and neutralisation give out heat, so they are exothermic. Photosynthesis and thermal decomposition take in energy from their surroundings, so they are endothermic.",
          ask: "Does a process that cools its surroundings take in energy or give it out?",
          hints: [
            "Exothermic means heat exits to the surroundings.",
            "Decomposition needs energy supplied, usually as heat.",
            "Photosynthesis stores energy taken in from light.",
          ],
        },
        {
          kind: "insight",
          body: "Follow the heat: if the surroundings get warmer the reaction released energy, and if they get colder it soaked energy up.",
        },
      ],
    },
    {
      key: "chem-organic-1",
      title: "The alkane and alkene families",
      topic: "c11-organic-chemistry",
      minutes: 5,
      talkPrompt: "Quiz me on alkanes and alkenes, one at a time.",
      steps: [
        {
          kind: "concept",
          heading: "Two hydrocarbon families",
          body: "Hydrocarbons contain only carbon and hydrogen. Alkanes have single bonds only and are saturated, with the general formula C_nH_{2n+2}. Alkenes contain a carbon to carbon double bond and are unsaturated, with the general formula C_nH_{2n}.",
        },
        {
          kind: "match",
          prompt: "Match each molecule to its name and family:",
          pairs: [
            { left: "CH_4", right: "Methane, an alkane" },
            { left: "C_2H_6", right: "Ethane, an alkane" },
            { left: "C_2H_4", right: "Ethene, an alkene" },
            { left: "C_3H_6", right: "Propene, an alkene" },
          ],
          explain: "Methane and ethane fit the alkane pattern with only single bonds. Ethene and propene each have a double bond and fit the alkene pattern, with two fewer hydrogen atoms than the matching alkane.",
          ask: "How can you tell an alkene formula from an alkane formula?",
          hints: [
            "Alkanes carry the most hydrogen atoms they possibly can.",
            "An alkene has two fewer hydrogen atoms because of its double bond.",
            "Ethene and propene both belong to the alkene family.",
          ],
        },
        {
          kind: "tiles",
          prompt: "Build the general formula of an alkane:",
          tiles: ["C_n", "H_{2n+2}", "H_{2n}", "C_{2n}"],
          answer: ["C_n", "H_{2n+2}"],
          explain: "An alkane has carbon n paired with hydrogen two n plus two. The hydrogen two n token would give an alkene, so it is a distractor here.",
          ask: "For every carbon n in an alkane, how many hydrogen atoms are there?",
          hints: [
            "Alkanes hold as many hydrogen atoms as possible.",
            "The count is two times the carbons, plus two more.",
            "Pick the carbon n tile and the two n plus two hydrogen tile.",
          ],
        },
        {
          kind: "insight",
          body: "One double bond is the whole difference: it makes an alkene unsaturated and reactive, while a saturated alkane holds all the hydrogen it can.",
        },
      ],
    },
    {
      key: "chem-airquality-1",
      title: "Air pollutants and their sources",
      topic: "c12-maintaining-air-quality",
      minutes: 4,
      talkPrompt: "Quiz me on air pollutants and their sources, one at a time.",
      steps: [
        {
          kind: "concept",
          heading: "What dirties the air",
          body: "Burning fuels adds harmful gases to the air. Incomplete combustion makes carbon monoxide, sulfur impurities make sulfur dioxide, and very hot engines make oxides of nitrogen. Some of these gases cause acid rain, while others harm health directly.",
        },
        {
          kind: "match",
          prompt: "Match each pollutant to its main source:",
          pairs: [
            { left: "Carbon monoxide", right: "Incomplete combustion of fuels" },
            { left: "Sulfur dioxide", right: "Burning fossil fuels that contain sulfur" },
            { left: "Oxides of nitrogen", right: "High temperature combustion in car engines" },
            { left: "Methane", right: "Decomposition of vegetation and waste from livestock" },
          ],
          explain: "Carbon monoxide comes from a lack of oxygen while burning. Sulfur dioxide comes from sulfur in the fuel. Oxides of nitrogen form when the air in a hot engine reacts. Methane comes mainly from rotting matter and livestock.",
          ask: "Which pollutant forms when there is not enough oxygen to burn a fuel fully?",
          hints: [
            "Too little oxygen leaves a carbon based gas.",
            "It is carbon joined to a single oxygen atom.",
            "That gas is carbon monoxide.",
          ],
        },
        {
          kind: "choice",
          question: "Which pollutant reduces the ability of blood to carry oxygen?",
          options: [
            "Carbon monoxide",
            "Sulfur dioxide",
            "Carbon dioxide",
            "Oxides of nitrogen",
          ],
          correct: 0,
          explain: "Carbon monoxide binds tightly to haemoglobin in red blood cells, so less oxygen can be carried around the body. This is why it is so dangerous.",
          ask: "Which gas attaches to the red pigment in blood in place of oxygen?",
          hints: [
            "It is the product of incomplete burning.",
            "It sticks to haemoglobin more strongly than oxygen does.",
            "The answer is carbon monoxide.",
          ],
        },
        {
          kind: "insight",
          body: "Most air pollutants trace straight back to burning: change how and what we burn, and the air gets cleaner.",
        },
      ],
    },
  ],
  physics: [
    {
      key: "phys-kinematics-1",
      title: "Speed, velocity and acceleration",
      topic: "t2-kinematics",
      minutes: 6,
      talkPrompt: "Quiz me on speed, velocity and acceleration, one at a time.",
      steps: [
        {
          kind: "concept",
          heading: "Describing motion",
          body: "Speed is how far you travel each second. Velocity is speed in a stated direction. Acceleration is how quickly velocity changes each second. On a speed against time graph, the gradient gives the acceleration and the area under the line gives the distance.",
        },
        {
          kind: "slider",
          prompt: "A car speeds up from rest to 20 m/s in 5 s. Set its acceleration in m/s^2:",
          min: 0,
          max: 10,
          step: 0.5,
          unit: "m/s^2",
          start: 8,
          targetMin: 3.5,
          targetMax: 4.5,
          explain: "Acceleration is the change in velocity divided by the time taken. Twenty metres per second gained over five seconds gives four metres per second squared.",
          ask: "Take the change in speed and divide it by the time. What do you get?",
          hints: [
            "Acceleration is change in velocity divided by time.",
            "The car gains twenty metres per second over five seconds.",
            "Twenty divided by five gives four.",
          ],
        },
        {
          kind: "plot",
          prompt: "On this speed against time graph, plot the car's motion at 5 s when its speed is 20 m/s:",
          xLabel: "time/s",
          yLabel: "speed/(m/s)",
          xMax: 10,
          yMax: 30,
          targetX: 5,
          targetY: 20,
          tolerance: 1,
          explain: "At five seconds the speed has reached twenty metres per second, so the point sits at five across and twenty up.",
          ask: "Where on the grid is a time of five seconds and a speed of twenty?",
          hints: [
            "Read five along the bottom time axis.",
            "Read twenty up the speed axis.",
            "Place the point where those two lines meet.",
          ],
        },
        {
          kind: "choice",
          question: "What does the gradient of a speed against time graph represent?",
          options: [
            "The acceleration",
            "The total distance",
            "The speed at that instant",
            "The force on the object",
          ],
          correct: 0,
          explain: "Gradient is change in speed over change in time, which is exactly the definition of acceleration. The area under the line, not the gradient, gives distance.",
          ask: "A steeper slope on this graph means the object is doing what more quickly?",
          hints: [
            "Gradient is a change in speed divided by a change in time.",
            "That ratio has a special name in motion.",
            "The gradient is the acceleration.",
          ],
        },
        {
          kind: "insight",
          body: "A speed against time graph packs two answers into one line: its slope is the acceleration and the area beneath it is the distance.",
        },
      ],
    },
    {
      key: "phys-pressure-1",
      title: "Pressure in solids and liquids",
      topic: "t5-pressure",
      minutes: 5,
      talkPrompt: "Quiz me on pressure, one at a time.",
      steps: [
        {
          kind: "concept",
          heading: "Force spread over area",
          body: "Pressure is the force acting on each unit of area, written as pressure equals force divided by area. A smaller area under the same force gives a larger pressure. In a liquid, pressure also grows with depth and acts equally in all directions.",
        },
        {
          kind: "slider",
          prompt: "A force of 20 N presses on an area of 4 m^2. Set the pressure in Pa:",
          min: 0,
          max: 20,
          step: 0.5,
          unit: "Pa",
          start: 14,
          targetMin: 4.5,
          targetMax: 5.5,
          explain: "Pressure is force divided by area. Twenty newtons spread over four square metres gives five pascals.",
          ask: "Divide the force by the area. What is the pressure?",
          hints: [
            "Pressure is force divided by area.",
            "Share twenty newtons over four square metres.",
            "Twenty divided by four gives five.",
          ],
        },
        {
          kind: "choice",
          question: "Pressure in a liquid increases mainly with which of these?",
          options: [
            "The depth below the surface",
            "The colour of the liquid",
            "The shape of the container",
            "The width of the container",
          ],
          correct: 0,
          explain: "The deeper you go, the greater the weight of liquid above you, so the pressure rises with depth. The shape and width of the container do not change it.",
          ask: "Does the pressure get larger as you go deeper or shallower?",
          hints: [
            "Think about the weight of liquid stacked above a point.",
            "More liquid above means more pressure.",
            "Pressure increases with depth.",
          ],
        },
        {
          kind: "insight",
          body: "The same force feels sharp or gentle depending on area: squeeze it onto a small area for high pressure, spread it wide for low pressure.",
        },
      ],
    },
    {
      key: "phys-kpm-1",
      title: "The kinetic particle model",
      topic: "t7-kinetic-particle-model-of-matter",
      minutes: 5,
      talkPrompt: "Quiz me on the kinetic particle model, one at a time.",
      steps: [
        {
          kind: "concept",
          heading: "Particles in motion",
          body: "The kinetic particle model says all matter is made of particles that are always moving. Heating gives them more kinetic energy. This one idea explains changes of state, gas pressure, and why gases can be squashed while solids cannot.",
        },
        {
          kind: "match",
          prompt: "Match each state to how its particles move:",
          pairs: [
            { left: "Solid", right: "Particles vibrate about fixed positions" },
            { left: "Liquid", right: "Particles are close but slide past one another" },
            { left: "Gas", right: "Particles move fast and far apart in all directions" },
          ],
          explain: "Solid particles are locked in place and only vibrate. Liquid particles keep contact but can move around. Gas particles are far apart and travel quickly until they collide.",
          ask: "In which state do the particles only vibrate on the spot?",
          hints: [
            "This state holds a rigid shape.",
            "Its particles cannot move from place to place.",
            "That state is a solid.",
          ],
        },
        {
          kind: "choice",
          question: "When a fixed volume of gas is heated, its pressure rises because the particles:",
          options: [
            "Hit the walls harder and more often",
            "Grow larger in size",
            "Gain extra mass",
            "Stop moving",
          ],
          correct: 0,
          explain: "Heating makes gas particles move faster, so they strike the container walls harder and more frequently. More frequent, harder collisions mean a greater pressure.",
          ask: "Heating speeds the particles up. What does that do to their collisions with the walls?",
          hints: [
            "Faster particles reach the walls more often.",
            "Each hit is also harder when they move faster.",
            "More frequent, stronger hits raise the pressure.",
          ],
        },
        {
          kind: "insight",
          body: "Almost every gas behaviour comes back to one picture: countless tiny particles, always moving, bouncing off whatever they meet.",
        },
      ],
    },
    {
      key: "phys-thermal-1",
      title: "Heat capacity and latent heat",
      topic: "t9-thermal-properties-of-matter",
      minutes: 5,
      talkPrompt: "Quiz me on heat capacity and latent heat, one at a time.",
      steps: [
        {
          kind: "concept",
          heading: "Two kinds of heating",
          body: "Specific heat capacity is the energy needed to raise one kilogram of a substance by one degree. Latent heat is the energy needed to change state with no change in temperature. During melting or boiling the temperature stays flat because the energy is breaking bonds between particles.",
        },
        {
          kind: "slider",
          prompt: "A 2 kg block needs 8000 J to warm up. Its specific heat capacity is 2000 J/(kg°C). Set the temperature rise in °C:",
          min: 0,
          max: 10,
          step: 1,
          unit: "°C",
          start: 7,
          targetMin: 1.5,
          targetMax: 2.5,
          explain: "The energy equals mass times specific heat capacity times temperature rise. Eight thousand joules divided by two kilograms and by two thousand gives a rise of two degrees.",
          ask: "Divide the energy by the mass and then by the specific heat capacity. What rise do you get?",
          hints: [
            "Energy equals mass times heat capacity times temperature rise.",
            "Rearrange to find the temperature rise on its own.",
            "Eight thousand divided by two, then by two thousand, gives two.",
          ],
        },
        {
          kind: "choice",
          question: "While a solid melts, its temperature stays constant because the energy is:",
          options: [
            "Breaking the bonds between particles",
            "Lost to outer space",
            "Increasing the particle speed",
            "Being destroyed",
          ],
          correct: 0,
          explain: "During a change of state the supplied energy separates the particles rather than speeding them up, so the temperature holds steady until melting is complete.",
          ask: "If the temperature is not rising, where is the energy going during melting?",
          hints: [
            "The particles are being pulled apart, not sped up.",
            "This energy is the latent heat of melting.",
            "It goes into breaking the bonds between particles.",
          ],
        },
        {
          kind: "insight",
          body: "A flat step on a heating graph is latent heat at work: energy is going into changing state, not into raising the temperature.",
        },
      ],
    },
    {
      key: "phys-light-1",
      title: "Reflection and refraction",
      topic: "t12-light",
      minutes: 5,
      talkPrompt: "Quiz me on reflection and refraction, one at a time.",
      steps: [
        {
          kind: "concept",
          heading: "Bouncing and bending",
          body: "Reflection is light bouncing off a surface, where the angle of incidence equals the angle of reflection. Refraction is light bending as it changes speed passing between materials. Both angles are always measured from the normal, the line drawn at ninety degrees to the surface.",
        },
        {
          kind: "match",
          prompt: "Match each term to its meaning:",
          pairs: [
            { left: "Law of reflection", right: "Angle of incidence equals angle of reflection" },
            { left: "Refraction", right: "Light bends as it changes speed between materials" },
            { left: "Normal", right: "A line drawn at ninety degrees to the surface" },
            { left: "Total internal reflection", right: "Light reflects fully beyond the critical angle" },
          ],
          explain: "The law of reflection compares the two angles at a mirror. Refraction is bending due to a speed change. The normal is the reference line for measuring angles. Beyond the critical angle, light stays inside by total internal reflection.",
          ask: "The angle of incidence and the angle of reflection compare how, at a mirror?",
          hints: [
            "Both angles are measured from the normal line.",
            "At a flat mirror they are always equal.",
            "The law of reflection states they are equal.",
          ],
        },
        {
          kind: "choice",
          question: "When light passes from air into glass, it:",
          options: [
            "Slows down and bends toward the normal",
            "Speeds up and bends toward the normal",
            "Slows down and bends away from the normal",
            "Keeps the same speed and direction",
          ],
          correct: 0,
          explain: "Glass is denser than air, so light slows down when it enters and bends toward the normal. Going the other way, into air, it would speed up and bend away.",
          ask: "Glass is denser than air, so does the light speed up or slow down going in?",
          hints: [
            "Denser materials slow light down.",
            "Slowing down bends the ray toward the normal.",
            "It slows down and bends toward the normal.",
          ],
        },
        {
          kind: "insight",
          body: "Every angle in optics is measured from the normal, and light bends toward that line whenever it slows into a denser material.",
        },
      ],
    },
    {
      key: "phys-current-1",
      title: "Current, voltage and resistance",
      topic: "t14-current-of-electricity",
      minutes: 5,
      talkPrompt: "Quiz me on current, voltage and resistance, one at a time.",
      steps: [
        {
          kind: "concept",
          heading: "Ohm's law",
          body: "Current is the flow of charge, voltage is the push that drives it, and resistance opposes the flow. They are linked by voltage equals current times resistance. In a series circuit the current is the same everywhere, while the voltage is shared between components.",
        },
        {
          kind: "slider",
          prompt: "A resistor of 5 Ω carries a current of 2 A. Set the voltage across it in V:",
          min: 0,
          max: 20,
          step: 1,
          unit: "V",
          start: 4,
          targetMin: 9.5,
          targetMax: 10.5,
          explain: "Voltage equals current times resistance. Two amperes through five ohms gives ten volts.",
          ask: "Multiply the current by the resistance. What voltage do you get?",
          hints: [
            "Voltage equals current times resistance.",
            "Multiply two amperes by five ohms.",
            "The answer is ten volts.",
          ],
        },
        {
          kind: "choice",
          question: "In a simple series circuit, the current is:",
          options: [
            "The same at every point",
            "Largest right next to the battery",
            "Zero in the wires",
            "Different through each component",
          ],
          correct: 0,
          explain: "A series circuit has only one path, so the same charge flows through every part each second. That means the current reads the same wherever you place the ammeter.",
          ask: "With only one loop for the charge to follow, how does the current compare around the circuit?",
          hints: [
            "There is only one path in a series circuit.",
            "Charge cannot pile up or disappear along the way.",
            "The current is the same at every point.",
          ],
        },
        {
          kind: "insight",
          body: "Voltage, current and resistance are locked together: fix any two and Ohm's law hands you the third.",
        },
      ],
    },
    {
      key: "phys-practical-elec-1",
      title: "Power, fuses and safety",
      topic: "t16-practical-electricity",
      minutes: 6,
      talkPrompt: "Quiz me on electrical power and safety, one at a time.",
      steps: [
        {
          kind: "concept",
          heading: "Power and protection",
          body: "Electrical power is the energy used each second, given by power equals voltage times current. Fuses and circuit breakers protect a circuit by cutting the flow if the current gets too high. A short circuit lets current bypass a device along a path of very low resistance.",
        },
        {
          kind: "slider",
          prompt: "A device runs at 240 V and draws a current of 0.5 A. Set its power in W:",
          min: 0,
          max: 300,
          step: 10,
          unit: "W",
          start: 200,
          targetMin: 115,
          targetMax: 125,
          explain: "Power equals voltage times current. Two hundred and forty volts times half an ampere gives one hundred and twenty watts.",
          ask: "Multiply the voltage by the current. What power do you get?",
          hints: [
            "Power equals voltage times current.",
            "Take two hundred and forty and multiply by one half.",
            "The answer is one hundred and twenty watts.",
          ],
        },
        {
          kind: "circuit",
          prompt: "Close the switches so the lamp lights, without creating a short circuit:",
          switches: [
            { id: "s1", label: "Main supply switch" },
            { id: "s2", label: "Lamp switch" },
            { id: "s3", label: "Bypass wire across the lamp", shortsLamp: true },
          ],
          needed: ["s1", "s2"],
          explain: "Closing the main supply and the lamp switch completes the loop through the lamp. The bypass wire must stay open, because closing it would short the lamp and stop it lighting.",
          ask: "Which switch must you leave open so the current does not skip past the lamp?",
          hints: [
            "You need the supply and the lamp in the loop.",
            "One switch offers a shortcut around the lamp.",
            "Leave the bypass wire open and close the other two.",
          ],
        },
        {
          kind: "choice",
          question: "A fuse protects a circuit by:",
          options: [
            "Melting and breaking the circuit if the current is too high",
            "Increasing the current in the circuit",
            "Storing charge for later",
            "Cooling the wires down",
          ],
          correct: 0,
          explain: "A fuse is a thin wire that heats up and melts when the current exceeds its rating. Once it melts, the circuit is broken and the flow stops, keeping the appliance and user safer.",
          ask: "What happens to the thin wire inside a fuse when the current gets too large?",
          hints: [
            "The fuse wire is deliberately thin so it heats up.",
            "Too much current makes it melt.",
            "Melting breaks the circuit and stops the current.",
          ],
        },
        {
          kind: "insight",
          body: "A fuse is a planned weak point: it is meant to fail first so that the rest of the circuit and the person using it stay safe.",
        },
      ],
    },
    {
      key: "phys-radioactivity-1",
      title: "Alpha, beta and gamma",
      topic: "t20-radioactivity",
      minutes: 5,
      talkPrompt: "Quiz me on the three types of radiation, one at a time.",
      steps: [
        {
          kind: "concept",
          heading: "Three kinds of radiation",
          body: "Unstable nuclei give out radiation. Alpha is a helium nucleus, heavy and easily stopped. Beta is a fast electron with medium penetration. Gamma is a high energy electromagnetic wave with the greatest penetration and no charge.",
        },
        {
          kind: "match",
          prompt: "Match each type of radiation to its description:",
          pairs: [
            { left: "Alpha", right: "A helium nucleus, stopped by a sheet of paper" },
            { left: "Beta", right: "A fast electron, stopped by a few millimetres of aluminium" },
            { left: "Gamma", right: "An electromagnetic wave, reduced by thick lead" },
          ],
          explain: "Alpha particles are large and lose energy quickly, so paper stops them. Beta particles are smaller and need aluminium. Gamma rays carry no charge and pass through most materials, so only dense lead reduces them much.",
          ask: "Which radiation is a helium nucleus that even paper can stop?",
          hints: [
            "It is the heaviest of the three and the least penetrating.",
            "It is made of two protons and two neutrons.",
            "That radiation is alpha.",
          ],
        },
        {
          kind: "order",
          prompt: "Order these radiations from least to most penetrating:",
          items: ["Alpha", "Beta", "Gamma"],
          explain: "Alpha is stopped by paper, beta needs aluminium, and gamma passes through all but thick lead, so penetration increases from alpha to beta to gamma.",
          ask: "Which radiation travels through the most material before it is stopped?",
          hints: [
            "Alpha is blocked most easily, by paper.",
            "Gamma slips through almost everything.",
            "The order runs alpha, then beta, then gamma.",
          ],
        },
        {
          kind: "insight",
          body: "There is a neat trade off in radiation: the heavier and more charged it is, the more damage it does up close but the more easily it is stopped.",
        },
      ],
    },
  ],
  biology: [
    {
      key: "bio-nutrition-1",
      title: "The human digestive system",
      topic: "t4-nutrition-in-humans",
      minutes: 5,
      talkPrompt: "Quiz me on digestion, one at a time.",
      steps: [
        {
          kind: "concept",
          heading: "Breaking food down",
          body: "Digestion turns large food molecules into small soluble ones that can be absorbed into the blood. Enzymes speed up this breakdown along the gut. The small intestine is where most digested food is absorbed into the bloodstream.",
        },
        {
          kind: "order",
          prompt: "Order the parts that food passes through:",
          items: ["Mouth", "Oesophagus", "Stomach", "Small intestine", "Large intestine"],
          explain: "Food is chewed in the mouth, pushed down the oesophagus, churned in the stomach, digested and absorbed in the small intestine, then water is absorbed in the large intestine.",
          ask: "After the stomach, which part absorbs most of the digested food?",
          hints: [
            "Food starts in the mouth and ends at the large intestine.",
            "The stomach comes before the intestines.",
            "The small intestine handles most absorption, before the large intestine.",
          ],
        },
        {
          kind: "match",
          prompt: "Match each enzyme to what it breaks down:",
          pairs: [
            { left: "Amylase", right: "Breaks starch into maltose" },
            { left: "Protease", right: "Breaks protein into amino acids" },
            { left: "Lipase", right: "Breaks fats into fatty acids and glycerol" },
          ],
          explain: "Amylase works on starch, protease on protein, and lipase on fats. Each enzyme is specific to one type of food molecule.",
          ask: "Which enzyme breaks protein down into amino acids?",
          hints: [
            "Its name is built from the word for the food it acts on.",
            "The enzyme that acts on protein starts with the same sound.",
            "Protease breaks protein into amino acids.",
          ],
        },
        {
          kind: "insight",
          body: "Digestion is a demolition job: enzymes cut big insoluble molecules into small soluble ones the body can finally absorb.",
        },
      ],
    },
    {
      key: "bio-circulation-1",
      title: "The heart and blood vessels",
      topic: "t5-transport-in-humans",
      minutes: 5,
      talkPrompt: "Quiz me on the heart and blood vessels, one at a time.",
      steps: [
        {
          kind: "concept",
          heading: "Pump and pipes",
          body: "The heart is a muscular pump that pushes blood around the body. Arteries carry blood away from the heart at high pressure, veins return it at low pressure, and capillaries are tiny vessels where substances are exchanged with the tissues.",
        },
        {
          kind: "match",
          prompt: "Match each vessel to its feature:",
          pairs: [
            { left: "Artery", right: "Carries blood away from the heart at high pressure" },
            { left: "Vein", right: "Returns blood to the heart and has valves" },
            { left: "Capillary", right: "Very thin wall for exchange with the tissues" },
          ],
          explain: "Arteries have thick walls to cope with high pressure. Veins have valves to stop backflow at low pressure. Capillaries have walls one cell thick so substances can pass through easily.",
          ask: "Which vessel has valves to stop blood flowing backwards?",
          hints: [
            "It carries blood back toward the heart at low pressure.",
            "Low pressure needs help to keep blood moving one way.",
            "Veins have valves.",
          ],
        },
        {
          kind: "choice",
          question: "Which side of the heart pumps oxygenated blood to the body?",
          options: [
            "The left side",
            "The right side",
            "Both sides equally",
            "Neither side",
          ],
          correct: 0,
          explain: "The left side receives oxygenated blood from the lungs and pumps it around the whole body, so its muscle wall is thicker. The right side sends deoxygenated blood to the lungs.",
          ask: "The thicker, more muscular side pushes blood the furthest. Which side is that?",
          hints: [
            "One side pumps only to the nearby lungs, the other to the whole body.",
            "Pumping further needs a thicker muscle wall.",
            "The left side pumps oxygenated blood to the body.",
          ],
        },
        {
          kind: "insight",
          body: "Vessel walls match the job: thick and springy for high pressure arteries, valved for low pressure veins, and paper thin for exchange in capillaries.",
        },
      ],
    },
    {
      key: "bio-respiration-1",
      title: "Aerobic and anaerobic respiration",
      topic: "t6-respiration-in-humans",
      minutes: 5,
      talkPrompt: "Quiz me on respiration, one at a time.",
      steps: [
        {
          kind: "concept",
          heading: "Releasing energy from glucose",
          body: "Respiration releases energy from glucose in every living cell. Aerobic respiration uses oxygen and releases a lot of energy. Anaerobic respiration works without oxygen, releases less energy, and produces different products depending on the organism.",
        },
        {
          kind: "choice",
          question: "Aerobic respiration releases more energy than anaerobic respiration because it:",
          options: [
            "Fully breaks glucose down to carbon dioxide and water",
            "Uses much less oxygen",
            "Always produces lactic acid",
            "Happens much faster",
          ],
          correct: 0,
          explain: "With oxygen present, glucose is broken down completely to carbon dioxide and water, releasing all its stored energy. Anaerobic respiration only breaks it down partly, so it releases far less.",
          ask: "Does aerobic respiration break glucose down completely or only part way?",
          hints: [
            "Oxygen lets the cell finish the job.",
            "A complete breakdown releases more energy.",
            "It breaks glucose fully to carbon dioxide and water.",
          ],
        },
        {
          kind: "match",
          prompt: "Match each type of respiration to its products:",
          pairs: [
            { left: "Aerobic respiration", right: "Glucose plus oxygen gives carbon dioxide and water" },
            { left: "Anaerobic respiration in muscle", right: "Glucose gives lactic acid" },
            { left: "Anaerobic respiration in yeast", right: "Glucose gives ethanol and carbon dioxide" },
          ],
          explain: "With oxygen, the products are carbon dioxide and water. In hard working muscle without enough oxygen, lactic acid builds up. In yeast, the products are ethanol and carbon dioxide, which is used in brewing.",
          ask: "What does hard working muscle produce when it runs short of oxygen?",
          hints: [
            "Muscle uses anaerobic respiration when oxygen runs low.",
            "The product causes the burning feeling in tired muscles.",
            "It produces lactic acid.",
          ],
        },
        {
          kind: "insight",
          body: "Oxygen is the difference: with it, glucose is fully burned for maximum energy, and without it the cell settles for a smaller, quicker payout.",
        },
      ],
    },
    {
      key: "bio-excretion-1",
      title: "Kidneys and excretion",
      topic: "t7-excretion-in-humans",
      minutes: 5,
      talkPrompt: "Quiz me on excretion, one at a time.",
      steps: [
        {
          kind: "concept",
          heading: "Removing waste",
          body: "Excretion is the removal of waste made by the body's own reactions. The kidneys filter the blood, remove urea and excess water and salts, and make urine. The lungs excrete carbon dioxide, and the skin loses some salts and water in sweat.",
        },
        {
          kind: "choice",
          question: "Which organ removes urea from the blood?",
          options: [
            "The kidney",
            "The lung",
            "The stomach",
            "The heart",
          ],
          correct: 0,
          explain: "Urea is made in the liver from excess amino acids, then carried in the blood to the kidneys, which filter it out and pass it into urine.",
          ask: "Which organ filters the blood to make urine?",
          hints: [
            "This organ makes urine.",
            "There is a pair of them near the lower back.",
            "The kidney removes urea from the blood.",
          ],
        },
        {
          kind: "match",
          prompt: "Match each organ to its role in excretion:",
          pairs: [
            { left: "Kidney", right: "Filters blood and makes urine" },
            { left: "Lungs", right: "Remove carbon dioxide from the body" },
            { left: "Bladder", right: "Stores urine before it is released" },
            { left: "Ureter", right: "Carries urine from the kidney to the bladder" },
          ],
          explain: "The kidney filters and makes urine, the ureter carries it, and the bladder stores it. The lungs deal with a different waste, carbon dioxide from respiration.",
          ask: "Which tube carries urine from the kidney to the bladder?",
          hints: [
            "It connects the kidney to the storage organ.",
            "Its name is close to the word for urine.",
            "The ureter carries urine to the bladder.",
          ],
        },
        {
          kind: "insight",
          body: "Excretion is housekeeping for the body: the kidneys, lungs and skin each clear out a waste that would otherwise build up and harm you.",
        },
      ],
    },
    {
      key: "bio-homeostasis-1",
      title: "Keeping the body steady",
      topic: "t8-homeostasis-co-ordination-and-response",
      minutes: 5,
      talkPrompt: "Quiz me on homeostasis, one at a time.",
      steps: [
        {
          kind: "concept",
          heading: "Staying in balance",
          body: "Homeostasis is keeping conditions inside the body steady, such as temperature and blood glucose. The body senses a change, then responds to bring the level back to normal. This constant correction is called negative feedback.",
        },
        {
          kind: "choice",
          question: "When blood glucose rises, the pancreas releases insulin, which:",
          options: [
            "Helps the liver store glucose as glycogen",
            "Breaks stored glycogen back into glucose",
            "Raises the blood glucose even higher",
            "Has no effect on glucose",
          ],
          correct: 0,
          explain: "Insulin tells the liver and muscles to take glucose out of the blood and store it as glycogen, which lowers the blood glucose back toward normal.",
          ask: "Insulin lowers blood glucose. How does the liver help store the extra sugar?",
          hints: [
            "The liver converts glucose into a storage form.",
            "That store is called glycogen.",
            "Insulin makes the liver store glucose as glycogen.",
          ],
        },
        {
          kind: "match",
          prompt: "Match each response to what it controls:",
          pairs: [
            { left: "Releasing insulin", right: "Lowers blood glucose" },
            { left: "Sweating", right: "Cools the body when it is too hot" },
            { left: "Shivering", right: "Generates heat when the body is too cold" },
          ],
          explain: "Insulin manages blood glucose. Sweating cools the body as water evaporates, while shivering releases heat from muscle movement to warm it up.",
          ask: "Which response helps cool you down when you are too hot?",
          hints: [
            "Think about what your skin does on a hot day.",
            "Evaporating water carries heat away.",
            "Sweating cools the body.",
          ],
        },
        {
          kind: "insight",
          body: "Homeostasis works like a thermostat for the whole body: sense the drift, push back the other way, and settle near the set point.",
        },
      ],
    },
    {
      key: "bio-plant-transport-1",
      title: "Xylem, phloem and transpiration",
      topic: "t10-nutrition-and-transport-in-plants",
      minutes: 5,
      talkPrompt: "Quiz me on transport in plants, one at a time.",
      steps: [
        {
          kind: "concept",
          heading: "Two transport tissues",
          body: "Plants move substances through two tissues. Xylem carries water and dissolved minerals upward from the roots. Phloem carries sugars made in the leaves to wherever they are needed. Transpiration is the loss of water vapour from the leaves, which helps pull water up.",
        },
        {
          kind: "match",
          prompt: "Match each structure to its job:",
          pairs: [
            { left: "Xylem", right: "Carries water and minerals up from the roots" },
            { left: "Phloem", right: "Carries sugars made in the leaves" },
            { left: "Transpiration", right: "Loss of water vapour from the leaves" },
            { left: "Stomata", right: "Pores where water vapour and gases leave the leaf" },
          ],
          explain: "Xylem moves water upward and phloem moves sugars in both directions. Transpiration is water loss from the leaf, and stomata are the tiny pores through which that water vapour escapes.",
          ask: "Which tissue carries the sugars made during photosynthesis?",
          hints: [
            "One tissue carries water, the other carries food.",
            "The sugar carrier is not the xylem.",
            "Phloem carries the sugars.",
          ],
        },
        {
          kind: "choice",
          question: "The rate of transpiration increases most when the air is:",
          options: [
            "Hot, dry and windy",
            "Cold and still",
            "Humid and dark",
            "Cool and damp",
          ],
          correct: 0,
          explain: "Heat gives water molecules more energy to evaporate, dry air holds more water vapour, and wind carries the vapour away, so all three raise the transpiration rate.",
          ask: "Do hot, dry, windy conditions speed transpiration up or slow it down?",
          hints: [
            "Warmth and moving air both encourage evaporation.",
            "Dry air can take up more water vapour.",
            "Hot, dry and windy conditions speed it up.",
          ],
        },
        {
          kind: "insight",
          body: "Water rides a one way lift in the xylem, pulled upward by transpiration escaping through the leaves, while phloem shuttles sugar wherever the plant needs it.",
        },
      ],
    },
    {
      key: "bio-molecular-genetics-1",
      title: "DNA, genes and proteins",
      topic: "t12-molecular-genetics",
      minutes: 5,
      talkPrompt: "Quiz me on DNA, genes and proteins, one at a time.",
      steps: [
        {
          kind: "concept",
          heading: "From code to protein",
          body: "DNA is a molecule that stores instructions as a sequence of four bases. A gene is a section of DNA that codes for one protein. The base sequence is copied and read so that the correct protein is built, and proteins do most of the work in a cell.",
        },
        {
          kind: "order",
          prompt: "Order the flow of genetic information:",
          items: ["DNA", "mRNA", "Protein"],
          explain: "The DNA code is first copied into messenger RNA, and that message is then read to join amino acids into a protein.",
          ask: "What is made from the messenger molecule at the end of this flow?",
          hints: [
            "The information starts stored in the DNA.",
            "A messenger molecule carries the code out.",
            "The order runs DNA, then messenger RNA, then protein.",
          ],
        },
        {
          kind: "tiles",
          prompt: "Build the complementary DNA strand for the bases A T G C:",
          tiles: ["T", "A", "C", "G", "U"],
          answer: ["T", "A", "C", "G"],
          explain: "In DNA, A pairs with T and G pairs with C. So the strand facing A T G C reads T A C G. The base U belongs to RNA, not DNA, so it is a distractor.",
          ask: "Which base always pairs with A in DNA?",
          hints: [
            "The bases pair up in fixed couples.",
            "A goes with T, and G goes with C.",
            "The complement of A T G C is T A C G.",
          ],
        },
        {
          kind: "insight",
          body: "A gene is a recipe written in four letters: read the base sequence and you read the instructions for one protein.",
        },
      ],
    },
    {
      key: "bio-reproduction-1",
      title: "Human reproduction basics",
      topic: "t13-reproduction",
      minutes: 4,
      talkPrompt: "Quiz me on the basics of human reproduction, one at a time.",
      steps: [
        {
          kind: "concept",
          heading: "Gametes and fertilisation",
          body: "Reproduction begins with special sex cells called gametes. The female gamete is the egg cell and the male gamete is the sperm cell. Fertilisation is when a sperm nucleus and an egg nucleus join to form a single cell that can grow into a new individual.",
        },
        {
          kind: "match",
          prompt: "Match each organ to its function:",
          pairs: [
            { left: "Ovary", right: "Produces egg cells" },
            { left: "Testis", right: "Produces sperm cells" },
            { left: "Oviduct", right: "Where fertilisation usually takes place" },
            { left: "Uterus", right: "Where the developing embryo grows" },
          ],
          explain: "The ovary makes eggs and the testis makes sperm. Fertilisation usually happens in the oviduct, and the resulting embryo then develops in the uterus.",
          ask: "In which structure does fertilisation usually take place?",
          hints: [
            "It is the tube that the egg travels along after release.",
            "It sits between the ovary and the uterus.",
            "Fertilisation usually happens in the oviduct.",
          ],
        },
        {
          kind: "choice",
          question: "Fertilisation is best described as the:",
          options: [
            "Fusion of a sperm nucleus and an egg nucleus",
            "Growth of an embryo in the uterus",
            "Release of an egg from the ovary",
            "Formation of a gamete",
          ],
          correct: 0,
          explain: "Fertilisation is the moment the nucleus of a sperm joins with the nucleus of an egg, combining their genetic material into one new cell.",
          ask: "Fertilisation joins which two things together?",
          hints: [
            "It brings together the two gametes.",
            "The genetic material of both cells is combined.",
            "It is the fusion of a sperm nucleus and an egg nucleus.",
          ],
        },
        {
          kind: "insight",
          body: "Fertilisation is a single defining moment: two gametes fuse into one cell that carries genetic material from both parents.",
        },
      ],
    },
  ],
};
