import type { PlaygroundLesson } from "@/lib/playground-lessons";

// Project Playground Round 3 (Coddy-authored): one interactive lesson per
// O-Level Maths topic. E-Math 18, A-Math 10.

export const PLAYGROUND_MATHS: Record<"e-math" | "a-math", PlaygroundLesson[]> = {
  "e-math": [
    {
      key: "emath-numbers-1",
      title: "Indices and standard form",
      minutes: 5,
      topic: "n1-numbers-indices-and-standard-form",
      steps: [
        {
          kind: "concept",
          heading: "Powers and big numbers",
          body: "Indices are a short way to write repeated multiplication, so x^2 means x times x. When you multiply powers of the same base you add the indices: a^m times a^n = a^{m+n}. Standard form writes a number as A x 10^n, where A is at least 1 and less than 10, which keeps very large or very small numbers tidy.",
        },
        {
          kind: "tiles",
          prompt: "Build the index law for multiplying powers of the same base.",
          tiles: ["a^m", "×", "a^n", "=", "a^{m+n}", "a^{m-n}"],
          answer: ["a^m", "×", "a^n", "=", "a^{m+n}"],
          ask: "Let us build the multiplication law for indices. When the base is the same, you add the powers. Lay out the tiles.",
          hints: [
            "The left side is a to the m times a to the n.",
            "When you multiply, you add the indices, not subtract them.",
            "It reads a to the m, times a to the n, equals a to the m plus n.",
          ],
          explain: "The law is a to the m times a to the n equals a to the m plus n. You add the indices when the base is the same.",
        },
        {
          kind: "slider",
          prompt: "Write 36000 in standard form as 3.6 x 10^n. Slide to the value of n.",
          min: 0,
          max: 8,
          step: 1,
          unit: "",
          start: 6,
          targetMin: 4,
          targetMax: 4,
          ask: "Move the decimal point until the front number is three point six. Count how many places you moved, then slide to n.",
          hints: [
            "Standard form needs the front number between one and ten.",
            "From 36000 to three point six the point moves four places left.",
            "So n is four, because three point six times ten to the power four is 36000.",
          ],
          explain: "Moving the decimal point four places gives three point six times ten to the power four, which is 36000, so n is four.",
        },
        {
          kind: "insight",
          body: "Multiply powers, add the indices. In standard form the front number sits between 1 and 10 and the power counts the places.",
        },
      ],
      talkPrompt: "Quiz me on indices and standard form, one at a time.",
    },
    {
      key: "emath-ratio-1",
      title: "Ratio and proportion",
      minutes: 5,
      topic: "n2-ratio-proportion-and-map-scales",
      steps: [
        {
          kind: "concept",
          heading: "Sharing in parts",
          body: "A ratio compares quantities in parts. To share an amount in a given ratio, you add the parts to find the total number of parts, work out the value of one part, then multiply for each share. Map scales are ratios too, so a scale of 1 to 50000 means 1 cm on the map is 50000 cm on the ground.",
        },
        {
          kind: "order",
          prompt: "Order the steps to share an amount in a given ratio.",
          items: [
            "Add the ratio parts to get the total number of parts",
            "Divide the amount by the total number of parts",
            "Multiply by the number of parts in each share",
          ],
          ask: "Think about what you need before you can value one part. Put the sharing steps in order.",
          hints: [
            "You cannot find one part until you know how many parts there are in total.",
            "Find the total parts, then one part, then each share.",
            "Add the parts, divide the amount, then multiply for each share.",
          ],
          explain: "First add the parts for the total, divide the amount by that total to get one part, then multiply by the parts in each share.",
        },
        {
          kind: "slider",
          prompt: "Share 60 dollars in the ratio 2 to 3. Slide to the larger share.",
          min: 0,
          max: 60,
          step: 1,
          unit: " dollars",
          start: 20,
          targetMin: 36,
          targetMax: 36,
          ask: "There are two plus three parts in total. Find one part, then take the bigger share of three parts. Slide to it.",
          hints: [
            "Two plus three is five parts in total.",
            "Sixty divided by five is twelve for one part.",
            "The larger share is three parts, so three times twelve is thirty six.",
          ],
          explain: "The total is five parts, so one part is sixty divided by five, which is twelve. The larger share is three parts, so three times twelve is thirty six dollars.",
        },
        {
          kind: "insight",
          body: "Add the parts, value one part, then scale up. A map scale is just a ratio of map length to real length.",
        },
      ],
      talkPrompt: "Quiz me on ratio and proportion, one at a time.",
    },
    {
      key: "emath-percentage-1",
      title: "Percentage change",
      minutes: 5,
      topic: "n3-percentage",
      steps: [
        {
          kind: "concept",
          heading: "Parts per hundred",
          body: "A percentage is a fraction out of one hundred. To increase a quantity by a percentage, you find that percentage of it and add it on, or multiply by a factor such as 1.15 for a fifteen percent rise. Percentage change is the change divided by the original amount, times one hundred.",
        },
        {
          kind: "tiles",
          prompt: "Build the formula for percentage change.",
          tiles: ["change", "÷", "original", "×", "100", "+"],
          answer: ["change", "÷", "original", "×", "100"],
          ask: "Let us build percentage change. It is the change compared with the original, turned into a percentage. Lay out the tiles.",
          hints: [
            "Start with the change divided by the original.",
            "Then multiply by one hundred to make it a percentage.",
            "It reads change, divided by original, times one hundred.",
          ],
          explain: "Percentage change is the change divided by the original, times one hundred. Always compare with the original amount, not the new one.",
        },
        {
          kind: "slider",
          prompt: "Increase 80 by 15 percent. Slide to the new amount.",
          min: 0,
          max: 120,
          step: 1,
          unit: "",
          start: 60,
          targetMin: 91,
          targetMax: 93,
          ask: "Find fifteen percent of eighty, then add it on. Or multiply eighty by one point one five. Slide to the answer.",
          hints: [
            "Fifteen percent of eighty is twelve.",
            "Add the twelve onto the eighty.",
            "Eighty plus twelve is ninety two.",
          ],
          explain: "Fifteen percent of eighty is twelve, and eighty plus twelve is ninety two. The same as eighty times one point one five.",
        },
        {
          kind: "insight",
          body: "For a rise, multiply by one point something. Percentage change always divides by the original amount.",
        },
      ],
      talkPrompt: "Quiz me on percentages, one at a time.",
    },
    {
      key: "emath-rate-speed-1",
      title: "Speed and financial maths",
      minutes: 5,
      topic: "n4-rate-speed-and-financial-maths",
      steps: [
        {
          kind: "concept",
          heading: "Comparing per unit",
          body: "A rate compares one quantity against another, such as cost per item or distance per hour. Average speed is the distance travelled divided by the time taken, so speed = distance ÷ time. The same idea drives money problems, where interest is a rate charged or earned per year.",
        },
        {
          kind: "tiles",
          prompt: "Build the formula for average speed.",
          tiles: ["speed", "=", "distance", "time", "÷", "×"],
          answer: ["speed", "=", "distance", "÷", "time"],
          ask: "Let us build the speed formula. Speed is distance shared over the time taken. Lay out the tiles.",
          hints: [
            "Start with speed equals.",
            "Distance goes on top, so it comes before the divide sign.",
            "It reads speed equals distance divided by time.",
          ],
          explain: "Average speed equals distance divided by time. Distance on top, time underneath.",
        },
        {
          kind: "slider",
          prompt: "A car travels 150 km in 2 hours. Slide to its average speed in km per hour.",
          min: 0,
          max: 120,
          step: 1,
          unit: " km/h",
          start: 40,
          targetMin: 74,
          targetMax: 76,
          ask: "Use speed equals distance divided by time. One hundred fifty kilometres over two hours. Slide to the speed.",
          hints: [
            "Divide the distance by the time.",
            "That is one hundred fifty divided by two.",
            "One hundred fifty divided by two is seventy five.",
          ],
          explain: "Speed is distance divided by time, which is one hundred fifty divided by two, giving seventy five kilometres per hour.",
        },
        {
          kind: "insight",
          body: "Speed is distance divided by time. Every rate is one quantity measured against one unit of another.",
        },
      ],
      talkPrompt: "Quiz me on speed and rates, one at a time.",
    },
    {
      key: "emath-algebra-1",
      title: "Expanding and factorising",
      minutes: 5,
      topic: "n5-algebraic-manipulation-and-formulae",
      steps: [
        {
          kind: "concept",
          heading: "Two directions of the same skill",
          body: "Expanding removes brackets by multiplying every term, so (x+3)(x+2) becomes x^2 + 5x + 6. Factorising is the reverse, writing an expression as a product of brackets. Being fluent both ways lets you simplify expressions and solve equations.",
        },
        {
          kind: "tiles",
          prompt: "Expand (x+3)(x+2). Build the result in order.",
          tiles: ["x^2", "+", "5x", "6x", "+", "6"],
          answer: ["x^2", "+", "5x", "+", "6"],
          ask: "Multiply each term in the first bracket by each term in the second, then collect. Build the expansion.",
          hints: [
            "The first terms give x squared, and the last terms give six.",
            "The middle comes from three x plus two x, which is five x.",
            "It reads x squared plus five x plus six.",
          ],
          explain: "Expanding gives x squared plus two x plus three x plus six, and two x plus three x is five x, so the result is x squared plus five x plus six.",
        },
        {
          kind: "choice",
          question: "Factorise x^2 + 5x + 6.",
          options: ["(x+2)(x+3)", "(x+1)(x+6)", "(x+2)(x+4)", "(x-2)(x-3)"],
          correct: 0,
          ask: "You need two numbers that multiply to six and add to five. Which factorisation is correct? Pick one.",
          hints: [
            "Look for two numbers with product six and sum five.",
            "Two and three multiply to six and add to five.",
          ],
          explain: "Two and three multiply to six and add to five, so x squared plus five x plus six factorises to open bracket x plus two, close, open bracket x plus three.",
        },
        {
          kind: "insight",
          body: "Expanding multiplies out, factorising puts back into brackets. For a quadratic, find numbers that multiply to the last term and add to the middle.",
        },
      ],
      talkPrompt: "Quiz me on expanding and factorising, one at a time.",
    },
    {
      key: "emath-functions-1",
      title: "Linear functions and graphs",
      minutes: 5,
      topic: "n6-functions-and-graphs",
      steps: [
        {
          kind: "concept",
          heading: "The straight line rule",
          body: "A linear function has the form y = mx + c. Here m is the gradient, telling you how steep the line is, and c is the y intercept, the value of y where the line crosses the y axis. For y = 2x + 3, the gradient is 2 and the line crosses the y axis at 3.",
        },
        {
          kind: "plot",
          prompt: "For the line y = 2x + 3, plot the point where it crosses the y axis.",
          xLabel: "x",
          yLabel: "y",
          xMax: 6,
          yMax: 8,
          targetX: 0,
          targetY: 3,
          ask: "The line crosses the y axis when x is zero. Work out y there, then plot the point.",
          hints: [
            "Set x to zero in y equals two x plus three.",
            "Two times zero is zero, so y is three.",
            "Plot the point where x is zero and y is three.",
          ],
          explain: "When x is zero, y equals two times zero plus three, which is three. So the line crosses the y axis at the point zero, three.",
        },
        {
          kind: "choice",
          question: "What is the gradient of the line y = 2x + 3?",
          options: ["2", "3", "5", "1 over 2"],
          correct: 0,
          ask: "The gradient is the number multiplying x. What is it here? Pick one.",
          hints: [
            "Compare with y equals m x plus c.",
            "The gradient m is the coefficient of x.",
          ],
          explain: "In y equals m x plus c the gradient is m, the number multiplying x. Here that is two.",
        },
        {
          kind: "insight",
          body: "In y equals m x plus c, m is the steepness and c is where the line meets the y axis.",
        },
      ],
      talkPrompt: "Quiz me on linear functions and graphs, one at a time.",
    },
    {
      key: "emath-equations-1",
      title: "Solving linear equations",
      minutes: 5,
      topic: "n7-equations-and-inequalities",
      steps: [
        {
          kind: "concept",
          heading: "Keep the balance",
          body: "An equation stays true if you do the same thing to both sides. To solve 3x + 4 = 19, you undo the operations in reverse: first remove the plus 4, then undo the times 3. Inequalities work the same way, except the direction flips if you multiply or divide by a negative number.",
        },
        {
          kind: "order",
          prompt: "Order the steps to solve 3x + 4 = 19.",
          items: [
            "Subtract 4 from both sides to get 3x = 15",
            "Divide both sides by 3",
            "x = 5",
          ],
          ask: "Undo the operations in reverse order. What do you clear first, the plus four or the times three? Put the steps in order.",
          hints: [
            "Deal with the added four before the multiplication.",
            "After subtracting four you get three x equals fifteen.",
            "Subtract four, then divide by three, to reach x equals five.",
          ],
          explain: "Subtract four to get three x equals fifteen, then divide by three, giving x equals five.",
        },
        {
          kind: "slider",
          prompt: "Solve 3x + 4 = 19. Slide to the value of x.",
          min: 0,
          max: 10,
          step: 1,
          unit: "",
          start: 2,
          targetMin: 5,
          targetMax: 5,
          ask: "You found three x equals fifteen. Now divide by three and slide to x.",
          hints: [
            "Three x equals nineteen minus four, which is fifteen.",
            "Divide fifteen by three.",
            "Fifteen divided by three is five.",
          ],
          explain: "Three x equals fifteen, so x equals fifteen divided by three, which is five. Check: three times five plus four is nineteen.",
        },
        {
          kind: "insight",
          body: "Undo operations in reverse and keep both sides equal. For inequalities, flip the sign when you multiply or divide by a negative.",
        },
      ],
      talkPrompt: "Quiz me on solving equations, one at a time.",
    },
    {
      key: "emath-sets-1",
      title: "Set language and Venn diagrams",
      minutes: 5,
      topic: "n8-set-language-and-venn-diagrams",
      steps: [
        {
          kind: "concept",
          heading: "Grouping with sets",
          body: "A set is a collection of objects called elements. Two sets can be combined: the union holds everything in either set, and the intersection holds only what is in both. The complement of A holds everything not in A. Venn diagrams show these regions as overlapping circles.",
        },
        {
          kind: "match",
          prompt: "Match each set symbol to its meaning.",
          pairs: [
            { left: "A ∪ B", right: "Union, in A or B or both" },
            { left: "A ∩ B", right: "Intersection, in both A and B" },
            { left: "A'", right: "Complement, everything not in A" },
            { left: "n(A)", right: "The number of elements in A" },
          ],
          ask: "Match each symbol to what it means. The cup shape is union, the cap shape is intersection.",
          hints: [
            "The cup, that opens upward, is union, meaning either set.",
            "The cap, that opens downward, is intersection, meaning both sets.",
            "A with a dash is the complement, and n of A counts the elements.",
          ],
          explain: "A cup B is the union, in either set. A cap B is the intersection, in both. A dash is the complement, not in A. And n of A is the number of elements in A.",
        },
        {
          kind: "choice",
          question: "Which region does A ∩ B describe?",
          options: [
            "Elements in both A and B",
            "Elements in A or B or both",
            "Elements in neither set",
            "Elements only in A",
          ],
          correct: 0,
          ask: "The cap symbol points to the overlap of the two circles. What does it describe? Pick one.",
          hints: [
            "Intersection is about what the two sets share.",
            "It is the overlapping middle of the Venn diagram.",
          ],
          explain: "A cap B is the intersection, the elements that are in both A and B, shown by the overlap of the two circles.",
        },
        {
          kind: "insight",
          body: "Union is either set, intersection is both, complement is outside. Venn diagrams turn these into regions you can shade.",
        },
      ],
      talkPrompt: "Quiz me on set language and Venn diagrams, one at a time.",
    },
    {
      key: "emath-matrices-1",
      title: "Matrices and determinants",
      minutes: 5,
      topic: "n9-matrices",
      steps: [
        {
          kind: "concept",
          heading: "Numbers in a grid",
          body: "A matrix is a rectangular array of numbers arranged in rows and columns. Its order is written as rows by columns, so a matrix with 2 rows and 3 columns has order 2 by 3. For a 2 by 2 matrix with entries a, b on top and c, d below, the determinant is ad minus bc.",
        },
        {
          kind: "choice",
          question: "A matrix has 2 rows and 3 columns. What is its order?",
          options: ["2 by 3", "3 by 2", "6", "2 by 2"],
          correct: 0,
          ask: "Order is always rows first, then columns. What is the order here? Pick one.",
          hints: [
            "Count the rows, then the columns.",
            "Rows come first, so two rows and three columns.",
          ],
          explain: "Order is rows by columns, so 2 rows and 3 columns gives an order of 2 by 3.",
        },
        {
          kind: "slider",
          prompt: "Find the determinant of the 2 by 2 matrix with top row 3, 1 and bottom row 2, 4. Slide to it.",
          min: 0,
          max: 20,
          step: 1,
          unit: "",
          start: 5,
          targetMin: 10,
          targetMax: 10,
          ask: "The determinant is a d minus b c. Multiply the diagonal pairs, then subtract. Slide to the value.",
          hints: [
            "Multiply the leading diagonal: three times four.",
            "Subtract the other diagonal: one times two.",
            "Twelve minus two is ten.",
          ],
          explain: "The determinant is a d minus b c, which is three times four minus one times two, so twelve minus two equals ten.",
        },
        {
          kind: "insight",
          body: "Order is rows by columns. For a two by two matrix, the determinant is the leading diagonal product minus the other diagonal product.",
        },
      ],
      talkPrompt: "Quiz me on matrices, one at a time.",
    },
    {
      key: "emath-angles-1",
      title: "Angles and polygons",
      minutes: 5,
      topic: "g1-angles-triangles-and-polygons",
      steps: [
        {
          kind: "concept",
          heading: "Angle rules that always hold",
          body: "Angles on a straight line add to 180 degrees, and the angles in a triangle also add to 180 degrees. For any polygon, the interior angles add to (n minus 2) times 180 degrees, where n is the number of sides. The exterior angles of any polygon always add to 360 degrees.",
        },
        {
          kind: "slider",
          prompt: "Find the sum of the interior angles of a pentagon, which has 5 sides. Slide to the total in degrees.",
          min: 0,
          max: 900,
          step: 10,
          unit: " degrees",
          start: 300,
          targetMin: 535,
          targetMax: 545,
          ask: "Use n minus two, times one hundred eighty, with n as five. Work it out, then slide to the total.",
          hints: [
            "A pentagon has five sides, so n minus two is three.",
            "Multiply three by one hundred eighty.",
            "Three times one hundred eighty is five hundred forty.",
          ],
          explain: "The sum is n minus two, times one hundred eighty. With five sides that is three times one hundred eighty, which is five hundred forty degrees.",
        },
        {
          kind: "choice",
          question: "What do the exterior angles of any polygon add up to?",
          options: ["360 degrees", "180 degrees", "540 degrees", "It depends on the number of sides"],
          correct: 0,
          ask: "This total is the same for every polygon, no matter how many sides. What is it? Pick one.",
          hints: [
            "Imagine walking around the shape and turning at each corner.",
            "One full turn brings you back facing the start.",
          ],
          explain: "The exterior angles of any polygon add to 360 degrees, because going around the shape is one full turn.",
        },
        {
          kind: "insight",
          body: "Interior angles sum to n minus two, times 180. Exterior angles always sum to 360, whatever the shape.",
        },
      ],
      talkPrompt: "Quiz me on angles and polygons, one at a time.",
    },
    {
      key: "emath-congruence-1",
      title: "Congruence and similarity",
      minutes: 5,
      topic: "g2-congruence-and-similarity",
      steps: [
        {
          kind: "concept",
          heading: "Same shape, same or scaled size",
          body: "Two figures are congruent if they are exactly the same shape and size. They are similar if they are the same shape but one is a scaled version of the other. In similar figures, matching sides are in the same ratio, called the scale factor, and matching angles stay equal.",
        },
        {
          kind: "match",
          prompt: "Match each congruence test to what it needs.",
          pairs: [
            { left: "SSS", right: "Three pairs of sides equal" },
            { left: "SAS", right: "Two sides and the angle between them" },
            { left: "ASA", right: "Two angles and the side between them" },
            { left: "RHS", right: "Right angle, hypotenuse, and one side" },
          ],
          ask: "Match each shorthand to the parts it checks. The letters stand for sides and angles.",
          hints: [
            "S is a side and A is an angle.",
            "SAS has the angle between the two sides, ASA has the side between the two angles.",
            "SSS three sides, SAS side angle side, ASA angle side angle, RHS right angle hypotenuse side.",
          ],
          explain: "SSS needs three equal sides, SAS two sides and the included angle, ASA two angles and the included side, and RHS a right angle with the hypotenuse and one side.",
        },
        {
          kind: "slider",
          prompt: "Two triangles are similar. The smaller has sides 3, 4, 5. The larger has sides 6, 8, and one unknown. Slide to the unknown side.",
          min: 0,
          max: 20,
          step: 1,
          unit: "",
          start: 4,
          targetMin: 10,
          targetMax: 10,
          ask: "Find the scale factor from a matching pair, then apply it to the last side. Slide to the answer.",
          hints: [
            "Six divided by three is a scale factor of two.",
            "Multiply the last small side, which is five, by two.",
            "Five times two is ten.",
          ],
          explain: "The scale factor is six divided by three, which is two. The last side is five times two, which is ten.",
        },
        {
          kind: "insight",
          body: "Congruent means identical, similar means scaled. In similar figures, matching sides share one scale factor.",
        },
      ],
      talkPrompt: "Quiz me on congruence and similarity, one at a time.",
    },
    {
      key: "emath-circles-1",
      title: "Properties of circles",
      minutes: 5,
      topic: "g3-properties-of-circles",
      steps: [
        {
          kind: "concept",
          heading: "Angles inside a circle",
          body: "Circle theorems link angles and lines. The angle in a semicircle is a right angle. The angle at the centre is twice the angle at the circumference standing on the same arc. A tangent to a circle meets the radius at the point of contact at a right angle.",
        },
        {
          kind: "slider",
          prompt: "An angle at the circumference is 35 degrees. Slide to the angle at the centre standing on the same arc.",
          min: 0,
          max: 180,
          step: 5,
          unit: " degrees",
          start: 120,
          targetMin: 65,
          targetMax: 75,
          ask: "The angle at the centre is twice the angle at the circumference on the same arc. Double it, then slide.",
          hints: [
            "The centre angle is two times the circumference angle.",
            "Double thirty five.",
            "Two times thirty five is seventy.",
          ],
          explain: "The angle at the centre is twice the angle at the circumference, so two times thirty five is seventy degrees.",
        },
        {
          kind: "choice",
          question: "A triangle is drawn inside a circle with one side as the diameter. What is the angle opposite the diameter?",
          options: ["90 degrees", "45 degrees", "60 degrees", "180 degrees"],
          correct: 0,
          ask: "This is the angle in a semicircle. What must it be? Pick one.",
          hints: [
            "The diameter splits the circle into two semicircles.",
            "The angle in a semicircle is always a right angle.",
          ],
          explain: "The angle in a semicircle is 90 degrees, so the angle opposite the diameter is a right angle.",
        },
        {
          kind: "insight",
          body: "Angle in a semicircle is 90 degrees, and the centre angle is double the one at the circumference on the same arc.",
        },
      ],
      talkPrompt: "Quiz me on circle properties, one at a time.",
    },
    {
      key: "emath-trig-1",
      title: "Pythagoras and trigonometry",
      minutes: 5,
      topic: "g4-pythagoras-trigonometry-and-bearings",
      steps: [
        {
          kind: "concept",
          heading: "Sides and angles of right triangles",
          body: "In a right angled triangle, Pythagoras theorem links the sides: a^2 + b^2 = c^2, where c is the hypotenuse. To connect sides with angles, use sine, cosine and tangent, remembered as SOHCAHTOA. Bearings measure direction clockwise from north as three figures, such as 060 degrees.",
        },
        {
          kind: "tiles",
          prompt: "Build Pythagoras theorem for a right triangle with hypotenuse c.",
          tiles: ["a^2", "+", "b^2", "=", "c^2", "-"],
          answer: ["a^2", "+", "b^2", "=", "c^2"],
          ask: "Let us build Pythagoras theorem. The two shorter sides squared add to the hypotenuse squared. Lay out the tiles.",
          hints: [
            "Add the squares of the two shorter sides.",
            "That total equals the hypotenuse squared.",
            "It reads a squared plus b squared equals c squared.",
          ],
          explain: "Pythagoras theorem is a squared plus b squared equals c squared, where c is the hypotenuse, the side opposite the right angle.",
        },
        {
          kind: "slider",
          prompt: "A right triangle has shorter sides 3 and 4. Slide to the length of the hypotenuse.",
          min: 0,
          max: 10,
          step: 1,
          unit: "",
          start: 8,
          targetMin: 5,
          targetMax: 5,
          ask: "Square the two sides, add them, then take the square root. Slide to the hypotenuse.",
          hints: [
            "Three squared is nine and four squared is sixteen.",
            "Nine plus sixteen is twenty five.",
            "The square root of twenty five is five.",
          ],
          explain: "Three squared plus four squared is nine plus sixteen, which is twenty five, and the square root of twenty five is five.",
        },
        {
          kind: "insight",
          body: "Pythagoras links the three sides, SOHCAHTOA links sides with angles, and bearings are three figure directions from north.",
        },
      ],
      talkPrompt: "Quiz me on Pythagoras and trigonometry, one at a time.",
    },
    {
      key: "emath-mensuration-1",
      title: "Mensuration: area and volume",
      minutes: 5,
      topic: "g5-mensuration",
      steps: [
        {
          kind: "concept",
          heading: "Measuring space",
          body: "Mensuration is about lengths, areas and volumes. The area of a circle is A = pi times r^2, and its circumference is 2 pi r. Volumes build on areas, so a cylinder is the base circle area times its height. Keeping units consistent, such as cm^2 for area and cm^3 for volume, avoids errors.",
        },
        {
          kind: "tiles",
          prompt: "Build the formula for the area of a circle.",
          tiles: ["A", "=", "pi", "r^2", "r", "×"],
          answer: ["A", "=", "pi", "r^2"],
          ask: "Let us build the circle area formula. It is pi times the radius squared. Lay out the tiles.",
          hints: [
            "Start with A equals pi.",
            "Then multiply by the radius squared, not just the radius.",
            "It reads A equals pi r squared.",
          ],
          explain: "The area of a circle is A equals pi times r squared, where r is the radius.",
        },
        {
          kind: "slider",
          prompt: "Find the area of a circle with radius 7, using pi as 22 over 7. Slide to the area.",
          min: 0,
          max: 200,
          step: 1,
          unit: " cm^2",
          start: 100,
          targetMin: 152,
          targetMax: 156,
          ask: "Use pi r squared with pi as twenty two over seven and radius seven. Slide to the area.",
          hints: [
            "Radius squared is seven times seven, which is forty nine.",
            "Twenty two over seven times forty nine cancels the seven.",
            "Twenty two times seven is one hundred fifty four.",
          ],
          explain: "The area is pi r squared, which is twenty two over seven times forty nine. The seven cancels, leaving twenty two times seven, which is one hundred fifty four square centimetres.",
        },
        {
          kind: "insight",
          body: "Circle area is pi r squared. Volumes are a base area times a length, and area uses square units while volume uses cubic units.",
        },
      ],
      talkPrompt: "Quiz me on mensuration, one at a time.",
    },
    {
      key: "emath-coordgeo-1",
      title: "Coordinate geometry",
      minutes: 5,
      topic: "g6-coordinate-geometry",
      steps: [
        {
          kind: "concept",
          heading: "Geometry on a grid",
          body: "Coordinate geometry describes points and lines using numbers. The gradient of a line joining two points is the change in y divided by the change in x. The midpoint of a segment is the average of the x values and the average of the y values. These let you measure slope and centre without a ruler.",
        },
        {
          kind: "plot",
          prompt: "Plot the midpoint of the segment joining (0, 0) and (6, 4).",
          xLabel: "x",
          yLabel: "y",
          xMax: 6,
          yMax: 6,
          targetX: 3,
          targetY: 2,
          ask: "Average the x values and average the y values, then plot that middle point.",
          hints: [
            "The x of the midpoint is zero plus six, over two.",
            "The y of the midpoint is zero plus four, over two.",
            "That gives x is three and y is two.",
          ],
          explain: "The midpoint averages the coordinates: x is zero plus six over two, which is three, and y is zero plus four over two, which is two. So the midpoint is three, two.",
        },
        {
          kind: "slider",
          prompt: "A line passes through (0, 0) and (2, 6). Slide to its gradient.",
          min: 0,
          max: 10,
          step: 1,
          unit: "",
          start: 6,
          targetMin: 3,
          targetMax: 3,
          ask: "Gradient is the change in y divided by the change in x. Work it out, then slide.",
          hints: [
            "The y changes by six and the x changes by two.",
            "Divide six by two.",
            "Six divided by two is three.",
          ],
          explain: "Gradient is change in y over change in x, which is six over two, giving three.",
        },
        {
          kind: "insight",
          body: "Gradient is rise over run, and the midpoint is the average of the coordinates. Geometry becomes arithmetic on a grid.",
        },
      ],
      talkPrompt: "Quiz me on coordinate geometry, one at a time.",
    },
    {
      key: "emath-vectors-1",
      title: "Vectors in two dimensions",
      minutes: 5,
      topic: "g7-vectors-in-two-dimensions",
      steps: [
        {
          kind: "concept",
          heading: "Size and direction",
          body: "A vector has both size and direction, often written as a column with a top number for the x step and a bottom number for the y step. You add vectors by adding matching components. The magnitude, or length, of a vector with components a and b is the square root of a^2 + b^2.",
        },
        {
          kind: "choice",
          question: "Add the vectors with columns (2, 1) and (3, 4). What is the result?",
          options: ["(5, 5)", "(6, 4)", "(5, 4)", "(1, 3)"],
          correct: 0,
          ask: "Add the top numbers together and the bottom numbers together. What is the result vector? Pick one.",
          hints: [
            "Add the x parts: two plus three.",
            "Add the y parts: one plus four.",
            "That gives five and five.",
          ],
          explain: "Add components: two plus three is five, and one plus four is five, so the result is the column five, five.",
        },
        {
          kind: "slider",
          prompt: "Find the magnitude of the vector with components 3 and 4. Slide to its length.",
          min: 0,
          max: 10,
          step: 1,
          unit: "",
          start: 8,
          targetMin: 5,
          targetMax: 5,
          ask: "Square each component, add them, then take the square root. Slide to the length.",
          hints: [
            "Three squared is nine and four squared is sixteen.",
            "Nine plus sixteen is twenty five.",
            "The square root of twenty five is five.",
          ],
          explain: "The magnitude is the square root of three squared plus four squared, which is the square root of twenty five, so it is five.",
        },
        {
          kind: "insight",
          body: "Add vectors component by component. The length comes from Pythagoras on the two components.",
        },
      ],
      talkPrompt: "Quiz me on vectors, one at a time.",
    },
    {
      key: "emath-statistics-1",
      title: "Averages and data",
      minutes: 5,
      topic: "s1-data-analysis-and-statistics",
      steps: [
        {
          kind: "concept",
          heading: "Summarising a data set",
          body: "Averages describe the middle of a data set. The mean is the total of the values divided by how many there are. The median is the middle value once the data is in order. The mode is the value that appears most often. Each tells a slightly different story about the data.",
        },
        {
          kind: "order",
          prompt: "Order the steps to find the median of a data set.",
          items: [
            "Arrange the values in order of size",
            "Find the middle position",
            "Read off the value at that position",
          ],
          ask: "The median depends on position, so something has to happen first. Put the steps in order.",
          hints: [
            "You cannot find the middle until the data is sorted.",
            "Sort first, then locate the middle position, then read the value.",
            "Arrange in order, find the middle position, read off the middle value.",
          ],
          explain: "First arrange the values in order, then find the middle position, then read off the value there. That value is the median.",
        },
        {
          kind: "slider",
          prompt: "Find the mean of 4, 6, 8, 10, 12. Slide to the mean.",
          min: 0,
          max: 20,
          step: 1,
          unit: "",
          start: 12,
          targetMin: 8,
          targetMax: 8,
          ask: "Add all the values, then divide by how many there are. Slide to the mean.",
          hints: [
            "The five values add to forty.",
            "There are five values, so divide forty by five.",
            "Forty divided by five is eight.",
          ],
          explain: "The values add to forty, and there are five of them, so the mean is forty divided by five, which is eight.",
        },
        {
          kind: "insight",
          body: "Mean is the total shared out, median is the middle of sorted data, mode is the most common value.",
        },
      ],
      talkPrompt: "Quiz me on averages and data, one at a time.",
    },
    {
      key: "emath-probability-1",
      title: "Probability basics",
      minutes: 5,
      topic: "s2-probability",
      steps: [
        {
          kind: "concept",
          heading: "How likely is it",
          body: "Probability measures how likely an event is, on a scale from 0 for impossible to 1 for certain. For equally likely outcomes, the probability is the number of favourable outcomes divided by the total number of outcomes. A fair six sided die has six equally likely outcomes.",
        },
        {
          kind: "tiles",
          prompt: "Build the formula for the probability of an event with equally likely outcomes.",
          tiles: ["probability", "=", "favourable", "total", "÷", "×"],
          answer: ["probability", "=", "favourable", "÷", "total"],
          ask: "Let us build the probability formula. It compares favourable outcomes with all outcomes. Lay out the tiles.",
          hints: [
            "Start with probability equals favourable.",
            "Divide by the total number of outcomes.",
            "It reads probability equals favourable divided by total.",
          ],
          explain: "Probability equals the number of favourable outcomes divided by the total number of outcomes.",
        },
        {
          kind: "slider",
          prompt: "A fair six sided die is rolled. Slide to the probability of getting an even number.",
          min: 0,
          max: 1,
          step: 0.05,
          unit: "",
          start: 0.8,
          targetMin: 0.45,
          targetMax: 0.55,
          ask: "Count the even numbers on a die, then divide by six. Slide to the probability.",
          hints: [
            "The even numbers are two, four and six, so three of them.",
            "Three favourable out of six total.",
            "Three divided by six is one half, which is zero point five.",
          ],
          explain: "There are three even numbers out of six, so the probability is three over six, which is one half, or zero point five.",
        },
        {
          kind: "insight",
          body: "Probability runs from 0 to 1 and equals favourable over total. Certain is 1, impossible is 0.",
        },
      ],
      talkPrompt: "Quiz me on probability, one at a time.",
    },
  ],
  "a-math": [
    {
      key: "amath-quadratics-1",
      title: "Quadratic functions",
      minutes: 6,
      topic: "quadratic-functions",
      steps: [
        {
          kind: "concept",
          heading: "The shape of a parabola",
          body: "A quadratic function has the form y = ax^2 + bx + c and its graph is a parabola. The discriminant, b^2 minus 4ac, tells you how many times the curve meets the x axis: two roots if it is positive, one if it is zero, and none if it is negative.",
        },
        {
          kind: "tiles",
          prompt: "Build the discriminant of a quadratic.",
          tiles: ["b^2", "-", "4ac", "=", "4bc", "+"],
          answer: ["b^2", "-", "4ac"],
          ask: "Let us build the discriminant. It is b squared take away four a c. Lay out the tiles.",
          hints: [
            "Start with b squared.",
            "Then subtract four a c.",
            "It reads b squared minus four a c.",
          ],
          explain: "The discriminant is b squared minus four a c. Its sign tells you the number of real roots.",
        },
        {
          kind: "slider",
          prompt: "Find the discriminant of x^2 - 5x + 6, where a = 1, b = -5, c = 6. Slide to its value.",
          min: 0,
          max: 20,
          step: 1,
          unit: "",
          start: 8,
          targetMin: 0,
          targetMax: 2,
          ask: "Work out b squared minus four a c using a as one, b as negative five, c as six. Slide to the value.",
          hints: [
            "b squared is negative five squared, which is twenty five.",
            "Four a c is four times one times six, which is twenty four.",
            "Twenty five minus twenty four is one.",
          ],
          explain: "b squared is twenty five and four a c is twenty four, so the discriminant is twenty five minus twenty four, which is one. Being positive, the curve has two roots.",
        },
        {
          kind: "insight",
          body: "The discriminant b squared minus four a c counts the roots: positive gives two, zero gives one, negative gives none.",
        },
      ],
      talkPrompt: "Quiz me on quadratic functions, one at a time.",
    },
    {
      key: "amath-equations-1",
      title: "Simultaneous equations",
      minutes: 5,
      topic: "equations-and-inequalities",
      steps: [
        {
          kind: "concept",
          heading: "Two equations, two unknowns",
          body: "Simultaneous equations are solved together to find values that satisfy both. In the elimination method, you combine the equations to cancel one unknown. For x + y = 10 and x minus y = 4, adding them removes y and lets you find x, then you substitute back to find y.",
        },
        {
          kind: "order",
          prompt: "Order the elimination steps for x + y = 10 and x - y = 4.",
          items: [
            "Add the two equations to remove y, giving 2x = 14",
            "Divide by 2 to find x = 7",
            "Substitute x back to find y = 3",
          ],
          ask: "Adding the equations cancels one letter. Which comes first, adding or substituting? Put the steps in order.",
          hints: [
            "Adding the equations makes the y terms cancel.",
            "Solve for x before you find y.",
            "Add to remove y, find x, then substitute for y.",
          ],
          explain: "Adding gives two x equals fourteen, so x is seven. Substituting into x plus y equals ten gives y equals three.",
        },
        {
          kind: "slider",
          prompt: "For x + y = 10 and x - y = 4, slide to the value of x.",
          min: 0,
          max: 12,
          step: 1,
          unit: "",
          start: 3,
          targetMin: 7,
          targetMax: 7,
          ask: "Add the two equations to get two x, then halve it. Slide to x.",
          hints: [
            "Adding gives two x equals ten plus four.",
            "Two x equals fourteen.",
            "x is fourteen divided by two, which is seven.",
          ],
          explain: "Adding the equations gives two x equals fourteen, so x equals seven. Then y equals three.",
        },
        {
          kind: "insight",
          body: "Combine the equations to cancel one unknown, solve for the other, then substitute back.",
        },
      ],
      talkPrompt: "Quiz me on simultaneous equations, one at a time.",
    },
    {
      key: "amath-surds-1",
      title: "Surds",
      minutes: 5,
      topic: "surds",
      steps: [
        {
          kind: "concept",
          heading: "Exact roots",
          body: "A surd is a root that cannot be simplified to a whole number, such as the square root of 2. You simplify a surd by pulling out square factors, so sqrt(50) becomes 5 times sqrt(2). To rationalise a fraction, you clear the surd from the denominator by multiplying top and bottom by it.",
        },
        {
          kind: "slider",
          prompt: "Simplify sqrt(50) into the form a times sqrt(2). Slide to the value of a.",
          min: 0,
          max: 10,
          step: 1,
          unit: "",
          start: 3,
          targetMin: 5,
          targetMax: 5,
          ask: "Find the largest square number that divides fifty, then take its root outside. Slide to a.",
          hints: [
            "Fifty is twenty five times two, and twenty five is a square.",
            "The square root of twenty five is five, and the two stays under the root.",
            "So a is five, giving five times the square root of two.",
          ],
          explain: "Fifty is twenty five times two, and the square root of twenty five is five, so sqrt of fifty is five times the square root of two. So a is five.",
        },
        {
          kind: "choice",
          question: "Rationalise the denominator of 1 over sqrt(2).",
          options: ["sqrt(2) over 2", "2 over sqrt(2)", "sqrt(2)", "1 over 2"],
          correct: 0,
          ask: "Multiply top and bottom by the square root of two. What do you get? Pick one.",
          hints: [
            "Multiplying the bottom by root two gives two.",
            "The top becomes root two.",
          ],
          explain: "Multiplying top and bottom by the square root of two gives the square root of two over two, since root two times root two is two.",
        },
        {
          kind: "insight",
          body: "Simplify surds by pulling out square factors, and rationalise by clearing the root from the denominator.",
        },
      ],
      talkPrompt: "Quiz me on surds, one at a time.",
    },
    {
      key: "amath-polynomials-1",
      title: "Polynomials and partial fractions",
      minutes: 6,
      topic: "polynomials-and-partial-fractions",
      steps: [
        {
          kind: "concept",
          heading: "Remainders and splitting fractions",
          body: "The remainder theorem says that dividing a polynomial f(x) by (x minus a) leaves a remainder of f(a). If that remainder is zero, then (x minus a) is a factor. Partial fractions reverse the adding of fractions, splitting one algebraic fraction into a sum of simpler ones.",
        },
        {
          kind: "slider",
          prompt: "For f(x) = x^2 + 2x + 3, find the remainder when it is divided by (x - 1). Slide to the remainder.",
          min: 0,
          max: 12,
          step: 1,
          unit: "",
          start: 3,
          targetMin: 6,
          targetMax: 6,
          ask: "By the remainder theorem, the remainder is f of one. Put one into the polynomial, then slide.",
          hints: [
            "Substitute x equals one into x squared plus two x plus three.",
            "That is one plus two plus three.",
            "One plus two plus three is six.",
          ],
          explain: "The remainder is f of one, which is one squared plus two times one plus three, so one plus two plus three, which is six.",
        },
        {
          kind: "order",
          prompt: "Order the steps to split a fraction into partial fractions.",
          items: [
            "Factorise the denominator",
            "Write it as a sum of fractions with unknown numerators",
            "Multiply through and compare coefficients",
            "Solve for the unknown numerators",
          ],
          ask: "Think about what you need before you can guess the form. Put the steps in order.",
          hints: [
            "You must know the factors of the denominator first.",
            "Set up the unknowns, then clear the fractions to solve them.",
            "Factorise, write the sum form, multiply through, then solve.",
          ],
          explain: "First factorise the denominator, write the sum with unknown numerators, multiply through to clear fractions, then compare coefficients to solve for the unknowns.",
        },
        {
          kind: "insight",
          body: "The remainder theorem gives f of a as the remainder. Partial fractions undo the adding of fractions.",
        },
      ],
      talkPrompt: "Quiz me on polynomials and partial fractions, one at a time.",
    },
    {
      key: "amath-binomial-1",
      title: "Binomial expansions",
      minutes: 5,
      topic: "binomial-expansions",
      steps: [
        {
          kind: "concept",
          heading: "Expanding powers of brackets",
          body: "The binomial theorem expands a bracket raised to a power. A small case is (a+b)^2 = a^2 + 2ab + b^2. For higher powers, the coefficients come from combinations, written as n choose r, which count how many ways terms combine. These are the numbers in Pascal's triangle.",
        },
        {
          kind: "tiles",
          prompt: "Expand (a+b)^2. Build the result in order.",
          tiles: ["a^2", "+", "2ab", "b^2", "+", "ab"],
          answer: ["a^2", "+", "2ab", "+", "b^2"],
          ask: "Square the bracket by multiplying it by itself, then collect. Build the expansion.",
          hints: [
            "The square and the last term give a squared and b squared.",
            "The middle is a b plus a b, which is two a b.",
            "It reads a squared plus two a b plus b squared.",
          ],
          explain: "Multiplying out gives a squared plus a b plus a b plus b squared, and the two middle terms make two a b, so a squared plus two a b plus b squared.",
        },
        {
          kind: "slider",
          prompt: "In the expansion of (1+x)^4, find the coefficient of x^2, which is 4 choose 2. Slide to it.",
          min: 0,
          max: 12,
          step: 1,
          unit: "",
          start: 3,
          targetMin: 6,
          targetMax: 6,
          ask: "Work out four choose two, the number of ways to pick two from four. Slide to the coefficient.",
          hints: [
            "Four choose two is four times three, over two times one.",
            "That is twelve over two.",
            "Twelve over two is six.",
          ],
          explain: "Four choose two is four times three divided by two times one, which is twelve over two, so six. The coefficient of x squared is six.",
        },
        {
          kind: "insight",
          body: "Squaring a bracket gives a squared plus two a b plus b squared. Higher powers use n choose r for the coefficients.",
        },
      ],
      talkPrompt: "Quiz me on binomial expansions, one at a time.",
    },
    {
      key: "amath-explog-1",
      title: "Exponentials and logarithms",
      minutes: 5,
      topic: "exponential-and-logarithmic-functions",
      steps: [
        {
          kind: "concept",
          heading: "Undoing powers",
          body: "A logarithm answers the question, what power gives this number. So log_2(8) asks two to what power is eight, and the answer is three. Logarithms turn products into sums, which is the law log(ab) = log a + log b. They are the inverse of exponential functions.",
        },
        {
          kind: "tiles",
          prompt: "Build the logarithm law for a product.",
          tiles: ["log(ab)", "=", "log a", "+", "log b", "×"],
          answer: ["log(ab)", "=", "log a", "+", "log b"],
          ask: "Let us build the product law for logarithms. The log of a product becomes a sum of logs. Lay out the tiles.",
          hints: [
            "Start with log of a b equals.",
            "A product inside becomes addition outside.",
            "It reads log of a b equals log a plus log b.",
          ],
          explain: "The law is log of a b equals log a plus log b. Logarithms turn multiplication into addition.",
        },
        {
          kind: "slider",
          prompt: "Evaluate log_2(8). Slide to its value.",
          min: 0,
          max: 8,
          step: 1,
          unit: "",
          start: 6,
          targetMin: 3,
          targetMax: 3,
          ask: "Ask yourself, two to what power gives eight. Slide to that power.",
          hints: [
            "Two times two times two is eight.",
            "That is three twos multiplied.",
            "So log base two of eight is three.",
          ],
          explain: "Two to the power three is eight, so log base two of eight is three.",
        },
        {
          kind: "insight",
          body: "A logarithm is the power you raise the base to. Logs turn products into sums and undo exponentials.",
        },
      ],
      talkPrompt: "Quiz me on exponentials and logarithms, one at a time.",
    },
    {
      key: "amath-coordgeo-1",
      title: "Circles and linear law",
      minutes: 5,
      topic: "coordinate-geometry-circles-and-linear-law",
      steps: [
        {
          kind: "concept",
          heading: "Circles and straightening curves",
          body: "A circle with centre (a, b) and radius r has the equation (x minus a)^2 + (y minus b)^2 = r^2. The linear law rewrites a non linear relationship as a straight line, Y = mX + c, by choosing new variables, so you can find constants from the gradient and intercept of a line of best fit.",
        },
        {
          kind: "slider",
          prompt: "A circle has equation x^2 + y^2 = 25. Slide to its radius.",
          min: 0,
          max: 10,
          step: 1,
          unit: "",
          start: 8,
          targetMin: 5,
          targetMax: 5,
          ask: "The right side is the radius squared. Take its square root, then slide to the radius.",
          hints: [
            "Compare with x squared plus y squared equals r squared.",
            "So r squared is twenty five.",
            "The square root of twenty five is five.",
          ],
          explain: "The equation matches x squared plus y squared equals r squared, so r squared is twenty five and the radius is the square root of twenty five, which is five.",
        },
        {
          kind: "choice",
          question: "What is the centre of the circle (x - 2)^2 + (y + 1)^2 = 9?",
          options: ["(2, -1)", "(-2, 1)", "(2, 1)", "(-2, -1)"],
          correct: 0,
          ask: "Read the centre from the brackets, remembering the signs are reversed. Which point is it? Pick one.",
          hints: [
            "The form is x minus a and y minus b, so the centre is a, b.",
            "x minus two gives a is two, and y plus one is y minus negative one, so b is negative one.",
          ],
          explain: "In the standard form the centre is a, b. Here x minus two gives a is two, and y plus one gives b is negative one, so the centre is two, negative one.",
        },
        {
          kind: "insight",
          body: "A circle equation hides its centre and radius in the brackets. Linear law turns a curve into a straight line to read off constants.",
        },
      ],
      talkPrompt: "Quiz me on circles and linear law, one at a time.",
    },
    {
      key: "amath-trig-1",
      title: "Trigonometric identities",
      minutes: 6,
      topic: "trigonometry-functions-identities-r-formula",
      steps: [
        {
          kind: "concept",
          heading: "Relationships that always hold",
          body: "Trigonometric identities are true for every angle. The key one is sin^2 x + cos^2 x = 1, which comes straight from Pythagoras on the unit circle. The R formula rewrites a sin x + b cos x as a single sine or cosine wave, which helps solve equations and find maximum values.",
        },
        {
          kind: "tiles",
          prompt: "Build the fundamental trigonometric identity.",
          tiles: ["sin^2 x", "+", "cos^2 x", "=", "1", "-"],
          answer: ["sin^2 x", "+", "cos^2 x", "=", "1"],
          ask: "Let us build the identity that links sine and cosine. Their squares add to one. Lay out the tiles.",
          hints: [
            "Add sine squared and cosine squared.",
            "The total is exactly one.",
            "It reads sine squared x plus cosine squared x equals one.",
          ],
          explain: "The identity is sine squared x plus cosine squared x equals one, true for every angle x.",
        },
        {
          kind: "slider",
          prompt: "If sin x = 0.6, use the identity to find cos^2 x. Slide to its value.",
          min: 0,
          max: 1,
          step: 0.01,
          unit: "",
          start: 0.3,
          targetMin: 0.63,
          targetMax: 0.65,
          ask: "Rearrange the identity to cosine squared equals one minus sine squared. Work it out, then slide.",
          hints: [
            "Sine squared is zero point six squared, which is zero point three six.",
            "Cosine squared is one minus zero point three six.",
            "One minus zero point three six is zero point six four.",
          ],
          explain: "Cosine squared x is one minus sine squared x, which is one minus zero point three six, giving zero point six four.",
        },
        {
          kind: "insight",
          body: "Sine squared plus cosine squared is always one. The R formula combines a sine and cosine into one wave.",
        },
      ],
      talkPrompt: "Quiz me on trigonometric identities, one at a time.",
    },
    {
      key: "amath-planegeo-1",
      title: "Plane geometry proofs",
      minutes: 5,
      topic: "plane-geometry-proofs",
      steps: [
        {
          kind: "concept",
          heading: "Building an argument",
          body: "A geometry proof is a chain of statements, each backed by a reason such as a known theorem. You start from what is given, apply circle and triangle properties step by step, and reach the required conclusion. Every step must be justified, so the reader can follow the logic without gaps.",
        },
        {
          kind: "match",
          prompt: "Match each circle theorem to its statement.",
          pairs: [
            { left: "Angle in a semicircle", right: "Equals 90 degrees" },
            { left: "Angles in the same segment", right: "Are equal" },
            { left: "Angle at the centre", right: "Twice the angle at the circumference" },
            { left: "Opposite angles of a cyclic quadrilateral", right: "Add to 180 degrees" },
          ],
          ask: "Match each theorem to what it states. These are the tools you cite as reasons in a proof.",
          hints: [
            "The semicircle angle is a right angle.",
            "The centre angle is double, and same segment angles are equal.",
            "Opposite angles of a cyclic quadrilateral are supplementary, adding to one hundred eighty.",
          ],
          explain: "The angle in a semicircle is 90 degrees, angles in the same segment are equal, the angle at the centre is twice that at the circumference, and opposite angles of a cyclic quadrilateral add to 180 degrees.",
        },
        {
          kind: "order",
          prompt: "Order the parts of a well structured geometry proof.",
          items: [
            "State what is given",
            "State what you need to prove",
            "Give each step with a supporting reason",
            "Reach the conclusion",
          ],
          ask: "A proof moves from the known to the required. Put the parts in a sensible order.",
          hints: [
            "Begin from the information you are given.",
            "Set the goal, work through justified steps, then conclude.",
            "Given, to prove, reasoned steps, then conclusion.",
          ],
          explain: "State what is given, state what to prove, work through each step with a reason, then reach the conclusion. Reasons are what make it a proof.",
        },
        {
          kind: "insight",
          body: "A proof is justified steps from given to conclusion. Circle theorems are the reasons you lean on.",
        },
      ],
      talkPrompt: "Quiz me on plane geometry proofs, one at a time.",
    },
    {
      key: "amath-calculus-1",
      title: "Differentiation and kinematics",
      minutes: 6,
      topic: "calculus-differentiation-integration-and-kinemat",
      steps: [
        {
          kind: "concept",
          heading: "Rates of change",
          body: "Differentiation finds the gradient of a curve at any point. The power rule says the derivative of x^n is n times x^{n-1}. Integration reverses this. In kinematics, differentiating displacement with respect to time gives velocity, and differentiating velocity gives acceleration.",
        },
        {
          kind: "tiles",
          prompt: "Build the derivative of x^n using the power rule.",
          tiles: ["n", "x^{n-1}", "x^{n+1}", "x^n"],
          answer: ["n", "x^{n-1}"],
          ask: "Let us build the power rule. Bring the power down in front, then reduce the power by one. Lay out the tiles.",
          hints: [
            "The old power n comes down to the front.",
            "The new power is one less than before.",
            "It reads n times x to the power n minus one.",
          ],
          explain: "The derivative of x to the n is n times x to the power n minus one. The power drops by one and moves to the front.",
        },
        {
          kind: "slider",
          prompt: "For y = x^3, find dy/dx at x = 2. Slide to its value.",
          min: 0,
          max: 20,
          step: 1,
          unit: "",
          start: 6,
          targetMin: 12,
          targetMax: 12,
          ask: "Differentiate to get three x squared, then put x as two. Slide to the value.",
          hints: [
            "The derivative of x cubed is three x squared.",
            "Put x equals two, so three times two squared.",
            "Two squared is four, and three times four is twelve.",
          ],
          explain: "The derivative of x cubed is three x squared. At x equals two that is three times four, which is twelve.",
        },
        {
          kind: "insight",
          body: "Differentiate by dropping the power in front and reducing it by one. Displacement to velocity to acceleration is one differentiation each.",
        },
      ],
      talkPrompt: "Quiz me on differentiation and kinematics, one at a time.",
    },
  ],
};
