import type { Subconcept } from "@/lib/teaching/subconcepts";

// TP2 Measurements and Kinematics, Revision 2. Checkpoint over Practical Chapter 02,
// sections tp2.4 to tp2.6: measuring small quantities, the simple pendulum and g,
// and a cylinder down a ramp. Question-only.

export const BOXES: Subconcept[] = [
  {
    id: "tp2.rev2",
    code: "R2",
    title: "Revision 2",
    blurb: "Checkpoint: small quantities, the pendulum and the ramp",
    kind: "revision",
    steps: [
      {
        kind: "choice",
        question: "A wire is wound in 50 tight touching turns of total length 45.0 mm. What is the diameter of the wire?",
        figure: "fig-pr2-03-wire-coil",
        options: ["9.0 mm", "0.90 mm", "2250 mm", "45.0 mm"],
        correct: 1,
                ask: "One diameter is the total length divided by the number of turns, so work out 45.0 ÷ 50. Which option is that?",
        hints: [
          "Coiling 50 turns makes the length 50 times larger, so divide the length by 50 to get 1 diameter.",
          "45.0 ÷ 50 is 0.90, measured in millimetres.",
        ],
        working: [
          { label: "Formula", latex: "d = \\dfrac{L}{n}" },
          { label: "Substitute", latex: "d = \\dfrac{45.0}{50}" },
          { label: "Answer", latex: "d = 0.90\\ \\text{mm}" },
        ],
        explain: "The diameter is 0.90 millimetres, because 45.0 millimetres divided by 50 turns is 0.90 millimetres. Coiling many turns makes the error 50 times smaller than measuring 1 turn.",
      },
      {
        kind: "choice",
        question: "For a pendulum, a graph of T^2 against l is a straight line through the origin with gradient 4.02 s^2/m. Taking 4 pi^2 = 39.48, find g.",
        figure: "fig-pr2-09-period2-length-graph",
        options: ["4.02 m/s^2", "39.48 m/s^2", "9.7 m/s^2", "9.8 m/s^2"],
        correct: 3,
                ask: "The gradient equals 4 pi squared divided by g, so g is 4 pi squared divided by the gradient. Work out 39.48 ÷ 4.02.",
        hints: [
          "Squaring the pendulum equation gives T^2 equals 4 pi squared over g, times l.",
          "39.48 ÷ 4.02 is about 9.8, in metres per second squared.",
        ],
        working: [
          { label: "Formula", latex: "g = \\dfrac{4\\pi^2}{\\text{gradient}}" },
          { label: "Substitute", latex: "g = \\dfrac{39.48}{4.02}" },
          { label: "Answer", latex: "g = 9.8\\ \\text{m/s}^2" },
        ],
        explain: "The gravitational field strength is 9.8 metres per second squared, because 39.48 divided by the gradient 4.02 is 9.8. The gradient of the T^2 against l line is 4 pi squared over g.",
      },
      {
        kind: "choice",
        question: "Which change would leave the period of a simple pendulum unchanged?",
        figure: "fig-pr2-07-pendulum-apparatus",
        options: ["Using a heavier bob", "Using a longer string", "Moving to a planet where g is larger", "Shortening the string"],
        correct: 0,
        ask: "The period depends only on the length and on g. Which of these changes neither the length nor g?",
        hints: [
          "The period is set by the length of the string and the gravitational field strength, not by how much matter is in the bob.",
          "Swapping to a heavier bob keeps the length and g the same, so the period does not change.",
        ],
        explain: "Using a heavier bob leaves the period unchanged, because the period depends only on the length and on g, not on the mass of the bob. Changing the length or g would change the period.",
      },
      {
        kind: "choice",
        question: "A cylinder rests on a ramp of slope distance 0.800 m and height 0.139 m. Find sin theta for the ramp.",
        figure: "fig-pr2-11-ramp",
        options: ["0.800", "5.76", "0.174", "0.139"],
        correct: 2,
                ask: "The sine of the ramp angle is the height divided by the slope distance, so work out 0.139 ÷ 0.800.",
        hints: [
          "For a right-angled triangle, sine theta is the opposite side, the height, over the hypotenuse, the slope distance.",
          "0.139 ÷ 0.800 is about 0.174, with no unit.",
        ],
        working: [
          { label: "Formula", latex: "\\sin\\theta = \\dfrac{h}{s}" },
          { label: "Substitute", latex: "\\sin\\theta = \\dfrac{0.139}{0.800}" },
          { label: "Answer", latex: "\\sin\\theta = 0.174" },
        ],
        explain: "The sine of the ramp angle is 0.174, because 0.139 metres divided by 0.800 metres is 0.174. It has no unit because it is a length divided by a length.",
      },
      {
        kind: "choice",
        question: "A cylinder starts from rest and covers x = 0.900 m of the ramp in an average time of 1.036 s. The final speed is twice the average speed, so v = 2x / t. Find v.",
        options: ["0.87 m/s", "1.04 m/s", "0.90 m/s", "1.74 m/s"],
        correct: 3,
                ask: "Because it starts from rest, the final speed is 2 times x divided by t. Work out 2 × 0.900, then divide by 1.036.",
        hints: [
          "From rest, the average speed is half the final speed, so the final speed is 2x divided by t.",
          "2 × 0.900 is 1.800, and 1.800 ÷ 1.036 is about 1.74 metres per second.",
        ],
        working: [
          { label: "Formula", latex: "v = \\dfrac{2x}{t}" },
          { label: "Substitute", latex: "v = \\dfrac{2 \\times 0.900}{1.036}" },
          { label: "Answer", latex: "v = 1.74\\ \\text{m/s}" },
        ],
        explain: "The final speed is 1.74 metres per second, because 2 × 0.900 metres is 1.800 metres, and dividing by 1.036 seconds gives 1.74 metres per second. From rest the final speed is twice the average speed.",
      },
      {
        kind: "graphpick",
        prompt: "For a simple pendulum, which graph shows how T^2 depends on l?",
        xLabel: "l (m)",
        yLabel: "T^2 (s^2)",
        options: [
          { points: [[0, 0], [0.5, 1.0], [1.0, 4.0]] },
          { points: [[0, 0], [0.5, 2.0], [1.0, 4.0]] },
          { points: [[0, 1.0], [0.5, 3.0], [1.0, 5.0]] },
          { points: [[0, 4.0], [0.5, 2.0], [1.0, 0]] },
        ],
        correct: 1,
        ask: "T^2 equals 4 pi squared over g, times l. That is a straight line that passes through the origin and rises as l rises. Which graph matches?",
        hints: [
          "The relation T^2 equals a constant times l has no added number, so the line goes through the origin.",
          "It is a straight line, not a curve, and it rises as the length increases.",
        ],
        explain: "T^2 is proportional to l, so the correct graph is a straight line rising through the origin. A curve would mean T^2 is not proportional to l, and a line that misses the origin would have an added constant.",
      },
      {
        kind: "order",
        prompt: "Put these steps for finding g with a pendulum in the correct order.",
        items: [
          "Measure the length l from the support to the centre of the bob",
          "Time 20 oscillations and divide by 20 to get the period T",
          "Repeat for several lengths, then plot T^2 against l",
          "Find the gradient of the straight line",
          "Calculate g from g = 4 pi^2 / gradient",
        ],
        ask: "You need a period for each length before you can plot anything, and the gradient must come before the final calculation. Put the steps in order.",
        hints: [
          "Start by measuring a length, then time many oscillations to get its period.",
          "Only once the line is plotted can you read its gradient and put it into g equals 4 pi squared over the gradient.",
        ],
        explain: "First measure the length to the centre of the bob, then time 20 oscillations for the period, repeat for several lengths and plot T^2 against l, read the gradient, and finally calculate g as 4 pi squared divided by the gradient.",
      },
      {
        kind: "match",
        prompt: "Match each small quantity to the technique that measures it accurately.",
        pairs: [
          { left: "Diameter of a thin wire", right: "Coil 50 turns and divide the length by 50" },
          { left: "Thickness of one sheet of paper", right: "Measure a stack of 50 sheets and divide by 50" },
          { left: "Period of a pendulum", right: "Time 20 oscillations and divide by 20" },
          { left: "Diameter of a coin", right: "Read R2 minus R1 between 2 set squares" },
        ],
        ask: "Each technique spreads a tiny quantity over many items or many swings so the error is smaller. Match each quantity to its method.",
        hints: [
          "Wire and paper are both measured by stacking or coiling many identical pieces and dividing.",
          "A pendulum is timed over 20 swings, and a coin is trapped between 2 set squares to read its 2 edges.",
        ],
        explain: "A wire diameter comes from 50 coiled turns, one sheet from a stack of 50 sheets, a period from 20 oscillations, and a coin diameter from the 2 set-square readings R2 minus R1. Each method divides a small quantity by a large number so the error shrinks.",
      },
      {
        kind: "slider",
        prompt: "A T^2 against l graph has a gradient of 4.05 s^2/m. Taking 4 pi^2 = 39.48, set the slider to the value of g, in m/s^2.",
        min: 0,
        max: 15,
        step: 0.1,
        unit: "m/s^2",
        start: 0,
        targetMin: 9.6,
        targetMax: 9.8,
                ask: "g is 4 pi squared divided by the gradient, so work out 39.48 ÷ 4.05 and slide to that value.",
        hints: [
          "The gradient of the T^2 against l line is 4 pi squared over g, so g is 4 pi squared over the gradient.",
          "39.48 ÷ 4.05 is about 9.7, so slide to 9.7 metres per second squared.",
        ],
        working: [
          { label: "Formula", latex: "g = \\dfrac{4\\pi^2}{\\text{gradient}}" },
          { label: "Substitute", latex: "g = \\dfrac{39.48}{4.05}" },
          { label: "Answer", latex: "g = 9.7\\ \\text{m/s}^2" },
        ],
        explain: "The gravitational field strength is 9.7 metres per second squared, because 39.48 divided by the gradient 4.05 is 9.7. A slightly larger gradient gives a slightly smaller g.",
      },
      {
        kind: "spoterror",
        prompt: "One line in this method for finding g with a pendulum is wrong. Find it.",
        lines: [
          "To find g, measure the length l to the centre of the bob.",
          "Time 20 complete oscillations and divide by 20 to get the period T.",
          "The period of a pendulum increases with the mass of the bob.",
          "Plot T^2 against l, then find g from the gradient of the line.",
        ],
        errorLine: 2,
        ask: "3 of these lines describe the pendulum correctly. Think about which quantities actually change the period.",
        hints: [
          "The period is set by the length and by g, and by nothing about the bob itself.",
          "Adding more mass to the bob does not change how long one swing takes.",
        ],
        explain: "The wrong line says the period increases with the mass of the bob. The period of a pendulum does not depend on the mass of the bob at all; it depends only on the length and on g.",
      },
      {
        kind: "open",
        prompt: "A student measures the length l of a pendulum to find g. Explain one precaution that makes l accurate.",
        figure: "fig-pr2-10-pendulum-blocks",
        modelAnswer: "Measure the length from the point of support down to the centre of the bob, not to its top or bottom, because the bob swings about its centre. Keep the metre rule vertical and read it with the line of sight perpendicular to the scale to avoid a parallax error. Clamping the string firmly, for example between 2 blocks, fixes the support point so the length does not change during the swings.",
        marks: [
          "Measure to the centre of the bob, from the support point.",
          "Keep the rule vertical and view perpendicular to avoid parallax.",
          "Fix the support so the length stays constant.",
        ],
        ask: "Think about where the length should be measured from and to, how the rule should be held, and how parallax is avoided.",
      },
      {
        kind: "open",
        prompt: "Explain why measuring a stack of 50 sheets of paper gives a more accurate thickness for one sheet than measuring a single sheet.",
        modelAnswer: "A single sheet is so thin that the instrument's smallest division is a large fraction of the reading, so the fractional error is large. Stacking 50 sheets makes the total thickness 50 times larger, which is easy to measure with a small fractional error. Dividing that total by 50 gives one sheet's thickness, and the error is also divided by 50, so the result is far more accurate.",
        marks: [
          "A single sheet is too thin, so its fractional error is large.",
          "A stack of 50 makes the measured quantity 50 times larger.",
          "Dividing by 50 divides the error by 50, giving a more accurate value.",
        ],
        ask: "Think about how big the measurement error is compared with the thickness of one sheet, and what stacking 50 sheets does to that comparison.",
      },
    ],
  },
];
