import type { Subconcept } from "@/lib/teaching/subconcepts";

// TP4 Heat (Practical Chapter 4), topical quiz. Whole-topic check: heat transfer and
// thermometry, heat capacity and Q = mc\Delta\theta, latent heat and changes of state,
// specific heat capacity by electrical heating, joulemeter and method of mixtures, and
// specific latent heat by electrical methods. Question-only; no formula fields.

export const BOXES: Subconcept[] = [
  {
    id: "tp4.quiz",
    code: "Quiz",
    title: "Heat topical quiz",
    blurb: "Whole-topic check: heat transfer, thermometry, heat capacity, latent heat, and measuring c and l",
    kind: "quiz",
    steps: [
      {
        kind: "choice",
        question: "Which type of heat transfer can cross a vacuum, needing no medium?",
        options: ["Conduction", "Convection", "Radiation", "Both conduction and convection"],
        correct: 2,
        ask: "One transfer travels as infra-red waves and needs no particles. Which one reaches us across empty space from the Sun?",
        hints: [
          "Conduction and convection both need particles, so they cannot cross a vacuum.",
          "Radiation travels as infra-red waves and crosses empty space, like sunlight reaching the Earth.",
        ],
        explain: "Radiation can cross a vacuum, because it travels as infra-red waves and needs no medium. Conduction and convection both rely on particles, so they cannot cross empty space.",
      },
      {
        kind: "classify",
        prompt: "Sort each example by the type of heat transfer it shows.",
        bins: ["Conduction", "Convection", "Radiation"],
        items: [
          { text: "heat passing along a metal spoon left in hot soup", bin: 0 },
          { text: "free electrons carrying energy through a copper rod", bin: 0 },
          { text: "warm water rising in a beaker heated from below", bin: 1 },
          { text: "a breeze forming as warm air rises over hot land", bin: 1 },
          { text: "warmth reaching you across empty space from the Sun", bin: 2 },
          { text: "infra-red waves felt from a glowing fire", bin: 2 },
        ],
        ask: "Conduction passes energy through particles or free electrons in a solid; convection is a current in a moving fluid; radiation travels as waves with no medium. Tap each example and drop it in its bin.",
        hints: [
          "If energy passes through a solid without the material flowing, it is conduction.",
          "A rising warm fluid is convection; energy crossing empty space is radiation.",
        ],
        explain: "The spoon and the copper rod carry heat by conduction through particles and free electrons. The rising warm water and the breeze are convection currents in a fluid. The warmth from the Sun and from a fire arrives as radiation, which needs no medium.",
      },
      {
        kind: "choice",
        question: "A resistance wire reads 50 ohm at the ice point, 95 ohm at the steam point and 77 ohm in a warm liquid. Find the temperature of the liquid.",
        options: ["60 degC", "27 degC", "45 degC", "77 degC"],
        correct: 0,
        ask: "Use theta = (reading minus ice-point value) divided by (steam-point value minus ice-point value), times 100. Work out 77 - 50, over 95 - 50, then times 100.",
        hints: [
          "The formula is theta = (reading minus ice-point value) divided by (steam-point value minus ice-point value), all times 100.",
          "77 - 50 is 27, and 95 - 50 is 45; 27 ÷ 45 is 0.6, × 100 is 60 degrees Celsius.",
        ],
        working: [
          { label: "Formula", latex: "\\theta = \\dfrac{X_\\theta - X_0}{X_{100} - X_0} \\times 100" },
          { label: "Substitute", latex: "\\theta = \\dfrac{77 - 50}{95 - 50} \\times 100" },
          { label: "Answer", latex: "\\theta = 60\\ ^\\circ\\text{C}" },
        ],
        explain: "The temperature is 60 degrees Celsius, because 77 - 50 is 27, 95 - 50 is 45, and 27 ÷ 45 × 100 is 60.",
      },
      {
        kind: "slider",
        prompt: "A thermistor reads 820 ohm at the ice point, 200 ohm at the steam point and 510 ohm in a warm bath. Set the slider to the temperature of the bath, in degC.",
        min: 0,
        max: 100,
        step: 1,
        unit: "degC",
        start: 0,
        targetMin: 49,
        targetMax: 51,
        ask: "Use theta = (reading minus ice-point value) divided by (steam-point value minus ice-point value), times 100. Work out 510 - 820, over 200 - 820, then times 100.",
        hints: [
          "510 - 820 is negative 310, and 200 - 820 is negative 620.",
          "Negative 310 divided by negative 620 is 0.5, and times 100 is 50 degrees Celsius.",
        ],
        working: [
          { label: "Formula", latex: "\\theta = \\dfrac{X_\\theta - X_0}{X_{100} - X_0} \\times 100" },
          { label: "Substitute", latex: "\\theta = \\dfrac{510 - 820}{200 - 820} \\times 100" },
          { label: "Answer", latex: "\\theta = 50\\ ^\\circ\\text{C}" },
        ],
        explain: "The temperature is 50 degrees Celsius, because 510 - 820 is negative 310, 200 - 820 is negative 620, and negative 310 divided by negative 620 × 100 is 50.",
      },
      {
        kind: "open",
        prompt: "Explain what is meant by the ice point and the steam point, and how they are used to calibrate a thermometer.",
        figure: "fig-pr4-01-thermometer",
        modelAnswer: "The ice point is the temperature of pure melting ice, taken as 0 degrees Celsius, and the steam point is the temperature of steam above boiling water, taken as 100 degrees Celsius. To calibrate a thermometer, you measure its thermometric property, such as the length of a liquid column or a resistance, at each fixed point. The scale between the 2 values is then divided evenly, so any reading can be turned into a temperature using theta = (reading minus the ice-point value) divided by (the steam-point value minus the ice-point value), all times 100.",
        marks: [
          "Ice point is melting ice at 0 degC; steam point is steam over boiling water at 100 degC.",
          "The thermometric property is measured at both fixed points.",
          "The scale between the 2 points is divided evenly to read other temperatures.",
        ],
        ask: "Say what temperature each fixed point is, and how the 2 readings set the scale in between.",
      },
      {
        kind: "choice",
        question: "0.50 kg of water is heated from 20 degC to 80 degC. Take c = 4200 J/(kg degC). Find the heat supplied Q.",
        options: ["126 J", "1.26 x 10^3 J", "2.1 x 10^4 J", "1.26 x 10^5 J"],
        correct: 3,
        ask: "The rise is 80 - 20, which is 60. Multiply mass times c times that rise: 0.50 × 4200 × 60.",
        hints: [
          "Use Q = m times c times the temperature rise.",
          "0.50 × 4200 is 2100, and 2100 × 60 is 126000 joules, which is 1.26 × 10 to the power 5 joules.",
        ],
        working: [
          { label: "Formula", latex: "Q = mc\\Delta\\theta" },
          { label: "Substitute", latex: "Q = 0.50 \\times 4200 \\times 60" },
          { label: "Answer", latex: "Q = 1.26 \\times 10^{5}\\ \\text{J}" },
        ],
        explain: "The heat supplied is 1.26 × 10 to the power 5 joules, because 0.50 × 4200 times a 60 degree rise is 126000 joules.",
      },
      {
        kind: "choice",
        question: "0.20 kg of ice at 0 degC melts completely. Take l_f = 3.34 x 10^5 J/kg. Find the heat needed.",
        options: ["6.68 x 10^3 J", "6.68 x 10^4 J", "1.67 x 10^6 J", "3.34 x 10^5 J"],
        correct: 1,
        ask: "The heat to melt is l_f times the mass, so work out 3.34 × 10 to the power 5, × 0.20.",
        hints: [
          "Use L = l_f times m.",
          "3.34 × 10 to the power 5 × 0.20 is 66800 joules, which is 6.68 × 10 to the power 4 joules.",
        ],
        working: [
          { label: "Formula", latex: "L = l_f m" },
          { label: "Substitute", latex: "L = 3.34 \\times 10^{5} \\times 0.20" },
          { label: "Answer", latex: "L = 6.68 \\times 10^{4}\\ \\text{J}" },
        ],
        explain: "The heat needed is 6.68 × 10 to the power 4 joules, because 3.34 × 10 to the power 5 joules per kilogram times 0.20 kilograms is 66800 joules.",
      },
      {
        kind: "choice",
        question: "While a solid is melting, its temperature stays constant even though heat is still supplied. Why?",
        options: [
          "The heater has stopped supplying energy",
          "The heat raises the particles' kinetic energy",
          "The heat raises the particles' potential energy as bonds are loosened",
          "The solid has reached its heat capacity",
        ],
        correct: 2,
        ask: "During melting the energy is not speeding the particles up. What kind of energy is it changing as bonds are broken?",
        hints: [
          "Temperature is a measure of the particles' kinetic energy, and that is not changing here.",
          "The supplied energy goes into potential energy, loosening the bonds between particles, so the temperature stays constant.",
        ],
        explain: "The temperature stays constant because the heat raises the particles' potential energy, loosening the bonds between them, rather than their kinetic energy. Only when the kinetic energy rises does the temperature go up.",
      },
      {
        kind: "cloze",
        prompt: "Complete the sentence about what happens to energy during a change of state.",
        segments: [
          "During a change of state the temperature stays ",
          " while heat is still supplied. The energy raises the particles' ",
          " energy by breaking bonds, not their ",
          " energy.",
        ],
        bank: ["constant", "potential", "kinetic", "rising", "chemical"],
        answer: ["constant", "potential", "kinetic"],
        ask: "Temperature depends on the particles' kinetic energy. Think about what stays the same, and which energy the heat is changing while bonds break.",
        hints: [
          "The temperature does not change during melting or boiling, so it stays constant.",
          "The energy goes into potential energy as bonds break, not into kinetic energy.",
        ],
        explain: "During a change of state the temperature stays constant while heat is still supplied. The energy raises the particles' potential energy by breaking bonds, not their kinetic energy, so the temperature does not rise.",
      },
      {
        kind: "graphpick",
        prompt: "A solid is heated steadily from below its melting point until it has all boiled away. Which temperature-time graph shows this heating curve?",
        xLabel: "time / s",
        yLabel: "temperature / degC",
        options: [
          { points: [[0, 20], [1, 50], [2, 50], [3, 80], [4, 100], [5, 100], [6, 120]], caption: "Rises, flat, rises, flat, rises" },
          { points: [[0, 20], [2, 60], [4, 100], [6, 140]], caption: "Rises as a straight line" },
          { points: [[0, 20], [2, 60], [3, 60], [5, 120]], caption: "Rises, one flat part, then rises" },
          { points: [[0, 120], [2, 80], [4, 40], [6, 0]], caption: "Falls steadily to zero" },
        ],
        correct: 0,
        ask: "The substance melts at one temperature and boils at a higher one. At each change of state the temperature holds steady. How many flat plateaus should the curve have?",
        hints: [
          "Between changes of state the temperature rises as the substance warms.",
          "There is a flat plateau at melting and a second flat plateau at boiling, so the curve rises, flattens, rises, flattens, then rises again.",
        ],
        explain: "The correct graph rises, then holds flat at the melting point, rises again, holds flat at the boiling point, then rises. The 2 flat plateaus are the changes of state, where the heat raises potential energy at constant temperature.",
      },
      {
        kind: "choice",
        question: "In the electrical method for specific heat capacity, why is a graph of temperature against time better than using just the start and finish readings?",
        options: [
          "The gradient of the best-fit line averages many readings and reduces random errors",
          "The gradient removes the need to know the power",
          "A single pair of readings is always more accurate",
          "The graph makes the block heat up faster",
        ],
        correct: 0,
        ask: "Think about what a best-fit line drawn through many plotted points does, compared with only 2 readings.",
        hints: [
          "Many plotted points let you draw a best-fit line through them.",
          "The gradient of that line averages many readings, so random errors in single points matter less.",
        ],
        explain: "A graph is better because the gradient of its best-fit line uses many readings, averaging them out and reducing the effect of random errors in any single pair. 2 readings alone give no such averaging.",
      },
      {
        kind: "slider",
        prompt: "A 1.00 kg metal block is heated at P = 48 W and its temperature-time graph has a gradient of 0.056 degC/s. Set the slider to the specific heat capacity c, in J/(kg degC).",
        min: 0,
        max: 1500,
        step: 10,
        unit: "J/(kg degC)",
        start: 0,
        targetMin: 850,
        targetMax: 870,
        ask: "The gradient equals P divided by m times c, so c = P divided by m times the gradient. Work out 48 ÷ 1.00 × 0.056.",
        hints: [
          "Rearrange to c = P divided by (m times the gradient).",
          "48 ÷ 1.00 × 0.056 is 48 ÷ 0.056, which is about 860, so slide to 8.6 × 10 to the power 2.",
        ],
        working: [
          { label: "Formula", latex: "c = \\dfrac{P}{m \\times \\text{gradient}}" },
          { label: "Substitute", latex: "c = \\dfrac{48}{1.00 \\times 0.056}" },
          { label: "Answer", latex: "c = 8.6 \\times 10^{2}\\ \\text{J/(kg}\\,^\\circ\\text{C)}" },
        ],
        explain: "The specific heat capacity is about 8.6 × 10 to the power 2 joules per kilogram per degree Celsius, because 48 ÷ 1.00 × 0.056 is 48 over 0.056, which is about 860.",
      },
      {
        kind: "spoterror",
        prompt: "A student writes 4 statements about measuring specific heat capacity by electrical heating. Tap the line with the mistake.",
        lines: [
          "The immersion heater supplies energy at a steady rate",
          "The ammeter is connected in series with the heater",
          "Heat loss to the room makes the measured c come out too low",
          "Lagging the block reduces the heat lost to the surroundings",
        ],
        errorLine: 2,
        ask: "Follow where the supplied energy goes. The sum credits all the supplied energy to the block, but some leaks away, so does the calculated c end up above or below the true value?",
        hints: [
          "The calculation counts all the supplied energy as warming the block, even the part lost to the room.",
          "Crediting energy that actually escaped makes the calculated c come out too high, not too low.",
        ],
        explain: "The mistake is the line saying heat loss makes the measured c too low. Some supplied energy is lost to the room, but the calculation credits all of it to the block, so the value of c comes out too high, not too low.",
      },
      {
        kind: "open",
        prompt: "Define the specific heat capacity of a material, and state the equation used to find the heat supplied when its temperature changes.",
        modelAnswer: "The specific heat capacity is the energy needed to raise the temperature of 1 kilogram of the material by 1 degree Celsius, measured in joules per kilogram per degree Celsius. The heat supplied for a temperature change is Q = m times c times the change in temperature, where m is the mass, c is the specific heat capacity and the change in temperature is the rise in degrees Celsius.",
        marks: [
          "Specific heat capacity is the energy to raise 1 kg by 1 degC.",
          "Its unit is J/(kg degC).",
          "Q = mc times the temperature change, with m, c and the rise defined.",
        ],
        ask: "Give the meaning and unit of specific heat capacity, then the equation linking heat, mass and temperature change.",
      },
      {
        kind: "choice",
        question: "0.30 kg of water at 0 degC freezes completely. Take l_f = 3.34 x 10^5 J/kg. How much heat is released?",
        options: ["3.34 x 10^4 J", "1.11 x 10^6 J", "6.68 x 10^4 J", "1.0 x 10^5 J"],
        correct: 3,
        ask: "Freezing releases the same latent heat that melting would need, l_f times the mass. Work out 3.34 × 10 to the power 5, × 0.30.",
        hints: [
          "Use L = l_f times m.",
          "3.34 × 10 to the power 5 × 0.30 is 100200 joules, which rounds to 1.0 × 10 to the power 5 joules.",
        ],
        working: [
          { label: "Formula", latex: "L = l_f m" },
          { label: "Substitute", latex: "L = 3.34 \\times 10^{5} \\times 0.30" },
          { label: "Answer", latex: "L = 1.0 \\times 10^{5}\\ \\text{J}" },
        ],
        explain: "The heat released is about 1.0 × 10 to the power 5 joules, because 3.34 × 10 to the power 5 joules per kilogram times 0.30 kilograms is 100200 joules.",
      },
      {
        kind: "match",
        prompt: "Match each quantity to its correct unit.",
        pairs: [
          { left: "specific heat capacity c", right: "J/(kg degC)" },
          { left: "heat capacity C", right: "J/degC" },
          { left: "specific latent heat l", right: "J/kg" },
          { left: "power P", right: "W" },
        ],
        ask: "2 of these are per kilogram or per degree; one is per kilogram only; one is a rate of energy. Match each to its unit.",
        hints: [
          "Specific quantities are per kilogram; heat capacity is for the whole object per degree Celsius.",
          "Specific latent heat has no temperature in its unit, and power is measured in watts.",
        ],
        explain: "Specific heat capacity is in J/(kg degC), heat capacity is in J/degC, specific latent heat is in J/kg, and power is in watts. The specific quantities are per kilogram, and latent heat has no temperature in its unit because it is a change of state.",
      },
      {
        kind: "choice",
        question: "Which statement correctly distinguishes heat capacity from specific heat capacity?",
        options: [
          "Heat capacity is the heat to raise 1 kg by 1 degC",
          "Specific heat capacity is the heat to raise 1 kg by 1 degC, while heat capacity is the heat to raise the whole object by 1 degC",
          "They are the same quantity with different units",
          "Specific heat capacity depends on the size of the object",
        ],
        correct: 1,
        ask: "One quantity is per kilogram of the material; the other is for the whole object. Which is which?",
        hints: [
          "Specific heat capacity is measured per kilogram, in J/(kg degC), and depends only on the material.",
          "Heat capacity is for the whole object, in J/degC, and they link by C = m times c.",
        ],
        explain: "Specific heat capacity is the heat to raise 1 kilogram of a material by 1 degree Celsius, depending only on the material. Heat capacity is the heat to raise the whole object by 1 degree Celsius, depending on its size too, and they link by C equals m times c.",
      },
      {
        kind: "open",
        prompt: "Using a heating curve, explain why the temperature stays constant while a substance changes state, and what happens to the energy supplied.",
        figure: "fig-pr4-02-heating-curve",
        modelAnswer: "On a heating curve the flat plateaus are where the substance changes state, for example melting or boiling. During these plateaus the temperature stays constant even though heat is still supplied. The energy goes into raising the particles' potential energy by breaking or loosening the bonds between them, rather than their kinetic energy. Because temperature depends on the kinetic energy, it does not change until the change of state is complete.",
        marks: [
          "The flat plateaus on the curve are the changes of state.",
          "Temperature stays constant while heat is still supplied.",
          "Energy raises potential energy (breaking bonds), not kinetic energy, so temperature is unchanged.",
        ],
        ask: "Point to the flat parts of the curve, and say which kind of particle energy the heat is changing there.",
      },
      {
        kind: "tiles",
        prompt: "A 60 W heater runs for 300 s. Build the working line for the energy supplied Q, using Q = Pt.",
        tiles: ["Q =", "60", "\\times", "300", "=", "18000", "J", "W"],
        answer: ["Q =", "60", "\\times", "300", "=", "18000", "J"],
        ask: "The energy is power times time, so set up 60 × 300.",
        hints: [
          "Use Q = P times t.",
          "60 × 300 is 18000, and energy is measured in joules.",
        ],
        working: [
          { label: "Formula", latex: "Q = Pt" },
          { label: "Substitute", latex: "Q = 60 \\times 300" },
          { label: "Answer", latex: "Q = 18000\\ \\text{J}" },
        ],
        explain: "The energy supplied is 18000 joules, because 60 watts times 300 seconds is 18000 joules.",
      },
      {
        kind: "choice",
        question: "A 2.0 kg copper block is heated by a 60 W heater for 300 s. Take c = 385 J/(kg degC) and assume no heat loss. Find the temperature rise.",
        options: ["9.0 degC", "47 degC", "23 degC", "230 degC"],
        correct: 2,
        ask: "First find the energy: power times time, 60 × 300. Then divide by mass times c: divide by 2.0 × 385.",
        hints: [
          "The energy supplied is Q = P times t = 60 × 300 = 18000 joules.",
          "The rise is Q divided by m times c: 18000 ÷ 2.0 × 385, which is 18000 over 770, about 23 degrees Celsius.",
        ],
        working: [
          { label: "Formula", latex: "\\Delta\\theta = \\dfrac{Pt}{mc}" },
          { label: "Substitute", latex: "\\Delta\\theta = \\dfrac{60 \\times 300}{2.0 \\times 385}" },
          { label: "Answer", latex: "\\Delta\\theta = 23\\ ^\\circ\\text{C}" },
        ],
        explain: "The energy supplied is 60 × 300, which is 18000 joules, so the temperature rise is 18000 ÷ 2.0 × 385, or 18000 over 770, about 23 degrees Celsius.",
      },
      {
        kind: "classify",
        prompt: "On a heating curve, sort each situation by whether it is a sloping part or a flat plateau.",
        bins: ["Sloping part of the curve", "Flat plateau of the curve"],
        items: [
          { text: "water warming from 20 degC to 80 degC", bin: 0 },
          { text: "ice at 0 degC melting into water", bin: 1 },
          { text: "water boiling into steam at 100 degC", bin: 1 },
          { text: "steam heating up above 100 degC", bin: 0 },
          { text: "the particles' kinetic energy increasing", bin: 0 },
          { text: "the particles' potential energy rising as bonds break", bin: 1 },
        ],
        ask: "Sloping parts are where the temperature changes and Q = mc\\Delta\\theta applies; flat plateaus are changes of state where L = lm applies. Tap each item and drop it in its bin.",
        hints: [
          "If the temperature is changing and kinetic energy is rising, it is a sloping part.",
          "If the substance is changing state at constant temperature with potential energy rising, it is a flat plateau.",
        ],
        explain: "Warming the water, warming the steam and raising the kinetic energy are sloping parts, where Q = mc times the temperature change applies. Melting, boiling and raising the potential energy as bonds break are flat plateaus, where L = l times m applies.",
      },
      {
        kind: "order",
        prompt: "Put these steps of measuring the specific latent heat of vaporisation l_v in the correct order.",
        items: [
          "Set up the immersion heater in water on a top-pan balance",
          "Switch on and wait until the water boils steadily",
          "Start the timer and record the balance reading",
          "Record the mass and time at regular intervals as steam escapes",
          "Plot the mass evaporated against time and find the gradient",
          "Use l_v = P divided by the gradient",
        ],
        ask: "You take mass readings only once the boiling is steady, then use the gradient of the graph. Put the steps in order from setting up to the final calculation.",
        hints: [
          "Readings should only start when the water is boiling steadily, so all the energy vaporises it.",
          "The last steps are plotting mass against time and dividing the power by the gradient to get l_v.",
        ],
        explain: "You set up the heater in water on a balance, wait until it boils steadily, then start timing and record the mass at regular intervals as steam escapes. Plotting mass evaporated against time gives a gradient of P divided by l_v, so l_v is the power divided by that gradient.",
      },
      {
        kind: "choice",
        question: "In the experiment to measure l_f, an identical control funnel of ice has its heater switched off. What is its purpose?",
        figure: "fig-pr4-08-latent-fusion",
        options: [
          "To measure the ice melted by the warm room, so it can be subtracted",
          "To keep the ice cold for longer",
          "To double the mass of melted water collected",
          "To supply extra power to the heated funnel",
        ],
        correct: 0,
        ask: "Some ice melts just from the warm room, with no heater at all. What does the control funnel let you measure and then remove?",
        hints: [
          "The control funnel has no heater, so any melt from it is caused only by the warm room.",
          "Subtracting the control's melt leaves only the ice the heater melted, so l_f does not come out too small.",
        ],
        explain: "The control funnel measures the ice melted by the warm room alone, because its heater is off. Subtracting that from the heated funnel's melt leaves only the ice the heater melted, which stops l_f coming out too small.",
      },
      {
        kind: "open",
        prompt: "In measuring the specific heat capacity of a metal block by electrical heating, explain why the value obtained is often too high, and give 2 ways to reduce this error.",
        figure: "fig-pr4-05-shc-block-graph",
        modelAnswer: "Some of the electrical energy supplied is lost as heat to the surroundings rather than warming the block, so the real temperature rise is smaller than the energy supplied would give. But the calculation still credits all of the supplied energy to the block, so dividing that full energy by the smaller rise makes the measured c come out too high. The error can be reduced by lagging the block well to cut heat loss, and by starting near room temperature so there is a smaller temperature difference driving the loss. Using the gradient of a temperature-time graph also helps.",
        marks: [
          "Some energy is lost to the surroundings, not to the block, yet all of it is credited to the block.",
          "Dividing the full supplied energy by the smaller temperature rise makes the measured c too high.",
          "Reduce it by lagging well and starting near room temperature (or fitting a lid).",
        ],
        ask: "Think about where the supplied energy goes, how that affects the temperature rise, and how lagging helps.",
      },
      {
        kind: "open",
        prompt: "In the method of mixtures, a hot metal block is dropped into cold water in a calorimeter. Explain the energy transfer that lets you find the metal's specific heat capacity, and give one precaution taken.",
        figure: "fig-pr4-07-method-of-mixtures",
        modelAnswer: "By conservation of energy, the heat lost by the hot metal as it cools equals the heat gained by the water and the calorimeter as they warm, once thermal equilibrium is reached. Writing heat lost by the metal equal to heat gained by the water and calorimeter gives an equation you can solve for the metal's specific heat capacity. A key precaution is to transfer the metal quickly so it loses little heat on the way, and to stir the water so its temperature is even. Lagging the calorimeter or fitting a lid also reduces heat loss.",
        marks: [
          "By conservation of energy, heat lost by the metal = heat gained by the water and calorimeter.",
          "This energy balance is solved for the metal's specific heat capacity.",
          "A precaution: transfer the metal quickly and stir (or lag the calorimeter).",
        ],
        ask: "Link the heat lost by the metal to the heat gained by the water and calorimeter, and name one thing done to reduce error.",
      },
    ],
  },
];
