import type { Subconcept } from "@/lib/teaching/subconcepts";

export const BOXES: Subconcept[] = [
  {
    id: "t2.6-1",
    code: "T2.6a",
    title: "Reading a displacement-time graph",
    blurb: "Displacement up the side, time along the bottom, gradient is velocity",
    steps: [
      {
        kind: "concept",
        heading: "What it shows",
        body: "A *displacement-time graph* shows how the displacement of an object changes with time. Displacement is on the *y-axis* and time is on the *x-axis*. The object moves in a straight line from a fixed starting point called the *origin*.",
        say: "A displacement-time graph is a simple picture of a journey. The height of the line tells you how far the object is from where it started, and moving right along the bottom means time is passing. That starting point is called the origin.",
      },
      {
        kind: "concept",
        heading: "Gradient is velocity",
        figure: "fig-02-13-dt-gradient",
        body: "The *gradient*, or *slope*, of the line is the *velocity* of the object. gradient = (d_2 - d_1) / (t_2 - t_1) = velocity. So a steady slope means a steady velocity.",
        say: "Look at the diagram. The blue line climbs steadily across the graph, with displacement up the side and time along the bottom, and the grey dashed lines mark out a triangle on it: the rise is d two minus d one, and the run is t two minus t one. Here is the key idea. The steepness of that line is the velocity. You work it out as the change in displacement divided by the change in time, which is just the rise over the run of that triangle. So reading velocity off this graph is the same as reading a slope.",
      },
      {
        kind: "choice",
        question: "On a displacement-time graph, what does the gradient of the line represent?",
        options: [
          "The acceleration",
          "The velocity",
          "The total distance",
          "The time taken",
        ],
        correct: 1,
        ask: "Gradient is change in displacement over change in time. Which quantity is that?",
        hints: [
          "Displacement divided by time gives velocity.",
          "The slope tells you how fast the displacement is changing.",
        ],
        explain: "The gradient is the velocity, because it is the change in displacement divided by the change in time.",
      },
      {
        kind: "choice",
        question: "A displacement-time line rises steadily from 0 m to 5 m in 2 s. What is the velocity?",
        options: [
          "10 m/s",
          "3 m/s",
          "2.5 m/s",
          "0.4 m/s",
        ],
        correct: 2,
        ask: "Take the rise in displacement over the time. Five metres over two seconds. Which option is that?",
        hints: [
          "Velocity is the gradient, rise over run.",
          "Five divided by two is two point five.",
        ],
        explain: "The velocity is two point five metres per second, because five metres divided by two seconds is two point five.",
      },
      {
        kind: "slider",
        prompt: "A displacement-time line rises steadily from 0 m to 12 m in 4 s. Set the slider to the velocity in m/s.",
        min: 0,
        max: 10,
        step: 1,
        unit: "m/s",
        start: 0,
        targetMin: 3,
        targetMax: 3,
        ask: "Velocity is the gradient. Twelve metres over four seconds. Slide to that value.",
        hints: [
          "Divide the rise in displacement by the time.",
          "Twelve divided by four is three.",
        ],
        explain: "The velocity is three metres per second, because twelve metres divided by four seconds is three.",
      },
      {
        kind: "order",
        prompt: "Put the steps to find a velocity from a displacement-time graph in order.",
        items: [
          "Read the change in displacement off the y-axis",
          "Read the matching change in time off the x-axis",
          "Divide the change in displacement by the change in time",
          "State the answer in metres per second",
        ],
        explain: "Read the rise in displacement, read the run in time, divide displacement by time to get the gradient, then state the velocity in metres per second.",
        ask: "You need both a rise and a run before you can divide. Put the steps in order.",
        hints: [
          "Gradient is rise over run.",
          "You need the change in time before you can divide.",
        ],
      },
    ],
  },
  {
    id: "t2.6-2",
    code: "T2.6b",
    title: "Sign, height and steepness",
    blurb: "Positive slope goes forward, height is distance from origin, steeper means faster",
    steps: [
      {
        kind: "concept",
        heading: "Sign of the gradient",
        body: "A *positive gradient* means the object moves *forward*, away from the origin, so the velocity is positive. A *negative gradient* means the object moves *backward*, towards the origin, so the velocity is negative.",
        say: "The direction of the slope tells you which way the object goes. A line climbing upward means it is heading away from the start, which we call positive. A line sloping downward means it is coming back towards the start, which we call negative.",
      },
      {
        kind: "concept",
        heading: "Height and the axis",
        body: "The *vertical height* of the line gives the object's *distance from the origin* at that moment. When the line touches the *time-axis* again, the object is back at the origin, so its displacement is *0*.",
        say: "Look at how high the line sits. That height is exactly how far the object is from where it started. And when the line drops back down and touches the bottom axis, the object has returned to the origin, so its displacement is zero again.",
      },
      {
        kind: "concept",
        heading: "Steeper means faster",
        figure: "fig-02-15-dt-steeper",
        body: "The *steeper* the line, the *greater the velocity*. A *gentle slope* is a slow object and a *steep slope* is a fast one. Two lines can both go forward, but the steeper one is quicker.",
        say: "Look at the diagram. Two straight lines start from the same corner of the graph: the blue line, labelled A, shoots up steeply, while the yellow line, labelled B, climbs at a much gentler angle. Steepness is speed here. The steep blue line belongs to a fast object, while the lazy yellow slope belongs to a slow one. So when you compare two forward lines, just look at which one is steeper to see which is faster. Here, A is faster than B.",
      },
      {
        kind: "choice",
        question: "A displacement-time line has a negative gradient. What is the object doing?",
        options: [
          "Moving forward, away from the origin",
          "Moving backward, towards the origin",
          "Staying at rest",
          "Speeding up away from the origin",
        ],
        correct: 1,
        ask: "A downward slope means the displacement is shrinking. Which way is that?",
        hints: [
          "A negative gradient means the displacement is decreasing.",
          "Shrinking displacement means heading back to the start.",
        ],
        explain: "A negative gradient means the object moves backward, towards the origin, so its velocity is negative.",
      },
      {
        kind: "choice",
        question: "Two straight displacement-time lines both slope up, but line P is steeper than line Q. What does this tell you?",
        options: [
          "P has the greater velocity",
          "Q has the greater velocity",
          "They have the same velocity",
          "Q is moving backward",
        ],
        correct: 0,
        ask: "Steeper means a bigger gradient. A bigger gradient means what?",
        hints: [
          "The gradient is the velocity.",
          "The steeper line has the larger velocity.",
        ],
        explain: "P has the greater velocity, because a steeper line has a larger gradient and the gradient is the velocity.",
      },
      {
        kind: "graphpick",
        prompt: "Which displacement-time graph shows an object that leaves the origin and later returns to it?",
        yLabel: "d",
        xLabel: "t",
        options: [
          { points: [[0, 0], [2, 6], [4, 0]], caption: "up then back down to the axis" },
          { points: [[0, 0], [4, 8]], caption: "straight line climbing up" },
          { points: [[0, 4], [4, 4]], caption: "flat line above the axis" },
        ],
        correct: 0,
        ask: "Returning to the origin means the line has to touch the time-axis again. Which graph does that?",
        hints: [
          "At the origin the displacement is zero.",
          "Look for the line that comes back down to the bottom axis.",
        ],
        explain: "The first graph rises and then falls back to the time-axis, so the object leaves the origin and returns to it when the displacement is zero again.",
      },
      {
        kind: "match",
        prompt: "Match each displacement-time feature to what it tells you.",
        pairs: [
          { left: "Vertical height of the line", right: "Distance from the origin now" },
          { left: "Line touches the time-axis", right: "Back at the origin" },
          { left: "Steeper slope", right: "Greater velocity" },
        ],
        explain: "The height is the distance from the origin, touching the time-axis means back at the origin, and a steeper slope is a greater velocity.",
        ask: "Think about what each part of the line is telling you. Match each feature to its meaning.",
        hints: [
          "The height measures how far from the start the object is.",
          "The bottom axis is where displacement is zero.",
        ],
      },
    ],
  },
  {
    id: "t2.6-3",
    code: "T2.6c",
    title: "Shapes: moving forward",
    blurb: "Flat, straight and curved lines while an object heads away from the origin",
    steps: [
      {
        kind: "concept",
        heading: "Flat line: at rest",
        body: "A *horizontal line* means the displacement stays the same. The object is *not moving*, so its *velocity is zero*. It simply sits at a fixed distance from the origin.",
        say: "A flat line is the easiest one. If the height never changes, the object is standing still. Its velocity is zero, and it just waits at the same distance from the start.",
      },
      {
        kind: "concept",
        heading: "Straight slope: constant velocity",
        body: "A *straight line* with a *positive slope* means the displacement increases uniformly. The object moves away from the origin at a *constant*, or *uniform*, velocity.",
        say: "A straight, sloping line means steady progress. The displacement grows by the same amount each second, so the velocity never changes. We call that constant or uniform velocity.",
      },
      {
        kind: "concept",
        heading: "Curves: changing velocity",
        figure: "fig-02-16-dt-forward-types",
        body: "A *curve getting steeper* means the velocity is *increasing*, because the displacement grows faster and faster. A *curve getting less steep* means the velocity is *decreasing*, because the displacement grows more and more slowly.",
        say: "Look at the diagram. Four little graphs sit side by side, each with a blue line: a flat line for staying still, a straight slope for steady velocity, a curve that bends upward and gets steeper, and a curve that rises quickly then levels off. The two curves are the interesting ones, because curves mean the speed is changing. If the line gets steeper, the object is speeding up. If it bends over and gets gentler, the object is slowing down, even though it is still moving forward the whole time.",
      },
      {
        kind: "choice",
        question: "A displacement-time graph is a horizontal line. What is the object doing?",
        options: [
          "Moving forward at constant velocity",
          "Speeding up",
          "At rest",
          "Moving back to the origin",
        ],
        correct: 2,
        ask: "A flat line means the displacement is not changing at all. What does that mean for the object?",
        hints: [
          "No change in displacement means no movement.",
          "A stationary object has zero velocity.",
        ],
        explain: "The object is at rest, because a horizontal line means the displacement stays the same and the velocity is zero.",
      },
      {
        kind: "graphpick",
        prompt: "Which displacement-time graph shows an object moving forward with a constant velocity?",
        yLabel: "d",
        xLabel: "t",
        options: [
          { points: [[0, 2], [4, 2]], caption: "flat line" },
          { points: [[0, 0], [4, 8]], caption: "straight line sloping up" },
          { points: [[0, 0], [2, 1], [4, 8]], caption: "curve getting steeper" },
        ],
        correct: 1,
        ask: "Constant velocity means the displacement grows by the same amount each second. What shape is that?",
        hints: [
          "Uniform velocity is a straight, sloping line.",
          "A flat line is at rest and a curve is a changing velocity.",
        ],
        explain: "A straight line sloping up shows a constant velocity: the displacement increases by the same amount every second.",
      },
      {
        kind: "match",
        prompt: "Match each forward displacement-time shape to the motion it describes.",
        pairs: [
          { left: "Horizontal line", right: "At rest, zero velocity" },
          { left: "Straight positive slope", right: "Constant velocity" },
          { left: "Curve getting steeper", right: "Increasing velocity" },
          { left: "Curve getting less steep", right: "Decreasing velocity" },
        ],
        explain: "A horizontal line is at rest, a straight slope is constant velocity, a curve getting steeper is increasing velocity, and a curve getting less steep is decreasing velocity.",
        ask: "Picture how the slope changes in each case. Match each shape to its motion.",
        hints: [
          "A flat line has no slope, so no velocity.",
          "A steeper curve means a faster and faster object.",
        ],
      },
    ],
  },
  {
    id: "t2.6-4",
    code: "T2.6d",
    title: "Shapes: moving back",
    blurb: "Falling lines that bring an object back towards the origin",
    steps: [
      {
        kind: "concept",
        heading: "Straight fall: constant velocity back",
        body: "A straight line with a *negative slope* means the displacement *decreases uniformly*. The object moves at a *constant velocity* towards the origin. It gets closer to the start by the same amount each second.",
        say: "When the line falls in a straight line, the object is heading home at a steady pace. The displacement shrinks by the same amount each second, so this is a constant velocity, just pointed back towards the origin.",
      },
      {
        kind: "concept",
        heading: "The two backward curves",
        body: "A *downward curve getting steeper* means a *non-uniform velocity* that is *increasing* towards the origin. A *downward curve getting less steep* means a non-uniform velocity that is *decreasing* towards the origin.",
        say: "Backward curves work just like the forward ones, but flipped. If the falling line keeps getting steeper, the object rushes back faster and faster. If it flattens out as it falls, it is easing to a stop as it nears the start.",
      },
      {
        kind: "insight",
        body: "For every *forward shape* there is a matching *backward shape*. The only difference is that the line *falls* instead of *rises*, so the velocity points towards the origin instead of away from it.",
        say: "Here is a handy way to remember it. The backward graphs mirror the forward ones. Whatever the shape tells you about speeding up or slowing down still holds. The single change is the direction: the object is now travelling back towards where it started.",
      },
      {
        kind: "choice",
        question: "A displacement-time line falls in a straight line back to the time-axis. What is the motion?",
        options: [
          "Constant velocity towards the origin",
          "Increasing velocity away from the origin",
          "At rest",
          "Decreasing velocity away from the origin",
        ],
        correct: 0,
        ask: "A straight falling line has a steady negative slope. What kind of velocity is that, and which way?",
        hints: [
          "A straight line means the velocity is constant.",
          "A falling line points back towards the origin.",
        ],
        explain: "It is a constant velocity towards the origin, because a straight negative slope means the displacement decreases by the same amount each second.",
      },
      {
        kind: "graphpick",
        prompt: "Which displacement-time graph shows an object returning to the origin at a constant velocity?",
        yLabel: "d",
        xLabel: "t",
        options: [
          { points: [[0, 8], [4, 0]], caption: "straight line falling to the axis" },
          { points: [[0, 8], [4, 8]], caption: "flat line" },
          { points: [[0, 0], [4, 8]], caption: "straight line climbing up" },
        ],
        correct: 0,
        ask: "Returning at constant velocity means a straight line falling towards the time-axis. Which graph is that?",
        hints: [
          "Constant velocity is a straight line.",
          "Returning to the origin means the line drops to the bottom axis.",
        ],
        explain: "A straight line falling to the time-axis shows a constant velocity towards the origin, ending back at the start.",
      },
      {
        kind: "match",
        prompt: "Match each falling displacement-time shape to the motion towards the origin.",
        pairs: [
          { left: "Straight negative slope", right: "Constant velocity back" },
          { left: "Downward curve getting steeper", right: "Increasing velocity back" },
          { left: "Downward curve getting less steep", right: "Decreasing velocity back" },
        ],
        explain: "A straight fall is a constant velocity back, a steepening fall is an increasing velocity back, and a flattening fall is a decreasing velocity back.",
        ask: "Every falling line heads towards the origin. Match each shape to how its velocity changes.",
        hints: [
          "A straight line always means a constant velocity.",
          "A steepening curve means the object is speeding up.",
        ],
      },
    ],
  },
];
