import type { Subconcept } from "@/lib/teaching/subconcepts";

export const BOXES: Subconcept[] = [
  {
    id: "t2.7-1",
    code: "T2.7a",
    title: "Reading a velocity-time graph",
    blurb: "Velocity on the y-axis, and the gradient is the acceleration",
    steps: [
      {
        kind: "concept",
        heading: "Axes and direction",
        figure: "fig-02-23-vt-positive-negative",
        body: "On a *velocity-time graph*, velocity is on the y-axis and time is on the x-axis. A line above the time-axis is *positive velocity*, moving forward. A line below the axis is *negative velocity*, moving backward.",
        say: "Look at the diagram. Velocity goes up the side with a plus sign near the top and a minus sign near the bottom, and the time axis cuts across the middle at 0: the blue label above the axis reads positive velocity, moving forward, and the red label below it reads negative velocity, moving backward. That is the whole trick to reading this graph. When the line sits above the axis the object is moving forward. When it drops below the axis it is moving backward. The sign is telling you the direction.",
      },
      {
        kind: "concept",
        heading: "Gradient is acceleration",
        figure: "fig-02-24-vt-gradient",
        body: "The *gradient*, or steepness, of a *velocity-time graph* is the *acceleration*. You find it as the change in velocity divided by the change in time: (v_2 - v_1) / (t_2 - t_1).",
        say: "Look at the diagram. The blue line climbs steadily, with velocity up the side and time along the bottom, and the grey dashed lines mark out a triangle on it: the rise is v 2 minus v 1, and the run is t 2 minus t 1. Here is the key idea. The slope of this line is the acceleration. You take how much the velocity changed and divide by how long it took, the rise over the run. A steeper line means a bigger acceleration.",
      },
      {
        kind: "choice",
        question: "A velocity-time graph rises in a straight line from 0 to 30 m/s in 15 s. What is the acceleration?",
        options: ["2 m/s^2", "0.5 m/s^2", "45 m/s^2", "450 m/s^2"],
        correct: 0,
        ask: "The gradient is the change in velocity over the time. 30 minus 0 is 30, then divide by 15. Which option is that?",
        hints: [
          "Acceleration is the gradient: change in velocity divided by change in time.",
          "30 divided by 15 is 2.",
        ],
        working: [
          { label: "Formula", latex: "a = \\dfrac{v - u}{t}" },
          { label: "Substitute", latex: "a = \\dfrac{30 - 0}{15}" },
          { label: "Answer", latex: "a = 2\\ \\text{m/s}^2" },
        ],
        explain: "The acceleration is 2 metres per second squared, because the velocity climbs by 30 over 15 seconds, and 30 divided by 15 is 2.",
      },
      {
        kind: "choice",
        question: "On a velocity-time graph, what does a line drawn below the time-axis mean?",
        options: [
          "The object is speeding up",
          "The object is moving backward",
          "The object is at rest",
          "The object has zero acceleration",
        ],
        correct: 1,
        ask: "Below the axis the velocity has a negative sign. What does a negative velocity tell you about the direction?",
        hints: [
          "A negative velocity points the opposite way.",
          "Below the axis means the object moves backward.",
        ],
        explain: "A line below the time-axis means negative velocity, so the object is moving backward, in the opposite direction.",
      },
      {
        kind: "spoterror",
        prompt: "A student finds the acceleration from a velocity-time graph that rises from 0 to 30 m/s in 15 s. Tap the line with the mistake.",
        lines: [
          "v_1 = 0 m/s, v_2 = 30 m/s, t = 15 s",
          "gradient = (v_2 - v_1) / t",
          "gradient = (30 - 0) / 15",
          "gradient = 30 / 15 = 3 m/s^2",
        ],
        errorLine: 3,
        ask: "Check the last line. 30 divided by 15. Is that 3?",
        hints: [
          "Work out 30 divided by 15.",
          "30 divided by 15 is 2, not 3.",
        ],
        working: [
          { label: "Formula", latex: "a = \\dfrac{v - u}{t}" },
          { label: "Substitute", latex: "a = \\dfrac{30 - 0}{15}" },
          { label: "Answer", latex: "a = 2\\ \\text{m/s}^2" },
        ],
        explain: "The last line is wrong: 30 divided by 15 is 2, so the acceleration is 2 metres per second squared.",
      },
      {
        kind: "insight",
        body: "A *velocity-time graph* packs in two things at once: the height tells you the *velocity*, and the slope tells you the *acceleration*.",
        say: "So keep this in mind. On a velocity against time graph, how high the line sits gives the velocity, while how steep it is gives the acceleration. 2 readings from one line.",
      },
    ],
  },
  {
    id: "t2.7-2",
    code: "T2.7b",
    title: "Area = displacement",
    blurb: "The area under the line is the displacement",
    steps: [
      {
        kind: "concept",
        heading: "Area under the line",
        figure: "fig-02-25-vt-area",
        body: "The *area* between the velocity-time line and the time-axis is the *displacement*. For a straight line you split the area into *triangles* and *rectangles* and add them up.",
        say: "Look at the diagram. The blue line slopes down to the time axis and shades in a blue triangle above it, then carries on below the axis and shades a pink triangle underneath. Here is the lovely trick. The area trapped between the line and the axis is the displacement. The blue triangle above the axis is forward displacement, the pink one below is backward displacement, and you find each one just by working out the area of the shape.",
      },
      {
        kind: "concept",
        heading: "Below the axis is negative",
        body: "Area above the time-axis is a *positive*, forward *displacement*. Area below the axis is a *negative*, backward displacement. When the line touches the axis the velocity is zero, so the object is momentarily *at rest*.",
        say: "Watch the sign. Area above the axis counts as forward displacement, and area below it counts as backward displacement. And the moment the line touches the axis, the velocity is 0, so the object is briefly at rest.",
      },
      {
        kind: "choice",
        question: "A velocity-time graph rises in a straight line from 0 to 30 m/s over 15 s. What displacement does the triangle under it give?",
        options: ["450 m", "45 m", "225 m", "2 m"],
        correct: 2,
        ask: "The area is a triangle: a half times base times height. A half times 15 times 30. Which option is that?",
        hints: [
          "The area of a triangle is a half times base times height.",
          "A half times 15 times 30 is 225.",
        ],
        working: [
          { label: "Formula", latex: "d = \\tfrac{1}{2} \\times b \\times h" },
          { label: "Substitute", latex: "d = \\tfrac{1}{2} \\times 15 \\times 30" },
          { label: "Answer", latex: "d = 225\\ \\text{m}" },
        ],
        explain: "The displacement is 225 metres, because the triangle area is a half times 15 times 30, which is 225.",
      },
      {
        kind: "choice",
        question: "A train's motion has three parts, with areas of 225 m, 900 m and 225 m under the graph. What is the total displacement?",
        options: ["1125 m", "1350 m", "450 m", "900 m"],
        correct: 1,
        ask: "The total displacement is the whole area, so add the 3 parts. 225 plus 900 plus 225. Which option is that?",
        hints: [
          "Total displacement is the sum of all the areas.",
          "225 plus 900 plus 225 is 1350.",
        ],
        working: [
          { label: "Formula", latex: "d = d_1 + d_2 + d_3" },
          { label: "Substitute", latex: "d = 225 + 900 + 225" },
          { label: "Answer", latex: "d = 1350\\ \\text{m}" },
        ],
        explain: "The total displacement is 1350 metres, because you add the 3 areas: 225 plus 900 plus 225.",
      },
      {
        kind: "tiles",
        prompt: "Build the area of the triangle under a velocity-time line that rises from 0 to 30 m/s in 15 s.",
        tiles: ["1/2", "x", "15", "30", "+", "15"],
        answer: ["1/2", "x", "15", "30"],
        explain: "The triangle area is a half times the base of 15 seconds times the height of 30 metres per second, which is 225 metres.",
        ask: "The area of a triangle is a half times base times height. The base is the time and the height is the velocity. Put the tiles together.",
        hints: [
          "Start with a half.",
          "Then multiply by the base of 15 and the height of 30.",
        ],
      },
      {
        kind: "insight",
        body: "Gradient and area answer different questions. The *gradient* of the line gives the *acceleration*, while the *area* under the line gives the *displacement*.",
        say: "Do not mix these two up. The slope of the line is the acceleration. The area underneath it is the displacement. One is about how fast the velocity changes, the other is about how far the object travels.",
      },
    ],
  },
  {
    id: "t2.7-3",
    code: "T2.7c",
    title: "Shapes: speeding up and slowing down",
    blurb: "Straight lines, curves, and negative slopes",
    steps: [
      {
        kind: "concept",
        heading: "Straight slope, uniform",
        figure: "fig-02-26-vt-accel-types",
        body: "A straight sloping line on a *velocity-time graph* means *constant*, *uniform acceleration*: the velocity gains the same amount each second.",
        say: "Look at the diagram. 4 little velocity time graphs sit in a row, each with a green line: a flat line, a straight rising slope, a curve that gets steeper, and a curve that levels off. Start with the second one, the simplest moving shape. A straight sloping line means the velocity climbs by the same amount every second. That is constant, uniform acceleration.",
      },
      {
        kind: "concept",
        heading: "Curves are non-uniform",
        body: "A curve means *non-uniform acceleration*. A curve getting steeper is acceleration that *increases*. A curve getting less steep is acceleration that *decreases*.",
        say: "Now bend the line into a curve. A curve means the acceleration is changing. If the curve gets steeper the acceleration is growing, and if it gets less steep the acceleration is shrinking.",
      },
      {
        kind: "concept",
        heading: "Negative slope, slowing",
        figure: "fig-02-27-vt-decel-types",
        body: "A line that slopes downward has a *negative gradient*, so the object is *decelerating*. A straight downward slope is *uniform deceleration*; a downward curve is *non-uniform deceleration*.",
        say: "Look at the diagram. All 3 small graphs show a red line heading downhill: the first drops in a dead straight slope, and the other 2 are curves that fall in different ways, one steep at first then flattening out, the other gentle at first then plunging. A downward slope is a negative gradient, so in every panel the object is slowing down. Straight down is steady deceleration, and a downward curve means the deceleration itself is changing.",
      },
      {
        kind: "graphpick",
        prompt: "Which velocity-time graph shows uniform deceleration to rest?",
        yLabel: "v",
        xLabel: "t",
        options: [
          { points: [[0, 8], [4, 0]], caption: "straight line down to zero" },
          { points: [[0, 0], [4, 8]], caption: "straight line up from zero" },
          { points: [[0, 4], [4, 4]], caption: "flat line" },
        ],
        correct: 0,
        ask: "Slowing down means the velocity falls, and to rest means it ends at zero. What shape is that?",
        hints: [
          "Deceleration is a line that slopes downward.",
          "To rest means the line reaches zero velocity.",
        ],
        explain: "A straight line sloping down to zero shows uniform deceleration: the velocity loses the same amount each second until the object stops.",
      },
      {
        kind: "graphpick",
        prompt: "Which velocity-time graph shows acceleration that increases over time?",
        yLabel: "v",
        xLabel: "t",
        options: [
          { points: [[0, 0], [4, 8]], caption: "straight sloping line" },
          { points: [[0, 0], [2, 1], [4, 8]], caption: "curve getting steeper" },
          { points: [[0, 2], [4, 2]], caption: "flat line" },
        ],
        correct: 1,
        ask: "A straight line is steady acceleration. What shape shows the velocity gaining more and more each second?",
        hints: [
          "Increasing acceleration means the slope keeps getting steeper.",
          "A curve that gets steeper shows a growing acceleration.",
        ],
        explain: "A curve that gets steeper shows increasing acceleration: the velocity gains a larger amount in each passing second.",
      },
      {
        kind: "choice",
        question: "A velocity-time graph is a straight line sloping downward. What is the motion?",
        options: [
          "Speeding up at an increasing rate",
          "Constant velocity",
          "Uniform deceleration",
          "At rest",
        ],
        correct: 2,
        ask: "A downward straight line has a steady negative gradient. What kind of motion does a steady negative gradient show?",
        hints: [
          "A downward slope means the object is slowing down.",
          "A straight downward line is a steady, uniform deceleration.",
        ],
        explain: "The motion is uniform deceleration, because the straight downward line means the velocity falls by the same amount each second.",
      },
      {
        kind: "insight",
        body: "Read the shape first. Straight means *uniform*, curved means *non-uniform*; sloping up is *speeding up*, sloping down is *slowing down*.",
        say: "So glance at the shape before anything else. Straight lines are uniform and curves are non-uniform. Uphill means speeding up and downhill means slowing down. The picture tells the story.",
      },
    ],
  },
  {
    id: "t2.7-4",
    code: "T2.7d",
    title: "Speed-time vs velocity-time",
    blurb: "Speed never goes negative, velocity can",
    steps: [
      {
        kind: "concept",
        heading: "Speed cannot be negative",
        body: "Speed is a *scalar*, so it has size only and can never be *negative*. A *speed-time graph* always stays on or above the time-axis, at zero or higher.",
        say: "Remember that speed is a scalar with no direction. It is always 0 or more. So a speed against time graph can never dip below the axis. It simply cannot go negative.",
      },
      {
        kind: "concept",
        heading: "Velocity can be negative",
        body: "Velocity is a *vector*, so a *negative* sign shows motion in the opposite direction. A *velocity-time graph* can dip below the time-axis, but a speed-time graph cannot.",
        say: "Velocity is different. It is a vector, so a minus sign just means the object is now going the other way. That is why a velocity graph can drop below the axis while a speed graph never does.",
      },
      {
        kind: "concept",
        heading: "The ball thrown up",
        figure: "fig-02-30-ball-thrown",
        body: "Take *upward as positive*. As the ball rises it slows to zero at the top. As it falls, the *speed-time graph* rises again from zero, but the *velocity-time graph* goes *negative*, because the ball now moves downward.",
        say: "Look at the diagram. On the left, the blue ball is drawn at 3 moments with yellow arrows for its velocity: at A it moves up at 5 metres per second, at B it hangs at the top with 0 velocity, and at C it falls at 5 metres per second. Next to it, the blue speed time graph dips to 0 and climbs back up in a V shape, but the velocity time graph is one straight line that crosses the axis, shaded blue above and pink below. That is the whole story of a ball thrown straight up, with up as positive. Going up it slows to a stop at the top. Coming down, the speed graph climbs back up from 0, but on the velocity graph the line goes below the axis, because the ball is now heading the opposite way.",
      },
      {
        kind: "choice",
        question: "A ball is thrown straight up and falls back. On the way down, what happens on the velocity-time graph, taking up as positive?",
        options: [
          "The line stays above the axis",
          "The line goes below the axis",
          "The line is flat at the top value",
          "The line disappears",
        ],
        correct: 1,
        ask: "On the way down the ball moves the opposite way to the throw. With up as positive, what sign is downward velocity, and where does that put the line?",
        hints: [
          "Downward motion is negative when up is positive.",
          "A negative velocity puts the line below the axis.",
        ],
        explain: "The line goes below the axis, because on the way down the velocity is negative, showing the ball now moves in the opposite direction.",
      },
      {
        kind: "choice",
        question: "For the same ball thrown up and caught again, what does its speed-time graph do?",
        options: [
          "It goes negative on the way down",
          "It stays at or above zero the whole time",
          "It stays flat throughout",
          "It ends below where it started",
        ],
        correct: 1,
        ask: "Speed is a scalar with size only. Can a speed-time graph ever dip below the axis?",
        hints: [
          "Speed can never be negative.",
          "A speed-time graph stays on or above the time-axis.",
        ],
        explain: "The speed-time graph stays at or above zero the whole time, because speed is a scalar and can never be negative.",
      },
      {
        kind: "classify",
        prompt: "Sort each statement as true of speed or true of velocity.",
        bins: ["Speed", "Velocity"],
        items: [
          { text: "A scalar with size only", bin: 0 },
          { text: "Can be shown as negative", bin: 1 },
          { text: "Its graph never dips below the axis", bin: 0 },
          { text: "A negative sign shows the opposite direction", bin: 1 },
        ],
        explain: "Speed is a scalar that stays zero or positive, while velocity is a vector whose negative sign shows the opposite direction.",
        ask: "If it has size only and never goes negative it is speed. If it can carry a direction and a negative sign it is velocity. Sort each one.",
        hints: [
          "Speed is a scalar and never negative.",
          "Only velocity can be negative, to show the opposite direction.",
        ],
      },
      {
        kind: "insight",
        body: "For motion that reverses, distance and *speed* keep piling up, but *displacement* and *velocity* can cancel back toward zero.",
        say: "One closing thought. When motion doubles back, like the ball returning to your hand, the distance and speed keep adding up, yet the displacement and velocity can cancel out to zero. Direction is the difference.",
      },
    ],
  },
];
