import type { Subconcept } from "@/lib/teaching/subconcepts";

// T5 Pressure, topical quiz. Whole-topic check across KB Chapter 06 (Pressure, including
// density): pressure P = F / A and area, density rho = m / V with unit conversion and
// floating/sinking, pressure in a liquid P = h rho g with depth (not shape) and jets, total
// pressure with the atmosphere, Pascal's principle and the hydraulic press F1/A1 = F2/A2,
// atmospheric pressure and the mercury barometer, and the manometer with two-liquid balance.
// Figure colours follow the T5 key: applied/input force and atmospheric-pressure arrows = yellow,
// output force F2 = green, weight/load = pink, liquid/mercury/oil/water jets = blue, tanks/tubes/
// pistons/reservoirs and dimension/depth guides = grey, solid object/block = white.

export const BOXES: Subconcept[] = [
  {
    id: "t5.quiz",
    code: "Quiz",
    title: "Pressure topical quiz",
    blurb: "Whole-topic check: pressure, density, liquid pressure, hydraulics, atmospheric pressure, manometer",
    kind: "quiz",
    steps: [
      {
        kind: "choice",
        question: "Why does a sharp knife cut more easily than a blunt one, for the same pushing force?",
        options: [
          "Its thin edge is a small area, so the pressure is greater",
          "Its thin edge is a large area, so the pressure is greater",
          "A sharp knife exerts a larger force",
          "A sharp knife has less weight",
        ],
        correct: 0,
        ask: "Pressure is the force spread over the area in contact. For the same push, what does a smaller area do to the pressure?",
        hints: [
          "Pressure is force divided by area.",
          "A thin edge is a very small area, so the same force gives a much greater pressure.",
        ],
        explain: "The thin edge is a very small area, so for the same pushing force the pressure is much greater, and that high pressure cuts through the material. Pressure is force divided by area.",
      },
      {
        kind: "choice",
        question: "A crate weighs 540 N and stands on a base of area 0.90 m^2. Find the pressure it exerts on the floor.",
        options: ["600 Pa", "486 Pa", "540 Pa", "0.0017 Pa"],
        correct: 0,
        ask: "Pressure is force divided by area, so work out 540 divided by 0.90.",
        hints: [
          "Use P equals F divided by A.",
          "540 divided by 0.90 is 600, and pressure is measured in pascals.",
        ],
        working: [
          { label: "Formula", latex: "P = \\dfrac{F}{A}" },
          { label: "Substitute", latex: "P = \\dfrac{540}{0.90}" },
          { label: "Answer", latex: "P = 600\\ \\text{Pa}" },
        ],
        explain: "The pressure is 600 pascals, because 540 newtons divided by 0.90 metres squared is 600 pascals.",
      },
      {
        kind: "spoterror",
        prompt: "A force of 10 N acts on an area of 2 cm^2. Here is a student's working to find the pressure. Tap the line with the mistake.",
        lines: [
          "A = 2\\ \\text{cm}^2 = 0.0002\\ \\text{m}^2",
          "P = \\dfrac{F}{A}",
          "P = \\dfrac{10}{2}",
          "P = 5\\ \\text{Pa}",
        ],
        errorLine: 2,
        ask: "Check that the area used in the division is in metres squared, not centimetres squared.",
        hints: [
          "The area was correctly converted to 0.0002 metres squared on the first line.",
          "The division should use 0.0002, not 2, so it is 10 divided by 0.0002, which is 50000 pascals.",
        ],
        working: [
          { label: "Formula", latex: "P = \\dfrac{F}{A}" },
          { label: "Substitute", latex: "P = \\dfrac{10}{0.0002}" },
          { label: "Answer", latex: "P = 50000\\ \\text{Pa}" },
        ],
        explain: "The mistake is on the line P equals 10 divided by 2. The area must be in metres squared, so it should be 10 divided by 0.0002, which is 50000 pascals, not 5 pascals.",
      },
      {
        kind: "open",
        prompt: "Explain why a person wearing skis does not sink into soft snow, while the same person in normal shoes sinks in. Use the idea of pressure.",
        figure: "fig-06-01-force-area-blocks",
        modelAnswer: "Pressure is the force acting on each unit of area, P = F/A. The person's weight is the same in both cases, but skis spread that weight over a much larger area. A larger area gives a smaller pressure on the snow, so the skis do not sink. Normal shoes have a small area, so the same weight gives a much greater pressure and the person sinks in.",
        marks: [
          "Pressure is force divided by area, P = F/A.",
          "The weight (force) is the same in both cases.",
          "Skis have a larger area, so a smaller pressure; shoes have a small area, so a greater pressure.",
        ],
        ask: "Compare the area in contact with the snow in each case, and link a larger area to a smaller pressure for the same weight.",
      },
      {
        kind: "choice",
        question: "A solid object is placed in a liquid. It will float if...",
        options: [
          "its density is less than the density of the liquid",
          "its density is greater than the density of the liquid",
          "its mass is less than the mass of the liquid",
          "its volume is greater than the volume of the liquid",
        ],
        correct: 0,
        ask: "Floating depends on how the object's density compares with the liquid's density. Which comparison makes it float?",
        hints: [
          "Compare the density of the object with the density of the liquid.",
          "An object floats when its density is less than the density of the liquid.",
        ],
        explain: "An object floats when its density is less than the density of the liquid, and sinks when its density is greater. It is the densities that matter, not the masses or volumes on their own.",
      },
      {
        kind: "tiles",
        prompt: "A metal has mass 0.45 kg and volume 18 x 10^-6 m^3. Build the working line for its density, using rho = m / V.",
        tiles: ["rho =", "0.45", "\\div", "18 \\times 10^-6", "=", "2.5 \\times 10^4", "kg/m^3", "m"],
        answer: ["rho =", "0.45", "\\div", "18 \\times 10^-6", "=", "2.5 \\times 10^4", "kg/m^3"],
        ask: "Density is mass divided by volume, so divide 0.45 by 18 times 10 to the power minus 6.",
        hints: [
          "Use rho equals m divided by V.",
          "0.45 divided by 18 times 10 to the power minus 6 is 2.5 times 10 to the power 4, in kilograms per metre cubed.",
        ],
        working: [
          { label: "Formula", latex: "\\rho = \\dfrac{m}{V}" },
          { label: "Substitute", latex: "\\rho = \\dfrac{0.45}{18 \\times 10^{-6}}" },
          { label: "Answer", latex: "\\rho = 2.5 \\times 10^4\\ \\text{kg/m}^3" },
        ],
        explain: "The density is 2.5 times 10 to the power 4 kilograms per metre cubed, because 0.45 kilograms divided by 18 times 10 to the power minus 6 metres cubed is 2.5 times 10 to the power 4.",
      },
      {
        kind: "classify",
        prompt: "The liquid is water of density 1000 kg/m^3. Sort each material by whether it floats on the water or sinks in it.",
        bins: ["Floats on the water", "Sinks in the water"],
        items: [
          { text: "wood, 700 kg/m^3", bin: 0 },
          { text: "ice, 920 kg/m^3", bin: 0 },
          { text: "cooking oil, 800 kg/m^3", bin: 0 },
          { text: "aluminium, 2700 kg/m^3", bin: 1 },
          { text: "iron, 7900 kg/m^3", bin: 1 },
          { text: "glass, 2500 kg/m^3", bin: 1 },
        ],
        ask: "Compare each density with the 1000 kilograms per metre cubed of water. Less than that floats, more than that sinks. Tap each material and drop it in its bin.",
        hints: [
          "A material floats if its density is less than 1000 kilograms per metre cubed.",
          "Wood, ice and oil are below 1000, so they float; aluminium, iron and glass are above 1000, so they sink.",
        ],
        explain: "Wood at 700, ice at 920 and oil at 800 kilograms per metre cubed are all less dense than water, so they float. Aluminium at 2700, iron at 7900 and glass at 2500 are all denser than water, so they sink.",
      },
      {
        kind: "open",
        prompt: "A block of wood floats on water but a steel nail sinks. Explain this using the idea of density.",
        modelAnswer: "An object floats if its density is less than the density of the liquid, and sinks if its density is greater. Wood has a density less than that of water, about 1000 kilograms per metre cubed, so it floats. Steel has a density much greater than water, so the nail sinks. Density is the mass per unit volume, rho = m/V.",
        marks: [
          "An object floats if its density is less than the liquid's, and sinks if it is greater.",
          "Wood has a lower density than water, so it floats.",
          "Steel has a higher density than water, so it sinks.",
        ],
        ask: "Compare the density of each object with the density of water, and say what decides floating or sinking.",
      },
      {
        kind: "choice",
        question: "3 connected vessels of different shapes hold the same liquid. At the same depth below the surface, the pressure is...",
        figure: "fig-06-05-same-level-pressure",
        options: [
          "the same in every vessel, because pressure depends on depth not shape",
          "greatest in the widest vessel",
          "greatest in the narrowest vessel",
          "different in every vessel",
        ],
        correct: 0,
        ask: "Pressure in a liquid depends only on the depth, not on the shape or width of the container. What does that mean at the same depth?",
        hints: [
          "Pressure in a liquid depends on depth, not shape.",
          "At the same depth the pressure is the same in every vessel, however wide or narrow.",
        ],
        explain: "The pressure is the same in every vessel at the same depth, because pressure in a liquid depends on the depth, not on the shape or width of the container.",
      },
      {
        kind: "choice",
        question: "A flat plate lies 4.0 m below the surface of water of density 1000 kg/m^3 (g = 10 N/kg). Find the pressure of the water on it.",
        options: ["40000 Pa", "4000 Pa", "400 Pa", "14000 Pa"],
        correct: 0,
        ask: "Use pressure equals depth times density times g, so work out 4.0 times 1000 times 10.",
        hints: [
          "Use P equals h rho g.",
          "4.0 times 1000 is 4000, and 4000 times 10 is 40000, in pascals.",
        ],
        working: [
          { label: "Formula", latex: "P = h\\rho g" },
          { label: "Substitute", latex: "P = 4.0 \\times 1000 \\times 10" },
          { label: "Answer", latex: "P = 40000\\ \\text{Pa}" },
        ],
        explain: "The pressure is 40000 pascals, because 4.0 metres times 1000 kilograms per metre cubed times 10 newtons per kilogram is 40000 pascals.",
      },
      {
        kind: "graphpick",
        prompt: "An open tank is filled with water. Which graph best shows how the total pressure in the water changes with depth?",
        xLabel: "depth / m",
        yLabel: "pressure / kPa",
        options: [
          { points: [[0, 100], [1, 110], [2, 120], [3, 130], [4, 140]], caption: "Starts at atmospheric pressure and rises in a straight line" },
          { points: [[0, 0], [1, 10], [2, 20], [3, 30], [4, 40]], caption: "Starts at zero and rises in a straight line" },
          { points: [[0, 100], [1, 100], [2, 100], [3, 100], [4, 100]], caption: "Stays constant with depth" },
          { points: [[0, 100], [1, 104], [2, 116], [3, 136], [4, 164]], caption: "Rises faster and faster with depth" },
        ],
        correct: 0,
        ask: "At the surface the pressure is already the atmospheric pressure, and it then rises steadily as h rho g adds with depth. Which graph starts above zero and rises in a straight line?",
        hints: [
          "The pressure at the surface is atmospheric, not zero, so the line does not start at the origin.",
          "Below that, the pressure rises in a straight line because h rho g increases evenly with depth.",
        ],
        explain: "The correct graph starts at atmospheric pressure at the surface and rises in a straight line, because the total pressure is the atmospheric pressure plus h rho g, and h rho g increases evenly with depth.",
      },
      {
        kind: "choice",
        question: "An object rests at the bottom of an open tank of water. What is the total pressure on it?",
        options: [
          "The atmospheric pressure plus the pressure from the water above it",
          "Only the pressure from the water above it",
          "Only the atmospheric pressure",
          "The atmospheric pressure minus the water pressure",
        ],
        correct: 0,
        ask: "The water is open to the air, so the atmosphere presses on the surface as well. What adds to the water pressure at the bottom?",
        hints: [
          "The air above an open liquid presses down as atmospheric pressure.",
          "The total pressure is the atmospheric pressure plus the pressure from the water above, h rho g.",
        ],
        explain: "The total pressure is the atmospheric pressure plus the pressure from the water above the object. In an open tank the atmosphere presses on the surface, so it adds to the liquid pressure at every depth.",
      },
      {
        kind: "open",
        prompt: "A tall tank of water has 3 small holes at different depths. Explain why the water jet from the lowest hole is the fastest and reaches furthest, and state how the atmosphere adds to the pressure inside the tank.",
        figure: "fig-06-06-tank-jets",
        modelAnswer: "The pressure in a liquid increases with depth, because a greater depth of water above a point has more weight pressing down. The lowest hole is at the greatest depth, so the water pressure there is greatest, P = h rho g, and the jet is fastest and reaches furthest. The pressure acts in all directions, which is why it pushes the water out sideways. In an open tank the total pressure at any point is the atmospheric pressure plus h rho g.",
        marks: [
          "Pressure in a liquid increases with depth, P = h rho g.",
          "The lowest hole is deepest, so the greatest pressure gives the fastest, furthest jet.",
          "The total pressure is the atmospheric pressure plus h rho g, and pressure acts in all directions.",
        ],
        ask: "Link the depth of each hole to the water pressure there, and remember the atmosphere also presses on the surface.",
      },
      {
        kind: "choice",
        question: "A hydraulic press can lift a heavy car with a small input force. Which statement explains why?",
        options: [
          "The pressure is transmitted equally through the liquid, and the large piston has a bigger area",
          "The liquid increases the input force by adding energy",
          "The large piston has a smaller area than the small piston",
          "Liquids can be compressed to store the extra force",
        ],
        correct: 0,
        ask: "A liquid passes on the pressure equally, and pressure is force divided by area. What does a bigger piston area give?",
        hints: [
          "The pressure made by the small piston is transmitted equally through the liquid.",
          "The same pressure acting on a larger piston area gives a larger force.",
        ],
        explain: "The pressure from the small piston is transmitted equally through the liquid, and the large piston has a bigger area, so the same pressure gives a much larger output force. Liquids cannot be compressed, so no force is lost.",
      },
      {
        kind: "slider",
        prompt: "In a hydraulic press an input force of 30 N acts on a small piston of area 3.0 cm^2. The large piston has an area of 60 cm^2. Set the slider to the output force, in newtons.",
        min: 0,
        max: 1000,
        step: 10,
        unit: "N",
        start: 0,
        targetMin: 590,
        targetMax: 610,
        ask: "First find the pressure, 30 divided by 3.0, then multiply by the large area of 60.",
        hints: [
          "The pressure is 30 divided by 3.0, which is 10 newtons per centimetre squared.",
          "10 times 60 is 600, so slide to 600 newtons.",
        ],
        working: [
          { label: "Formula", latex: "\\dfrac{F_1}{A_1} = \\dfrac{F_2}{A_2}" },
          { label: "Substitute", latex: "F_2 = \\dfrac{30}{3.0} \\times 60" },
          { label: "Answer", latex: "F_2 = 600\\ \\text{N}" },
        ],
        explain: "The pressure is 30 divided by 3.0, which is 10 newtons per centimetre squared. On the 60 centimetre squared piston that gives 10 times 60, which is 600 newtons.",
      },
      {
        kind: "choice",
        question: "In a hydraulic press an input force of 40 N acts on a small piston of area 5.0 cm^2. The large piston has an area of 200 cm^2. Find the output force on the load.",
        figure: "fig-06-16-hydraulic-load",
        options: ["1600 N", "8 N", "1000 N", "40 N"],
        correct: 0,
        ask: "First find the pressure, 40 divided by 5.0, then multiply by the large area of 200.",
        hints: [
          "The pressure is 40 divided by 5.0, which is 8 newtons per centimetre squared.",
          "8 times 200 is 1600, so the output force is 1600 newtons.",
        ],
        working: [
          { label: "Formula", latex: "\\dfrac{F_1}{A_1} = \\dfrac{F_2}{A_2}" },
          { label: "Substitute", latex: "F_2 = \\dfrac{40}{5.0} \\times 200" },
          { label: "Answer", latex: "F_2 = 1600\\ \\text{N}" },
        ],
        explain: "The pressure is 40 divided by 5.0, which is 8 newtons per centimetre squared. Acting on the 200 centimetre squared piston, that gives an output force of 8 times 200, which is 1600 newtons.",
      },
      {
        kind: "open",
        prompt: "Explain how a hydraulic press uses Pascal's principle to turn a small input force into a large output force.",
        modelAnswer: "A liquid is almost incompressible, and by Pascal's principle a pressure applied to it is transmitted equally to every part. A small input force F1 on a small piston of area A1 creates a pressure P = F1/A1. This same pressure acts on the large piston of area A2, giving an output force F2 = P times A2. Because A2 is much larger than A1, the output force F2 is much larger than F1, following F1/A1 = F2/A2.",
        marks: [
          "A liquid transmits pressure equally to every part (Pascal's principle).",
          "The input force makes a pressure P = F1/A1 that acts on the large piston.",
          "F1/A1 = F2/A2, so a larger area A2 gives a larger output force F2.",
        ],
        ask: "Track the pressure from the small piston to the large piston, and link the piston areas to the forces.",
      },
      {
        kind: "choice",
        question: "A mercury barometer column is 0.76 m tall. Mercury has density 1.36 x 10^4 kg/m^3 (g = 10 N/kg). Find the atmospheric pressure this represents.",
        options: ["1.03 x 10^5 Pa", "1.03 x 10^4 Pa", "7.6 x 10^4 Pa", "1.36 x 10^5 Pa"],
        correct: 0,
        ask: "Use pressure equals height times density times g, so work out 0.76 times 1.36 times 10 to the power 4, then times 10.",
        hints: [
          "Use P equals h rho g with h equal to 0.76 metres.",
          "0.76 times 1.36 times 10 to the power 4 times 10 is about 1.03 times 10 to the power 5 pascals.",
        ],
        working: [
          { label: "Formula", latex: "P = h\\rho g" },
          { label: "Substitute", latex: "P = 0.76 \\times (1.36 \\times 10^4) \\times 10" },
          { label: "Answer", latex: "P = 1.03 \\times 10^5\\ \\text{Pa}" },
        ],
        explain: "The pressure is about 1.03 times 10 to the power 5 pascals, because 0.76 metres times 1.36 times 10 to the power 4 kilograms per metre cubed times 10 newtons per kilogram is about 1.03 times 10 to the power 5 pascals.",
      },
      {
        kind: "slider",
        prompt: "In a mercury barometer, point B is at the reservoir surface where the pressure is 76 cm Hg. Point C is 4 cm below the reservoir surface. Set the slider to the pressure at C, in cm Hg.",
        min: 0,
        max: 100,
        step: 1,
        unit: "cm Hg",
        start: 0,
        targetMin: 79,
        targetMax: 81,
        ask: "Going down in the mercury you add the extra height, so add 4 to 76.",
        hints: [
          "Pressure at a point is the vertical height of mercury above it; going down you add the depth.",
          "76 plus 4 is 80, so slide to 80 cm Hg.",
        ],
        working: [
          { label: "Formula", latex: "P_C = P_B + h" },
          { label: "Substitute", latex: "P_C = 76 + 4" },
          { label: "Answer", latex: "P_C = 80\\ \\text{cm Hg}" },
        ],
        explain: "The pressure at C is 80 cm Hg, because C is 4 centimetres below the reservoir level, so you add 4 to the 76 cm Hg there.",
      },
      {
        kind: "order",
        prompt: "Put these steps for setting up a simple mercury barometer in the correct order.",
        items: [
          "Fill a long glass tube completely with mercury",
          "Cover the open end and turn the tube upside down into a dish of mercury",
          "Uncover the end while it is below the mercury surface",
          "The mercury falls a little, leaving a vacuum at the sealed top",
          "Atmospheric pressure holds up a mercury column about 76 cm tall",
        ],
        ask: "Start by filling the tube, and finish with the column that the air holds up. Put the steps in order.",
        hints: [
          "You must fill and invert the tube before the mercury can settle.",
          "The mercury falls to leave a vacuum at the top, and then the air holds up a column about 76 centimetres tall.",
        ],
        explain: "First fill the tube with mercury, then invert it into a dish of mercury and uncover the end below the surface. The mercury falls a little, leaving a vacuum at the sealed top, and atmospheric pressure holds up a column about 76 centimetres tall.",
      },
      {
        kind: "open",
        prompt: "Describe how a simple mercury barometer measures atmospheric pressure, and explain why mercury is used rather than water.",
        modelAnswer: "A glass tube is filled with mercury and inverted into a dish of mercury. The mercury falls a little, leaving a vacuum at the sealed top, and atmospheric pressure pushing down on the mercury in the dish holds up a column about 76 centimetres tall at sea level. The height of the column measures the atmospheric pressure. Mercury is used because it is very dense, so the column is short. Water is much less dense, so a water barometer would need a column about 10 metres tall.",
        marks: [
          "Mercury in an inverted tube leaves a vacuum at the top; atmospheric pressure holds up the column.",
          "The column is about 76 cm tall at sea level, and its height measures atmospheric pressure.",
          "Mercury is very dense, so the column is short; water would need about 10 m.",
        ],
        ask: "Explain what holds the mercury up and what the column height tells you, then compare the density of mercury and water.",
      },
      {
        kind: "choice",
        question: "A manometer is connected to a gas supply. The liquid is pushed higher on the open side than on the gas side. What does this show?",
        options: [
          "The gas pressure is greater than atmospheric pressure",
          "The gas pressure is less than atmospheric pressure",
          "The gas pressure equals atmospheric pressure",
          "The gas has no pressure",
        ],
        correct: 0,
        ask: "The liquid is pushed down on the gas side and up on the open side. Which side has the greater push on the liquid?",
        hints: [
          "The gas pushes the liquid down on its side and up on the open side.",
          "If the open side is higher, the gas pressure must be greater than atmospheric pressure.",
        ],
        explain: "The gas pressure is greater than atmospheric pressure. The gas pushes the liquid down on its side and up on the open side, so the higher open column shows the gas pressure is above atmospheric.",
      },
      {
        kind: "tiles",
        prompt: "In a U-tube, 20 cm of oil of density 800 kg/m^3 balances a height h of water of density 1000 kg/m^3. Build the working line for h, using h_1 rho_1 = h_2 rho_2.",
        tiles: ["h =", "20", "\\times", "800", "\\div", "1000", "=", "16", "cm", "m"],
        answer: ["h =", "20", "\\times", "800", "\\div", "1000", "=", "16", "cm"],
        ask: "At the boundary the pressures balance, so h equals 20 times 800 divided by 1000.",
        hints: [
          "Use h_1 rho_1 equals h_2 rho_2, so h equals 20 times 800 divided by 1000.",
          "20 times 800 is 16000, and 16000 divided by 1000 is 16, in centimetres.",
        ],
        working: [
          { label: "Formula", latex: "h_1 \\rho_1 = h_2 \\rho_2" },
          { label: "Substitute", latex: "h = \\dfrac{20 \\times 800}{1000}" },
          { label: "Answer", latex: "h = 16\\ \\text{cm}" },
        ],
        explain: "The height of water is 16 centimetres, because 20 times 800 divided by 1000 is 16. The denser water needs a shorter column to balance the oil.",
      },
      {
        kind: "cloze",
        prompt: "Complete the sentences about a U-tube manometer connected to a gas supply.",
        segments: [
          "2 points at the ",
          " level in the connected liquid have equal pressure. If the gas pressure is above atmospheric, it pushes the liquid ",
          " on the open side, so the gas pressure equals the atmospheric pressure ",
          " the pressure from the height difference.",
        ],
        bank: ["same", "up", "plus", "different", "down", "minus"],
        answer: ["same", "up", "plus"],
        ask: "Think about points at equal levels, which way the gas pushes the liquid, and whether the height difference adds to or subtracts from the atmospheric pressure.",
        hints: [
          "Points at the same level in a connected liquid have equal pressure.",
          "A gas above atmospheric pushes the liquid up the open side, so the gas pressure is atmospheric plus the height difference.",
        ],
        explain: "2 points at the same level in a connected liquid have equal pressure. A gas above atmospheric pushes the liquid up the open side, so the gas pressure equals the atmospheric pressure plus the pressure from the height difference.",
      },
      {
        kind: "match",
        prompt: "Match each quantity or law to its equation.",
        pairs: [
          { left: "Pressure from a force", right: "P = F / A" },
          { left: "Density of a material", right: "rho = m / V" },
          { left: "Pressure at a depth in a liquid", right: "P = h rho g" },
          { left: "Hydraulic press balance", right: "F_1 / A_1 = F_2 / A_2" },
        ],
        ask: "Match each idea to its formula. One divides force by area, one divides mass by volume, one multiplies depth by density and g, and one balances 2 pressures.",
        hints: [
          "Pressure is force divided by area; density is mass divided by volume.",
          "Pressure at depth is h times rho times g; the hydraulic press balances F_1 over A_1 with F_2 over A_2.",
        ],
        explain: "Pressure from a force is P equals F divided by A. Density is rho equals m divided by V. Pressure at a depth is P equals h rho g. The hydraulic press balances F_1 divided by A_1 with F_2 divided by A_2.",
      },
    ],
  },
];
