import type { Subconcept } from "@/lib/teaching/subconcepts";

// T5 Pressure, Revision 2. Checkpoint over KB Chapter 06, sections t5.4 to t5.6:
// transmission and the hydraulic press, atmospheric pressure and the barometer,
// and the manometer. Question-only. Figures used only on choice and open steps.

export const BOXES: Subconcept[] = [
  {
    id: "t5.rev2",
    code: "R2",
    title: "Revision 2",
    blurb: "Checkpoint: the hydraulic press, atmospheric pressure and the manometer",
    kind: "revision",
    steps: [
      {
        kind: "choice",
        question: "Why can a hydraulic press turn a small input force into a much larger output force?",
        figure: "fig-06-09-hydraulic-press",
        options: [
          "The liquid transmits the pressure equally, and the output piston has a larger area",
          "The liquid compresses and stores extra energy",
          "The output piston is lighter than the input piston",
          "The liquid increases the force as it flows along the tube",
        ],
        correct: 0,
        ask: "The pressure is the same everywhere in the liquid. Think about what that same pressure does when it acts on a piston of larger area.",
        hints: [
          "A liquid is almost incompressible, so a pressure applied at one piston reaches the other piston unchanged.",
          "Force equals pressure times area, so the same pressure on a larger area gives a larger force.",
        ],
        explain: "The liquid transmits the pressure equally to both pistons, and because force is pressure times area, the larger output piston feels a larger force. That is why the press multiplies the force.",
      },
      {
        kind: "choice",
        question: "A hydraulic press has an input force of 40 N pressing on a small piston of area 5.0 cm^2. What pressure is transmitted through the liquid?",
        figure: "fig-06-16-hydraulic-load",
        options: ["8 N/cm^2", "200 N/cm^2", "45 N/cm^2", "0.125 N/cm^2"],
        correct: 0,
        ask: "Pressure is force divided by area, so work out 40 divided by 5.0.",
        hints: [
          "Use P equals F divided by A.",
          "40 divided by 5.0 is 8 newtons per square centimetre.",
        ],
        working: [
          { label: "Formula", latex: "P = \\dfrac{F}{A}" },
          { label: "Substitute", latex: "P = \\dfrac{40}{5.0}" },
          { label: "Answer", latex: "P = 8\\ \\text{N/cm}^2" },
        ],
        explain: "The transmitted pressure is 8 newtons per square centimetre, because 40 newtons divided by 5.0 square centimetres is 8. This same pressure acts on every part of the liquid.",
      },
      {
        kind: "choice",
        question: "Why is mercury, rather than water, used in a barometer?",
        figure: "fig-06-10-barometer",
        options: [
          "It is very dense, so a short column balances the atmosphere",
          "It is cheaper to buy than water",
          "It never evaporates at any temperature",
          "It is a much better electrical conductor",
        ],
        correct: 0,
        ask: "Think about how tall a column of each liquid you would need to balance the same atmospheric pressure, and how that links to density.",
        hints: [
          "The pressure of a column is height times density times g, so a denser liquid needs less height for the same pressure.",
          "Water would need a column about 10 metres tall, while mercury needs only about 0.76 metres.",
        ],
        explain: "Mercury is used because it is very dense, so a column only about 0.76 metres tall balances the atmosphere. Water is far less dense and would need a column about 10 metres tall.",
      },
      {
        kind: "choice",
        question: "In a mercury barometer the atmosphere supports a column of 76 cm Hg. A point C lies 4 cm below the mercury level in the reservoir. What is the pressure at C?",
        options: ["80 cm Hg", "76 cm Hg", "72 cm Hg", "4 cm Hg"],
        correct: 0,
        ask: "At the reservoir surface the pressure is 76 centimetres of mercury. Going 4 centimetres deeper adds to it, so work out 76 plus 4.",
        hints: [
          "Going down in a liquid adds the extra height of liquid above the point.",
          "76 plus 4 is 80 centimetres of mercury.",
        ],
        working: [
          { label: "Formula", latex: "P_C = P_{atm} + h" },
          { label: "Substitute", latex: "P_C = 76 + 4" },
          { label: "Answer", latex: "P_C = 80\\ \\text{cm Hg}" },
        ],
        explain: "The pressure at C is 80 centimetres of mercury, because the reservoir surface is at 76 centimetres of mercury and going 4 centimetres deeper adds 4, giving 80.",
      },
      {
        kind: "choice",
        question: "A mercury barometer reads a vertical column of 0.76 m. Mercury has density 1.36 x 10^4 kg/m^3 and g = 10 N/kg. What is the atmospheric pressure?",
        options: ["1.03 x 10^5 Pa", "1.03 x 10^4 Pa", "7.6 x 10^3 Pa", "1.36 x 10^5 Pa"],
        correct: 0,
        ask: "Use pressure equals height times density times g. Multiply 0.76 by 1.36 times 10 to the power 4, then by 10.",
        hints: [
          "The formula is P equals h times rho times g.",
          "0.76 times 1.36 times 10 to the power 4 times 10 is about 1.03 times 10 to the power 5.",
        ],
        working: [
          { label: "Formula", latex: "P = h \\rho g" },
          { label: "Substitute", latex: "P = 0.76 \\times (1.36 \\times 10^{4}) \\times 10" },
          { label: "Answer", latex: "P = 1.03 \\times 10^{5}\\ \\text{Pa}" },
        ],
        explain: "The atmospheric pressure is about 1.03 times 10 to the power 5 pascals, because 0.76 metres times 1.36 times 10 to the power 4 kilograms per metre cubed times 10 newtons per kilogram is about 1.03 times 10 to the power 5 pascals.",
      },
      {
        kind: "slider",
        prompt: "A hydraulic press transmits a pressure of 8 N/cm^2 to a large piston of area 200 cm^2. Set the slider to the output force on the load, in newtons.",
        min: 0,
        max: 2000,
        step: 10,
        unit: "N",
        start: 0,
        targetMin: 1590,
        targetMax: 1610,
        ask: "The output force is the pressure times the piston area, so work out 8 times 200.",
        hints: [
          "Use force equals pressure times area.",
          "8 times 200 is 1600, so slide to 1600 newtons.",
        ],
        working: [
          { label: "Formula", latex: "F = P \\times A" },
          { label: "Substitute", latex: "F = 8 \\times 200" },
          { label: "Answer", latex: "F = 1600\\ \\text{N}" },
        ],
        explain: "The output force is 1600 newtons, because 8 newtons per square centimetre times 200 square centimetres is 1600 newtons. A 40 newton input has become a 1600 newton lift.",
      },
      {
        kind: "tiles",
        prompt: "A gas raises the open side of a manometer by 9.0 cm above the gas side. Atmospheric pressure is 76 cm Hg. Build the working line that gives the gas pressure, in cm Hg.",
        tiles: ["P_gas =", "76", "+", "9.0", "=", "85", "cm Hg", "-"],
        answer: ["P_gas =", "76", "+", "9.0", "=", "85", "cm Hg"],
        ask: "The gas is above atmospheric, so add the height difference to 76. Work out 76 plus 9.0.",
        hints: [
          "Use gas pressure equals atmospheric pressure plus the height difference h.",
          "76 plus 9.0 is 85 centimetres of mercury.",
        ],
        working: [
          { label: "Formula", latex: "P_{gas} = P_{atm} + h" },
          { label: "Substitute", latex: "P_{gas} = 76 + 9.0" },
          { label: "Answer", latex: "P_{gas} = 85\\ \\text{cm Hg}" },
        ],
        explain: "The gas pressure is 85 centimetres of mercury, because the gas is above atmospheric, so you add the 9.0 centimetre height difference to the 76 centimetres of mercury of the atmosphere.",
      },
      {
        kind: "slider",
        prompt: "In a U-tube, a 20 cm column of oil of density 800 kg/m^3 balances a column of water of density 1000 kg/m^3. Set the slider to the height of the water column, in cm.",
        min: 0,
        max: 30,
        step: 0.5,
        unit: "cm",
        start: 0,
        targetMin: 15.5,
        targetMax: 16.5,
        ask: "At the boundary the 2 columns give equal pressure, so height times density is equal on both sides. Work out 20 times 800 divided by 1000.",
        hints: [
          "Balancing the pressures gives water height equal to 20 times 800 divided by 1000.",
          "20 times 800 is 16000, and divided by 1000 is 16, so slide to 16 centimetres.",
        ],
        working: [
          { label: "Formula", latex: "h_2 = \\dfrac{h_1 \\rho_1}{\\rho_2}" },
          { label: "Substitute", latex: "h_2 = \\dfrac{20 \\times 800}{1000}" },
          { label: "Answer", latex: "h_2 = 16\\ \\text{cm}" },
        ],
        explain: "The water column is 16 centimetres, because equal pressures at the boundary give height times density equal on both sides, and 20 times 800 divided by 1000 is 16. The denser water needs a shorter column.",
      },
      {
        kind: "classify",
        prompt: "Sort each manometer observation by what it tells you about the gas pressure.",
        bins: ["Gas pressure above atmospheric", "Gas pressure below atmospheric"],
        items: [
          { text: "The liquid rises higher on the open limb", bin: 0 },
          { text: "The gas pushes the liquid down on its own side", bin: 0 },
          { text: "The liquid on the open limb sits lower than the gas limb", bin: 1 },
          { text: "The atmosphere pushes the liquid back toward the gas side", bin: 1 },
        ],
        ask: "If the gas is stronger than the air it pushes the liquid up the open side; if it is weaker, the air wins. Tap each observation and drop it in its bin.",
        hints: [
          "A higher open limb means the gas is above atmospheric.",
          "A lower open limb means the gas is below atmospheric, so the air pushes back.",
        ],
        explain: "When the gas is above atmospheric it pushes the liquid up the open limb, so that side is higher. When the gas is below atmospheric the open limb sits lower, because the atmosphere pushes the liquid back toward the gas.",
      },
      {
        kind: "cloze",
        prompt: "Complete the summary of the mercury barometer.",
        segments: [
          "A mercury barometer has a ",
          " above the mercury at the sealed top. At sea level the atmosphere holds up a column about ",
          " centimetres tall. Mercury is used because it is very ",
          ", so the column stays short. Tilting the tube does not change the ",
          " height of the column.",
        ],
        bank: ["vacuum", "76", "dense", "vertical", "gas", "10"],
        answer: ["vacuum", "76", "dense", "vertical"],
        ask: "Recall what sits above the mercury, the standard column height at sea level, the property of mercury that keeps the column short, and which height stays fixed when you tilt the tube.",
        hints: [
          "The sealed top has no air above the mercury, and the sea-level column is about 76 centimetres.",
          "Mercury is very dense, and only the vertical height of the column matters.",
        ],
        explain: "A barometer has a vacuum above the mercury, and the atmosphere holds up a column about 76 centimetres tall. Mercury is used because it is very dense, and tilting the tube leaves the vertical height of the column unchanged.",
      },
      {
        kind: "open",
        prompt: "Explain how a hydraulic press lets a small input force lift a large load. Refer to Pascal's principle and the areas of the 2 pistons.",
        modelAnswer: "A liquid is almost incompressible, so by Pascal's principle a pressure applied at one point is transmitted equally to every part of the liquid. The small input force F1 on the small piston of area A1 sets up a pressure F1 divided by A1. This same pressure acts on the large output piston of area A2, so F1/A1 = F2/A2. Because A2 is larger than A1, the output force F2 is larger than the input force F1, and the press multiplies the force. Air in the liquid would make it inefficient because air is compressible.",
        marks: [
          "Liquid is incompressible and transmits the pressure equally (Pascal's principle).",
          "The same pressure acts on both pistons, so F1/A1 = F2/A2.",
          "A larger output area A2 gives a larger output force F2.",
        ],
        ask: "Start from the pressure that the input force makes on the small piston, and think about what that same pressure does on a larger piston area.",
      },
      {
        kind: "open",
        prompt: "A U-tube manometer is connected to a gas supply, with the other limb open to the air. Explain how the height difference of the liquid shows whether the gas pressure is above or below atmospheric pressure.",
        figure: "fig-06-12-manometer",
        modelAnswer: "Points at the same level in the connected liquid have equal pressure. If the gas pressure is above atmospheric, the gas pushes the liquid down on its side and up the open side, so the open limb is higher, and P_gas = P_atm + h rho g. If the gas pressure is below atmospheric, the atmosphere pushes the liquid down the open side and up the gas side, so the open limb is lower, and P_gas = P_atm - h rho g. The larger the height difference h, the further the gas pressure is from atmospheric.",
        marks: [
          "Points at the same level in the connected liquid have equal pressure.",
          "Open limb higher means the gas is above atmospheric, P_gas = P_atm + h rho g.",
          "Open limb lower means the gas is below atmospheric, P_gas = P_atm - h rho g.",
        ],
        ask: "Think about which way the liquid is pushed when the gas is stronger than the air, and which way when the gas is weaker than the air.",
      },
    ],
  },
];
