import type { Subconcept } from "@/lib/teaching/subconcepts";

// T6 Energy, topical quiz. Whole-topic check across KB Chapter 07 (Energy, Work and Power):
// systems and energy stores; energy transfer and the 4 pathways; E_k = 1/2 m v^2 and
// E_p = m g h; conservation of energy and the pendulum; work done W = F d; power P = W / t
// and P = F v; efficiency = useful / total x 100 percent; renewable and non-renewable resources.
// Question-only. Figures appear only on choice and open steps.

export const BOXES: Subconcept[] = [
  {
    id: "t6.quiz",
    code: "Quiz",
    title: "Energy topical quiz",
    blurb: "Whole-topic check: stores, transfers, KE and GPE, conservation, work, power, efficiency",
    kind: "quiz",
    steps: [
      {
        kind: "choice",
        question: "What is the SI unit of energy?",
        options: ["The joule (J)", "The newton (N)", "The watt (W)", "The pascal (Pa)"],
        correct: 0,
        ask: "Energy and work are measured in the same unit. Which of these is the unit of energy?",
        hints: [
          "The newton is a unit of force and the watt is a unit of power.",
          "Energy is measured in joules, with the symbol J.",
        ],
        explain: "Energy is measured in joules, written J. The newton is the unit of force, the watt is the unit of power, and the pascal is the unit of pressure.",
      },
      {
        kind: "classify",
        prompt: "Sort each example by the main energy store it holds.",
        bins: ["Kinetic store", "Gravitational potential store", "Chemical store"],
        items: [
          { text: "a car speeding along a road", bin: 0 },
          { text: "an arrow flying through the air", bin: 0 },
          { text: "a book held high on a shelf", bin: 1 },
          { text: "water stored behind a high dam", bin: 1 },
          { text: "the petrol in a fuel tank", bin: 2 },
          { text: "the food you eat for breakfast", bin: 2 },
        ],
        ask: "A moving object has a kinetic store, a raised object has a gravitational potential store, and fuel or food holds a chemical store. Tap each example and drop it in its bin.",
        hints: [
          "If the object is moving, it holds a kinetic store; if it is raised up, it holds a gravitational potential store.",
          "Petrol and food hold energy in chemical bonds, so they belong in the chemical store.",
        ],
        explain: "A speeding car and a flying arrow are moving, so they hold kinetic stores. A raised book and dammed water are lifted up, so they hold gravitational potential stores. Petrol and food hold chemical stores in their bonds.",
      },
      {
        kind: "open",
        prompt: "Explain what is meant by an energy store, and name 3 different energy stores.",
        modelAnswer: "An energy store is a way that energy is held in a system. When the system changes, the energy can be transferred from one store to another. Examples of stores include the kinetic store of a moving object, the gravitational potential store of a raised object, the elastic potential store of a stretched spring, the internal or thermal store of a hot object, the chemical store in food or fuel, and the nuclear store in a nucleus.",
        marks: [
          "An energy store is a way energy is held in a system.",
          "The energy can be transferred to another store when the system changes.",
          "3 correct stores named, such as kinetic, gravitational potential and chemical.",
        ],
        ask: "Say what a store holds, and list 3 named stores such as kinetic, gravitational potential or chemical.",
      },
      {
        kind: "match",
        prompt: "Match each situation to the pathway that transfers the energy.",
        pairs: [
          { left: "A hand pushes a box across the floor", right: "Mechanically" },
          { left: "A hot drink warms your cold hands", right: "By heating" },
          { left: "A lamp lights up a dark room", right: "By waves" },
          { left: "A battery drives a current round a torch circuit", right: "Electrically" },
        ],
        ask: "There are 4 pathways: mechanically, by heating, by waves, and electrically. Match each situation to the one that carries its energy.",
        hints: [
          "A force moving an object is mechanical; energy flowing from hot to cold is by heating.",
          "Light and sound travel by waves, and a current in a circuit carries energy electrically.",
        ],
        explain: "Pushing a box transfers energy mechanically. A hot drink warming your hands transfers it by heating. A lamp lighting a room transfers it by waves. A battery driving a current transfers it electrically.",
      },
      {
        kind: "choice",
        question: "A falling apple speeds up as it drops. By which pathway is energy transferred to its kinetic store?",
        options: ["Mechanically", "By heating", "Electrically", "By waves"],
        correct: 0,
        ask: "A pathway is mechanical when a force moves an object through a distance. What moves the apple as it falls?",
        hints: [
          "The apple falls because a force, its weight, moves it downward through a distance.",
          "A force moving an object through a distance is the mechanical pathway.",
        ],
        explain: "The transfer is mechanical, because the weight of the apple is a force that moves it through a distance as it falls, filling its kinetic store.",
      },
      {
        kind: "choice",
        question: "A 0.80 kg ball moves at 2.0 m/s. Find its kinetic store E_k.",
        options: ["1.6 J", "0.80 J", "3.2 J", "1.6 W"],
        correct: 0,
        ask: "The kinetic store is half the mass times the speed squared, so work out 0.5 times 0.80 times 2.0 squared.",
        hints: [
          "Use E_k equals a half m v squared.",
          "2.0 squared is 4.0, and 0.5 times 0.80 times 4.0 is 1.6, measured in joules.",
        ],
        working: [
          { label: "Formula", latex: "E_k = \\tfrac{1}{2} m v^2" },
          { label: "Substitute", latex: "E_k = \\tfrac{1}{2} \\times 0.80 \\times 2.0^2" },
          { label: "Answer", latex: "E_k = 1.6\\ \\text{J}" },
        ],
        explain: "The kinetic store is 1.6 joules, because a half times 0.80 kilograms times 2.0 metres per second squared, which is 4.0, gives 1.6 joules.",
      },
      {
        kind: "slider",
        prompt: "A 0.40 kg book is lifted 12 m (g = 10 N/kg). Set the slider to the gain in its gravitational potential store, in joules.",
        min: 0,
        max: 100,
        step: 1,
        unit: "J",
        start: 0,
        targetMin: 47,
        targetMax: 49,
        ask: "The gravitational potential store gained is mass times g times the height, so work out 0.40 times 10 times 12.",
        hints: [
          "Use E_p equals m g h, with g equal to 10 newtons per kilogram.",
          "0.40 times 10 times 12 is 48, so slide to 48 joules.",
        ],
        working: [
          { label: "Formula", latex: "E_p = mgh" },
          { label: "Substitute", latex: "E_p = 0.40 \\times 10 \\times 12" },
          { label: "Answer", latex: "E_p = 48\\ \\text{J}" },
        ],
        explain: "The gravitational potential store gained is 48 joules, because 0.40 kilograms times 10 newtons per kilogram times 12 metres is 48 joules.",
      },
      {
        kind: "tiles",
        prompt: "A block of weight 30 N is raised 3 m. Using E_p = W h, build the working line for the gain in its gravitational potential store.",
        tiles: ["E_p =", "30", "\\times", "3", "=", "90", "J", "N"],
        answer: ["E_p =", "30", "\\times", "3", "=", "90", "J"],
        ask: "Because W equals m g, the gravitational potential store gained is the weight times the height, so set up 30 times 3.",
        hints: [
          "Use E_p equals W times h, the weight times the height raised.",
          "30 times 3 is 90, and energy is measured in joules.",
        ],
        working: [
          { label: "Formula", latex: "E_p = W h" },
          { label: "Substitute", latex: "E_p = 30 \\times 3" },
          { label: "Answer", latex: "E_p = 90\\ \\text{J}" },
        ],
        explain: "The gravitational potential store gained is 90 joules, because the weight of 30 newtons times the height of 3 metres is 90 joules.",
      },
      {
        kind: "open",
        prompt: "Compare the kinetic store and the gravitational potential store of an object, and give the equation for each.",
        modelAnswer: "The kinetic store is the energy an object has because it is moving, given by E_k = 1/2 m v^2, so it depends on the mass and on the square of the speed. The gravitational potential store is the energy an object has because it is raised up, given by E_p = m g h, so it depends on the mass, the gravitational field strength, and the vertical height raised. Both stores are measured in joules.",
        marks: [
          "Kinetic store is due to motion, E_k = 1/2 m v^2.",
          "Gravitational potential store is due to height, E_p = m g h.",
          "Both stores are measured in joules.",
        ],
        ask: "For each store say what it depends on, give its equation, and state the unit.",
      },
      {
        kind: "choice",
        question: "A ball rolls from P, over the top of a bump at Q, and down to R at the same height as P. Ignoring friction, where is the ball moving fastest?",
        figure: "fig-07-15-ball-hill-pqr",
        options: [
          "At P and R, where it is lowest",
          "At Q, the top of the bump",
          "It moves at the same speed everywhere",
          "At Q, because it has the most energy there",
        ],
        correct: 0,
        ask: "By conservation of energy the kinetic store is largest where the gravitational potential store is smallest. Where is the ball lowest?",
        hints: [
          "As the ball climbs to Q its kinetic store falls and its gravitational potential store rises.",
          "The ball is fastest where it is lowest, at P and R, because the kinetic store is greatest there.",
        ],
        explain: "The ball moves fastest at P and R, where it is lowest. As it climbs to Q the kinetic store is transferred to the gravitational potential store, so it slows, then speeds up again coming down. The total energy stays the same throughout.",
      },
      {
        kind: "order",
        prompt: "An ideal pendulum swings from A at one side, through the lowest point B, to C at the other side. Put the energy changes in order.",
        items: [
          "At A the bob is highest, so the gravitational potential store is maximum and the kinetic store is zero",
          "Swinging down to B, the gravitational potential store falls and the kinetic store rises",
          "At B the bob is lowest and fastest, so the kinetic store is maximum and the gravitational potential store is minimum",
          "Rising from B to C, the kinetic store falls and the gravitational potential store rises",
          "At C the bob is highest again, so the gravitational potential store is maximum and the kinetic store is zero",
        ],
        ask: "Start at A where the bob is momentarily still and highest, follow it through the lowest point, and finish at C. Put the stages in order.",
        hints: [
          "At the ends of the swing the bob is highest and slowest; at the bottom it is lowest and fastest.",
          "The gravitational potential store turns into the kinetic store on the way down, then back again on the way up.",
        ],
        explain: "At A the gravitational potential store is maximum and the kinetic store is zero. Falling to B the store becomes kinetic, so at B the kinetic store is maximum. Rising to C it turns back, so at C the gravitational potential store is maximum again.",
      },
      {
        kind: "choice",
        question: "A 0.500 kg mango falls from a branch 20 m high (g = 10 N/kg). All of its gravitational potential store becomes kinetic. Find its speed just before it lands.",
        options: ["20 m/s", "10 m/s", "40 m/s", "4 m/s"],
        correct: 0,
        ask: "Set the gravitational potential store equal to the kinetic store: m g h equals a half m v squared. The mass cancels, so v is the square root of 2 g h.",
        hints: [
          "E_p is m g h, which is 0.500 times 10 times 20, giving 100 joules, and this equals the kinetic store.",
          "v equals the square root of 2 times 10 times 20, which is the square root of 400, giving 20 metres per second.",
        ],
        working: [
          { label: "Formula", latex: "mgh = \\tfrac{1}{2} m v^2 \\Rightarrow v = \\sqrt{2gh}" },
          { label: "Substitute", latex: "v = \\sqrt{2 \\times 10 \\times 20}" },
          { label: "Answer", latex: "v = 20\\ \\text{m/s}" },
        ],
        explain: "The speed is 20 metres per second, because the mass cancels and v is the square root of 2 times 10 times 20, which is the square root of 400, giving 20 metres per second.",
      },
      {
        kind: "cloze",
        prompt: "Complete the sentences about conservation of energy in a swing that slowly dies away.",
        segments: [
          "Energy cannot be created or ",
          ", only transferred from one store to another. When friction makes the swing die away, the energy is ",
          " to the internal store of the surroundings, so it is spread out and no longer ",
          ".",
        ],
        bank: ["destroyed", "transferred", "useful", "created", "stored"],
        answer: ["destroyed", "transferred", "useful"],
        ask: "By conservation of energy the total is constant. Think about what cannot happen to energy, where the swing's energy goes, and why we still call it 'lost'.",
        hints: [
          "Energy is never created or destroyed, only moved between stores.",
          "Friction transfers the energy to internal stores of the surroundings, where it is no longer useful.",
        ],
        explain: "Energy cannot be created or destroyed, only transferred. When the swing dies away the energy is transferred to the internal store of the surroundings, where it is spread out and no longer useful, though the total energy is unchanged.",
      },
      {
        kind: "choice",
        question: "A box is pushed with a steady force of 5 N and moves 6 m in the direction of the force. Find the work done.",
        options: ["30 J", "11 J", "1.2 J", "30 N"],
        correct: 0,
        ask: "Work done is the force times the distance moved in the direction of the force, so work out 5 times 6.",
        hints: [
          "Use W equals F times d.",
          "5 times 6 is 30, and work is measured in joules.",
        ],
        working: [
          { label: "Formula", latex: "W = F d" },
          { label: "Substitute", latex: "W = 5 \\times 6" },
          { label: "Answer", latex: "W = 30\\ \\text{J}" },
        ],
        explain: "The work done is 30 joules, because 5 newtons times 6 metres is 30 joules, and 1 newton metre is 1 joule.",
      },
      {
        kind: "spoterror",
        prompt: "A box is pushed 6 m up a slope by a 5 N force and gains a gravitational potential store of 24 J. Here is a student's working for the work done against friction. Tap the line with the mistake.",
        lines: [
          "W = F d = 5 \\times 6 = 30\\ \\text{J}",
          "E_p gained = 24\\ \\text{J}",
          "work against friction = W - E_p",
          "work against friction = 30 + 24 = 54\\ \\text{J}",
        ],
        errorLine: 3,
        ask: "The total work splits between the gravitational potential store and friction, so the friction work is the total work minus E_p. Should the last line add or subtract?",
        hints: [
          "Work against friction is the total work done minus the gain in the gravitational potential store.",
          "30 minus 24 is 6, so the friction work is 6 joules; the line that adds them to get 54 is wrong.",
        ],
        working: [
          { label: "Formula", latex: "W_{friction} = W - E_p" },
          { label: "Substitute", latex: "W_{friction} = 30 - 24" },
          { label: "Answer", latex: "W_{friction} = 6\\ \\text{J}" },
        ],
        explain: "The mistake is the last line, which adds 30 and 24. The work against friction is the total work minus the gravitational potential store gained, so it is 30 minus 24, which is 6 joules.",
      },
      {
        kind: "open",
        prompt: "State the condition for a force to do work on an object, and explain why no work is done when you hold a heavy bag still.",
        modelAnswer: "A force does work only when it moves the object through a distance in the direction of the force, and the work done is W = F d. When you hold a heavy bag still, the upward force you apply does not move the bag through any distance, so d is 0 and no work is done on the bag, even though holding it feels tiring.",
        marks: [
          "Work is done only when the force moves the object through a distance in its direction.",
          "W = F d stated.",
          "Holding the bag still means no movement, so d is 0 and no work is done.",
        ],
        ask: "Think about whether the object moves in the direction of the force, and what W = F d gives when the distance is 0.",
      },
      {
        kind: "choice",
        question: "A 50 kg student runs up a flight of stairs of vertical height 3.0 m in 6.0 s (g = 10 N/kg). Find the useful power.",
        options: ["250 W", "500 W", "150 W", "1500 W"],
        correct: 0,
        ask: "First find the work done against gravity with m g h, then divide by the time to get the power.",
        hints: [
          "The work done is m g h, which is 50 times 10 times 3.0, giving 1500 joules.",
          "Power is work divided by time, so 1500 divided by 6.0 is 250 watts.",
        ],
        working: [
          { label: "Formula", latex: "P = \\dfrac{W}{t} = \\dfrac{mgh}{t}" },
          { label: "Substitute", latex: "P = \\dfrac{50 \\times 10 \\times 3.0}{6.0}" },
          { label: "Answer", latex: "P = 250\\ \\text{W}" },
        ],
        explain: "The work done is 50 times 10 times 3.0, which is 1500 joules, and the power is 1500 divided by 6.0, giving 250 watts.",
      },
      {
        kind: "slider",
        prompt: "A conveyor belt drives a load with a force of 240 N at a constant speed of 2.5 m/s. Set the slider to the power, in watts.",
        min: 0,
        max: 1000,
        step: 10,
        unit: "W",
        start: 0,
        targetMin: 590,
        targetMax: 610,
        ask: "At constant speed the power is the force times the speed, so work out 240 times 2.5.",
        hints: [
          "Use P equals F times v.",
          "240 times 2.5 is 600, so slide to 600 watts.",
        ],
        working: [
          { label: "Formula", latex: "P = F v" },
          { label: "Substitute", latex: "P = 240 \\times 2.5" },
          { label: "Answer", latex: "P = 600\\ \\text{W}" },
        ],
        explain: "The power is 600 watts, because at constant speed the power is the force times the speed, and 240 newtons times 2.5 metres per second is 600 watts.",
      },
      {
        kind: "choice",
        question: "An electric heater takes in 200000 J of energy and usefully transfers 150000 J. Find its efficiency.",
        options: ["75%", "25%", "133%", "50%"],
        correct: 0,
        ask: "Efficiency is the useful output divided by the total input, times 100 percent, so work out 150000 divided by 200000.",
        hints: [
          "Use efficiency equals useful output divided by total input, times 100 percent.",
          "150000 divided by 200000 is 0.75, and times 100 percent that is 75 percent.",
        ],
        working: [
          { label: "Formula", latex: "\\text{efficiency} = \\dfrac{\\text{useful output}}{\\text{total input}} \\times 100\\%" },
          { label: "Substitute", latex: "= \\dfrac{150000}{200000} \\times 100\\%" },
          { label: "Answer", latex: "= 75\\%" },
        ],
        explain: "The efficiency is 75 percent, because 150000 joules of useful output divided by 200000 joules of total input is 0.75, which is 75 percent.",
      },
      {
        kind: "choice",
        question: "A wind turbine takes in 800 J of energy from the wind and usefully transfers 200 J to the generator. How much energy is dissipated (wasted)?",
        options: ["600 J", "200 J", "1000 J", "400 J"],
        correct: 0,
        ask: "The total input equals the useful output plus the dissipated energy, so the dissipated energy is the total minus the useful output.",
        hints: [
          "Use dissipated energy equals total input minus useful output.",
          "800 minus 200 is 600, measured in joules.",
        ],
        working: [
          { label: "Formula", latex: "\\text{dissipated} = \\text{total input} - \\text{useful output}" },
          { label: "Substitute", latex: "= 800 - 200" },
          { label: "Answer", latex: "= 600\\ \\text{J}" },
        ],
        explain: "The dissipated energy is 600 joules, because the total input of 800 joules minus the useful output of 200 joules is 600 joules, which is spread to the surroundings.",
      },
      {
        kind: "open",
        prompt: "Explain what the efficiency of a device tells you, and describe what happens to the energy that is not usefully transferred.",
        figure: "fig-07-12-sankey-efficiency",
        modelAnswer: "The efficiency tells you what fraction of the total energy input is transferred usefully, written as a percentage: efficiency = useful output / total input x 100%. No device is 100% efficient. The energy that is not usefully transferred is dissipated to the surroundings, mostly to internal or thermal stores by heating, and sometimes by sound, where it is spread out and no longer useful.",
        marks: [
          "Efficiency = useful output / total input x 100%.",
          "The wasted energy is dissipated to the surroundings.",
          "It mostly ends up in internal or thermal stores by heating.",
        ],
        ask: "Say what fraction efficiency compares, and where the wasted energy goes.",
      },
      {
        kind: "choice",
        question: "Which statement about energy resources is correct?",
        options: [
          "Renewable resources are replenished and will not run out; non-renewable resources will run out",
          "Renewable resources will run out; non-renewable resources will not",
          "All fossil fuels are renewable resources",
          "Nuclear fuel is a renewable resource",
        ],
        correct: 0,
        ask: "A renewable resource is refilled as fast as it is used. Which statement matches that idea?",
        hints: [
          "Fossil fuels and nuclear fuels are used up faster than they form, so they are non-renewable.",
          "Renewable resources such as wind and solar are replenished, so they will not run out.",
        ],
        explain: "Renewable resources such as wind, solar and hydropower are replenished and will not run out. Non-renewable resources such as fossil fuels and nuclear fuels are used faster than they form, so they will eventually run out.",
      },
      {
        kind: "classify",
        prompt: "Sort each energy resource as renewable or non-renewable.",
        bins: ["Renewable", "Non-renewable"],
        items: [
          { text: "wind", bin: 0 },
          { text: "solar", bin: 0 },
          { text: "hydropower", bin: 0 },
          { text: "coal", bin: 1 },
          { text: "natural gas", bin: 1 },
          { text: "nuclear fuel", bin: 1 },
        ],
        ask: "A renewable resource is replenished and will not run out; a non-renewable one is used up faster than it forms. Tap each resource and drop it in its bin.",
        hints: [
          "Wind, solar and hydropower are refilled naturally, so they are renewable.",
          "Coal, natural gas and nuclear fuel are used up and will run out, so they are non-renewable.",
        ],
        explain: "Wind, solar and hydropower are replenished, so they are renewable. Coal, natural gas and nuclear fuel form far more slowly than we use them, so they are non-renewable.",
      },
      {
        kind: "graphpick",
        prompt: "The kinetic store of a moving object is E_k = 1/2 m v^2. Which graph best shows how the kinetic store changes as the speed increases?",
        xLabel: "speed / m/s",
        yLabel: "kinetic store / J",
        options: [
          { points: [[0, 0], [1, 1], [2, 4], [3, 9], [4, 16]], caption: "A curve that rises more and more steeply" },
          { points: [[0, 0], [1, 4], [2, 8], [3, 12], [4, 16]], caption: "A straight line through the origin" },
          { points: [[0, 8], [1, 8], [2, 8], [3, 8], [4, 8]], caption: "A horizontal line" },
          { points: [[0, 16], [1, 9], [2, 4], [3, 1], [4, 0]], caption: "A curve that falls to zero" },
        ],
        correct: 0,
        ask: "The kinetic store depends on the square of the speed, so doubling the speed makes it 4 times as large. Which shape rises faster and faster?",
        hints: [
          "Because E_k depends on the speed squared, the graph is not a straight line.",
          "Squaring the speeds 1, 2, 3 and 4 gives 1, 4, 9 and 16, so the curve rises more and more steeply.",
        ],
        explain: "The kinetic store depends on the square of the speed, so as the speed rises the store grows more and more steeply, following a curve rather than a straight line.",
      },
      {
        kind: "open",
        prompt: "Explain the difference between renewable and non-renewable energy resources, and give 2 examples of each.",
        modelAnswer: "A renewable energy resource is one that is replenished as fast as it is used, so it will not run out; examples are wind, solar, hydropower, tides, geothermal and biofuels. A non-renewable energy resource is used up faster than it forms, so it will eventually run out; examples are the fossil fuels coal, oil and natural gas, and nuclear fuels such as uranium.",
        marks: [
          "Renewable resources are replenished and will not run out.",
          "Non-renewable resources will run out because they are used faster than they form.",
          "2 correct examples of each, such as wind and solar (renewable), coal and gas (non-renewable).",
        ],
        ask: "Say which type runs out and which is replenished, and give 2 named examples of each.",
      },
    ],
  },
];
