import type { Subconcept } from "@/lib/teaching/subconcepts";

// T4 Turning Effect of Forces, topical quiz. Whole-topic check across KB Chapter 05
// (Turning Effects of Forces): the moment of a force, the principle of moments, the two
// conditions for equilibrium, centre of gravity, and stability. Question-only.
// Figure colours follow the carry-over colour key: applied force/effort = yellow,
// weight/load = pink, support/tension = yellow, reaction/upthrust/resultant = green,
// rotation = blue, pivot/dimension/line-of-action guides = grey, beam/lamina = white.

export const BOXES: Subconcept[] = [
  {
    id: "t4.quiz",
    code: "Quiz",
    title: "Turning effect topical quiz",
    blurb: "Whole-topic check: moments, equilibrium, centre of gravity, stability",
    kind: "quiz",
    steps: [
      {
        kind: "choice",
        question: "A spanner turns a bolt. You push with a force of 60 N at a perpendicular distance of 0.25 m from the bolt. What is the moment of your push?",
        options: ["15 N m", "240 N m", "15 N", "0.25 N m"],
        correct: 0,
        ask: "The moment is the force times the perpendicular distance, so work out 60 times 0.25. Which option is that, with the right unit?",
        hints: [
          "Use moment equals force times distance.",
          "60 times 0.25 is 15, and the moment is measured in newton metres.",
        ],
        working: [
          { label: "Formula", latex: "M = F \\times d" },
          { label: "Substitute", latex: "M = 60 \\times 0.25" },
          { label: "Answer", latex: "M = 15\\ \\text{N m}" },
        ],
        explain: "The moment is 15 newton metres, because 60 newtons times 0.25 metres is 15 newton metres.",
      },
      {
        kind: "tiles",
        prompt: "An iron is held down by a force of 5 N acting 0.15 m from its pivot. Build the working line for the moment M of this force.",
        tiles: ["M =", "5", "\\times", "0.15", "=", "0.75", "0.075", "N m", "N"],
        answer: ["M =", "5", "\\times", "0.15", "=", "0.75", "N m"],
        ask: "The moment is force times the perpendicular distance, so set up 5 times 0.15.",
        hints: [
          "Use M equals force times distance.",
          "5 times 0.15 is 0.75, and the moment is measured in newton metres.",
        ],
        working: [
          { label: "Formula", latex: "M = F \\times d" },
          { label: "Substitute", latex: "M = 5 \\times 0.15" },
          { label: "Answer", latex: "M = 0.75\\ \\text{N m}" },
        ],
        explain: "The moment is 0.75 newton metres, because 5 newtons times 0.15 metres is 0.75 newton metres.",
      },
      {
        kind: "classify",
        prompt: "A beam is balanced on a central pivot. Sort each force by the way it turns the beam.",
        bins: ["Clockwise moment", "Anticlockwise moment"],
        items: [
          { text: "a weight pulling the right-hand end down", bin: 0 },
          { text: "a weight pulling the left-hand end down", bin: 1 },
          { text: "a push lifting the right-hand end up", bin: 1 },
          { text: "a push lifting the left-hand end up", bin: 0 },
        ],
        ask: "Picture a clock face. A force that turns the right side downward turns the beam clockwise; a force that turns the right side upward turns it anticlockwise. Tap each force and drop it in its bin.",
        hints: [
          "Right-hand end going down, or left-hand end going up, is a clockwise turn.",
          "Left-hand end going down, or right-hand end going up, is an anticlockwise turn.",
        ],
        explain: "A weight pulling the right end down, or a push lifting the left end up, turns the beam clockwise. A weight pulling the left end down, or a push lifting the right end up, turns it anticlockwise.",
      },
      {
        kind: "choice",
        question: "You keep the same force on a spanner but move your hand further from the bolt. What happens to the moment?",
        options: ["It increases", "It decreases", "It stays the same", "It changes direction"],
        correct: 0,
        ask: "The moment is force times perpendicular distance. If the force is unchanged but the distance grows, what happens to their product?",
        hints: [
          "A larger distance from the pivot gives a larger moment for the same force.",
          "Moving your hand out increases the distance, so the moment increases.",
        ],
        explain: "The moment increases, because for the same force a larger perpendicular distance from the pivot gives a larger turning effect. That is why a longer spanner loosens a stiff bolt more easily.",
      },
      {
        kind: "open",
        prompt: "Explain what is meant by the moment of a force, state its unit, and give 2 ways to make the moment of a force larger.",
        modelAnswer: "The moment of a force is its turning effect about a pivot. It is worked out as the force multiplied by the perpendicular distance from the pivot to the line of action of the force, and its unit is the newton metre. You can make the moment larger by using a bigger force, or by applying the force at a greater perpendicular distance from the pivot.",
        marks: [
          "The moment is the turning effect of a force about a pivot.",
          "Moment equals force times the perpendicular distance from the pivot, in newton metres.",
          "2 correct ways: a larger force, or a greater perpendicular distance.",
        ],
        ask: "Say what the moment measures, how it is calculated with its unit, and what you could change to increase it.",
      },
      {
        kind: "choice",
        question: "A see-saw balances about its central pivot. A downward force of 30 N acts 0.40 m from the pivot on one side, and a weight W acts 0.20 m from the pivot on the other side. Find W.",
        figure: "fig-05-07-seesaw-balance",
        options: ["60 N", "15 N", "24 N", "240 N"],
        correct: 0,
        ask: "For a balanced see-saw the clockwise moment equals the anticlockwise moment. Work out 30 times 0.40, then divide by 0.20.",
        hints: [
          "Use the principle of moments: 30 times 0.40 equals W times 0.20.",
          "30 times 0.40 is 12, and 12 divided by 0.20 is 60.",
        ],
        working: [
          { label: "Formula", latex: "F_1 d_1 = F_2 d_2" },
          { label: "Substitute", latex: "30 \\times 0.40 = W \\times 0.20" },
          { label: "Answer", latex: "W = 60\\ \\text{N}" },
        ],
        explain: "The weight is 60 newtons. The clockwise and anticlockwise moments are equal, so 30 times 0.40, which is 12 newton metres, equals W times 0.20, giving W equal to 60 newtons.",
      },
      {
        kind: "choice",
        question: "A uniform beam balances on a pivot. A downward force of 6 N acts 6 m from the pivot on one side, and a weight W acts 2 m from the pivot on the other side. Find W.",
        figure: "fig-05-21-mcq-beam",
        options: ["18 N", "2 N", "36 N", "12 N"],
        correct: 0,
        ask: "Balance means the moments are equal. Work out 6 times 6, then divide by 2.",
        hints: [
          "Use 6 times 6 equals W times 2.",
          "6 times 6 is 36, and 36 divided by 2 is 18.",
        ],
        working: [
          { label: "Formula", latex: "F_1 d_1 = F_2 d_2" },
          { label: "Substitute", latex: "6 \\times 6 = W \\times 2" },
          { label: "Answer", latex: "W = 18\\ \\text{N}" },
        ],
        explain: "The weight is 18 newtons, because 6 times 6, which is 36 newton metres, equals W times 2, so W is 36 divided by 2, which is 18 newtons.",
      },
      {
        kind: "slider",
        prompt: "A rod balances about a pivot. On one side, 20 N acts 0.30 m from the pivot and 12 N acts 0.20 m from the pivot, both turning it the same way. A single weight W on the other side acts 0.10 m from the pivot. Set the slider to W, in newtons.",
        min: 0,
        max: 120,
        step: 1,
        unit: "N",
        start: 0,
        targetMin: 83,
        targetMax: 85,
        ask: "Add the 2 moments on one side, then set that equal to W times 0.10. Work out 20 times 0.30 plus 12 times 0.20, then divide by 0.10.",
        hints: [
          "The total moment on one side is 20 times 0.30 plus 12 times 0.20.",
          "20 times 0.30 is 6 and 12 times 0.20 is 2.4, so the total is 8.4, and 8.4 divided by 0.10 is 84.",
        ],
        working: [
          { label: "Formula", latex: "F_1 d_1 + F_2 d_2 = W d" },
          { label: "Substitute", latex: "(20 \\times 0.30) + (12 \\times 0.20) = W \\times 0.10" },
          { label: "Answer", latex: "W = 84\\ \\text{N}" },
        ],
        explain: "The weight is 84 newtons. The 2 moments add to 6 plus 2.4, which is 8.4 newton metres, and that equals W times 0.10, so W is 8.4 divided by 0.10, which is 84 newtons.",
      },
      {
        kind: "spoterror",
        prompt: "A see-saw balances. A 300 N weight acts 1.5 m from the pivot, and a weight W acts 2.0 m from the pivot on the other side. Tap the line with the mistake in this working for W.",
        lines: [
          "\\text{clockwise moment} = \\text{anticlockwise moment}",
          "300 \\times 1.5 = W \\times 2.0",
          "W = 300 \\times 1.5 \\times 2.0",
          "W = 900\\ \\text{N}",
        ],
        errorLine: 2,
        ask: "Check how the student rearranges to find W. To get W by itself, do you multiply by 2.0 or divide by 2.0?",
        hints: [
          "The balance equation is 300 times 1.5 equals W times 2.0.",
          "To find W, divide 300 times 1.5 by 2.0, not multiply. The line that multiplies by 2.0 is wrong.",
        ],
        working: [
          { label: "Formula", latex: "F_1 d_1 = F_2 d_2" },
          { label: "Substitute", latex: "W = \\dfrac{300 \\times 1.5}{2.0}" },
          { label: "Answer", latex: "W = 225\\ \\text{N}" },
        ],
        explain: "The mistake is the line that writes W equals 300 times 1.5 times 2.0. To find W you divide 300 times 1.5 by 2.0, so W is 450 divided by 2.0, which is 225 newtons, not 900 newtons.",
      },
      {
        kind: "open",
        prompt: "State the principle of moments for an object in equilibrium.",
        modelAnswer: "The principle of moments states that when an object is in equilibrium, the total clockwise moment about any pivot equals the total anticlockwise moment about that same pivot. In symbols, the sum of the clockwise moments equals the sum of the anticlockwise moments, so for a simple balance F_1 times d_1 equals F_2 times d_2.",
        marks: [
          "For an object in equilibrium, the total clockwise moment equals the total anticlockwise moment.",
          "The moments are taken about the same pivot.",
          "Expressed as F_1 d_1 equals F_2 d_2 for a simple balance.",
        ],
        ask: "Say what is equal to what when a balanced object is in equilibrium, and about which point the moments are taken.",
      },
      {
        kind: "choice",
        question: "An object is in equilibrium. Which pair of conditions must both be true?",
        options: [
          "The resultant force is zero and the resultant moment is zero",
          "The resultant force is zero, but the moment can be anything",
          "The resultant moment is zero, but the force can be anything",
          "The object must be completely at rest",
        ],
        correct: 0,
        ask: "Equilibrium needs both a straight-line condition and a turning condition. Think about the resultant force and the resultant turning effect.",
        hints: [
          "One condition is that there is no resultant force in any direction.",
          "The other condition is that there is no resultant moment about any point.",
        ],
        explain: "For equilibrium there must be no resultant force and no resultant moment. If either were not zero the object would either accelerate along a line or start to turn.",
      },
      {
        kind: "choice",
        question: "A uniform metre rule is pivoted at one end. An 80 N weight hangs 0.75 m from the pivot, and a spring balance 1.0 m from the pivot holds the rule level. What does the spring balance read?",
        figure: "fig-05-24-metre-rule-spring",
        options: ["60 N", "107 N", "80 N", "0.94 N"],
        correct: 0,
        ask: "The rule is balanced, so the moments are equal. Work out 80 times 0.75, then divide by 1.0.",
        hints: [
          "Use 80 times 0.75 equals the spring force times 1.0.",
          "80 times 0.75 is 60, and 60 divided by 1.0 is 60.",
        ],
        working: [
          { label: "Formula", latex: "F_1 d_1 = F_2 d_2" },
          { label: "Substitute", latex: "80 \\times 0.75 = F \\times 1.0" },
          { label: "Answer", latex: "F = 60\\ \\text{N}" },
        ],
        explain: "The spring balance reads 60 newtons, because 80 times 0.75, which is 60 newton metres, equals the spring force times 1.0, so the force is 60 newtons.",
      },
      {
        kind: "cloze",
        prompt: "Complete the sentence about the conditions for equilibrium.",
        segments: [
          "An object is in equilibrium when the resultant force on it is ",
          " and the resultant ",
          " about any point is ",
          ".",
        ],
        bank: ["zero", "moment", "force", "maximum"],
        answer: ["zero", "moment", "zero"],
        ask: "Recall the 2 conditions for equilibrium: one about the resultant force, one about the resultant turning effect.",
        hints: [
          "The resultant force must be zero.",
          "The other blank names the turning quantity, the moment, which must also be zero.",
        ],
        explain: "An object is in equilibrium when the resultant force on it is zero and the resultant moment about any point is zero.",
      },
      {
        kind: "match",
        prompt: "Match each term to its correct meaning.",
        pairs: [
          { left: "Moment of a force", right: "Force times the perpendicular distance from the pivot" },
          { left: "Principle of moments", right: "In equilibrium, total clockwise moment equals total anticlockwise moment" },
          { left: "Centre of gravity", right: "The point where the whole weight of an object seems to act" },
          { left: "Equilibrium", right: "No resultant force and no resultant moment" },
        ],
        ask: "Match each item to its statement. One is a calculation, one is a balance rule, one is a single point, and one is a state of balance.",
        hints: [
          "The moment is a force times a distance; the principle of moments compares clockwise and anticlockwise turning.",
          "The centre of gravity is a single point where weight acts; equilibrium means no resultant force and no resultant moment.",
        ],
        explain: "The moment of a force is force times the perpendicular distance from the pivot. The principle of moments says the total clockwise moment equals the total anticlockwise moment in equilibrium. The centre of gravity is the point where the whole weight seems to act. Equilibrium means no resultant force and no resultant moment.",
      },
      {
        kind: "open",
        prompt: "State the 2 conditions that must both be satisfied for an object to be in equilibrium.",
        modelAnswer: "For an object to be in equilibrium, first there must be no resultant force on it, so the forces in every direction balance. Second, there must be no resultant moment about any point, so the total clockwise moment equals the total anticlockwise moment. When both hold, the object stays at rest or keeps moving steadily without turning.",
        marks: [
          "There is no resultant force on the object.",
          "There is no resultant moment about any point.",
          "Both conditions must hold at the same time.",
        ],
        ask: "Give one condition about the resultant force and one about the resultant moment.",
      },
      {
        kind: "choice",
        question: "What is meant by the centre of gravity of an object?",
        options: [
          "The single point where the whole weight of the object seems to act",
          "The exact geometric middle of every object",
          "The point where the object is pivoted",
          "The heaviest single part of the object",
        ],
        correct: 0,
        ask: "Think about where you could imagine the entire weight of an object being concentrated.",
        hints: [
          "Weight is spread through an object, but it acts as if it were all at one point.",
          "That point is the centre of gravity, where the whole weight seems to act.",
        ],
        explain: "The centre of gravity is the single point where the whole weight of the object seems to act. For a uniform, regular object it lies at the centre, but for an irregular object it can be found by experiment.",
      },
      {
        kind: "choice",
        question: "An irregular card is hung freely from a pin, with a plumb-line hanging from the same pin. When the card stops swinging, where does its centre of gravity lie?",
        figure: "fig-05-12-plumb-experiment",
        options: [
          "Somewhere along the vertical plumb-line, directly below the pin",
          "Directly above the pin",
          "Exactly at the pin",
          "At the lowest corner of the card",
        ],
        correct: 0,
        ask: "A freely hanging object settles so that its centre of gravity hangs directly below the point of support. What does the plumb-line show?",
        hints: [
          "When it settles, the centre of gravity is vertically below the pin.",
          "The plumb-line marks that vertical, so the centre of gravity lies somewhere along it.",
        ],
        explain: "When the card settles, its centre of gravity hangs directly below the pin, so it lies somewhere along the vertical plumb-line. Repeating from a second point and finding where the lines cross locates the centre of gravity.",
      },
      {
        kind: "order",
        prompt: "Put the steps of the plumb-line method for finding the centre of gravity of an irregular card into the correct order.",
        items: [
          "Hang the card freely from a pin so it can swing",
          "Hang a plumb-line from the same pin",
          "Wait until the card and the plumb-line stop swinging",
          "Draw the line of the plumb-line across the card",
          "Repeat from another point and mark where the 2 lines cross",
        ],
        ask: "Start by hanging the card so it can swing, and finish by finding the point where the marked lines meet. Put the steps in order.",
        hints: [
          "First hang the card and a plumb-line from the same point, then let them settle.",
          "After drawing the first vertical line, repeat from a different point; the crossing point is the centre of gravity.",
        ],
        explain: "You hang the card from a pin, hang a plumb-line from the same pin, let them settle, and draw the vertical line on the card. Repeating from another point gives a second line, and the centre of gravity is where the 2 lines cross.",
      },
      {
        kind: "cloze",
        prompt: "Complete the sentences about the centre of gravity.",
        segments: [
          "The centre of gravity of a regular, uniform shape lies at its ",
          ". When an object hangs freely, it settles with its centre of gravity ",
          " the point of ",
          ".",
        ],
        bank: ["centre", "below", "suspension", "above", "edge"],
        answer: ["centre", "below", "suspension"],
        ask: "Think where the centre of gravity sits for a symmetrical shape, and where it settles when an object hangs freely.",
        hints: [
          "For a regular, uniform shape the centre of gravity is at its centre.",
          "A freely hanging object settles with its centre of gravity below the point of suspension.",
        ],
        explain: "The centre of gravity of a regular, uniform shape lies at its centre. When an object hangs freely it settles with its centre of gravity below the point of suspension.",
      },
      {
        kind: "open",
        prompt: "Describe how you would use a plumb-line to find the centre of gravity of an irregular flat card (a lamina).",
        modelAnswer: "Hang the card freely from a pin near its edge so that it can swing, and hang a plumb-line from the same pin. When the card and plumb-line have stopped swinging, draw a line along the plumb-line onto the card, because the centre of gravity lies directly below the pin along that vertical. Hang the card from a different point and repeat to draw a second line. The centre of gravity is the point where the 2 lines cross.",
        marks: [
          "Hang the card freely from a pin with a plumb-line from the same point.",
          "Let it settle and draw the vertical plumb-line on the card.",
          "Repeat from another point; the centre of gravity is where the lines cross.",
        ],
        ask: "Explain what you hang the card from, why the plumb-line is vertical, and how a second line locates the centre of gravity.",
      },
      {
        kind: "choice",
        question: "Which change makes an object more stable?",
        options: [
          "Lowering its centre of gravity and making its base wider",
          "Raising its centre of gravity",
          "Making its base narrower",
          "Making it taller and thinner",
        ],
        correct: 0,
        ask: "Stability improves with a low centre of gravity and a broad base. Which option does both?",
        hints: [
          "A lower centre of gravity is harder to tip over.",
          "A wider base also makes an object more stable, so the best answer combines both.",
        ],
        explain: "An object is more stable when its centre of gravity is lower and its base is wider. Both changes make it harder to tip the vertical line through the centre of gravity outside the base.",
      },
      {
        kind: "choice",
        question: "An object resting on a table is tilted more and more. At what point will it topple over?",
        options: [
          "When the vertical line through its centre of gravity passes outside its base",
          "When the vertical line through its centre of gravity stays inside its base",
          "As soon as it is tilted at all",
          "Only if its centre of gravity is lowered",
        ],
        correct: 0,
        ask: "Watch the vertical line drawn down from the centre of gravity. The object rights itself while that line stays over the base. When does it topple?",
        hints: [
          "While the vertical line through the centre of gravity falls inside the base, the object falls back.",
          "It topples once that vertical line passes outside the edge of the base.",
        ],
        explain: "The object topples when the vertical line through its centre of gravity falls outside its base. While that line stays inside the base, the object's weight turns it back upright.",
      },
      {
        kind: "classify",
        prompt: "Sort each object by whether it is more stable or less stable.",
        bins: ["More stable", "Less stable"],
        items: [
          { text: "a racing car with a wide base and a low body", bin: 0 },
          { text: "a bus with heavy luggage loaded onto its roof", bin: 1 },
          { text: "a cone resting on its broad flat base", bin: 0 },
          { text: "a tall thin vase on a narrow foot", bin: 1 },
          { text: "a Bunsen burner with a broad, heavy base", bin: 0 },
          { text: "a cone balanced on its pointed tip", bin: 1 },
        ],
        ask: "A low centre of gravity and a wide base give more stability; a high centre of gravity or a narrow base give less. Tap each one and drop it in its bin.",
        hints: [
          "A wide base and a low, heavy bottom mean more stable.",
          "Weight high up or a narrow base mean less stable.",
        ],
        explain: "The racing car, the cone on its flat base, and the Bunsen burner all have a low centre of gravity and a wide base, so they are more stable. The roof-loaded bus, the tall narrow vase, and the cone on its tip all have a high centre of gravity or a narrow base, so they are less stable.",
      },
      {
        kind: "order",
        prompt: "Put these objects in order from least stable to most stable.",
        items: [
          "a pencil balanced on its sharp point",
          "a tall bottle standing upright",
          "a thick book lying on its largest face",
          "a wide flat tray resting on the table",
        ],
        ask: "Think about the base width and how high the centre of gravity is. Start with the one that topples most easily.",
        hints: [
          "A tiny base and a high centre of gravity is the least stable.",
          "A wide base and a low centre of gravity is the most stable.",
        ],
        explain: "The pencil on its point has almost no base, so it is least stable. The tall bottle is next, then the book lying flat, and the wide flat tray has the widest base and lowest centre of gravity, so it is most stable.",
      },
      {
        kind: "open",
        prompt: "Explain how the width of an object's base and the height of its centre of gravity affect its stability, and state the condition under which a tilted object will topple.",
        modelAnswer: "An object is more stable when it has a wider base and a lower centre of gravity, because these make it harder to tilt it far enough to fall over. When an object is tilted, a vertical line can be drawn down from its centre of gravity. While that line stays inside the base, the weight provides a moment that turns the object back upright, but once the line passes outside the base the weight turns the object over, so it topples.",
        marks: [
          "A wider base gives greater stability.",
          "A lower centre of gravity gives greater stability.",
          "The object topples when the vertical line through its centre of gravity falls outside its base.",
        ],
        ask: "Link base width and centre of gravity height to stability, then describe where the vertical line through the centre of gravity must fall for the object to topple.",
      },
    ],
  },
];
