import type { Subconcept } from "@/lib/teaching/subconcepts";

// T14 Current of Electricity, Revision 2. Checkpoint over KB Chapter 16,
// sections t14.4 to t14.6: resistors in series and parallel, R = rho l / A,
// Ohm's law and I-V characteristics. Question-only.

export const BOXES: Subconcept[] = [
  {
    id: "t14.rev2",
    code: "R2",
    title: "Revision 2",
    blurb: "Checkpoint: series and parallel resistors, resistivity, Ohm's law",
    kind: "revision",
    steps: [
      {
        kind: "choice",
        question: "3 resistors of 6 ohm, 4 ohm and 10 ohm are connected in series. What is their combined resistance?",
        options: ["16 ohm", "20 ohm", "24 ohm", "10 ohm"],
        correct: 1,
        ask: "Series resistances simply add, so work out 6 + 4 + 10. Which option is that?",
        hints: [
          "For resistors in series the effective resistance is R1 plus R2 plus R3.",
          "6 + 4 + 10 is 20 ohms, which is larger than any single resistor.",
        ],
        working: [
          { label: "Formula", latex: "R_E = R_1 + R_2 + R_3" },
          { label: "Substitute", latex: "R_E = 6 + 4 + 10" },
          { label: "Answer", latex: "R_E = 20\\ \\Omega" },
        ],
        explain: "The combined resistance is 20 ohms, because series resistors carry the same current and add, so 6 + 4 + 10 is 20 ohms. The total is always larger than any one resistor.",
      },
      {
        kind: "choice",
        question: "A 3 ohm, a 6 ohm and another 6 ohm resistor are connected in parallel. Find the effective resistance.",
        figure: "fig-16-11-parallel-resistors",
        options: ["15 ohm", "6 ohm", "3 ohm", "1.5 ohm"],
        correct: 3,
        ask: "For parallel resistors add the reciprocals: 1 over 3 + 1 over 6 + 1 over 6. What does that reciprocal come to?",
        hints: [
          "Use 1 over R equals 1 over 3 + 1 over 6 + 1 over 6.",
          "1 over 3 + 1 over 6 + 1 over 6 is 4 over 6, so R is 6 ÷ 4, which is 1.5 ohms.",
        ],
        working: [
          { label: "Formula", latex: "\\frac{1}{R_E} = \\frac{1}{R_1} + \\frac{1}{R_2} + \\frac{1}{R_3}" },
          { label: "Substitute", latex: "\\frac{1}{R_E} = \\frac{1}{3} + \\frac{1}{6} + \\frac{1}{6} = \\frac{4}{6}" },
          { label: "Answer", latex: "R_E = 1.5\\ \\Omega" },
        ],
        explain: "The effective resistance is 1.5 ohms, because the reciprocals give 4 over 6, so R is 6 ÷ 4. A parallel combination is always smaller than the smallest single resistor, here smaller than 3 ohms.",
      },
      {
        kind: "choice",
        question: "When several resistors are connected in parallel, the effective resistance is...",
        options: ["smaller than any one of them", "equal to the largest one", "larger than any one of them", "equal to their sum"],
        correct: 0,
        ask: "Adding another parallel path gives the current more routes to flow. Does that make it easier or harder for current to pass?",
        hints: [
          "Every extra parallel path opens another route, so more current flows for the same p.d.",
          "More current for the same p.d. means less resistance, so the combination is smaller than any single resistor.",
        ],
        explain: "The effective resistance is smaller than any one of them, because each parallel path gives the current another route, so more current flows for the same p.d. Adding the values only ever applies to a series circuit.",
      },
      {
        kind: "choice",
        question: "An iron wire has a resistance of 6 ohm. If its length is doubled while everything else stays the same, what is its new resistance?",
        options: ["3 ohm", "6 ohm", "12 ohm", "36 ohm"],
        correct: 2,
        ask: "Resistance is proportional to length, so doubling the length doubles the resistance. What is 2 × 6?",
        hints: [
          "From R equals rho l over A, resistance is proportional to length when rho and A stay fixed.",
          "Doubling the length doubles the resistance, and 2 × 6 is 12 ohms.",
        ],
        working: [
          { label: "Formula", latex: "R = \\frac{\\rho l}{A}\\ \\Rightarrow\\ R \\propto l" },
          { label: "Substitute", latex: "R_{new} = 2 \\times 6" },
          { label: "Answer", latex: "R_{new} = 12\\ \\Omega" },
        ],
        explain: "The new resistance is 12 ohms, because resistance is proportional to length, so doubling the length doubles the resistance from 6 ohms to 12 ohms. Doubling the area instead would have halved it to 3 ohms.",
      },
      {
        kind: "choice",
        question: "Which statement about an ohmic conductor at constant temperature is correct?",
        options: [
          "Its resistance rises as the current rises",
          "Its I-V graph is a curve that bends over",
          "It conducts in one direction only",
          "Its current is proportional to the p.d. across it",
        ],
        correct: 3,
        ask: "Ohm's law says how current and p.d. are related for such a conductor at fixed temperature. What is that relationship?",
        hints: [
          "For an ohmic conductor at constant temperature, V divided by I stays constant.",
          "A constant ratio means the current is proportional to the p.d., giving a straight line through the origin.",
        ],
        explain: "The current is proportional to the p.d., which is Ohm's law, so V over I stays constant and the I-V graph is a straight line through the origin. The bending curve belongs to a filament lamp and one-way conduction to a diode.",
      },
      {
        kind: "graphpick",
        prompt: "Which I-V graph belongs to an ohmic conductor kept at constant temperature?",
        xLabel: "V",
        yLabel: "I",
        options: [
          { points: [[0, 0], [1, 1], [2, 2], [3, 3]], caption: "A straight line through the origin" },
          { points: [[0, 0], [1, 1.4], [2, 2.2], [3, 2.6]], caption: "A curve that bends over towards the V axis" },
          { points: [[0, 0], [1, 0], [2, 0], [2.5, 1.5]], caption: "No current until a threshold, then a rise" },
          { points: [[0, 1.5], [1, 1.5], [2, 1.5], [3, 1.5]], caption: "A flat horizontal line" },
        ],
        correct: 0,
        ask: "An ohmic conductor has current proportional to p.d., so its graph passes through the origin as a straight line. Which shape matches?",
        hints: [
          "Proportional means that doubling the p.d. doubles the current.",
          "That gives a straight line through the origin, not a curve or a flat line.",
        ],
        explain: "The straight line through the origin is the ohmic conductor, because current proportional to p.d. gives a constant ratio V over I. The bending curve is a filament lamp and the delayed rise is a diode.",
      },
      {
        kind: "tiles",
        prompt: "2 8 ohm resistors are in parallel, and that pair is in series with a 4 ohm resistor. Build the working that gives the effective resistance.",
        tiles: [
          "1/R_p = 1/8 + 1/8",
          "R_p = 4 ohm",
          "R_E = 4 + 4",
          "R_E = 8 ohm",
          "R_E = 8 + 8",
          "R_p = 16 ohm",
        ],
        answer: ["1/R_p = 1/8 + 1/8", "R_p = 4 ohm", "R_E = 4 + 4", "R_E = 8 ohm"],
        ask: "Combine the parallel pair first, then add the 4 ohm resistor in series. 2 8 ohm resistors in parallel give what?",
        hints: [
          "2 equal resistors in parallel give half of one, so 8 in parallel with 8 is 4 ohms.",
          "Then add the series resistor: 4 + 4 is 8 ohms.",
        ],
        working: [
          { label: "Formula", latex: "\\frac{1}{R_p} = \\frac{1}{R_1} + \\frac{1}{R_2},\\quad R_E = R_p + R_3" },
          { label: "Substitute", latex: "\\frac{1}{R_p} = \\frac{1}{8} + \\frac{1}{8},\\quad R_E = 4 + 4" },
          { label: "Answer", latex: "R_E = 8\\ \\Omega" },
        ],
        explain: "The effective resistance is 8 ohms, because 8 ohms in parallel with 8 ohms is 4 ohms, and adding the 4 ohm series resistor gives 4 + 4, which is 8 ohms. Always combine the parallel part before adding the series part.",
      },
      {
        kind: "slider",
        prompt: "3 identical resistors in series give 36 ohm. Set the slider to the resistance of the same 3 connected in parallel, in ohm.",
        min: 0,
        max: 40,
        step: 0.1,
        unit: "ohm",
        start: 0,
        targetMin: 3.9,
        targetMax: 4.1,
        ask: "If 3 equal resistors add to 36 ohms in series, each one is 12 ohms. Now combine 3 12 ohm resistors in parallel.",
        hints: [
          "Each resistor is 36 ÷ 3, which is 12 ohms.",
          "In parallel, 1 over R equals 3 × 1 over 12, which is 1 over 4, so R is 4 ohms.",
        ],
        working: [
          { label: "Formula", latex: "\\frac{1}{R_E} = \\frac{1}{R_1} + \\frac{1}{R_2} + \\frac{1}{R_3}" },
          { label: "Substitute", latex: "\\frac{1}{R_E} = \\frac{1}{12} + \\frac{1}{12} + \\frac{1}{12} = \\frac{1}{4}" },
          { label: "Answer", latex: "R_E = 4\\ \\Omega" },
        ],
        explain: "The parallel resistance is 4 ohms, because each resistor is 12 ohms and 3 of them in parallel give 12 ÷ 3. That is 32 ohms less than the 36 ohms they give in series.",
      },
      {
        kind: "spoterror",
        prompt: "A student combines 2 6 ohm resistors joined in parallel. Find the line with the mistake.",
        lines: [
          "2 6 ohm resistors are joined in parallel.",
          "Parallel resistors combine by reciprocals: 1/R_E = 1/R1 + 1/R2.",
          "1/R_E = 1/6 + 1/6 = 2/6.",
          "So R_E = 6 + 6 = 12 ohm.",
        ],
        errorLine: 3,
        ask: "The reciprocal working on the line above already gives 2 over 6. Check whether the final line uses that, or wrongly adds the resistances instead.",
        hints: [
          "1 over R equals 2 over 6, so R should be 6 ÷ 2.",
          "The last line adds the resistors as if they were in series, which is wrong for a parallel pair.",
        ],
        explain: "The last line is wrong, because it adds the resistors like a series circuit. Since 1 over R is 2 over 6, R is 6 ÷ 2, which is 3 ohms, smaller than either resistor.",
      },
      {
        kind: "cloze",
        prompt: "Complete the summary of series and parallel resistors.",
        segments: [
          "In a ",
          " circuit the current is the same through every resistor, and the resistances ",
          ". In a parallel circuit the effective resistance is ",
          " than the smallest resistor.",
        ],
        bank: ["series", "add", "smaller", "parallel", "subtract", "larger"],
        answer: ["series", "add", "smaller"],
        ask: "Recall which arrangement shares one current and adds up, and whether a parallel combination ends up bigger or smaller than its parts.",
        hints: [
          "The same current flows through every resistor when they are in series, and their values add.",
          "A parallel combination gives the current extra paths, so it is smaller than any single resistor.",
        ],
        explain: "In a series circuit the current is the same through every resistor and the resistances add. In a parallel circuit the effective resistance is smaller than the smallest resistor, because each path carries part of the current.",
      },
      {
        kind: "open",
        prompt: "Explain why the I-V graph of a filament lamp is a curve rather than a straight line.",
        figure: "fig-16-13-iv-filament",
        modelAnswer: "As the current through the filament increases, the filament gets hotter. The rising temperature makes the metal ions vibrate more, so the electrons collide with them more often and the resistance rises. Because the resistance is no longer constant, the current is not proportional to the p.d., so the I-V graph bends over into a curve instead of a straight line.",
        marks: [
          "A larger current heats the filament, raising its temperature.",
          "Higher temperature means more collisions, so the resistance rises.",
          "Resistance is not constant, so current is not proportional to p.d. and the graph curves.",
        ],
        ask: "Think about what happens to the filament's temperature as the current grows, and how temperature changes the resistance of a metal.",
      },
      {
        kind: "open",
        prompt: "Describe how you would find the effective resistance of a circuit in which a parallel pair of resistors is connected in series with a third resistor.",
        modelAnswer: "First combine the parallel pair using 1 over R_p equals 1 over R1 + 1 over R2, then take the reciprocal to get R_p. This single value replaces the parallel pair. Then add the third resistor in series, R_E equals R_p plus R3, because series resistances add. The result is the effective resistance of the whole circuit.",
        marks: [
          "Combine the parallel pair first using the reciprocal rule.",
          "Take the reciprocal to get the parallel resistance R_p.",
          "Add the series resistor: R_E = R_p + R3.",
        ],
        ask: "Decide which part of the circuit you must simplify first, then think about how a series resistor is combined with that result.",
      },
    ],
  },
];
