import type { Subconcept } from "@/lib/teaching/subconcepts";

// T11 Electromagnetic Waves, topical quiz. Whole-topic check across KB Chapter 13:
// what an EM wave is, the spectrum, common properties and v = f lambda, uses of each
// region, and the harmful effects of the high-frequency end.

export const BOXES: Subconcept[] = [
  {
    id: "t11.quiz",
    code: "Quiz",
    title: "Electromagnetic waves topical quiz",
    blurb: "Whole-topic check: EM waves, the spectrum, v = f lambda, uses, and dangers",
    kind: "quiz",
    steps: [
      {
        kind: "choice",
        question: "Which statement correctly describes an electromagnetic wave?",
        figure: "fig-13-01-em-wave-structure",
        options: [
          "It is a longitudinal wave that needs a medium to travel",
          "Its electric and magnetic fields vibrate along the direction of travel",
          "Its electric and magnetic fields vibrate at right angles to each other and to the direction of travel",
          "It is a mechanical wave carried by vibrating particles",
        ],
        correct: 2,
        ask: "In an electromagnetic wave a changing electric field and a changing magnetic field oscillate together. Think about which directions those 2 fields point compared with the direction of travel.",
        hints: [
          "The electric field and the magnetic field are at 90 degrees to each other.",
          "Both fields also vibrate at right angles to the direction the wave travels, which makes it a transverse wave.",
        ],
        explain: "An electromagnetic wave has an electric field and a magnetic field vibrating at right angles to each other and to the direction of travel. Because the vibrations are at right angles to the travel direction, it is a transverse wave, not a longitudinal or mechanical one.",
      },
      {
        kind: "choice",
        question: "Sunlight reaches the Earth across the empty space between the Sun and our planet. What does this show about electromagnetic waves?",
        options: [
          "They can only travel through air",
          "They need no medium and can travel through a vacuum",
          "They slow down and stop in empty space",
          "They are carried by vibrating air particles",
        ],
        correct: 1,
        ask: "There is almost no matter between the Sun and the Earth, yet the light still gets through. What does that tell you about whether these waves need a material to travel in?",
        hints: [
          "Mechanical waves like sound need particles, but electromagnetic waves do not.",
          "Because sunlight crosses empty space, electromagnetic waves need no medium and can travel through a vacuum.",
        ],
        explain: "It shows that electromagnetic waves need no medium and can travel through a vacuum. Sunlight crosses the empty space between the Sun and the Earth, which a wave that needed particles, like sound, could never do.",
      },
      {
        kind: "cloze",
        prompt: "Complete the sentences about the shared features of all electromagnetic waves.",
        segments: [
          "Every electromagnetic wave is a ",
          " wave that can travel through a ",
          ". In empty space all electromagnetic waves travel at the same ",
          ".",
        ],
        bank: ["transverse", "vacuum", "speed", "longitudinal", "medium"],
        answer: ["transverse", "vacuum", "speed"],
        ask: "Think about the wave type set by the field directions, whether these waves need matter, and what is identical for all of them in empty space.",
        hints: [
          "The fields vibrate at right angles to the travel direction, so the wave type is transverse.",
          "Electromagnetic waves cross a vacuum, and in it they all share the same speed, 3.0 × 10 to the power 8 metres per second.",
        ],
        explain: "Every electromagnetic wave is a transverse wave that can travel through a vacuum, and in empty space they all travel at the same speed, 3.0 × 10 to the power 8 metres per second.",
      },
      {
        kind: "open",
        prompt: "Describe what an electromagnetic wave is and explain why it is called a transverse wave.",
        modelAnswer: "An electromagnetic wave is produced when an electric charge vibrates or accelerates. A changing electric field creates a changing magnetic field, and the 2 fields oscillate at right angles to each other and to the direction of travel. Because the vibrations are at right angles to the direction of travel, it is a transverse wave. Electromagnetic waves transfer energy and need no medium, so they can cross a vacuum at 3.0 × 10 to the power 8 metres per second.",
        marks: [
          "An electromagnetic wave is made by a vibrating or accelerating charge, with linked electric and magnetic fields.",
          "The fields oscillate at right angles to each other and to the direction of travel.",
          "It is transverse because the vibrations are at right angles to the direction of travel.",
          "It transfers energy and needs no medium, travelling at 3.0 × 10 to the power 8 metres per second in a vacuum.",
        ],
        ask: "Describe the 2 fields and the directions they vibrate in, then link that to the meaning of the word transverse.",
      },
      {
        kind: "order",
        prompt: "Put the seven regions of the electromagnetic spectrum in order of increasing frequency, from lowest to highest.",
        items: [
          "Radio waves",
          "Microwaves",
          "Infrared",
          "Visible light",
          "Ultraviolet",
          "X-rays",
          "Gamma rays",
        ],
        ask: "Start with the region that has the lowest frequency and longest wavelength, and finish with the one that has the highest frequency and most energy.",
        hints: [
          "Radio waves have the lowest frequency, and gamma rays have the highest.",
          "The order is radio, microwaves, infrared, visible light, ultraviolet, X-rays, gamma rays.",
        ],
        explain: "In order of increasing frequency the regions are radio waves, microwaves, infrared, visible light, ultraviolet, X-rays, gamma rays. As you go along this list the frequency and energy rise while the wavelength falls.",
      },
      {
        kind: "choice",
        question: "Which region of the electromagnetic spectrum has the longest wavelength?",
        options: ["Radio waves", "Visible light", "X-rays", "Gamma rays"],
        correct: 0,
        ask: "Wavelength is longest at the low-frequency end of the spectrum. Which region sits at that end?",
        hints: [
          "The longest wavelengths belong to the region with the lowest frequency.",
          "Radio waves are at the low-frequency end, so they have the longest wavelength.",
        ],
        explain: "Radio waves have the longest wavelength. They sit at the low-frequency end of the spectrum, where the wavelength is greatest, while gamma rays at the other end have the shortest.",
      },
      {
        kind: "choice",
        question: "Which region has the highest frequency and carries the most energy?",
        options: ["Radio waves", "Microwaves", "Infrared", "Gamma rays"],
        correct: 3,
        ask: "Energy rises with frequency across the spectrum. Which region is right at the high-frequency end?",
        hints: [
          "The most energetic waves are at the high-frequency end of the spectrum.",
          "Gamma rays have the highest frequency, so they carry the most energy.",
        ],
        explain: "Gamma rays have the highest frequency and carry the most energy. They lie at the top of the frequency scale, which is why they are the most penetrating and the most ionising.",
      },
      {
        kind: "match",
        prompt: "Match each region to the fact that describes its place in the spectrum.",
        pairs: [
          { left: "Radio waves", right: "The longest wavelength of all the regions" },
          { left: "Gamma rays", right: "The highest frequency and the most energy" },
          { left: "Red light", right: "The longest wavelength of visible light" },
          { left: "Violet light", right: "The shortest wavelength of visible light" },
          { left: "X-rays", right: "A higher frequency than ultraviolet" },
        ],
        ask: "Work from the ends inward. One region has the longest wavelength overall, one has the highest frequency, and within visible light red and violet sit at opposite ends.",
        hints: [
          "Radio waves have the longest wavelength and gamma rays the highest frequency.",
          "In visible light red has the longest wavelength and violet the shortest, and X-rays have a higher frequency than ultraviolet.",
        ],
        explain: "Radio waves have the longest wavelength and gamma rays the highest frequency and energy. Within visible light red has the longest wavelength and violet the shortest, and X-rays have a higher frequency than ultraviolet.",
      },
      {
        kind: "open",
        prompt: "Describe how the frequency, wavelength and energy of the waves change as you move across the spectrum from radio waves to gamma rays.",
        figure: "fig-13-02-em-spectrum",
        modelAnswer: "As you move from radio waves to gamma rays the frequency increases and the energy increases, while the wavelength decreases. Radio waves have the lowest frequency, longest wavelength and least energy, and gamma rays have the highest frequency, shortest wavelength and most energy.",
        marks: [
          "The frequency increases from radio waves to gamma rays.",
          "The wavelength decreases from radio waves to gamma rays.",
          "The energy increases from radio waves to gamma rays.",
        ],
        ask: "Take each of the 3 quantities in turn, and say whether it rises or falls as you go from the radio end to the gamma end.",
      },
      {
        kind: "choice",
        question: "Orange light has a wavelength of 5.0 x 10^{-7} m. Using v = 3.0 x 10^{8} m/s, find its frequency.",
        options: [
          "6.0 x 10^{13} Hz",
          "6.0 x 10^{14} Hz",
          "1.5 x 10^{15} Hz",
          "6.0 x 10^{7} Hz",
        ],
        correct: 1,
        ask: "Frequency is the speed divided by the wavelength, so work out 3.0 × 10 to the power 8 ÷ 5.0 × 10 to the power negative 7.",
        hints: [
          "Rearrange v equals f lambda into f equals v divided by lambda.",
          "3.0 ÷ 5.0 is 0.6, and 10 to the power 8 ÷ 10 to the power negative 7 is 10 to the power 15, giving 6.0 × 10 to the power 14 hertz.",
        ],
        working: [
          { label: "Formula", latex: "f = \\dfrac{v}{\\lambda}" },
          { label: "Substitute", latex: "f = \\dfrac{3.0 \\times 10^{8}}{5.0 \\times 10^{-7}}" },
          { label: "Answer", latex: "f = 6.0 \\times 10^{14}\\ \\text{Hz}" },
        ],
        explain: "The frequency is 6.0 × 10 to the power 14 hertz, because 3.0 × 10 to the power 8 ÷ 5.0 × 10 to the power negative 7 is 6.0 × 10 to the power 14.",
      },
      {
        kind: "choice",
        question: "An X-ray has a frequency of 1.5 x 10^{18} Hz. Using v = 3.0 x 10^{8} m/s, find its wavelength.",
        options: [
          "2.0 x 10^{-9} m",
          "5.0 x 10^{9} m",
          "2.0 x 10^{-10} m",
          "4.5 x 10^{26} m",
        ],
        correct: 2,
        ask: "Wavelength is the speed divided by the frequency, so work out 3.0 × 10 to the power 8 ÷ 1.5 × 10 to the power 18.",
        hints: [
          "Rearrange v equals f lambda into lambda equals v divided by f.",
          "3.0 ÷ 1.5 is 2.0, and 10 to the power 8 ÷ 10 to the power 18 is 10 to the power negative 10, giving 2.0 × 10 to the power negative 10 metres.",
        ],
        working: [
          { label: "Formula", latex: "\\lambda = \\dfrac{v}{f}" },
          { label: "Substitute", latex: "\\lambda = \\dfrac{3.0 \\times 10^{8}}{1.5 \\times 10^{18}}" },
          { label: "Answer", latex: "\\lambda = 2.0 \\times 10^{-10}\\ \\text{m}" },
        ],
        explain: "The wavelength is 2.0 × 10 to the power negative 10 metres, because 3.0 × 10 to the power 8 ÷ 1.5 × 10 to the power 18 is 2.0 × 10 to the power negative 10.",
      },
      {
        kind: "tiles",
        prompt: "Red-orange light has a wavelength of 6.0 x 10^{-7} m. Using v = 3.0 x 10^{8} m/s, build the working line for its frequency f, using f = v / lambda.",
        tiles: [
          "f =",
          "\\dfrac{3.0 \\times 10^{8}}{6.0 \\times 10^{-7}}",
          "=",
          "5.0 \\times 10^{14}",
          "Hz",
          "6.0 \\times 10^{14}",
          "m",
        ],
        answer: [
          "f =",
          "\\dfrac{3.0 \\times 10^{8}}{6.0 \\times 10^{-7}}",
          "=",
          "5.0 \\times 10^{14}",
          "Hz",
        ],
        ask: "Frequency is the speed over the wavelength, so divide 3.0 × 10 to the power 8 by 6.0 × 10 to the power negative 7, and remember the unit is hertz.",
        hints: [
          "Use f equals v divided by lambda.",
          "3.0 ÷ 6.0 is 0.5, and 10 to the power 8 ÷ 10 to the power negative 7 is 10 to the power 15, giving 5.0 × 10 to the power 14 hertz.",
        ],
        working: [
          { label: "Formula", latex: "f = \\dfrac{v}{\\lambda}" },
          { label: "Substitute", latex: "f = \\dfrac{3.0 \\times 10^{8}}{6.0 \\times 10^{-7}}" },
          { label: "Answer", latex: "f = 5.0 \\times 10^{14}\\ \\text{Hz}" },
        ],
        explain: "The frequency is 5.0 × 10 to the power 14 hertz, because 3.0 × 10 to the power 8 ÷ 6.0 × 10 to the power negative 7 is 5.0 × 10 to the power 14.",
      },
      {
        kind: "tiles",
        prompt: "A long-wave radio station transmits at 6.0 x 10^{5} Hz. Using v = 3.0 x 10^{8} m/s, build the working line for its wavelength lambda, using lambda = v / f.",
        tiles: [
          "\\lambda =",
          "\\dfrac{3.0 \\times 10^{8}}{6.0 \\times 10^{5}}",
          "=",
          "5.0 \\times 10^{2}",
          "m",
          "2.0 \\times 10^{-3}",
          "Hz",
        ],
        answer: [
          "\\lambda =",
          "\\dfrac{3.0 \\times 10^{8}}{6.0 \\times 10^{5}}",
          "=",
          "5.0 \\times 10^{2}",
          "m",
        ],
        ask: "Wavelength is the speed over the frequency, so divide 3.0 × 10 to the power 8 by 6.0 × 10 to the power 5, and remember the unit is metres.",
        hints: [
          "Use lambda equals v divided by f.",
          "3.0 ÷ 6.0 is 0.5, and 10 to the power 8 ÷ 10 to the power 5 is 10 to the power 3, giving 5.0 × 10 to the power 2 metres, which is 500 metres.",
        ],
        working: [
          { label: "Formula", latex: "\\lambda = \\dfrac{v}{f}" },
          { label: "Substitute", latex: "\\lambda = \\dfrac{3.0 \\times 10^{8}}{6.0 \\times 10^{5}}" },
          { label: "Answer", latex: "\\lambda = 5.0 \\times 10^{2}\\ \\text{m}" },
        ],
        explain: "The wavelength is 5.0 × 10 to the power 2 metres, which is 500 metres, because 3.0 × 10 to the power 8 ÷ 6.0 × 10 to the power 5 is 5.0 × 10 to the power 2.",
      },
      {
        kind: "spoterror",
        prompt: "An FM radio wave has a frequency of 9.0 x 10^{7} Hz (take v = 3.0 x 10^{8} m/s). Here is a student's working to find its wavelength. Tap the line with the mistake.",
        lines: [
          "\\lambda = \\dfrac{v}{f}",
          "\\lambda = \\dfrac{3.0 \\times 10^{8}}{9.0 \\times 10^{7}}",
          "\\lambda = 33\\ \\text{m}",
        ],
        errorLine: 2,
        ask: "Check the last step. Work out 3.0 × 10 to the power 8 ÷ 9.0 × 10 to the power 7 for yourself and compare it with the value written.",
        hints: [
          "3.0 ÷ 9.0 is 0.33, and 10 to the power 8 ÷ 10 to the power 7 is 10, so the answer is about 3.3.",
          "The final line should read 3.3 metres, not 33 metres.",
        ],
        working: [
          { label: "Formula", latex: "\\lambda = \\dfrac{v}{f}" },
          { label: "Substitute", latex: "\\lambda = \\dfrac{3.0 \\times 10^{8}}{9.0 \\times 10^{7}}" },
          { label: "Answer", latex: "\\lambda = 3.3\\ \\text{m}" },
        ],
        explain: "The mistake is on the last line. 3.0 × 10 to the power 8 ÷ 9.0 × 10 to the power 7 is about 3.3, so the wavelength is 3.3 metres, not 33 metres.",
      },
      {
        kind: "graphpick",
        prompt: "For electromagnetic waves in a vacuum the speed is fixed at 3.0 x 10^{8} m/s. Which graph best shows how the wavelength depends on the frequency?",
        xLabel: "frequency",
        yLabel: "wavelength",
        options: [
          { points: [[1, 12], [2, 6], [3, 4], [4, 3], [6, 2]], caption: "Wavelength falls steeply then flattens as frequency rises" },
          { points: [[0, 0], [1, 3], [2, 6], [3, 9], [4, 12]], caption: "Wavelength rises in proportion to frequency" },
          { points: [[0, 6], [1, 6], [2, 6], [3, 6], [4, 6]], caption: "Wavelength stays constant" },
          { points: [[0, 12], [1, 9], [2, 6], [3, 3], [4, 0]], caption: "Wavelength falls in a straight line to zero" },
        ],
        correct: 0,
        ask: "Rearrange v equals f lambda into lambda equals v divided by f. With v fixed, think about what happens to the wavelength as the frequency gets larger.",
        hints: [
          "Because lambda equals v divided by f, wavelength and frequency are inversely related.",
          "As the frequency rises the wavelength falls quickly at first and then more slowly, forming a curve, not a straight line.",
        ],
        explain: "The correct graph is the curve that falls steeply and then flattens. Since lambda equals v divided by f with v fixed, doubling the frequency halves the wavelength, so the relationship is an inverse curve rather than a straight line or a constant.",
      },
      {
        kind: "choice",
        question: "A ray of light passes from a vacuum into a glass block. Which quantity stays the same?",
        options: ["The frequency", "The speed", "The wavelength", "The direction"],
        correct: 0,
        ask: "One property of the wave is fixed by the source and does not change when the light enters glass. Think about which one that is.",
        hints: [
          "The speed drops and the wavelength shrinks inside the glass, and the direction can bend.",
          "The frequency is set by the source, so it stays the same as the light enters the glass.",
        ],
        explain: "The frequency stays the same because it is fixed by the source. The speed decreases in the glass and the wavelength decreases with it, and this drop in speed is what makes the light refract.",
      },
      {
        kind: "open",
        prompt: "Explain why a leaf appears green when white light shines on it.",
        figure: "fig-13-03-leaf-reflection",
        modelAnswer: "White light is a mixture of all the colours. When it falls on the leaf, the leaf absorbs most of the wavelengths and reflects the green wavelengths. Only the reflected green light reaches the eye, so the leaf looks green. The colour of a surface is the light it reflects rather than absorbs.",
        marks: [
          "White light contains all the colours or wavelengths.",
          "The leaf absorbs most wavelengths and reflects the green ones.",
          "Only the reflected green light reaches the eye, so the leaf looks green.",
        ],
        ask: "Think about what white light is made of, which colours the leaf absorbs, and which colour reaches your eye.",
      },
      {
        kind: "match",
        prompt: "Match each region of the spectrum to a real use.",
        pairs: [
          { left: "Radio waves", right: "Broadcasting television and radio programmes" },
          { left: "Microwaves", right: "Satellite links and mobile-phone signals" },
          { left: "Infrared", right: "Remote controls and thermal imaging" },
          { left: "Ultraviolet", right: "Sterilising water and security marking" },
          { left: "X-rays", right: "Taking images of broken bones" },
          { left: "Gamma rays", right: "Radiotherapy to treat cancer" },
        ],
        ask: "Match each region to its everyday use. Lower-energy waves tend to be used for communication, and higher-energy waves for imaging or treatment inside the body.",
        hints: [
          "Radio waves broadcast programmes, microwaves carry phone and satellite signals, and infrared runs remote controls.",
          "Ultraviolet sterilises and marks security features, X-rays image bones, and gamma rays are used in radiotherapy.",
        ],
        explain: "Radio waves broadcast television and radio, microwaves carry satellite and mobile-phone signals, and infrared drives remote controls and thermal imaging. Ultraviolet sterilises water and marks security features, X-rays image broken bones, and gamma rays are used for radiotherapy.",
      },
      {
        kind: "classify",
        prompt: "Sort each use under the region of the spectrum it belongs to.",
        bins: ["Infrared", "Microwaves", "X-rays"],
        items: [
          { text: "a television remote control", bin: 0 },
          { text: "a thermal imaging camera", bin: 0 },
          { text: "a satellite television link", bin: 1 },
          { text: "a WiFi router", bin: 1 },
          { text: "imaging a broken bone", bin: 2 },
          { text: "an airport luggage scanner", bin: 2 },
        ],
        ask: "Group the uses by the type of wave. Heat and remote controls point one way, wireless communication another, and imaging dense objects a third.",
        hints: [
          "Remote controls and thermal cameras use infrared, while WiFi and satellite links use microwaves.",
          "X-rays pass through soft tissue but are stopped by bone and metal, so they image bones and scan luggage.",
        ],
        explain: "Remote controls and thermal imaging cameras use infrared. Satellite links and WiFi routers use microwaves. Imaging a broken bone and scanning luggage at an airport both use X-rays, which pass through soft material but are stopped by dense material.",
      },
      {
        kind: "choice",
        question: "Which electromagnetic waves are used to sterilise surgical instruments?",
        options: ["Radio waves", "Microwaves", "Infrared", "Gamma rays"],
        correct: 3,
        ask: "Sterilising means killing microbes, which needs highly energetic, penetrating waves. Which region is the most energetic?",
        hints: [
          "The waves used must carry enough energy to kill bacteria on the instruments.",
          "Gamma rays are the most energetic and penetrating, so they are used to sterilise medical instruments.",
        ],
        explain: "Gamma rays are used to sterilise surgical instruments. They carry so much energy and penetrate so well that they kill the bacteria on the instruments, even through sealed packaging.",
      },
      {
        kind: "choice",
        question: "Which electromagnetic waves are used to take images of broken bones?",
        options: ["Radio waves", "X-rays", "Infrared", "Microwaves"],
        correct: 1,
        ask: "The waves used must pass through soft flesh but be stopped by bone so the bone shows up. Which region does that?",
        hints: [
          "The waves need to be blocked by dense bone while passing through softer tissue.",
          "X-rays pass through flesh but are absorbed by bone, so they are used to image fractures.",
        ],
        explain: "X-rays are used to image broken bones. They pass through soft tissue but are absorbed by the denser bone, so the bones show up clearly on the image.",
      },
      {
        kind: "open",
        prompt: "State one use each for infrared, ultraviolet and gamma rays.",
        modelAnswer: "Infrared is used in television remote controls, in grills and toasters, or in thermal imaging cameras. Ultraviolet is used to sterilise water, to make security markings that glow, or to help the skin make vitamin D. Gamma rays are used to sterilise medical instruments, in radiotherapy to treat cancer, or to find cracks in metal.",
        marks: [
          "A correct use of infrared, such as remote controls, heating or thermal imaging.",
          "A correct use of ultraviolet, such as sterilising water, security marking or making vitamin D.",
          "A correct use of gamma rays, such as sterilising instruments, radiotherapy or finding cracks in metal.",
        ],
        ask: "Give one clear everyday or medical use for each of the 3 regions named.",
      },
      {
        kind: "classify",
        prompt: "Sort each type of electromagnetic wave by whether it is ionising or non-ionising.",
        bins: ["Non-ionising", "Ionising"],
        items: [
          { text: "radio waves", bin: 0 },
          { text: "microwaves", bin: 0 },
          { text: "infrared", bin: 0 },
          { text: "ultraviolet", bin: 1 },
          { text: "X-rays", bin: 1 },
          { text: "gamma rays", bin: 1 },
        ],
        ask: "Ionising waves carry enough energy to knock electrons out of atoms, and these are the high-frequency ones. Sort each type into the right bin.",
        hints: [
          "The low-frequency waves, radio, microwaves and infrared, are non-ionising.",
          "The high-frequency waves, ultraviolet, X-rays and gamma rays, are ionising.",
        ],
        explain: "Radio waves, microwaves and infrared are non-ionising and carry too little energy to remove electrons. Ultraviolet, X-rays and gamma rays are ionising, because their high energy can knock electrons out of atoms and damage cells.",
      },
      {
        kind: "choice",
        question: "Why are gamma rays more dangerous to living cells than radio waves?",
        options: [
          "Gamma rays have a longer wavelength",
          "Gamma rays travel faster than radio waves",
          "Gamma rays have a much higher frequency and energy and are ionising",
          "Radio waves cannot pass through the body",
        ],
        correct: 2,
        ask: "All electromagnetic waves travel at the same speed, so speed is not the reason. Think about how much energy each carries and whether it can ionise atoms.",
        hints: [
          "Both waves travel at 3.0 × 10 to the power 8 metres per second, so speed is not the difference.",
          "Gamma rays have a far higher frequency and energy, which makes them ionising and able to damage cells.",
        ],
        explain: "Gamma rays are more dangerous because they have a much higher frequency and energy and are ionising, so they can knock electrons from atoms and damage or kill living cells. Radio waves are low-energy and non-ionising, and both types travel at the same speed.",
      },
      {
        kind: "open",
        prompt: "Explain why the high-frequency end of the electromagnetic spectrum is more dangerous to living cells than the low-frequency end.",
        modelAnswer: "The high-frequency waves, ultraviolet, X-rays and gamma rays, carry much more energy than low-frequency waves. This energy makes them ionising, so they can knock electrons out of atoms. That damages or kills living cells and can cause mutations and cancer. Too much ultraviolet also heats and burns the skin. Radio waves and microwaves are low-energy and non-ionising, so they are much less harmful.",
        marks: [
          "High-frequency waves carry much more energy than low-frequency waves.",
          "They are ionising, knocking electrons out of atoms.",
          "This damages or kills cells and can cause mutations or cancer.",
          "Low-frequency waves such as radio and microwaves are non-ionising and less harmful.",
        ],
        ask: "Link the higher frequency to more energy, then to ionisation, and then to the harm done to cells.",
      },
    ],
  },
];
