import type { Subconcept } from "@/lib/teaching/subconcepts";

// T3 Dynamics, topical quiz. Whole-topic check across KB Chapters 03 (Mass and Weight)
// and 04 (Forces): contact and non-contact forces, mass and inertia, gravitational field
// and g, weight, Newton's laws, resultant force, friction, and falling.

export const BOXES: Subconcept[] = [
  {
    id: "t3.quiz",
    code: "Quiz",
    title: "Dynamics topical quiz",
    blurb: "Whole-topic check: forces, mass, weight, Newton's laws, friction, falling",
    kind: "quiz",
    steps: [
      {
        kind: "choice",
        question: "Which of these is a contact force?",
        options: ["The gravitational force", "The magnetic force", "Friction", "The electrostatic force"],
        correct: 2,
        ask: "A contact force only acts while the 2 objects are touching. Which one needs the surfaces to meet?",
        hints: [
          "Gravity, magnetism and the electrostatic force all reach across a gap.",
          "Friction only acts where 2 surfaces are actually touching.",
        ],
        explain: "Friction is a contact force, because it only acts where 2 surfaces touch. The gravitational, magnetic and electrostatic forces all act across a gap, so they are non-contact forces.",
      },
      {
        kind: "choice",
        question: "2 trolleys are pushed with the same force. Trolley A has a mass of 2 kg and trolley B has a mass of 8 kg. Which statement is correct?",
        options: [
          "Trolley B is harder to get moving because it has more inertia",
          "Trolley A is harder to get moving because it has more inertia",
          "Both trolleys change their motion equally easily",
          "The heavier trolley has less inertia",
        ],
        correct: 0,
        ask: "Inertia is an object's resistance to a change in its motion, and it grows with mass. Which trolley has the larger mass?",
        hints: [
          "A larger mass has more inertia and resists changes in motion more.",
          "Trolley B has 8 kilograms, which is more than the 2 kilograms of trolley A.",
        ],
        explain: "Trolley B is harder to get moving, because its 8 kilograms give it more inertia than the 2 kilograms of trolley A. More mass means more resistance to a change in motion.",
      },
      {
        kind: "open",
        prompt: "Explain what inertia is and how it is related to the mass of an object.",
        modelAnswer: "Inertia is the tendency of an object to resist a change in its motion, whether that is starting to move, stopping, or changing direction. The greater the mass of an object, the greater its inertia, so a heavy object is harder to start moving or to stop than a light one.",
        marks: [
          "Inertia is the resistance of an object to a change in its motion.",
          "A larger mass means greater inertia.",
          "A heavier object is harder to start or to stop moving.",
        ],
        ask: "Think about what inertia resists, and whether a heavy or a light object is harder to get moving.",
      },
      {
        kind: "choice",
        question: "On the Moon the gravitational field strength is 1.6 N/kg. What does this tell you?",
        options: [
          "Each kilogram of mass is pulled with a force of 1.6 N",
          "The mass of an object becomes 1.6 kg on the Moon",
          "An object has no weight on the Moon",
          "Gravity does not act on the Moon",
        ],
        correct: 0,
        ask: "Gravitational field strength is the force of gravity on each kilogram of mass. What does 1.6 newtons per kilogram mean for 1 kilogram?",
        hints: [
          "The unit newtons per kilogram tells you the pull on every kilogram of mass.",
          "On the Moon each kilogram is pulled with 1.6 newtons, so a 1 kilogram mass weighs 1.6 newtons there.",
        ],
        explain: "It tells you that every kilogram of mass on the Moon is pulled with a force of 1.6 newtons. The mass does not change, but the weight is smaller because the field is weaker than the 10 newtons per kilogram on Earth.",
      },
      {
        kind: "choice",
        question: "A 3 kg bag rests on the Earth, where g = 10 N/kg. Find its weight W.",
        options: ["30 N", "3 N", "13 N", "0.3 N"],
        correct: 0,
        ask: "Weight is mass times g, so work out 3 × 10. Which option matches?",
        hints: [
          "Use W equals m times g.",
          "3 × 10 is 30, and weight is measured in newtons.",
        ],
        working: [
          { label: "Formula", latex: "W = mg" },
          { label: "Substitute", latex: "W = 3 \\times 10" },
          { label: "Answer", latex: "W = 30\\ \\text{N}" },
        ],
        explain: "The weight is 30 newtons, because 3 kilograms times 10 newtons per kilogram is 30 newtons.",
      },
      {
        kind: "slider",
        prompt: "A 3 kg mass is taken to the Moon, where g is 1.6 N/kg. Set the slider to its weight, in newtons.",
        min: 0,
        max: 30,
        step: 0.1,
        unit: "N",
        start: 0,
        targetMin: 4.7,
        targetMax: 4.9,
        ask: "On the Moon the weight is still mass times g, so work out 3 × 1.6.",
        hints: [
          "Use W equals m times g, with g equal to 1.6 on the Moon.",
          "3 × 1.6 is 4.8, so slide to 4.8 newtons.",
        ],
        working: [
          { label: "Formula", latex: "W = mg" },
          { label: "Substitute", latex: "W = 3 \\times 1.6" },
          { label: "Answer", latex: "W = 4.8\\ \\text{N}" },
        ],
        explain: "The weight on the Moon is 4.8 newtons, because 3 kilograms times 1.6 newtons per kilogram is 4.8 newtons. The same mass would weigh 30 newtons on Earth.",
      },
      {
        kind: "spoterror",
        prompt: "A 3 kg mass sits on the Earth (g = 10 N/kg). Here is a student's working to find its weight. Tap the line with the mistake.",
        lines: ["W = mg", "W = m \\div g", "W = 3 \\div 10", "W = 0.3\\ \\text{N}"],
        errorLine: 1,
        ask: "Check how weight relates to mass and g. In W equals m g, do you multiply the mass by g or divide by it?",
        hints: [
          "Weight is mass times g, written W equals m g.",
          "The line that divides 3 by 10 is wrong; it should be 3 × 10, giving 30 newtons.",
        ],
        working: [
          { label: "Formula", latex: "W = mg" },
          { label: "Substitute", latex: "W = 3 \\times 10" },
          { label: "Answer", latex: "W = 30\\ \\text{N}" },
        ],
        explain: "The mistake is on the line that writes W equals m divided by g. Weight is mass times g, so W equals 3 × 10, which is 30 newtons, not 0.3 newtons.",
      },
      {
        kind: "open",
        prompt: "Explain the difference between the mass and the weight of an object, and say whether each changes when the object is taken from the Earth to the Moon.",
        modelAnswer: "Mass is the amount of matter in an object, a scalar measured in kilograms, and it is the same on the Earth and the Moon. Weight is the gravitational force on that mass, a vector measured in newtons, given by W = mg. Because g is about 10 newtons per kilogram on Earth but only 1.6 on the Moon, the weight is smaller on the Moon while the mass stays the same.",
        marks: [
          "Mass is the amount of matter, a scalar in kilograms.",
          "Weight is the gravitational force, a vector in newtons, given by W = mg.",
          "Mass stays the same, but weight is smaller on the Moon because g is smaller.",
        ],
        ask: "For each quantity think about what it measures, its unit, and whether it depends on g.",
      },
      {
        kind: "choice",
        question: "A resultant force acts on a moving ball. Which of these can it do?",
        options: [
          "Change the ball's speed only",
          "Change the ball's direction only",
          "Change the ball's speed, its direction, or its shape",
          "Keep the ball's velocity exactly constant",
        ],
        correct: 2,
        ask: "Think of every way a push or a pull can affect an object, not just its speed.",
        hints: [
          "A resultant force can speed an object up, slow it down, or change its direction.",
          "A force can also change an object's shape, so the fullest answer includes all of these.",
        ],
        explain: "A resultant force can change an object's speed, its direction of motion, or its shape. It cannot leave the velocity unchanged, because an unbalanced force always causes a change in motion.",
      },
      {
        kind: "classify",
        prompt: "Sort each situation by whether the forces on the object are balanced or unbalanced.",
        bins: ["Balanced forces", "Unbalanced forces"],
        items: [
          { text: "a car cruising at a steady 20 m/s", bin: 0 },
          { text: "a book lying still on a desk", bin: 0 },
          { text: "a skydiver falling at terminal velocity", bin: 0 },
          { text: "a stone speeding up as it falls freely", bin: 1 },
          { text: "a car braking to a stop", bin: 1 },
          { text: "a rocket accelerating upward", bin: 1 },
        ],
        ask: "Balanced forces give a zero resultant, so the motion does not change: the object is at rest or moving at constant velocity. Tap each situation and drop it in its bin.",
        hints: [
          "If the velocity is steady or the object is still, the forces are balanced.",
          "If the object is speeding up, slowing down, or changing direction, the forces are unbalanced.",
        ],
        explain: "A car at a steady speed, a book at rest, and a skydiver at terminal velocity all have balanced forces and a zero resultant. A falling stone speeding up, a braking car, and an accelerating rocket all have unbalanced forces, so their motion changes.",
      },
      {
        kind: "choice",
        question: "A spacecraft drifts through deep space at a steady velocity with its engines off. What is the resultant force on it?",
        options: [
          "Zero",
          "A steady force in the direction of motion",
          "A force that grows with time",
          "A backward force that slows it",
        ],
        correct: 0,
        ask: "By Newton's first law, an object keeps a constant velocity only when the forces on it are balanced. What resultant does that mean?",
        hints: [
          "Constant velocity means the acceleration is zero.",
          "With zero acceleration the resultant force must be zero, by Newton's first law.",
        ],
        explain: "The resultant force is zero. By Newton's first law, an object moving at constant velocity has balanced forces, so it needs no resultant force to keep going.",
      },
      {
        kind: "choice",
        question: "A ball is pulled by 2 forces at right angles: 12 N to the east and 9 N to the north. Find the size of the resultant force.",
        options: ["15 N", "21 N", "3 N", "108 N"],
        correct: 0,
        ask: "The 2 forces are at right angles, so use Pythagoras: square them, add, then take the square root of 12 squared plus 9^2.",
        hints: [
          "For 2 forces at right angles, the resultant is the square root of the sum of their squares.",
          "12 squared is 144 and 9^2 is 81; 144 + 81 is 225, and the square root of 225 is 15.",
        ],
        working: [
          { label: "Formula", latex: "R = \\sqrt{F_1^2 + F_2^2}" },
          { label: "Substitute", latex: "R = \\sqrt{12^2 + 9^2}" },
          { label: "Answer", latex: "R = 15\\ \\text{N}" },
        ],
        explain: "The resultant is 15 newtons, because 12 squared plus 9^2 is 144 + 81, which is 225, and the square root of 225 is 15 newtons.",
      },
      {
        kind: "choice",
        question: "A resultant force of 12 N acts on a 4 kg trolley. Find its acceleration.",
        options: ["3 m/s^2", "48 m/s^2", "0.33 m/s^2", "16 m/s^2"],
        correct: 0,
        ask: "Acceleration is the resultant force divided by the mass, so work out 12 ÷ 4. Which option matches?",
        hints: [
          "Rearrange F equals m a into a equals F divided by m.",
          "12 ÷ 4 is 3, in metres per second squared.",
        ],
        working: [
          { label: "Formula", latex: "a = \\dfrac{F}{m}" },
          { label: "Substitute", latex: "a = \\dfrac{12}{4}" },
          { label: "Answer", latex: "a = 3\\ \\text{m/s}^2" },
        ],
        explain: "The acceleration is 3 metres per second squared, because 12 newtons divided by 4 kilograms is 3 metres per second squared.",
      },
      {
        kind: "slider",
        prompt: "A 4 kg box is pushed forward with 30 N while friction pulls back with 6 N. Set the slider to the box's acceleration, in m/s^2.",
        min: 0,
        max: 20,
        step: 0.1,
        unit: "m/s^2",
        start: 0,
        targetMin: 5.9,
        targetMax: 6.1,
        ask: "First combine the forces: 30 - 6 gives the resultant. Then divide by the 4 kilogram mass.",
        hints: [
          "The resultant force is 30 - 6, which is 24 newtons.",
          "24 ÷ 4 is 6, so slide to 6 metres per second squared.",
        ],
        working: [
          { label: "Formula", latex: "a = \\dfrac{F}{m}" },
          { label: "Substitute", latex: "a = \\dfrac{30 - 6}{4}" },
          { label: "Answer", latex: "a = 6\\ \\text{m/s}^2" },
        ],
        explain: "The resultant force is 30 - 6, which is 24 newtons, so the acceleration is 24 ÷ 4, giving 6 metres per second squared.",
      },
      {
        kind: "tiles",
        prompt: "A 5 kg mass has a resultant force that gives it an acceleration of 2 m/s^2. Build the working line for the resultant force F.",
        tiles: ["F =", "5", "\\times", "2", "=", "10", "N", "kg"],
        answer: ["F =", "5", "\\times", "2", "=", "10", "N"],
        ask: "The resultant force is mass times acceleration, so set up 5 × 2.",
        hints: [
          "Use F equals m times a.",
          "5 × 2 is 10, and force is measured in newtons.",
        ],
        working: [
          { label: "Formula", latex: "F = ma" },
          { label: "Substitute", latex: "F = 5 \\times 2" },
          { label: "Answer", latex: "F = 10\\ \\text{N}" },
        ],
        explain: "The resultant force is 10 newtons, because 5 kilograms times 2 metres per second squared is 10 newtons.",
      },
      {
        kind: "match",
        prompt: "Match each law or term to the statement that defines it.",
        pairs: [
          { left: "Newton's first law", right: "A body stays at rest or at constant velocity unless a resultant force acts" },
          { left: "Newton's second law", right: "Resultant force equals mass times acceleration" },
          { left: "Newton's third law", right: "Every action has an equal and opposite reaction on the other body" },
          { left: "Balanced forces", right: "Zero resultant force, so no acceleration" },
        ],
        ask: "Match each item to its statement. One is about staying still or steady, one links force to acceleration, and one is about pairs of forces.",
        hints: [
          "The first law is about balanced forces and constant velocity; the second law links resultant force, mass and acceleration.",
          "The third law is about action and reaction pairs, equal and opposite, on 2 different objects.",
        ],
        explain: "Newton's first law is about a body staying at rest or at constant velocity unless a resultant force acts. The second law says resultant force equals mass times acceleration. The third law says every action has an equal and opposite reaction on the other body. Balanced forces give a zero resultant and no acceleration.",
      },
      {
        kind: "choice",
        question: "A swimmer pushes backward on the water with her hands. By Newton's third law, what is the reaction force?",
        options: [
          "The water pushes forward on the swimmer with an equal force",
          "The water pushes backward on the swimmer",
          "The swimmer pushes harder than the water pushes back",
          "There is no reaction force in water",
        ],
        correct: 0,
        ask: "A third-law pair is equal in size, opposite in direction, and acts on the other body. If the swimmer pushes the water backward, what does the water do to her?",
        hints: [
          "Action and reaction are equal in size and opposite in direction.",
          "The reaction acts on the swimmer, pushing her forward as she pushes the water back.",
        ],
        explain: "The water pushes forward on the swimmer with an equal and opposite force. That reaction on the swimmer is what drives her forward through the water.",
      },
      {
        kind: "open",
        prompt: "State Newton's third law and give one everyday example.",
        modelAnswer: "Newton's third law says that when one object exerts a force on a second object, the second exerts a force on the first that is equal in size and opposite in direction. The 2 forces act on different objects. For example, when you step off a boat you push backward on the boat and the boat pushes you forward with an equal force.",
        marks: [
          "The forces are equal in size and opposite in direction.",
          "The 2 forces act on 2 different objects.",
          "A correct everyday example with the pair of forces named.",
        ],
        ask: "Say what is equal, what is opposite, and which objects the 2 forces act on.",
      },
      {
        kind: "open",
        prompt: "A book rests on a flat table. Describe the forces acting on the book and explain why it stays at rest.",
        figure: "fig-03-01-normal-force",
        modelAnswer: "2 forces act on the book. Its weight acts downward, pulling it toward the Earth, and the normal force from the table acts upward. The 2 forces are equal in size and opposite in direction, so the resultant force is zero. With no resultant force the book stays at rest.",
        marks: [
          "The weight acts downward on the book.",
          "The normal force from the table acts upward.",
          "The 2 forces are equal and opposite, so the resultant is zero and the book stays at rest.",
        ],
        ask: "Name the downward force and the upward force on the book, and compare their sizes.",
      },
      {
        kind: "cloze",
        prompt: "Complete the sentence about a crate that slides across the floor at a steady speed.",
        segments: [
          "When the crate moves at a ",
          " velocity its acceleration is zero, so the resultant force is ",
          ". The forward push is then exactly balanced by the ",
          " acting backward.",
        ],
        bank: ["constant", "zero", "friction", "weight", "increasing"],
        answer: ["constant", "zero", "friction"],
        ask: "A steady velocity means no acceleration. Think about what the resultant force must be, and which backward force balances the push.",
        hints: [
          "Constant velocity means zero acceleration and therefore a zero resultant force.",
          "The backward force on a sliding crate is friction, which balances the forward push.",
        ],
        explain: "At constant velocity the acceleration is zero, so the resultant force is zero, and the forward push is exactly balanced by the friction acting backward.",
      },
      {
        kind: "choice",
        question: "A raindrop falls and reaches terminal velocity. Which statement is then true?",
        options: [
          "Its weight is balanced by air resistance, so it falls at a constant velocity",
          "The air resistance on it is now zero",
          "It keeps accelerating at 10 m/s^2",
          "Its weight has become zero",
        ],
        correct: 0,
        ask: "At terminal velocity the drop stops speeding up. What must be true about the up and down forces for that to happen?",
        hints: [
          "Terminal velocity means zero acceleration, so the resultant force is zero.",
          "At that point the air resistance upward has grown to equal the weight downward.",
        ],
        explain: "At terminal velocity the upward air resistance has grown until it equals the downward weight. The resultant force is zero, so the raindrop falls at a constant velocity.",
      },
      {
        kind: "order",
        prompt: "Put these stages of a skydiver reaching terminal velocity in the correct order.",
        items: [
          "The skydiver jumps and speeds up under gravity",
          "Air resistance grows as the speed increases",
          "Air resistance grows until it equals the weight",
          "The resultant force becomes zero",
          "The skydiver falls at a constant terminal velocity",
        ],
        ask: "Start from the moment she jumps and speeds up, and finish when her speed stops changing. Put the stages in order.",
        hints: [
          "At first mainly her weight acts, so she accelerates and speeds up.",
          "As she goes faster the air resistance grows until it equals her weight, giving a zero resultant and a constant terminal velocity.",
        ],
        explain: "First she jumps and speeds up under gravity. As she goes faster, air resistance grows, until it equals her weight. The resultant force then becomes zero, so she falls at a constant terminal velocity.",
      },
      {
        kind: "tiles",
        prompt: "An object falls freely from rest for 4 s (take g = 10 m/s^2). Build the working line for its speed v, using v = g t.",
        tiles: ["v =", "10", "\\times", "4", "=", "40", "m/s", "s"],
        answer: ["v =", "10", "\\times", "4", "=", "40", "m/s"],
        ask: "In free fall the speed is g times the time, so set up 10 × 4.",
        hints: [
          "Use v equals g times t, with g equal to 10 metres per second squared.",
          "10 × 4 is 40, and speed is measured in metres per second.",
        ],
        working: [
          { label: "Formula", latex: "v = gt" },
          { label: "Substitute", latex: "v = 10 \\times 4" },
          { label: "Answer", latex: "v = 40\\ \\text{m/s}" },
        ],
        explain: "The speed is 40 metres per second, because in free fall the speed gained is g times the time, and 10 × 4 is 40 metres per second.",
      },
      {
        kind: "graphpick",
        prompt: "A ball falls from a tall tower and meets air resistance. Which velocity-time graph best shows its motion until it reaches terminal velocity?",
        xLabel: "time / s",
        yLabel: "velocity / m/s",
        options: [
          { points: [[0, 0], [1, 7], [2, 11], [3, 13], [4, 14], [5, 14]], caption: "Rises steeply, then levels off" },
          { points: [[0, 0], [1, 10], [2, 20], [3, 30], [4, 40]], caption: "Rises as a straight line" },
          { points: [[0, 14], [1, 14], [2, 14], [3, 14], [4, 14]], caption: "Constant from the start" },
          { points: [[0, 40], [1, 30], [2, 20], [3, 10], [4, 0]], caption: "Falls steadily to zero" },
        ],
        correct: 0,
        ask: "The ball speeds up at first, but as air resistance grows the speeding up eases off until the speed stays constant. Which graph rises and then levels out?",
        hints: [
          "Free fall with no air resistance would be a straight rising line, but here air resistance grows.",
          "The correct graph rises steeply at first, then curves and flattens as the ball reaches terminal velocity.",
        ],
        explain: "The correct graph rises steeply at first and then curves and levels off. The ball speeds up while its weight is greater than the air resistance, and it reaches a constant terminal velocity when the 2 forces balance.",
      },
      {
        kind: "open",
        prompt: "A skydiver jumps from a plane and later reaches terminal velocity. Explain why her speed increases at first and then becomes constant.",
        modelAnswer: "At first her weight is much larger than the air resistance, so there is a downward resultant force and she accelerates. As she speeds up the air resistance grows. Eventually the air resistance equals her weight, so the resultant force is zero, the acceleration is zero, and she falls at a constant terminal velocity.",
        marks: [
          "At first the weight is greater than the air resistance, giving a downward resultant force and acceleration.",
          "Air resistance increases as the speed increases.",
          "At terminal velocity the air resistance equals the weight, the resultant force is zero, so the speed is constant.",
        ],
        ask: "Compare the weight and the air resistance at the start and later, and link the resultant force to the change in speed.",
      },
    ],
  },
];