import type { Subconcept } from "@/lib/teaching/subconcepts";

// T1 Measurement, topical quiz. Whole-topic check across KB Chapter 01 (Measurement):
// physical quantities and SI base units, derived quantities, prefixes and conversions,
// standard form, measuring length and its instruments, parallax, end and zero error,
// precision of instruments, and measuring time with the simple pendulum. Question-only.
// Figures follow the apparatus colour note: white object being measured, grey rulers,
// scales and leader lines, green correct tick, red wrong cross.

export const BOXES: Subconcept[] = [
  {
    id: "t1.quiz",
    code: "Quiz",
    title: "Measurement topical quiz",
    blurb: "Whole-topic check: quantities, prefixes, standard form, length, precision, time",
    kind: "quiz",
    steps: [
      {
        kind: "choice",
        question: "A student writes the result of a measurement as just 4.5. Why is this not a complete measurement?",
        figure: "fig-01-01-measurement-anatomy",
        options: [
          "It has no unit, so you cannot tell what it measures",
          "The number is too small to be useful",
          "A measurement must always be a whole number",
          "A measurement must never use a decimal point",
        ],
        correct: 0,
        ask: "A complete measurement has 2 parts, a number and a unit. Which part is missing from 4.5?",
        hints: [
          "Every physical quantity is a numerical magnitude together with a unit.",
          "Without a unit, 4.5 could mean 4.5 metres, 4.5 kilograms, or anything else.",
        ],
        explain: "The measurement is not complete without a unit. The number 4.5 gives the magnitude, but with no unit you cannot tell whether it means 4.5 metres, 4.5 seconds, or something else. In the figure the grey leader lines label the number as the magnitude and kg as the unit.",
      },
      {
        kind: "choice",
        question: "Which of these is an SI base quantity?",
        options: ["Speed", "Mass", "Density", "Volume"],
        correct: 1,
        ask: "A base quantity is not built from any other quantity. Which one of these stands on its own?",
        hints: [
          "Speed, volume and density are all built by multiplying or dividing other quantities.",
          "Mass is one of the 5 SI base quantities, with the base unit the kilogram.",
        ],
        explain: "Mass is an SI base quantity, with the base unit the kilogram. Speed, volume and density are derived quantities, because each is built from base quantities by multiplying or dividing.",
      },
      {
        kind: "choice",
        question: "What is the SI unit of density?",
        options: ["kg/m^3", "m^3", "kg", "m/s"],
        correct: 0,
        ask: "Density is mass divided by volume, so combine the unit of mass with the unit of volume.",
        hints: [
          "Mass is measured in kilograms and volume in cubic metres.",
          "Dividing kilograms by cubic metres gives kilograms per cubic metre.",
        ],
        explain: "Density is mass divided by volume, so its unit is kilograms per cubic metre, written kg/m^3. It is a derived unit, built from the base units for mass and length.",
      },
      {
        kind: "choice",
        question: "The prefix milli stands for which factor?",
        options: ["10^-3", "10^3", "10^-6", "10^6"],
        correct: 0,
        ask: "Milli makes a unit smaller by a factor of 1000. Which power of 10 is 1000th?",
        hints: [
          "Milli means 1000th of the unit.",
          "One thousandth is 10 to the power minus 3.",
        ],
        explain: "The prefix milli stands for 10 to the power minus 3, which is 1000th. For example, 1 millimetre is 1000th of a metre.",
      },
      {
        kind: "choice",
        question: "Express 32 mm in kilometres, in standard form. (1 km = 10^6 mm)",
        options: ["3.2 x 10^-5 km", "3.2 x 10^-4 km", "3.2 x 10^-2 km", "3.2 x 10^5 km"],
        correct: 0,
        ask: "There are 10 to the power 6 millimetres in 1 kilometre, so divide 32 by 10 to the power 6.",
        hints: [
          "1 kilometre is 10 to the power 6 millimetres.",
          "32 divided by 10 to the power 6 is 3.2 times 10 to the power minus 5.",
        ],
        working: [
          { label: "Formula", latex: "1\\ \\text{km} = 10^{6}\\ \\text{mm}" },
          { label: "Substitute", latex: "32 \\div 10^{6}" },
          { label: "Answer", latex: "3.2 \\times 10^{-5}\\ \\text{km}" },
        ],
        explain: "32 millimetres is 3.2 times 10 to the power minus 5 kilometres, because there are 10 to the power 6 millimetres in a kilometre, and 32 divided by 10 to the power 6 is 3.2 times 10 to the power minus 5.",
      },
      {
        kind: "choice",
        question: "Which instrument is best for measuring the diameter of a thin wire?",
        options: [
          "A digital micrometer screw gauge",
          "A measuring tape",
          "A metre rule",
          "A stopwatch",
        ],
        correct: 0,
        ask: "The diameter of a thin wire is very small, so you need the instrument with the finest scale. Which one measures the smallest lengths?",
        hints: [
          "A tape and a metre rule are for lengths of centimetres up to metres, and a stopwatch measures time, not length.",
          "A digital micrometer screw gauge measures tiny lengths such as a wire diameter, to 0.001 millimetres.",
        ],
        explain: "A digital micrometer screw gauge is best for a thin wire, because it measures very small lengths to 0.001 millimetres. A tape or metre rule is far too coarse, and a stopwatch measures time, not length.",
      },
      {
        kind: "choice",
        question: "The zero end of an old wooden metre rule is worn and chipped. Which error does this most likely cause?",
        options: ["End error", "Parallax error", "A random reaction-time error", "No error at all"],
        correct: 0,
        ask: "The problem is at the end of the rule where the 0 mark sits. Which error is named after a worn or damaged end?",
        hints: [
          "Parallax error comes from the angle of your eye, not from the rule itself.",
          "A worn or chipped end of a rule causes an end error.",
        ],
        explain: "A worn or chipped end causes an end error, because the 0 mark is no longer in the right place. You can avoid it by measuring from a clear mark, such as the 1 centimetre mark, and subtracting.",
      },
      {
        kind: "choice",
        question: "An instrument has a positive zero error. How do its readings compare with the true value?",
        options: [
          "They read too large",
          "They read too small",
          "They are always correct",
          "They read zero every time",
        ],
        correct: 0,
        ask: "A positive zero error means the scale already shows a positive value before anything is measured. Does that push the readings up or down?",
        hints: [
          "With a positive zero error the scale reads above 0 when it should read 0.",
          "That extra amount is added to every reading, so the readings come out too large.",
        ],
        explain: "A positive zero error makes the readings too large, because the scale already shows a positive value before the measurement starts, and that amount is added to every reading.",
      },
      {
        kind: "choice",
        question: "Which of these instruments has the smallest division, making it the most precise?",
        options: [
          "Digital micrometer screw gauge",
          "Metre rule",
          "Measuring tape",
          "Digital calipers",
        ],
        correct: 0,
        ask: "The most precise instrument is the one that can read the smallest division. Which of these reads to 0.001 millimetres?",
        hints: [
          "A metre rule reads to 1 millimetre and digital calipers to 0.01 millimetres.",
          "A digital micrometer screw gauge reads to 0.001 millimetres, the smallest division of the 4.",
        ],
        explain: "The digital micrometer screw gauge is the most precise, because its smallest division is 0.001 millimetres. The calipers read to 0.01 millimetres and the metre rule to 1 millimetre, so they are less precise.",
      },
      {
        kind: "choice",
        question: "Which change increases the period of a simple pendulum?",
        options: [
          "Using a longer string",
          "Using a heavier bob",
          "Using a lighter bob",
          "Using a smaller angle of swing",
        ],
        correct: 0,
        ask: "The period of a pendulum depends on only 1 of these. Think about what happens to the swing time when the string is made longer.",
        hints: [
          "The period does not depend on the mass of the bob or on the size of the swing.",
          "A longer pendulum takes longer to complete each swing, so its period is larger.",
        ],
        explain: "Using a longer string increases the period, because the period of a simple pendulum depends on its length. The mass of the bob and the size of the swing do not change the period.",
      },
      {
        kind: "classify",
        prompt: "Sort each quantity by whether it is an SI base quantity or a derived quantity.",
        bins: ["Base quantity", "Derived quantity"],
        items: [
          { text: "length", bin: 0 },
          { text: "mass", bin: 0 },
          { text: "time", bin: 0 },
          { text: "speed", bin: 1 },
          { text: "volume", bin: 1 },
          { text: "density", bin: 1 },
        ],
        ask: "A base quantity stands on its own, while a derived quantity is built from base ones by multiplying or dividing. Tap each quantity and drop it in its bin.",
        hints: [
          "Length, mass and time are 3 of the 5 SI base quantities.",
          "Speed, volume and density are all built from base quantities, so they are derived.",
        ],
        explain: "Length, mass and time are SI base quantities. Speed, volume and density are derived, because speed is distance divided by time, volume is length times width times height, and density is mass divided by volume.",
      },
      {
        kind: "match",
        prompt: "Match each SI base quantity to its base unit.",
        pairs: [
          { left: "Length", right: "metre (m)" },
          { left: "Mass", right: "kilogram (kg)" },
          { left: "Time", right: "second (s)" },
          { left: "Electric current", right: "ampere (A)" },
          { left: "Temperature", right: "kelvin (K)" },
        ],
        ask: "Match each quantity to the unit it is measured in. Length is in metres, so work from there.",
        hints: [
          "Length is measured in metres and mass in kilograms.",
          "Time is in seconds, electric current in amperes, and temperature in kelvin.",
        ],
        explain: "Length is measured in metres, mass in kilograms, time in seconds, electric current in amperes, and temperature in kelvin. These are the 5 SI base units.",
      },
      {
        kind: "match",
        prompt: "Match each prefix to the factor it stands for.",
        pairs: [
          { left: "kilo", right: "10^3" },
          { left: "mega", right: "10^6" },
          { left: "milli", right: "10^-3" },
          { left: "micro", right: "10^-6" },
          { left: "nano", right: "10^-9" },
        ],
        ask: "Match each prefix to its power of 10. Kilo means 1000, so work out the others from there.",
        hints: [
          "Kilo is 10 to the power 3 and mega is 10 to the power 6.",
          "Milli is 10 to the power minus 3, micro is 10 to the power minus 6, and nano is 10 to the power minus 9.",
        ],
        explain: "Kilo stands for 10 to the power 3, mega for 10 to the power 6, milli for 10 to the power minus 3, micro for 10 to the power minus 6, and nano for 10 to the power minus 9.",
      },
      {
        kind: "tiles",
        prompt: "A block lies along a ruler from the 3.0 cm mark to the 5.4 cm mark. Build the working line for its length L.",
        tiles: ["L =", "5.4", "-", "3.0", "=", "2.4", "cm", "mm"],
        answer: ["L =", "5.4", "-", "3.0", "=", "2.4", "cm"],
        ask: "The length is the end reading minus the start reading, so set up 5.4 minus 3.0.",
        hints: [
          "Subtract the start mark from the end mark.",
          "5.4 minus 3.0 is 2.4, and the answer is in centimetres.",
        ],
        working: [
          { label: "Formula", latex: "L = x_2 - x_1" },
          { label: "Substitute", latex: "L = 5.4 - 3.0" },
          { label: "Answer", latex: "L = 2.4\\ \\text{cm}" },
        ],
        explain: "The length is 2.4 centimetres, because the block runs from 3.0 to 5.4 centimetres, and 5.4 minus 3.0 is 2.4 centimetres. Measuring from a mark other than 0 avoids any worn end of the rule.",
      },
      {
        kind: "slider",
        prompt: "Write 5 280 000 J in standard form as A x 10^6 J. Set the slider to the value of A.",
        min: 0,
        max: 10,
        step: 0.01,
        start: 0,
        targetMin: 5.27,
        targetMax: 5.29,
        ask: "Standard form needs A to be at least 1 and less than 10. Move the decimal point in 5 280 000 to find A.",
        hints: [
          "Put the decimal point just after the first digit, 5, then count how many places it moved.",
          "5 280 000 becomes 5.28 times 10 to the power 6, so A is 5.28.",
        ],
        working: [
          { label: "Formula", latex: "N = A \\times 10^{n},\\ 1 \\le A < 10" },
          { label: "Substitute", latex: "5\\,280\\,000 = 5.28 \\times 10^{6}" },
          { label: "Answer", latex: "A = 5.28" },
        ],
        explain: "In standard form 5 280 000 joules is 5.28 times 10 to the power 6 joules, so A is 5.28. A must be at least 1 and less than 10.",
      },
      {
        kind: "spoterror",
        prompt: "A student converts 0.08 m into nanometres. Tap the line with the mistake.",
        lines: [
          "1 m = 10^9 nm",
          "0.08 m = 0.08 x 10^9 nm",
          "= 8 x 10^8 nm",
        ],
        errorLine: 2,
        ask: "Check the last line. Write 0.08 in standard form first, then combine the powers of 10.",
        hints: [
          "0.08 is 8 times 10 to the power minus 2.",
          "Minus 2 plus 9 is 7, so 0.08 times 10 to the power 9 is 8 times 10 to the power 7, not 10 to the power 8.",
        ],
        working: [
          { label: "Formula", latex: "1\\ \\text{m} = 10^{9}\\ \\text{nm}" },
          { label: "Substitute", latex: "0.08\\ \\text{m} = 0.08 \\times 10^{9}\\ \\text{nm}" },
          { label: "Answer", latex: "= 8 \\times 10^{7}\\ \\text{nm}" },
        ],
        explain: "The last line is wrong. 0.08 is 8 times 10 to the power minus 2, and minus 2 plus 9 is 7, so 0.08 times 10 to the power 9 is 8 times 10 to the power 7 nanometres, not 8 times 10 to the power 8.",
      },
      {
        kind: "cloze",
        prompt: "Complete the sentence about reading a ruler correctly.",
        segments: [
          "To avoid parallax error, read the scale with your eye directly ",
          " the mark, at ",
          " degrees to the scale. A scale that does not start at ",
          " where the object sits has a zero error.",
        ],
        bank: ["above", "90", "0", "beside", "45"],
        answer: ["above", "90", "0"],
        ask: "Think about where your eye should be to avoid parallax, the angle your line of sight makes with the scale, and the reading a scale should start from.",
        hints: [
          "To avoid parallax, look straight down onto the mark, not from the side.",
          "Your line of sight should meet the scale at 90 degrees, and a good scale starts at 0.",
        ],
        explain: "To avoid parallax error, put your eye directly above the mark so your line of sight meets the scale at 90 degrees. A scale that does not start at 0 where the object sits has a zero error.",
      },
      {
        kind: "order",
        prompt: "Put these instruments in order, from the least precise to the most precise.",
        items: [
          "Metre rule, smallest division 1 mm",
          "Digital calipers, smallest division 0.01 mm",
          "Digital micrometer screw gauge, smallest division 0.001 mm",
        ],
        ask: "The most precise instrument has the smallest division. Start with the largest division and end with the smallest.",
        hints: [
          "The metre rule has the largest smallest-division at 1 millimetre, so it is the least precise.",
          "The micrometer reads to 0.001 millimetres, the smallest division, so it is the most precise.",
        ],
        explain: "From least to most precise the order is the metre rule at 1 millimetre, then the digital calipers at 0.01 millimetres, then the digital micrometer screw gauge at 0.001 millimetres. The smaller the division, the more precise the instrument.",
      },
      {
        kind: "slider",
        prompt: "A pendulum makes 20 complete oscillations in 30 s. Set the slider to its period, in seconds.",
        min: 0,
        max: 5,
        step: 0.1,
        unit: "s",
        start: 0,
        targetMin: 1.4,
        targetMax: 1.6,
        ask: "The period is the time for 1 oscillation, so divide the total time by the number of swings: 30 divided by 20.",
        hints: [
          "Use period equals total time divided by the number of oscillations.",
          "30 divided by 20 is 1.5, so slide to 1.5 seconds.",
        ],
        working: [
          { label: "Formula", latex: "T = \\dfrac{t}{20}" },
          { label: "Substitute", latex: "T = \\dfrac{30}{20}" },
          { label: "Answer", latex: "T = 1.5\\ \\text{s}" },
        ],
        explain: "The period is 1.5 seconds, because 30 seconds divided by 20 oscillations is 1.5 seconds. Timing 20 swings and dividing reduces the effect of your reaction time.",
      },
      {
        kind: "classify",
        prompt: "Sort each change by whether it changes the period of a simple pendulum.",
        bins: ["Changes the period", "Does not change the period"],
        items: [
          { text: "Using a longer pendulum", bin: 0 },
          { text: "Using a shorter pendulum", bin: 0 },
          { text: "Using a heavier bob", bin: 1 },
          { text: "Using a lighter bob", bin: 1 },
          { text: "Using a smaller angle of swing", bin: 1 },
        ],
        ask: "The period of a simple pendulum depends on its length only. Tap each change and drop it in its bin.",
        hints: [
          "Changing the length of the pendulum changes how long each swing takes.",
          "The mass of the bob and the size of the swing do not change the period.",
        ],
        explain: "Only the length changes the period, so a longer or shorter pendulum changes it. Using a heavier or lighter bob, or a smaller angle of swing, does not change the period.",
      },
      {
        kind: "open",
        prompt: "Explain what is meant by a physical quantity, and why a number on its own is not a complete measurement.",
        modelAnswer: "A physical quantity is written as a numerical magnitude together with a unit. The number tells you how much there is, and the unit tells you the standard it is measured against. A number on its own, such as 4.5, is not a complete measurement because without a unit you cannot tell whether it means 4.5 metres, 4.5 kilograms, or something else.",
        marks: [
          "A physical quantity has a numerical magnitude and a unit.",
          "The number says how much; the unit says the standard.",
          "A bare number is incomplete because the unit is missing.",
        ],
        ask: "Think about the 2 parts every measurement needs, and what is missing when only a number is given.",
      },
      {
        kind: "open",
        prompt: "Explain what standard form is and give one reason it is useful in physics.",
        modelAnswer: "Standard form writes a number as A times 10 to the power n, where A is at least 1 and less than 10, and n is a whole number. For example 5 280 000 joules is written as 5.28 times 10 to the power 6 joules. It is useful because it lets you write very large or very small numbers compactly and compare their sizes at a glance.",
        marks: [
          "Standard form is A times 10 to the power n, with A from 1 up to but not including 10.",
          "A correct example is given.",
          "It is useful for writing or comparing very large or very small numbers.",
        ],
        ask: "State the range that A must lie in, and think about the kind of numbers standard form makes easier to handle.",
      },
      {
        kind: "open",
        prompt: "A student reads a ruler from the side, with the eye at an angle to the scale. Name the error this causes and describe how to avoid it.",
        figure: "fig-01-02-parallax-error",
        modelAnswer: "Reading the scale from an angle causes a parallax error, where the mark appears to line up with the wrong value. To avoid it, place your eye directly above the mark you are reading, so your line of sight meets the scale at 90 degrees. Repeating the reading and taking an average helps as well.",
        marks: [
          "The error is a parallax error.",
          "Avoid it by reading with the eye directly above the mark, at 90 degrees to the scale.",
          "Repeating and averaging reduces the error further.",
        ],
        ask: "Name the error caused by looking from the side, then say where the eye should be when you read the mark.",
      },
      {
        kind: "open",
        prompt: "Explain what is meant by the precision of a measuring instrument, and state which is more precise, a metre rule or a digital micrometer screw gauge.",
        modelAnswer: "The precision of an instrument is the smallest division it can measure. The smaller that division, the more precise the instrument. A metre rule can measure to 0.1 centimetres, which is 1 millimetre, while a digital micrometer screw gauge can measure to 0.001 millimetres, so the micrometer is far more precise.",
        marks: [
          "Precision is the smallest division the instrument can measure.",
          "A smaller division means greater precision.",
          "The digital micrometer screw gauge is more precise than the metre rule.",
        ],
        ask: "Think about the smallest division each instrument can read, and which of the 2 has the smaller one.",
      },
      {
        kind: "open",
        prompt: "Describe how you would measure the period of a simple pendulum accurately using a stopwatch.",
        modelAnswer: "Time how long the pendulum takes to make 20 complete oscillations rather than just 1, then divide that time by 20 to find the period. Timing many swings and dividing reduces the effect of your reaction time. Repeating the measurement and taking an average makes it more reliable still. For example, if 20 oscillations take 30 seconds, the period is 30 divided by 20, which is 1.5 seconds.",
        marks: [
          "Time a number of oscillations, for example 20, not just 1.",
          "Divide the total time by the number of oscillations to get the period.",
          "Repeat and average to reduce the random error from reaction time.",
        ],
        ask: "Think about why timing 1 swing is unreliable, and what you can do with many swings to reduce the effect of your reaction time.",
      },
    ],
  },
];
