import type { Subconcept } from "@/lib/teaching/subconcepts";

// T17 Magnetism, topical quiz. Whole-topic check across KB Chapter 19: domains and
// the law of poles, induced magnetism, magnetising and demagnetising, soft and hard
// materials and storing magnets, field lines of a bar magnet, and fields between
// magnets with a plotting compass. Conceptual only: no calculations, no formulas.

export const BOXES: Subconcept[] = [
  {
    id: "t17.quiz",
    code: "Quiz",
    title: "Magnetism topical quiz",
    blurb: "Whole-topic check: poles, induced magnetism, magnetising, soft and hard materials, field lines",
    kind: "quiz",
    steps: [
      {
        kind: "choice",
        question: "What is true about the tiny atomic magnets, called domains, inside a magnetised iron bar?",
        options: [
          "They point in random directions, so their fields cancel out",
          "They vanish once the bar has been magnetised",
          "They line up pointing the same way, so their fields add together",
          "They are only found in copper and plastic",
        ],
        correct: 2,
        ask: "In a magnet the domains must all pull together. What must be true about the way they point?",
        hints: [
          "If the domains point every which way, their fields cancel and there is no magnet.",
          "A magnetised bar has its domains lined up the same way, so their fields add.",
        ],
        explain: "In a magnetised bar the domains are lined up pointing the same way, so their fields add together to make a magnet. When they point at random the fields cancel and the bar is unmagnetised.",
      },
      {
        kind: "classify",
        prompt: "Sort each material by whether it is magnetic or non-magnetic.",
        bins: ["Magnetic material", "Non-magnetic material"],
        items: [
          { text: "iron", bin: 0 },
          { text: "steel", bin: 0 },
          { text: "cobalt", bin: 0 },
          { text: "nickel", bin: 0 },
          { text: "copper", bin: 1 },
          { text: "aluminium", bin: 1 },
          { text: "wood", bin: 1 },
          { text: "plastic", bin: 1 },
        ],
        ask: "A magnetic material can be magnetised and is attracted by a magnet. Iron and the metals close to it are magnetic; most others are not. Drop each into its bin.",
        hints: [
          "Iron, cobalt, nickel and steel are the magnetic materials.",
          "Copper, aluminium, wood and plastic are not attracted by a magnet.",
        ],
        explain: "Iron, steel, cobalt and nickel are magnetic materials. Copper, aluminium, wood and plastic are non-magnetic, so a magnet does not attract them.",
      },
      {
        kind: "choice",
        question: "Why is repulsion, not attraction, the only sure test that an object is itself a magnet?",
        options: [
          "A magnet attracts any magnetic material, but only another magnet is repelled",
          "Attraction never happens between 2 magnets",
          "Repulsion is a much stronger force than attraction",
          "A magnet can only repel, never attract",
        ],
        correct: 0,
        ask: "Think about what a plain iron nail does near a magnet. Can it be attracted even though it is not a magnet?",
        hints: [
          "A magnet attracts any magnetic material, magnet or not, so attraction alone proves nothing.",
          "Only another magnet gets pushed away, so repulsion is the sure test.",
        ],
        explain: "A magnet attracts any magnetic material, whether or not it is a magnet, so attraction cannot prove it. Only another magnet is repelled, so repulsion is the only sure test.",
      },
      {
        kind: "spoterror",
        prompt: "Here are 4 statements about magnets. Tap the one statement that is wrong.",
        lines: [
          "A magnet has 2 poles, north and south, where the effect is strongest.",
          "Like poles repel and unlike poles attract.",
          "A magnet attracts any magnetic material brought near it.",
          "So attraction alone proves that an object is itself a magnet.",
        ],
        errorLine: 3,
        ask: "Check each statement against the law of poles and the test for a magnet. Which one claims too much?",
        hints: [
          "A plain iron bar, which is not a magnet, is still attracted by a magnet.",
          "Because any magnetic material is attracted, attraction cannot prove an object is a magnet; only repulsion can.",
        ],
        explain: "The wrong line is the last one. Attraction happens with any magnetic material, so it does not prove an object is a magnet. Only repulsion is the sure test.",
      },
      {
        kind: "open",
        prompt: "Using the idea of domains, explain the difference between a magnetised and an unmagnetised piece of iron.",
        figure: "fig-19-01-domains",
        modelAnswer: "Iron is made of many tiny atomic magnets grouped into regions called domains. In a magnetised piece the domains all point the same way, so their fields add up and the piece acts as a magnet with a north and a south pole. In an unmagnetised piece the domains point in random directions, so their fields cancel out and there is no overall magnetism.",
        marks: [
          "Iron contains tiny atomic magnets grouped into domains.",
          "In a magnetised piece the domains point the same way, so their fields add.",
          "In an unmagnetised piece the domains point at random, so their fields cancel.",
        ],
        ask: "Talk about how the domains point in each case, and whether their fields add or cancel.",
      },
      {
        kind: "choice",
        question: "An unmagnetised iron bar is brought near the north pole of a magnet. What pole does the near end of the bar become?",
        figure: "fig-19-04-induced-magnetism",
        options: [
          "A north pole, so the bar is repelled",
          "A south pole, so the bar is attracted",
          "No pole forms at all",
          "A north pole, so the bar is attracted",
        ],
        correct: 1,
        ask: "The bar gains induced magnetism. Remember that unlike poles attract, so the near end must be the opposite pole.",
        hints: [
          "The near end takes the opposite pole to the magnet pole it faces.",
          "Facing a north pole, the near end becomes a south pole, so unlike poles attract.",
        ],
        explain: "The near end becomes a south pole, the opposite of the magnet's north pole. Unlike poles face each other, so the bar is attracted. This is induced magnetism.",
      },
      {
        kind: "order",
        prompt: "Put these stages of a magnet picking up a chain of iron nails in the correct order.",
        items: [
          "A permanent magnet is held just above a pile of iron nails.",
          "The nail touching the magnet becomes an induced magnet.",
          "Its far end becomes a pole that induces magnetism in the next nail.",
          "A hanging chain of nails builds up, each one an induced magnet.",
          "The magnet is lifted away and the nails lose their magnetism and drop apart.",
        ],
        ask: "Start from the moment the magnet meets the first nail and finish when the magnet is removed. Put the stages in order.",
        hints: [
          "The first nail is magnetised by induction, and it then induces magnetism in the next.",
          "Once the magnet is taken away the soft iron loses its magnetism, so the chain falls apart.",
        ],
        explain: "The magnet magnetises the first nail by induction, that nail magnetises the next, and so a chain builds up. When the magnet is removed the soft iron loses its magnetism almost at once, so the nails drop apart.",
      },
      {
        kind: "cloze",
        prompt: "Complete the sentences about an iron bar held near a magnet.",
        segments: [
          "An iron bar brought near a magnet becomes a magnet itself by ",
          " magnetism. The end nearest the magnet takes the ",
          " pole, so it is attracted. When the magnet is removed the soft iron loses its magnetism almost at once, because this magnetism is only ",
          ".",
        ],
        bank: ["induced", "opposite", "temporary", "same", "permanent"],
        answer: ["induced", "opposite", "temporary"],
        ask: "Name the kind of magnetism, then the pole the near end takes, then whether it lasts. Every blank uses a word from the bank.",
        hints: [
          "A material magnetised just by being near a magnet has induced magnetism.",
          "The near end takes the opposite pole, and the effect is only temporary in soft iron.",
        ],
        explain: "The bar gains induced magnetism, its near end takes the opposite pole so it is attracted, and the effect is only temporary, so it is lost when the magnet is removed.",
      },
      {
        kind: "open",
        prompt: "A magnet held above a pile of iron nails picks up a hanging chain of them. Explain, using induced magnetism, why the chain forms and why it drops apart when the magnet is taken away.",
        figure: "fig-19-05-nail-chain",
        modelAnswer: "Each nail is magnetised by induction. The first nail becomes a magnet because it touches the permanent magnet, with its near end taking the opposite pole, so it is attracted. That nail then induces magnetism in the next, and so on, so a chain of induced magnets hangs from the magnet. Induced magnetism in soft iron is only temporary, so when the magnet is lifted away the nails lose their magnetism almost at once and drop apart.",
        marks: [
          "Each nail becomes a magnet by induction, taking the opposite pole at its near end.",
          "Each induced magnet induces magnetism in the next nail, so a chain forms.",
          "Induced magnetism is temporary, so the nails lose it and drop apart when the magnet is removed.",
        ],
        ask: "Explain how induction passes from one nail to the next, and why the chain cannot survive without the magnet.",
      },
      {
        kind: "choice",
        question: "You look end-on at a steel bar inside a d.c. solenoid, and the current runs anticlockwise. Which pole faces you?",
        options: [
          "A south pole",
          "No pole, because the field is uniform",
          "It depends only on the core material",
          "A north pole",
        ],
        correct: 3,
        ask: "Use the right-hand grip rule for a solenoid. Anticlockwise current, seen from that end, gives which pole?",
        hints: [
          "Anticlockwise current viewed end-on makes that face a north pole; clockwise makes a south pole.",
          "The letter N can be traced by the anticlockwise arrows, so it is a north pole.",
        ],
        explain: "Seen end-on, an anticlockwise current makes that end a north pole, while a clockwise current would make a south pole. This follows the right-hand grip rule.",
      },
      {
        kind: "classify",
        prompt: "Sort each method by whether it magnetises a material or demagnetises a magnet.",
        bins: ["Magnetises a material", "Demagnetises a magnet"],
        items: [
          { text: "stroking steel with one pole of a magnet", bin: 0 },
          { text: "putting steel inside a d.c. solenoid", bin: 0 },
          { text: "double-touch stroking with 2 magnets", bin: 0 },
          { text: "slowly withdrawing it from an a.c. solenoid", bin: 1 },
          { text: "hammering it repeatedly", bin: 1 },
          { text: "heating it strongly in a flame", bin: 1 },
        ],
        ask: "Magnetising lines the domains up; demagnetising leaves them random. Sort each method into its bin.",
        hints: [
          "Stroking and a steady direct current line the domains up, so they magnetise.",
          "A reversing a.c. field, hammering, and heating jumble the domains, so they demagnetise.",
        ],
        explain: "Stroking, a d.c. solenoid, and double-touch all line the domains up, so they magnetise. Slowly withdrawing from an a.c. solenoid, hammering, and heating all leave the domains random, so they demagnetise.",
      },
      {
        kind: "choice",
        question: "Which is the best way to demagnetise a steel magnet?",
        options: [
          "Place it in a d.c. solenoid and switch on",
          "Withdraw it slowly from a solenoid carrying alternating current",
          "Stroke it with one pole of another magnet",
          "Cool it in a refrigerator",
        ],
        correct: 1,
        ask: "To demagnetise you must jumble the domains. Which method uses a field that keeps reversing?",
        hints: [
          "A direct current or stroking would magnetise it, not demagnetise it.",
          "An alternating current keeps reversing the field, so slowly withdrawing the magnet leaves the domains random.",
        ],
        explain: "Withdrawing it slowly from an a.c. solenoid works, because the reversing field keeps flipping the domains and leaves them random. A d.c. solenoid or stroking would magnetise it instead.",
      },
      {
        kind: "order",
        prompt: "Put these steps of demagnetising a magnet with an a.c. solenoid in the correct order.",
        items: [
          "Place the magnet inside a solenoid carrying an alternating current.",
          "The alternating current makes the field keep reversing.",
          "Slowly withdraw the magnet from the solenoid.",
          "The domains are left pointing in random directions.",
          "The material is now demagnetised.",
        ],
        ask: "Begin by putting the magnet in the coil and finish once it has lost its magnetism. Put the steps in order.",
        hints: [
          "The magnet goes into the a.c. coil first, and the reversing field keeps flipping the domains.",
          "Withdrawing it slowly leaves the domains random, so the material ends up demagnetised.",
        ],
        explain: "The magnet is placed in the a.c. solenoid, whose field keeps reversing. As it is slowly withdrawn the domains are left pointing at random, so the material is demagnetised.",
      },
      {
        kind: "open",
        prompt: "Compare soft and hard magnetic materials, and give one everyday use of each.",
        modelAnswer: "Soft magnetic materials, such as soft iron, are easily magnetised but also lose their magnetism easily, so they make temporary magnets. They are used for electromagnet cores, relays and bells, where the magnetism needs to switch on and off. Hard magnetic materials, such as steel, are hard to magnetise but keep their magnetism, so they make permanent magnets. They are used in loudspeakers, motors and door catches. Here soft means the magnetism is easily changed, not that the material is physically soft.",
        marks: [
          "Soft material is easily magnetised and easily loses it, making a temporary magnet, used for an electromagnet core.",
          "Hard material is hard to magnetise but keeps its magnetism, making a permanent magnet, used in a loudspeaker or motor.",
          "Soft refers to the magnetism being easily changed, not to being physically soft.",
        ],
        ask: "For each type say how easily it magnetises, whether it keeps the magnetism, and one place it is used.",
      },
      {
        kind: "choice",
        question: "Which material is best for the core of an electromagnet?",
        options: [
          "Soft iron, because it magnetises and demagnetises easily",
          "Steel, because it keeps its magnetism",
          "Copper, because it carries the current",
          "Plastic, because it is light",
        ],
        correct: 0,
        ask: "An electromagnet must switch on and off. Which material can gain and lose its magnetism easily?",
        hints: [
          "Steel would keep its magnetism, so the electromagnet could not switch off.",
          "Soft iron magnetises when the current is on and loses it when the current is off.",
        ],
        explain: "Soft iron is best, because it magnetises strongly when the current is on and loses its magnetism when the current is off. Steel would stay magnetised, so it would not switch off.",
      },
      {
        kind: "match",
        prompt: "Match each item to the description that fits it.",
        pairs: [
          { left: "Soft iron", right: "Easily magnetised and quickly loses it, so it makes a temporary magnet" },
          { left: "Steel", right: "Hard to magnetise but keeps its magnetism, so it makes a permanent magnet" },
          { left: "Electromagnet core", right: "Needs a soft material so its magnetism can be switched on and off" },
          { left: "Loudspeaker magnet", right: "Needs a hard material that stays magnetised all the time" },
        ],
        ask: "Match each item to its description. One material is easily changed, one holds its magnetism, and each type suits a different job.",
        hints: [
          "Soft iron changes its magnetism easily, so it suits the switching core of an electromagnet.",
          "Steel keeps its magnetism, so it suits a permanent magnet like the one in a loudspeaker.",
        ],
        explain: "Soft iron is easily magnetised and quickly loses it, so it suits an electromagnet core that switches on and off. Steel keeps its magnetism, so it suits a permanent magnet such as the one in a loudspeaker.",
      },
      {
        kind: "choice",
        question: "Why are bar magnets stored with soft iron keepers laid across their ends?",
        options: [
          "To make the magnets physically softer",
          "To turn them into electromagnets",
          "To swap their north and south poles over",
          "So the poles form a closed loop and the magnets keep their strength",
        ],
        correct: 3,
        ask: "The keepers join the poles together. Think about what happens to the field lines and why that protects the magnet.",
        hints: [
          "With keepers the poles are joined N to S to N to S in a continuous ring.",
          "A closed loop with no free poles left exposed helps the magnets keep their strength.",
        ],
        explain: "The soft iron keepers join the poles into a closed N-S-N-S loop with no free poles exposed, so the domains stay lined up and the magnets keep their strength.",
      },
      {
        kind: "tiles",
        prompt: "Build the sentence that explains how bar magnets are stored to keep their strength.",
        tiles: ["Soft iron", "keepers", "join the poles", "into a", "closed loop", "open chain", "copper strips"],
        answer: ["Soft iron", "keepers", "join the poles", "into a", "closed loop"],
        ask: "The store uses keepers made of a soft material that link the poles. Build the sentence from the tiles.",
        hints: [
          "The keepers are made of soft iron, not copper.",
          "They join the poles into a closed loop, not an open chain.",
        ],
        explain: "Soft iron keepers join the poles into a closed loop, so the domains stay aligned and the magnets keep their strength.",
      },
      {
        kind: "open",
        prompt: "Describe the pattern of magnetic field lines around a bar magnet, and state 2 rules that field lines always obey.",
        figure: "fig-19-10-bar-field-lines",
        modelAnswer: "The field lines come out of the north pole, curve round through the space outside the magnet, and go into the south pole. The lines are crowded close together at the poles, where the field is strongest, and spread out at the sides, where the field is weaker. 2 rules the lines obey are that field lines never cross one another, and that they form continuous closed loops. The spacing of the lines also shows the strength of the field.",
        marks: [
          "Field lines run out of the north pole and into the south pole.",
          "The lines are close together at the poles, where the field is strongest, and spread out at the sides.",
          "2 rules: field lines never cross, and they form continuous closed loops.",
        ],
        ask: "Say which way the lines point, where they are crowded or spread out, and give 2 rules they obey.",
      },
      {
        kind: "choice",
        question: "In which direction do the magnetic field lines around a bar magnet point?",
        options: [
          "Into the north pole and out of the south pole",
          "Both ways along each line at once",
          "Out of the north pole and into the south pole",
          "They have no direction",
        ],
        correct: 2,
        ask: "Recall the standard convention for a field line. Which pole do the arrows leave, and which pole do they enter?",
        hints: [
          "The arrows always leave one pole and enter the other.",
          "By convention they point out of the north pole and into the south pole.",
        ],
        explain: "Field lines point out of the north pole and into the south pole. This is the standard convention, matching the way a compass needle would line up.",
      },
      {
        kind: "spoterror",
        prompt: "Here are 4 statements about the field lines of a bar magnet. Tap the one that is wrong.",
        lines: [
          "Field lines show the direction and shape of a magnetic field.",
          "The lines point out of the north pole and into the south pole.",
          "Field lines are continuous closed loops.",
          "Field lines cross over one another where the field is strong.",
        ],
        errorLine: 3,
        ask: "Check each statement against the rules for field lines. Which rule is broken?",
        hints: [
          "One rule is that field lines never cross each other.",
          "The line claiming that field lines cross where the field is strong breaks that rule.",
        ],
        explain: "The wrong line is the last one. Field lines never cross one another. Where the field is strong the lines are close together, but they still do not cross.",
      },
      {
        kind: "choice",
        question: "Where the field lines of a magnet are drawn close together, the magnetic field is",
        options: [
          "strong",
          "weak",
          "zero",
          "reversed",
        ],
        correct: 0,
        ask: "The spacing of the lines shows the strength of the field. What does close spacing mean?",
        hints: [
          "Lines that are spread far apart show a weak field.",
          "Lines crowded close together show a strong field, such as near the poles.",
        ],
        explain: "Close lines mean a strong field. The spacing shows the strength, so crowded lines near the poles show where a bar magnet is strongest, and spread-out lines show a weaker field.",
      },
      {
        kind: "choice",
        question: "2 like poles are placed facing each other. What is found at the point midway between them?",
        figure: "fig-19-13-like-poles-field",
        options: [
          "The strongest field of the whole arrangement",
          "A neutral point where the fields cancel and there is no net field",
          "A north pole created in the gap",
          "One field line crossing another",
        ],
        correct: 1,
        ask: "The 2 fields push against each other in the middle. What happens where they are equal and opposite?",
        hints: [
          "Where 2 equal, opposite fields meet, they cancel.",
          "This leaves a neutral point with no net field and no field line through it.",
        ],
        explain: "Between 2 like poles the fields are equal and opposite midway, so they cancel. This leaves a neutral point where there is no net field and no field line.",
      },
      {
        kind: "cloze",
        prompt: "Complete the sentences about the fields between 2 magnets.",
        segments: [
          "Between 2 unlike poles the field lines run straight across the gap from the north pole into the ",
          " pole. Between 2 like poles the fields ",
          " midway, leaving a ",
          " point where there is no net field.",
        ],
        bank: ["south", "cancel", "neutral", "north", "add"],
        answer: ["south", "cancel", "neutral"],
        ask: "Think about which pole the lines enter with unlike poles, then what the fields do between like poles. Every blank uses a word from the bank.",
        hints: [
          "Field lines always end at a south pole, so between unlike poles they cross into the south pole.",
          "Between like poles the fields cancel midway, leaving a neutral point.",
        ],
        explain: "Between unlike poles the lines run from the north pole into the south pole. Between like poles the fields cancel midway, leaving a neutral point with no net field.",
      },
      {
        kind: "open",
        prompt: "Describe how you would use a plotting compass to trace a magnetic field line around a bar magnet, and say which way the traced line points.",
        figure: "fig-19-15-plotting-compass",
        modelAnswer: "Place the bar magnet on a sheet of paper and put the plotting compass near one pole. Mark a dot at each end of the compass needle. Move the compass on so that its tail sits over the dot just made by its tip, and mark a new dot at the tip. Repeat this, dot by dot, until you reach the other pole, then join the dots into a smooth curve to get one field line. Because the red north-seeking tip of the needle points along the field, the traced line points out of the north pole and into the south pole.",
        marks: [
          "Place the compass near a pole and mark dots at the ends of the needle.",
          "Move the compass on so its tail meets the last dot, and repeat dot by dot, then join the dots into a smooth line.",
          "The line points out of the north pole and into the south pole, following the north-seeking tip.",
        ],
        ask: "Describe how you move the compass and mark dots step by step, and say which pole the finished line points away from.",
      },
    ],
  },
];
